In [17]:
import pandas as pd
import pingouin as pg
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import statsmodels.api as sm

In [ ]:
# Loding the TO csv file
df = pd.read_csv("../../RadiomiK/Features_TO/Final/cyl0.csv")
#Elimino le colonne diagnostics
string_to_match = 'diagnostics'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
string_to_match = 'Unnamed:'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
df_TO = df
df_TO

,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,...,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,image_ID,Manufacturer,Slice Thickness,Pixel_Spacing,Kernel,Dose,ASIR,Num_Acquisition
0,32338.0,32455.0,2.274190e+12,2.895033,67.0,2.497114,32543.0,37.152096,32395.408399,32396.0,...,5.281891,0.006676,RAD_TO_LUNG_4_STRONG_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STRONG,1
1,32339.0,32452.0,2.274172e+12,2.877628,64.0,2.738984,32537.0,35.899859,32395.286571,32396.0,...,7.479260,0.003848,RAD_TO_LUNG_4_STRONG_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STRONG,2
2,32336.0,32451.0,2.274120e+12,2.888346,65.5,2.623098,32539.0,36.830678,32394.909552,32395.0,...,5.642828,0.006768,RAD_TO_LUNG_4_STRONG_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STRONG,3
3,32329.0,32458.0,2.273763e+12,3.011258,72.0,2.507076,32539.0,40.127979,32392.365482,32391.0,...,7.878124,0.004552,RAD_TO_LUNG_2_STRONG_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STRONG,1
4,32330.0,32455.0,2.273936e+12,2.977948,69.0,2.523126,32533.0,39.099131,32393.598985,32394.0,...,5.701022,0.007985,RAD_TO_LUNG_2_STRONG_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STRONG,3
5,32332.0,32457.0,2.274011e+12,2.992587,69.0,2.583730,32540.0,39.163642,32394.129211,32395.0,...,6.173102,0.007797,RAD_TO_LUNG_2_STRONG_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STRONG,2
6,32326.0,32460.0,2.274073e+12,3.092705,76.0,2.553842,32553.0,42.526532,32394.570835,32394.0,...,10.138136,0.006199,RAD_TO_LUNG_4_STD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STD,3
7,32329.0,32461.0,2.274126e+12,3.078267,75.0,2.653363,32555.0,42.117601,32394.946931,32394.0,...,9.988204,0.005321,RAD_TO_LUNG_4_STD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STD,2
8,32329.0,32462.0,2.274146e+12,3.073643,77.0,2.461091,32551.0,42.435558,32395.088140,32396.0,...,7.192142,0.010203,RAD_TO_LUNG_4_STD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STD,1
9,32317.0,32470.0,2.274039e+12,3.265483,88.0,2.505607,32577.0,48.602242,32394.315644,32396.0,...,11.482843,0.009766,RAD_TO_LUNG_2_STD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STD,2
10,32298.0,32489.0,2.274075e+12,3.559581,109.0,2.388872,32617.0,59.985422,32394.543609,32396.0,...,19.506912,0.010464,RAD_TO_LUNG_2_MILD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,MILD,2
11,32299.0,32487.4,2.273928e+12,3.542748,106.0,2.433877,32602.0,59.010417,32393.495616,32394.0,...,20.872147,0.011107,RAD_TO_LUNG_2_MILD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,MILD,3
12,32318.0,32468.4,2.273943e+12,3.253406,87.0,2.469045,32568.0,48.339913,32393.629903,32394.0,...,11.483168,0.009006,RAD_TO_LUNG_2_STD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STD,3
13,32316.0,32471.0,2.273714e+12,3.286617,89.0,2.450295,32570.0,49.262521,32391.994462,32391.0,...,14.882420,0.005155,RAD_TO_LUNG_2_STD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STD,1
14,32299.0,32487.4,2.273928e+12,3.542748,106.0,2.433877,32602.0,59.010417,32393.495616,32394.0,...,20.872147,0.011107,RAD_TO_LUNG_2_MILD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,MILD,1
15,32310.0,32480.4,2.274132e+12,3.373294,100.0,2.259960,32579.0,53.746216,32394.968159,32396.0,...,13.505470,0.012326,RAD_TO_LUNG_4_MILD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,MILD,1
16,32309.0,32477.4,2.274030e+12,3.417376,99.0,2.493803,32616.0,53.966167,32394.240425,32394.0,...,25.772186,0.003558,RAD_TO_LUNG_4_MILD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,MILD,3
17,32310.0,32479.0,2.274108e+12,3.409438,98.0,2.360435,32584.0,53.743352,32394.795108,32395.0,...,17.196053,0.006855,RAD_TO_LUNG_4_MILD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,MILD,2
18,32263.0,32527.0,2.274016e+12,4.088952,140.0,2.888306,32767.0,83.013199,32394.040148,32394.0,...,76.527510,0.006074,RAD_TO_LUNG_4_FBP_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,2
19,32261.0,32525.0,2.273965e+12,4.081283,140.0,3.052700,32807.0,82.061545,32393.676973,32395.0,...,107.590368,0.003133,RAD_TO_LUNG_4_FBP_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,3
20,32264.6,32529.0,2.274062e+12,4.072355,140.0,2.853564,32762.0,81.849881,32394.368251,32397.0,...,74.678801,0.006375,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1

In [19]:
# Loding the GE csv files and joining them in a single dataframe
df_21 = pd.read_csv("../../../RadiomiK/Features_GE/Final/cyl0_21.csv")
df_35 = pd.read_csv("../../../RadiomiK/Features_GE/Final/cyl0_35.csv")
df_40 = pd.read_csv("../../../RadiomiK/Features_GE/Final/cyl0_40.csv")
df_42 = pd.read_csv("../../../RadiomiK/Features_GE/Final/cyl0_42.csv")
df_43 = pd.read_csv("../../../RadiomiK/Features_GE/Final/cyl0_43.csv")

df = pd.concat([df_21, df_35, df_40, df_42, df_43], ignore_index=True)

#Elimino le colonne diagnostics
string_to_match = 'diagnostics'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
string_to_match = 'Unnamed:'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
df_GE = df
df_GE

,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,...,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,image_ID,Manufacturer,Slice Thickness,Pixel_Spacing,Kernel,Dose,ASIR,Num_Acquisition
0,33344.0,33490.0,1.412471e+12,3.221387,74.0,2.935066,33619.0,45.152775,33415.189723,33414.0,...,17.220030,0.006960,RAD_GE_LUNG_14_ASIR10_1,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,1
1,33346.0,33487.0,1.412299e+12,3.197765,74.0,3.133934,33641.0,44.078295,33413.156522,33410.0,...,12.069037,0.011463,RAD_GE_LUNG_14_ASIR10_2,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,2
2,33300.0,33546.4,2.543435e+12,4.000990,133.0,3.003631,33812.0,77.926702,33421.579710,33422.0,...,80.978034,0.003297,RAD_GE_LUNG_7_ASIR10_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,2
3,33299.0,33533.0,2.542614e+12,3.901266,121.0,3.015717,33720.0,71.936515,33416.206412,33416.0,...,93.241728,0.002293,RAD_GE_LUNG_7_ASIR10_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,3
4,33288.0,33538.0,2.542451e+12,4.012106,132.0,2.890578,33729.0,78.352207,33415.113746,33416.0,...,66.559543,0.004717,RAD_GE_LUNG_7_ASIR10_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,1
5,33388.0,33450.0,2.543006e+12,2.081753,32.0,3.180377,33507.0,19.438513,33418.891085,33418.0,...,1.178598,0.007244,RAD_GE_LUNG_7_ASIR40_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,1
6,33393.0,33458.0,2.543952e+12,2.129809,36.0,2.837403,33512.0,20.417512,33425.104523,33424.0,...,1.365667,0.005231,RAD_GE_LUNG_7_ASIR40_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,2
7,33391.0,33452.0,2.543265e+12,2.027945,31.0,2.916172,33502.0,18.844810,33420.593325,33420.0,...,0.979950,0.004714,RAD_GE_LUNG_7_ASIR40_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,3
8,33335.0,33489.0,2.542245e+12,3.325224,82.0,2.965017,33603.0,48.232958,33413.845411,33413.0,...,19.771240,0.005302,RAD_GE_LUNG_7_ASIR70_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,1
9,33342.0,33489.0,2.542475e+12,3.232351,75.0,2.993069,33603.0,45.097725,33415.368028,33415.0,...,21.698186,0.003354,RAD_GE_LUNG_7_ASIR70_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,3
10,33344.0,33500.0,2.543235e+12,3.334653,84.0,2.951259,33661.0,48.935184,33420.353096,33420.0,...,21.228772,0.004383,RAD_GE_LUNG_7_ASIR70_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,2
11,33316.0,33520.0,2.542485e+12,3.716511,112.0,2.979709,33697.0,64.205387,33415.382082,33414.0,...,75.224946,0.002165,RAD_GE_LUNG_14_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,1
12,33317.0,33517.0,2.542419e+12,3.661898,101.0,2.944268,33706.0,60.913980,33414.954326,33413.0,...,33.641324,0.006847,RAD_GE_LUNG_14_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,2
13,33277.0,33549.0,2.542475e+12,4.125807,142.0,2.882909,33755.0,84.663516,33415.244181,33416.0,...,83.668857,0.004333,RAD_GE_LUNG_7_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,1
14,33290.0,33541.4,2.542633e+12,4.003946,131.0,3.019469,33745.0,77.327081,33416.306983,33416.0,...,114.164765,0.002122,RAD_GE_LUNG_7_FBP_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,3
15,33290.0,33557.0,2.543460e+12,4.108609,143.0,3.015338,33844.0,83.784293,33421.721563,33422.0,...,99.159101,0.003110,RAD_GE_LUNG_7_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,2

In [22]:
df_TOGE = pd.concat([df_TO, df_GE], ignore_index=True)
df_TOGE

,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,...,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,image_ID,Manufacturer,Slice Thickness,Pixel_Spacing,Kernel,Dose,ASIR,Num_Acquisition
0,32338.0,32455.0,2.274190e+12,2.895033,67.0,2.497114,32543.0,37.152096,32395.408399,32396.0,...,5.281891,0.006676,RAD_TO_LUNG_4_STRONG_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STRONG,1
1,32339.0,32452.0,2.274172e+12,2.877628,64.0,2.738984,32537.0,35.899859,32395.286571,32396.0,...,7.479260,0.003848,RAD_TO_LUNG_4_STRONG_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STRONG,2
2,32336.0,32451.0,2.274120e+12,2.888346,65.5,2.623098,32539.0,36.830678,32394.909552,32395.0,...,5.642828,0.006768,RAD_TO_LUNG_4_STRONG_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STRONG,3
3,32329.0,32458.0,2.273763e+12,3.011258,72.0,2.507076,32539.0,40.127979,32392.365482,32391.0,...,7.878124,0.004552,RAD_TO_LUNG_2_STRONG_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STRONG,1
4,32330.0,32455.0,2.273936e+12,2.977948,69.0,2.523126,32533.0,39.099131,32393.598985,32394.0,...,5.701022,0.007985,RAD_TO_LUNG_2_STRONG_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STRONG,3
5,32332.0,32457.0,2.274011e+12,2.992587,69.0,2.583730,32540.0,39.163642,32394.129211,32395.0,...,6.173102,0.007797,RAD_TO_LUNG_2_STRONG_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STRONG,2
6,32326.0,32460.0,2.274073e+12,3.092705,76.0,2.553842,32553.0,42.526532,32394.570835,32394.0,...,10.138136,0.006199,RAD_TO_LUNG_4_STD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STD,3
7,32329.0,32461.0,2.274126e+12,3.078267,75.0,2.653363,32555.0,42.117601,32394.946931,32394.0,...,9.988204,0.005321,RAD_TO_LUNG_4_STD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STD,2
8,32329.0,32462.0,2.274146e+12,3.073643,77.0,2.461091,32551.0,42.435558,32395.088140,32396.0,...,7.192142,0.010203,RAD_TO_LUNG_4_STD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STD,1
9,32317.0,32470.0,2.274039e+12,3.265483,88.0,2.505607,32577.0,48.602242,32394.315644,32396.0,...,11.482843,0.009766,RAD_TO_LUNG_2_STD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STD,2
10,32298.0,32489.0,2.274075e+12,3.559581,109.0,2.388872,32617.0,59.985422,32394.543609,32396.0,...,19.506912,0.010464,RAD_TO_LUNG_2_MILD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,MILD,2
11,32299.0,32487.4,2.273928e+12,3.542748,106.0,2.433877,32602.0,59.010417,32393.495616,32394.0,...,20.872147,0.011107,RAD_TO_LUNG_2_MILD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,MILD,3
12,32318.0,32468.4,2.273943e+12,3.253406,87.0,2.469045,32568.0,48.339913,32393.629903,32394.0,...,11.483168,0.009006,RAD_TO_LUNG_2_STD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STD,3
13,32316.0,32471.0,2.273714e+12,3.286617,89.0,2.450295,32570.0,49.262521,32391.994462,32391.0,...,14.882420,0.005155,RAD_TO_LUNG_2_STD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STD,1
14,32299.0,32487.4,2.273928e+12,3.542748,106.0,2.433877,32602.0,59.010417,32393.495616,32394.0,...,20.872147,0.011107,RAD_TO_LUNG_2_MILD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,MILD,1
15,32310.0,32480.4,2.274132e+12,3.373294,100.0,2.259960,32579.0,53.746216,32394.968159,32396.0,...,13.505470,0.012326,RAD_TO_LUNG_4_MILD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,MILD,1
16,32309.0,32477.4,2.274030e+12,3.417376,99.0,2.493803,32616.0,53.966167,32394.240425,32394.0,...,25.772186,0.003558,RAD_TO_LUNG_4_MILD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,MILD,3
17,32310.0,32479.0,2.274108e+12,3.409438,98.0,2.360435,32584.0,53.743352,32394.795108,32395.0,...,17.196053,0.006855,RAD_TO_LUNG_4_MILD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,MILD,2
18,32263.0,32527.0,2.274016e+12,4.088952,140.0,2.888306,32767.0,83.013199,32394.040148,32394.0,...,76.527510,0.006074,RAD_TO_LUNG_4_FBP_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,FBP,2
19,32261.0,32525.0,2.273965e+12,4.081283,140.0,3.052700,32807.0,82.061545,32393.676973,32395.0,...,107.590368,0.003133,RAD_TO_LUNG_4_FBP_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,FBP,3
20,32264.6,32529.0,2.274062e+12,4.072355,140.0,2.853564,32762.0,81.849881,32394.368251,32397.0,...,74.678801,0.006375,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,FBP,1
21,33344.0,33490.0,1.412471e+12,3.221387,74.0,2.935066,33619.0,45.152775,33415.189723,33414.0,...,17.220030,0.006960,RAD_GE_LUNG_14_ASIR10_1,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,1
22,33346.0,33487.0,1.412299e+12,3.197765,74.0,3.133934,33641.0,44.078295,33413.156522,33410.0,...,12.069037,0.011463,RAD_GE_LUNG_14_ASIR10_2,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,2
23,33300.0,33546.4,2.543435e+12,4.000990,133.0,3.003631,33812.0,77.926702,33421.579710,33422.0,...,80.978034,0.003297,RAD_GE_LUNG_7_ASIR10_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,2
24,33299.0,33533.0,2.542614e+12,3.901266,121.0,3.015717,33720.0,71.936515,33416.206412,33416.0,...,93.241728,0.002293,RAD_GE_LUNG_7_ASIR10_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,3
25,33288.0,33538.0,2.542451e+12,4.012106,132.0,2.890578,33729.0,78.352207,33415.113746,33416.0,...,66.559543,0.004717,RAD_GE_LUNG_7_ASIR10_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,1
26,33388.0,33450.0,2.543006e+12,2.081753,32.0,3.180377,33507.0,19.438513,33418.891085,33418.0,...,1.178598,0.007244,RAD_GE_LUNG_7_ASIR40_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,1
27,33393.0,33458.0,2.543952e+12,2.129809,36.0,2.837403,33512.0,20.417512,33425.104523,33424.0,...,1.365667,0.005231,RAD_GE_LUNG_7_ASIR40_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,2
28,33391.0,33452.0,2.543265e+12,2.027945,31.0,2.916172,33502.0,18.844810,33420.593325,33420.0,...,0.979950,0.004714,RAD_GE_LUNG_7_ASIR40_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,3
29,33335.0,33489.0,2.542245e+12,3.325224,82.0,2.965017,33603.0,48.232958,33413.845411,33413.0,...,19.771240,0.005302,RAD_GE_LUNG_7_ASIR70_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,1
30,33342.0,33489.0,2.542475e+12,3.232351,75.0,2.993069,33603.0,45.097725,33415.368028,33415.0,...,21.698186,0.003354,RAD_GE_LUNG_7_ASIR70_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,3
31,33344.0,33500.0,2.543235e+12,3.334653,84.0,2.951259,33661.0,48.935184,33420.353096,33420.0,...,21.228772,0.004383,RAD_GE_LUNG_7_ASIR70_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,2
32,33316.0,33520.0,2.542485e+12,3.716511,112.0,2.979709,33697.0,64.205387,33415.382082,33414.0,...,75.224946,0.002165,RAD_GE_LUNG_14_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,1
33,33317.0,33517.0,2.542419e+12,3.661898,101.0,2.944268,33706.0,60.913980,33414.954326,33413.0,...,33.641324,0.006847,RAD_GE_LUNG_14_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,2
34,33277.0,33549.0,2.542475e+12,4.125807,142.0,2.882909,33755.0,84.663516,33415.244181,33416.0,...,83.668857,0.004333,RAD_GE_LUNG_7_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,1
35,33290.0,33541.4,2.542633e+12,4.003946,131.0,3.019469,33745.0,77.327081,33416.306983,33416.0,...,114.164765,0.002122,RAD_GE_LUNG_7_FBP_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,3
36,33290.0,33557.0,2.543460e+12,4.108609,143.0,3.015338,33844.0,83.784293,33421.721563,33422.0,...,99.159101,0.003110,RAD_GE_LUNG_7_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,2

In [ ]:
#Save the dataframe in a csv file
df_TOGE.to_csv('../../../RadiomiK/Features_Global/cyl0_glob.csv', index=False)