In [1]:
import pandas as pd
import pingouin as pg
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import statsmodels.api as sm

In [ ]:
# Loding the TO csv file
df = pd.read_csv("../../RadiomiK/Features_TO/Final/cyl1.csv")
#Elimino le colonne diagnostics
string_to_match = 'diagnostics'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
string_to_match = 'Unnamed:'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
df_TO = df
df_TO

,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,...,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,image_ID,Manufacturer,Slice Thickness,Pixel_Spacing,Kernel,Dose,ASIR,Num_Acquisition
0,32029.0,32703.0,2.271440e+12,5.140786,487.0,1.682371,32843.0,234.018129,32374.793263,32420.0,...,351.151127,0.004638,RAD_TO_LUNG_4_STRONG_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STRONG,1
1,32018.0,32705.0,2.271475e+12,5.127535,493.5,1.640018,32835.0,238.595079,32375.008768,32427.0,...,384.010589,0.003128,RAD_TO_LUNG_4_STRONG_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STRONG,2
2,32009.0,32702.0,2.271325e+12,5.107679,493.5,1.638528,32839.0,238.902226,32373.935856,32422.0,...,339.210729,0.004916,RAD_TO_LUNG_4_STRONG_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STRONG,3
3,32093.6,32625.4,2.270111e+12,4.789971,383.0,1.678177,32744.0,182.820893,32365.721274,32397.0,...,204.339194,0.004207,RAD_TO_LUNG_2_STRONG_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STRONG,1
4,32086.0,32626.4,2.269915e+12,4.840467,387.5,1.694667,32752.0,185.579851,32364.305491,32393.0,...,210.675018,0.004765,RAD_TO_LUNG_2_STRONG_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STRONG,3
5,32089.0,32623.0,2.269723e+12,4.826153,384.0,1.682070,32743.0,184.103308,32362.949239,32394.0,...,195.916202,0.006159,RAD_TO_LUNG_2_STRONG_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STRONG,2
6,31954.0,32762.4,2.272183e+12,5.328649,583.5,1.633341,32921.0,280.629960,32379.638671,32442.0,...,471.958122,0.006314,RAD_TO_LUNG_4_STD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STD,3
7,31959.6,32769.0,2.272372e+12,5.352393,582.0,1.642716,32939.0,280.963207,32380.979695,32443.0,...,531.571022,0.002927,RAD_TO_LUNG_4_STD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STD,2
8,31967.0,32762.0,2.272369e+12,5.360024,570.0,1.665136,32931.0,274.984543,32381.015690,32437.0,...,511.455441,0.005354,RAD_TO_LUNG_4_STD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STD,1
9,32033.6,32683.0,2.270829e+12,5.092727,465.5,1.667073,32833.0,224.503452,32370.523304,32410.0,...,357.502660,0.003133,RAD_TO_LUNG_2_STD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STD,2
10,31922.0,32705.0,2.267037e+12,5.305066,555.5,1.708648,32861.0,264.780095,32343.078449,32414.0,...,504.563772,0.003082,RAD_TO_LUNG_2_MILD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,MILD,2
11,31914.6,32705.4,2.267253e+12,5.301046,583.0,1.700755,32876.0,268.148886,32344.577296,32414.0,...,477.029467,0.004654,RAD_TO_LUNG_2_MILD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,MILD,3
12,32027.6,32689.0,2.270896e+12,5.128375,477.0,1.690853,32848.0,228.551406,32370.956622,32409.0,...,375.464353,0.004597,RAD_TO_LUNG_2_STD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STD,3
13,32039.6,32690.0,2.271264e+12,5.070511,468.5,1.674975,32828.0,223.155852,32373.624365,32415.0,...,328.593159,0.004477,RAD_TO_LUNG_2_STD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STD,1
14,31914.6,32705.4,2.267253e+12,5.301046,583.0,1.700755,32876.0,268.148886,32344.577296,32414.0,...,477.029467,0.004654,RAD_TO_LUNG_2_MILD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,MILD,1
15,31844.0,32777.0,2.267707e+12,5.520944,700.0,1.670642,32947.0,321.071916,32347.221966,32439.0,...,685.583626,0.004152,RAD_TO_LUNG_4_MILD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,MILD,1
16,31840.0,32774.0,2.267712e+12,5.483328,713.5,1.619809,32946.0,325.200565,32347.230734,32447.0,...,673.436544,0.003591,RAD_TO_LUNG_4_MILD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,MILD,3
17,31836.6,32785.4,2.267865e+12,5.527931,704.5,1.645902,32950.0,326.302999,32348.300415,32445.0,...,728.797537,0.003159,RAD_TO_LUNG_4_MILD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,MILD,2
18,31576.2,32843.0,2.262636e+12,6.047287,785.5,2.151174,33158.0,418.484658,32309.397323,32455.0,...,1952.093878,0.002198,RAD_TO_LUNG_4_FBP_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,2
19,31567.0,32833.4,2.262593e+12,6.030394,802.0,2.106747,33226.0,418.293592,32309.121827,32456.0,...,1788.128726,0.001872,RAD_TO_LUNG_4_FBP_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,3
20,31570.4,32842.8,2.262266e+12,6.071180,803.5,2.187278,33268.0,419.412257,32306.700969,32450.0,...,1958.383846,0.001580,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1

In [3]:
# Loding the GE csv files and joining them in a single dataframe
df_21 = pd.read_csv("../../../RadiomiK/Features_GE/Final/cyl1_21.csv")
df_35 = pd.read_csv("../../../RadiomiK/Features_GE/Final/cyl1_35.csv")
df_40 = pd.read_csv("../../../RadiomiK/Features_GE/Final/cyl1_40.csv")
df_42 = pd.read_csv("../../../RadiomiK/Features_GE/Final/cyl1_42.csv")
df_43 = pd.read_csv("../../../RadiomiK/Features_GE/Final/cyl1_43.csv")

df = pd.concat([df_21, df_35, df_40, df_42, df_43], ignore_index=True)

#Elimino le colonne diagnostics
string_to_match = 'diagnostics'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
string_to_match = 'Unnamed:'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
df_GE = df
df_GE

,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,...,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,image_ID,Manufacturer,Slice Thickness,Pixel_Spacing,Kernel,Dose,ASIR,Num_Acquisition
0,32768.0,34178.0,1.417822e+12,5.265331,1153.0,1.531357,34551.0,488.838548,33474.032411,33541.0,...,1009.655759,0.010561,RAD_GE_LUNG_14_ASIR10_1,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,1
1,32768.0,34141.0,1.416696e+12,5.251375,1101.0,1.528744,34439.0,475.355959,33461.009486,33550.0,...,976.018343,0.011002,RAD_GE_LUNG_14_ASIR10_2,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,2
2,32768.0,34157.8,2.551631e+12,5.349666,1135.0,1.573242,34578.0,484.456050,33471.146245,33532.0,...,1013.150225,0.011430,RAD_GE_LUNG_7_ASIR10_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,2
3,32768.0,34135.8,2.550264e+12,5.331146,1094.0,1.575085,34575.0,475.907915,33462.343434,33532.0,...,1002.448595,0.010427,RAD_GE_LUNG_7_ASIR10_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,3
4,32768.0,34154.4,2.551158e+12,5.302459,1151.0,1.563882,34563.0,484.806422,33468.040404,33535.0,...,980.275321,0.011692,RAD_GE_LUNG_7_ASIR10_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,1
5,33003.6,33561.0,2.532346e+12,4.759310,291.0,2.774367,33658.0,168.788278,33348.155468,33410.0,...,255.104653,0.004198,RAD_GE_LUNG_7_ASIR40_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,1
6,33011.0,33567.0,2.532897e+12,4.746490,287.0,2.723575,33653.0,167.520770,33351.796223,33411.0,...,248.815222,0.004582,RAD_GE_LUNG_7_ASIR40_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,2
7,33025.0,33559.0,2.532547e+12,4.726301,283.0,2.727329,33651.0,163.795449,33349.516469,33408.0,...,234.158907,0.003378,RAD_GE_LUNG_7_ASIR40_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,3
8,32768.0,34133.4,2.550235e+12,5.300118,1123.0,1.558922,34515.0,476.518687,33462.131752,33534.0,...,959.428133,0.011308,RAD_GE_LUNG_7_ASIR70_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,1
9,32768.0,34119.0,2.549396e+12,5.331596,1067.0,1.574748,34532.0,467.333942,33456.790953,33530.0,...,968.116515,0.010624,RAD_GE_LUNG_7_ASIR70_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,3
10,32768.0,34134.0,2.550725e+12,5.341406,1101.0,1.570180,34539.0,475.771674,33465.353535,33528.0,...,953.760227,0.011222,RAD_GE_LUNG_7_ASIR70_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,2
11,32768.0,34186.0,2.552493e+12,5.295535,1172.0,1.548772,34575.0,492.861834,33476.657883,33531.0,...,980.565243,0.009583,RAD_GE_LUNG_14_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,1
12,32768.0,34152.4,2.550548e+12,5.298235,1105.0,1.551214,34510.0,478.515522,33464.182257,33546.0,...,959.791182,0.010563,RAD_GE_LUNG_14_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,2
13,32768.0,34160.0,2.551384e+12,5.306171,1156.0,1.566351,34579.0,486.930781,33469.486605,33535.0,...,1010.629826,0.011698,RAD_GE_LUNG_7_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,1
14,32768.0,34140.4,2.550476e+12,5.336396,1104.0,1.575910,34588.0,478.074903,33463.699605,33534.0,...,970.627774,0.010233,RAD_GE_LUNG_7_FBP_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,3
15,32768.0,34163.4,2.551855e+12,5.353128,1142.0,1.574963,34588.0,486.667993,33472.577075,33531.0,...,1016.023365,0.011694,RAD_GE_LUNG_7_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,2

In [4]:
df_TOGE = pd.concat([df_TO, df_GE], ignore_index=True)
df_TOGE

,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,...,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,image_ID,Manufacturer,Slice Thickness,Pixel_Spacing,Kernel,Dose,ASIR,Num_Acquisition
0,32029.0,32703.0,2.271440e+12,5.140786,487.0,1.682371,32843.0,234.018129,32374.793263,32420.0,...,351.151127,0.004638,RAD_TO_LUNG_4_STRONG_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STRONG,1
1,32018.0,32705.0,2.271475e+12,5.127535,493.5,1.640018,32835.0,238.595079,32375.008768,32427.0,...,384.010589,0.003128,RAD_TO_LUNG_4_STRONG_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STRONG,2
2,32009.0,32702.0,2.271325e+12,5.107679,493.5,1.638528,32839.0,238.902226,32373.935856,32422.0,...,339.210729,0.004916,RAD_TO_LUNG_4_STRONG_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STRONG,3
3,32093.6,32625.4,2.270111e+12,4.789971,383.0,1.678177,32744.0,182.820893,32365.721274,32397.0,...,204.339194,0.004207,RAD_TO_LUNG_2_STRONG_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STRONG,1
4,32086.0,32626.4,2.269915e+12,4.840467,387.5,1.694667,32752.0,185.579851,32364.305491,32393.0,...,210.675018,0.004765,RAD_TO_LUNG_2_STRONG_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STRONG,3
5,32089.0,32623.0,2.269723e+12,4.826153,384.0,1.682070,32743.0,184.103308,32362.949239,32394.0,...,195.916202,0.006159,RAD_TO_LUNG_2_STRONG_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STRONG,2
6,31954.0,32762.4,2.272183e+12,5.328649,583.5,1.633341,32921.0,280.629960,32379.638671,32442.0,...,471.958122,0.006314,RAD_TO_LUNG_4_STD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STD,3
7,31959.6,32769.0,2.272372e+12,5.352393,582.0,1.642716,32939.0,280.963207,32380.979695,32443.0,...,531.571022,0.002927,RAD_TO_LUNG_4_STD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STD,2
8,31967.0,32762.0,2.272369e+12,5.360024,570.0,1.665136,32931.0,274.984543,32381.015690,32437.0,...,511.455441,0.005354,RAD_TO_LUNG_4_STD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STD,1
9,32033.6,32683.0,2.270829e+12,5.092727,465.5,1.667073,32833.0,224.503452,32370.523304,32410.0,...,357.502660,0.003133,RAD_TO_LUNG_2_STD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STD,2
10,31922.0,32705.0,2.267037e+12,5.305066,555.5,1.708648,32861.0,264.780095,32343.078449,32414.0,...,504.563772,0.003082,RAD_TO_LUNG_2_MILD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,MILD,2
11,31914.6,32705.4,2.267253e+12,5.301046,583.0,1.700755,32876.0,268.148886,32344.577296,32414.0,...,477.029467,0.004654,RAD_TO_LUNG_2_MILD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,MILD,3
12,32027.6,32689.0,2.270896e+12,5.128375,477.0,1.690853,32848.0,228.551406,32370.956622,32409.0,...,375.464353,0.004597,RAD_TO_LUNG_2_STD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STD,3
13,32039.6,32690.0,2.271264e+12,5.070511,468.5,1.674975,32828.0,223.155852,32373.624365,32415.0,...,328.593159,0.004477,RAD_TO_LUNG_2_STD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STD,1
14,31914.6,32705.4,2.267253e+12,5.301046,583.0,1.700755,32876.0,268.148886,32344.577296,32414.0,...,477.029467,0.004654,RAD_TO_LUNG_2_MILD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,MILD,1
15,31844.0,32777.0,2.267707e+12,5.520944,700.0,1.670642,32947.0,321.071916,32347.221966,32439.0,...,685.583626,0.004152,RAD_TO_LUNG_4_MILD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,MILD,1
16,31840.0,32774.0,2.267712e+12,5.483328,713.5,1.619809,32946.0,325.200565,32347.230734,32447.0,...,673.436544,0.003591,RAD_TO_LUNG_4_MILD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,MILD,3
17,31836.6,32785.4,2.267865e+12,5.527931,704.5,1.645902,32950.0,326.302999,32348.300415,32445.0,...,728.797537,0.003159,RAD_TO_LUNG_4_MILD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,MILD,2
18,31576.2,32843.0,2.262636e+12,6.047287,785.5,2.151174,33158.0,418.484658,32309.397323,32455.0,...,1952.093878,0.002198,RAD_TO_LUNG_4_FBP_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,FBP,2
19,31567.0,32833.4,2.262593e+12,6.030394,802.0,2.106747,33226.0,418.293592,32309.121827,32456.0,...,1788.128726,0.001872,RAD_TO_LUNG_4_FBP_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,FBP,3
20,31570.4,32842.8,2.262266e+12,6.071180,803.5,2.187278,33268.0,419.412257,32306.700969,32450.0,...,1958.383846,0.001580,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,FBP,1
21,32768.0,34178.0,1.417822e+12,5.265331,1153.0,1.531357,34551.0,488.838548,33474.032411,33541.0,...,1009.655759,0.010561,RAD_GE_LUNG_14_ASIR10_1,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,1
22,32768.0,34141.0,1.416696e+12,5.251375,1101.0,1.528744,34439.0,475.355959,33461.009486,33550.0,...,976.018343,0.011002,RAD_GE_LUNG_14_ASIR10_2,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,2
23,32768.0,34157.8,2.551631e+12,5.349666,1135.0,1.573242,34578.0,484.456050,33471.146245,33532.0,...,1013.150225,0.011430,RAD_GE_LUNG_7_ASIR10_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,2
24,32768.0,34135.8,2.550264e+12,5.331146,1094.0,1.575085,34575.0,475.907915,33462.343434,33532.0,...,1002.448595,0.010427,RAD_GE_LUNG_7_ASIR10_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,3
25,32768.0,34154.4,2.551158e+12,5.302459,1151.0,1.563882,34563.0,484.806422,33468.040404,33535.0,...,980.275321,0.011692,RAD_GE_LUNG_7_ASIR10_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,1
26,33003.6,33561.0,2.532346e+12,4.759310,291.0,2.774367,33658.0,168.788278,33348.155468,33410.0,...,255.104653,0.004198,RAD_GE_LUNG_7_ASIR40_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,1
27,33011.0,33567.0,2.532897e+12,4.746490,287.0,2.723575,33653.0,167.520770,33351.796223,33411.0,...,248.815222,0.004582,RAD_GE_LUNG_7_ASIR40_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,2
28,33025.0,33559.0,2.532547e+12,4.726301,283.0,2.727329,33651.0,163.795449,33349.516469,33408.0,...,234.158907,0.003378,RAD_GE_LUNG_7_ASIR40_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,3
29,32768.0,34133.4,2.550235e+12,5.300118,1123.0,1.558922,34515.0,476.518687,33462.131752,33534.0,...,959.428133,0.011308,RAD_GE_LUNG_7_ASIR70_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,1
30,32768.0,34119.0,2.549396e+12,5.331596,1067.0,1.574748,34532.0,467.333942,33456.790953,33530.0,...,968.116515,0.010624,RAD_GE_LUNG_7_ASIR70_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,3
31,32768.0,34134.0,2.550725e+12,5.341406,1101.0,1.570180,34539.0,475.771674,33465.353535,33528.0,...,953.760227,0.011222,RAD_GE_LUNG_7_ASIR70_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,2
32,32768.0,34186.0,2.552493e+12,5.295535,1172.0,1.548772,34575.0,492.861834,33476.657883,33531.0,...,980.565243,0.009583,RAD_GE_LUNG_14_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,1
33,32768.0,34152.4,2.550548e+12,5.298235,1105.0,1.551214,34510.0,478.515522,33464.182257,33546.0,...,959.791182,0.010563,RAD_GE_LUNG_14_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,2
34,32768.0,34160.0,2.551384e+12,5.306171,1156.0,1.566351,34579.0,486.930781,33469.486605,33535.0,...,1010.629826,0.011698,RAD_GE_LUNG_7_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,1
35,32768.0,34140.4,2.550476e+12,5.336396,1104.0,1.575910,34588.0,478.074903,33463.699605,33534.0,...,970.627774,0.010233,RAD_GE_LUNG_7_FBP_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,3
36,32768.0,34163.4,2.551855e+12,5.353128,1142.0,1.574963,34588.0,486.667993,33472.577075,33531.0,...,1016.023365,0.011694,RAD_GE_LUNG_7_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,2

In [5]:
#Save the dataframe in a csv file
df_TOGE.to_csv('../../../RadiomiK/Features_Global/cyl1_glob.csv', index=False)