In [1]:
import pandas as pd
import pingouin as pg
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import statsmodels.api as sm

In [ ]:
# Loding the TO csv file
df = pd.read_csv("../../RadiomiK/Features_TO/Final/cyl2.csv")
#Elimino le colonne diagnostics
string_to_match = 'diagnostics'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
string_to_match = 'Unnamed:'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
df_TO = df
df_TO

,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,...,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,image_ID,Manufacturer,Slice Thickness,Pixel_Spacing,Kernel,Dose,ASIR,Num_Acquisition
0,31726.0,32212.0,2.214319e+12,4.791997,326.5,1.867750,32407.0,160.535693,31965.636825,31956.0,...,209.159803,0.004741,RAD_TO_LUNG_4_STRONG_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STRONG,1
1,31715.0,32218.0,2.214301e+12,4.828498,339.0,1.834580,32416.0,166.826825,31965.473466,31960.0,...,231.580954,0.003720,RAD_TO_LUNG_4_STRONG_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STRONG,2
2,31714.0,32221.0,2.214316e+12,4.823206,343.5,1.800783,32410.0,169.285291,31965.568989,31961.0,...,193.602363,0.005565,RAD_TO_LUNG_4_STRONG_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STRONG,3
3,31762.6,32169.4,2.214518e+12,4.566473,255.0,2.015820,32343.0,130.288426,31967.245962,31963.0,...,128.919666,0.006508,RAD_TO_LUNG_2_STRONG_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STRONG,1
4,31769.6,32177.0,2.215279e+12,4.570872,264.5,1.961122,32335.0,133.098293,31972.727273,31971.0,...,144.566358,0.005350,RAD_TO_LUNG_2_STRONG_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STRONG,3
5,31773.0,32174.4,2.215073e+12,4.548118,251.0,2.027476,32335.0,129.203037,31971.256576,31968.0,...,147.621488,0.003998,RAD_TO_LUNG_2_STRONG_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STRONG,2
6,31677.0,32255.4,2.213935e+12,4.994084,390.5,1.788788,32474.0,192.629043,31962.649746,31953.0,...,261.858381,0.005132,RAD_TO_LUNG_4_STD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STD,3
7,31680.0,32252.0,2.213975e+12,4.999037,391.5,1.813670,32459.0,190.562679,31962.946008,31956.0,...,279.006935,0.004559,RAD_TO_LUNG_4_STD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STD,2
8,31688.6,32246.8,2.214003e+12,4.975229,376.0,1.856327,32462.0,183.433581,31963.189663,31954.0,...,273.557808,0.004418,RAD_TO_LUNG_4_STD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STD,1
9,31735.0,32213.0,2.214790e+12,4.801665,310.0,1.979427,32420.0,157.154094,31969.054915,31964.0,...,204.159836,0.004308,RAD_TO_LUNG_2_STD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STD,2
10,31700.8,32255.0,2.215127e+12,4.971610,333.5,2.004194,32527.0,174.716252,31971.349331,31961.0,...,252.772390,0.004147,RAD_TO_LUNG_2_MILD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,MILD,2
11,31698.6,32267.0,2.215316e+12,4.991999,355.0,1.924860,32448.0,180.712716,31972.675588,31964.0,...,246.679800,0.005337,RAD_TO_LUNG_2_MILD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,MILD,3
12,31728.0,32217.4,2.214926e+12,4.812458,325.0,1.888980,32421.0,162.226648,31970.006922,31966.0,...,218.828219,0.004309,RAD_TO_LUNG_2_STD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STD,3
13,31720.0,32215.0,2.214170e+12,4.825825,307.5,1.953897,32410.0,158.961837,31964.562067,31959.0,...,211.720038,0.005074,RAD_TO_LUNG_2_STD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STD,1
14,31698.6,32267.0,2.215316e+12,4.991999,355.0,1.924860,32448.0,180.712716,31972.675588,31964.0,...,246.679800,0.005337,RAD_TO_LUNG_2_MILD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,MILD,1
15,31662.0,32307.0,2.214661e+12,5.129764,410.5,1.887828,32519.0,204.307013,31967.755422,31952.0,...,358.987873,0.004250,RAD_TO_LUNG_4_MILD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,MILD,1
16,31649.2,32312.0,2.214572e+12,5.176541,427.0,1.851810,32540.0,213.731449,31967.052607,31949.0,...,301.475461,0.008869,RAD_TO_LUNG_4_MILD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,MILD,3
17,31656.0,32311.0,2.214587e+12,5.170102,427.0,1.854159,32546.0,211.888781,31967.174435,31953.0,...,343.577158,0.004409,RAD_TO_LUNG_4_MILD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,MILD,2
18,31568.0,32425.0,2.215240e+12,5.659134,499.0,2.352891,32945.0,269.515764,31971.186433,31941.0,...,900.969978,0.001826,RAD_TO_LUNG_4_FBP_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,2
19,31573.6,32432.0,2.215178e+12,5.660884,488.5,2.390772,32950.0,270.977154,31970.729580,31940.0,...,919.371670,0.001828,RAD_TO_LUNG_4_FBP_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,3
20,31587.0,32420.0,2.215392e+12,5.629998,480.0,2.408650,32868.0,261.327738,31972.352100,31939.0,...,789.021725,0.002402,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1

In [3]:
# Loding the GE csv files and joining them in a single dataframe
df_21 = pd.read_csv("../../../RadiomiK/Features_GE/Final/cyl2_21.csv")
df_35 = pd.read_csv("../../../RadiomiK/Features_GE/Final/cyl2_35.csv")
df_40 = pd.read_csv("../../../RadiomiK/Features_GE/Final/cyl2_40.csv")
df_42 = pd.read_csv("../../../RadiomiK/Features_GE/Final/cyl2_42.csv")
df_43 = pd.read_csv("../../../RadiomiK/Features_GE/Final/cyl2_43.csv")

df = pd.concat([df_21, df_35, df_40, df_42, df_43], ignore_index=True)

#Elimino le colonne diagnostics
string_to_match = 'diagnostics'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
string_to_match = 'Unnamed:'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
df_GE = df
df_GE

,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,...,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,image_ID,Manufacturer,Slice Thickness,Pixel_Spacing,Kernel,Dose,ASIR,Num_Acquisition
0,32768.0,33368.2,1.380546e+12,4.674530,390.0,2.326791,33679.0,194.402372,33034.651383,33003.0,...,168.429503,0.026350,RAD_GE_LUNG_14_ASIR10_1,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,1
1,32768.0,33325.6,1.380366e+12,4.671743,339.0,2.373118,33787.0,176.686757,33032.626087,33007.0,...,155.142638,0.021869,RAD_GE_LUNG_14_ASIR10_2,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,2
2,32768.0,33534.4,2.489415e+12,4.502964,521.0,2.488664,34190.0,265.221017,33063.451910,32971.0,...,256.485808,0.015655,RAD_GE_LUNG_7_ASIR10_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,2
3,32768.0,33516.4,2.489394e+12,4.540886,525.0,2.414254,34094.0,260.173594,33063.375494,32986.0,...,247.491444,0.016859,RAD_GE_LUNG_7_ASIR10_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,3
4,32768.0,33565.4,2.490513e+12,4.500705,532.0,2.517432,34028.0,274.385943,33070.629337,32979.0,...,279.338767,0.015536,RAD_GE_LUNG_7_ASIR10_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,1
5,32872.0,33164.0,2.481616e+12,4.093018,167.0,2.192677,33285.0,90.522901,33012.880105,33009.0,...,50.128488,0.011737,RAD_GE_LUNG_7_ASIR40_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,1
6,32878.0,33155.0,2.481638e+12,4.043520,163.0,2.213143,33322.0,86.943003,33013.043478,33007.0,...,46.704303,0.010924,RAD_GE_LUNG_7_ASIR40_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,2
7,32888.0,33156.0,2.482307e+12,4.000017,156.0,2.230803,33293.0,84.439884,33017.501537,33012.0,...,46.020618,0.008734,RAD_GE_LUNG_7_ASIR40_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,3
8,32768.0,33527.4,2.489086e+12,4.509097,510.0,2.500818,33988.0,261.724622,33061.295125,32978.0,...,262.038534,0.015581,RAD_GE_LUNG_7_ASIR70_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,1
9,32768.0,33479.0,2.488156e+12,4.554650,503.0,2.392291,34037.0,248.357140,33055.277119,32983.0,...,224.838006,0.018790,RAD_GE_LUNG_7_ASIR70_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,3
10,32768.0,33501.0,2.488120e+12,4.528554,500.0,2.465557,34123.0,252.772251,33054.980676,32972.0,...,243.269235,0.017158,RAD_GE_LUNG_7_ASIR70_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,2
11,32768.0,33558.4,2.490332e+12,4.475719,541.0,2.405030,34181.0,277.126228,33069.440931,32970.0,...,265.930679,0.015819,RAD_GE_LUNG_14_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,1
12,32768.0,33537.0,2.489539e+12,4.470385,539.0,2.380958,34102.0,267.657807,33064.273606,32976.0,...,255.207152,0.015518,RAD_GE_LUNG_14_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,2
13,32768.0,33574.0,2.490865e+12,4.496482,536.0,2.523734,34038.0,277.488443,33072.931489,32980.0,...,280.292530,0.014701,RAD_GE_LUNG_7_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,1
14,32768.0,33523.4,2.489703e+12,4.535582,529.0,2.420572,34108.0,263.059214,33065.392183,32987.0,...,259.666865,0.016641,RAD_GE_LUNG_7_FBP_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,3
15,32768.0,33543.0,2.489740e+12,4.505310,526.0,2.496196,34207.0,268.315122,33065.573123,32969.0,...,267.614461,0.016079,RAD_GE_LUNG_7_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,2

In [4]:
df_TOGE = pd.concat([df_TO, df_GE], ignore_index=True)
df_TOGE

,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,...,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,image_ID,Manufacturer,Slice Thickness,Pixel_Spacing,Kernel,Dose,ASIR,Num_Acquisition
0,31726.0,32212.0,2.214319e+12,4.791997,326.5,1.867750,32407.0,160.535693,31965.636825,31956.0,...,209.159803,0.004741,RAD_TO_LUNG_4_STRONG_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STRONG,1
1,31715.0,32218.0,2.214301e+12,4.828498,339.0,1.834580,32416.0,166.826825,31965.473466,31960.0,...,231.580954,0.003720,RAD_TO_LUNG_4_STRONG_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STRONG,2
2,31714.0,32221.0,2.214316e+12,4.823206,343.5,1.800783,32410.0,169.285291,31965.568989,31961.0,...,193.602363,0.005565,RAD_TO_LUNG_4_STRONG_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STRONG,3
3,31762.6,32169.4,2.214518e+12,4.566473,255.0,2.015820,32343.0,130.288426,31967.245962,31963.0,...,128.919666,0.006508,RAD_TO_LUNG_2_STRONG_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STRONG,1
4,31769.6,32177.0,2.215279e+12,4.570872,264.5,1.961122,32335.0,133.098293,31972.727273,31971.0,...,144.566358,0.005350,RAD_TO_LUNG_2_STRONG_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STRONG,3
5,31773.0,32174.4,2.215073e+12,4.548118,251.0,2.027476,32335.0,129.203037,31971.256576,31968.0,...,147.621488,0.003998,RAD_TO_LUNG_2_STRONG_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STRONG,2
6,31677.0,32255.4,2.213935e+12,4.994084,390.5,1.788788,32474.0,192.629043,31962.649746,31953.0,...,261.858381,0.005132,RAD_TO_LUNG_4_STD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STD,3
7,31680.0,32252.0,2.213975e+12,4.999037,391.5,1.813670,32459.0,190.562679,31962.946008,31956.0,...,279.006935,0.004559,RAD_TO_LUNG_4_STD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STD,2
8,31688.6,32246.8,2.214003e+12,4.975229,376.0,1.856327,32462.0,183.433581,31963.189663,31954.0,...,273.557808,0.004418,RAD_TO_LUNG_4_STD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STD,1
9,31735.0,32213.0,2.214790e+12,4.801665,310.0,1.979427,32420.0,157.154094,31969.054915,31964.0,...,204.159836,0.004308,RAD_TO_LUNG_2_STD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STD,2
10,31700.8,32255.0,2.215127e+12,4.971610,333.5,2.004194,32527.0,174.716252,31971.349331,31961.0,...,252.772390,0.004147,RAD_TO_LUNG_2_MILD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,MILD,2
11,31698.6,32267.0,2.215316e+12,4.991999,355.0,1.924860,32448.0,180.712716,31972.675588,31964.0,...,246.679800,0.005337,RAD_TO_LUNG_2_MILD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,MILD,3
12,31728.0,32217.4,2.214926e+12,4.812458,325.0,1.888980,32421.0,162.226648,31970.006922,31966.0,...,218.828219,0.004309,RAD_TO_LUNG_2_STD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STD,3
13,31720.0,32215.0,2.214170e+12,4.825825,307.5,1.953897,32410.0,158.961837,31964.562067,31959.0,...,211.720038,0.005074,RAD_TO_LUNG_2_STD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STD,1
14,31698.6,32267.0,2.215316e+12,4.991999,355.0,1.924860,32448.0,180.712716,31972.675588,31964.0,...,246.679800,0.005337,RAD_TO_LUNG_2_MILD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,MILD,1
15,31662.0,32307.0,2.214661e+12,5.129764,410.5,1.887828,32519.0,204.307013,31967.755422,31952.0,...,358.987873,0.004250,RAD_TO_LUNG_4_MILD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,MILD,1
16,31649.2,32312.0,2.214572e+12,5.176541,427.0,1.851810,32540.0,213.731449,31967.052607,31949.0,...,301.475461,0.008869,RAD_TO_LUNG_4_MILD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,MILD,3
17,31656.0,32311.0,2.214587e+12,5.170102,427.0,1.854159,32546.0,211.888781,31967.174435,31953.0,...,343.577158,0.004409,RAD_TO_LUNG_4_MILD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,MILD,2
18,31568.0,32425.0,2.215240e+12,5.659134,499.0,2.352891,32945.0,269.515764,31971.186433,31941.0,...,900.969978,0.001826,RAD_TO_LUNG_4_FBP_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,FBP,2
19,31573.6,32432.0,2.215178e+12,5.660884,488.5,2.390772,32950.0,270.977154,31970.729580,31940.0,...,919.371670,0.001828,RAD_TO_LUNG_4_FBP_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,FBP,3
20,31587.0,32420.0,2.215392e+12,5.629998,480.0,2.408650,32868.0,261.327738,31972.352100,31939.0,...,789.021725,0.002402,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,FBP,1
21,32768.0,33368.2,1.380546e+12,4.674530,390.0,2.326791,33679.0,194.402372,33034.651383,33003.0,...,168.429503,0.026350,RAD_GE_LUNG_14_ASIR10_1,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,1
22,32768.0,33325.6,1.380366e+12,4.671743,339.0,2.373118,33787.0,176.686757,33032.626087,33007.0,...,155.142638,0.021869,RAD_GE_LUNG_14_ASIR10_2,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,2
23,32768.0,33534.4,2.489415e+12,4.502964,521.0,2.488664,34190.0,265.221017,33063.451910,32971.0,...,256.485808,0.015655,RAD_GE_LUNG_7_ASIR10_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,2
24,32768.0,33516.4,2.489394e+12,4.540886,525.0,2.414254,34094.0,260.173594,33063.375494,32986.0,...,247.491444,0.016859,RAD_GE_LUNG_7_ASIR10_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,3
25,32768.0,33565.4,2.490513e+12,4.500705,532.0,2.517432,34028.0,274.385943,33070.629337,32979.0,...,279.338767,0.015536,RAD_GE_LUNG_7_ASIR10_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,1
26,32872.0,33164.0,2.481616e+12,4.093018,167.0,2.192677,33285.0,90.522901,33012.880105,33009.0,...,50.128488,0.011737,RAD_GE_LUNG_7_ASIR40_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,1
27,32878.0,33155.0,2.481638e+12,4.043520,163.0,2.213143,33322.0,86.943003,33013.043478,33007.0,...,46.704303,0.010924,RAD_GE_LUNG_7_ASIR40_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,2
28,32888.0,33156.0,2.482307e+12,4.000017,156.0,2.230803,33293.0,84.439884,33017.501537,33012.0,...,46.020618,0.008734,RAD_GE_LUNG_7_ASIR40_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,3
29,32768.0,33527.4,2.489086e+12,4.509097,510.0,2.500818,33988.0,261.724622,33061.295125,32978.0,...,262.038534,0.015581,RAD_GE_LUNG_7_ASIR70_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,1
30,32768.0,33479.0,2.488156e+12,4.554650,503.0,2.392291,34037.0,248.357140,33055.277119,32983.0,...,224.838006,0.018790,RAD_GE_LUNG_7_ASIR70_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,3
31,32768.0,33501.0,2.488120e+12,4.528554,500.0,2.465557,34123.0,252.772251,33054.980676,32972.0,...,243.269235,0.017158,RAD_GE_LUNG_7_ASIR70_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,2
32,32768.0,33558.4,2.490332e+12,4.475719,541.0,2.405030,34181.0,277.126228,33069.440931,32970.0,...,265.930679,0.015819,RAD_GE_LUNG_14_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,1
33,32768.0,33537.0,2.489539e+12,4.470385,539.0,2.380958,34102.0,267.657807,33064.273606,32976.0,...,255.207152,0.015518,RAD_GE_LUNG_14_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,2
34,32768.0,33574.0,2.490865e+12,4.496482,536.0,2.523734,34038.0,277.488443,33072.931489,32980.0,...,280.292530,0.014701,RAD_GE_LUNG_7_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,1
35,32768.0,33523.4,2.489703e+12,4.535582,529.0,2.420572,34108.0,263.059214,33065.392183,32987.0,...,259.666865,0.016641,RAD_GE_LUNG_7_FBP_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,3
36,32768.0,33543.0,2.489740e+12,4.505310,526.0,2.496196,34207.0,268.315122,33065.573123,32969.0,...,267.614461,0.016079,RAD_GE_LUNG_7_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,2

In [5]:
#Save the dataframe in a csv file
df_TOGE.to_csv('../../../RadiomiK/Features_Global/cyl2_glob.csv', index=False)