In [1]:
import pandas as pd
import pingouin as pg
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import statsmodels.api as sm

In [ ]:
# Loding the TO csv file
df = pd.read_csv("../../RadiomiK/Features_TO/Final/cyl3.csv")
#Elimino le colonne diagnostics
string_to_match = 'diagnostics'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
string_to_match = 'Unnamed:'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
df_TO = df
df_TO

,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,...,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,image_ID,Manufacturer,Slice Thickness,Pixel_Spacing,Kernel,Dose,ASIR,Num_Acquisition
0,32331.6,32445.0,2.273077e+12,2.842853,65.0,2.442648,32507.0,35.970498,32387.484079,32387.0,...,3.844810,0.015246,RAD_TO_LUNG_4_STRONG_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STRONG,1
1,32330.0,32441.0,2.272759e+12,2.857729,65.0,2.624602,32518.0,35.595862,32385.222427,32384.0,...,5.469541,0.008347,RAD_TO_LUNG_4_STRONG_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STRONG,2
2,32328.0,32441.0,2.272806e+12,2.842110,64.0,2.443522,32509.0,35.896113,32385.551454,32387.0,...,5.219272,0.007670,RAD_TO_LUNG_4_STRONG_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STRONG,3
3,32325.0,32446.0,2.272925e+12,2.936380,67.0,2.521435,32528.0,37.815437,32386.401477,32385.0,...,7.593458,0.004509,RAD_TO_LUNG_2_STRONG_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STRONG,1
4,32326.6,32444.4,2.272798e+12,2.908631,67.0,2.536384,32532.0,37.199597,32385.496078,32386.0,...,5.295244,0.009337,RAD_TO_LUNG_2_STRONG_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STRONG,3
5,32327.0,32450.0,2.273217e+12,2.971008,70.0,2.629883,32563.0,39.466211,32388.479926,32388.0,...,9.681974,0.003323,RAD_TO_LUNG_2_STRONG_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STRONG,2
6,32316.0,32452.4,2.272711e+12,3.087085,79.0,2.374503,32525.0,43.152009,32384.863867,32385.0,...,11.607278,0.004735,RAD_TO_LUNG_4_STD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STD,3
7,32320.0,32449.0,2.272679e+12,3.061675,76.0,2.543412,32527.0,41.623285,32384.637287,32383.0,...,9.121487,0.007615,RAD_TO_LUNG_4_STD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STD,2
8,32320.0,32455.0,2.273017e+12,3.085396,77.0,2.383998,32533.0,42.924161,32387.044762,32387.0,...,7.695169,0.013854,RAD_TO_LUNG_4_STD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STD,1
9,32314.0,32465.4,2.273205e+12,3.285925,90.0,2.609937,32616.0,49.350008,32388.371020,32389.0,...,17.572324,0.004052,RAD_TO_LUNG_2_STD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STD,2
10,32293.0,32483.0,2.273170e+12,3.573847,111.0,2.475803,32616.0,60.471022,32388.091832,32390.0,...,29.560068,0.005192,RAD_TO_LUNG_2_MILD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,MILD,2
11,32291.0,32478.4,2.272723e+12,3.523406,103.5,2.432517,32587.0,57.854715,32384.918782,32386.0,...,28.939519,0.004907,RAD_TO_LUNG_2_MILD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,MILD,3
12,32312.0,32460.0,2.272722e+12,3.227041,84.0,2.504906,32568.0,46.518717,32384.937702,32385.0,...,10.327557,0.010506,RAD_TO_LUNG_2_STD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STD,3
13,32312.0,32461.0,2.272886e+12,3.236147,85.5,2.403209,32556.0,47.466221,32386.100138,32386.0,...,10.761258,0.008638,RAD_TO_LUNG_2_STD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STD,1
14,32291.0,32478.4,2.272723e+12,3.523406,103.5,2.432517,32587.0,57.854715,32384.918782,32386.0,...,28.939519,0.004907,RAD_TO_LUNG_2_MILD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,MILD,1
15,32302.0,32474.4,2.273004e+12,3.405909,100.0,2.260502,32556.0,54.465703,32386.925242,32386.0,...,16.869030,0.007758,RAD_TO_LUNG_4_MILD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,MILD,1
16,32297.0,32470.0,2.272665e+12,3.425390,100.0,2.309464,32559.0,54.828364,32384.514998,32386.0,...,20.759441,0.005872,RAD_TO_LUNG_4_MILD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,MILD,3
17,32299.0,32468.0,2.272572e+12,3.400081,96.5,2.380886,32577.0,53.410437,32383.856022,32383.0,...,16.284379,0.009155,RAD_TO_LUNG_4_MILD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,MILD,2
18,32245.0,32514.4,2.272326e+12,4.117349,143.0,3.021147,32716.0,83.810921,32381.993539,32384.0,...,104.059211,0.003076,RAD_TO_LUNG_4_FBP_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,2
19,32247.0,32520.4,2.272534e+12,4.146499,144.0,3.069952,32745.0,86.064508,32383.467928,32384.0,...,107.984626,0.003246,RAD_TO_LUNG_4_FBP_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,3
20,32251.0,32524.0,2.272997e+12,4.128003,147.5,2.855686,32729.0,85.425630,32386.771574,32387.0,...,96.096769,0.003536,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1

In [3]:
# Loding the GE csv files and joining them in a single dataframe
df_21 = pd.read_csv("../../../RadiomiK/Features_GE/Final/cyl3_21.csv")
df_35 = pd.read_csv("../../../RadiomiK/Features_GE/Final/cyl3_35.csv")
df_40 = pd.read_csv("../../../RadiomiK/Features_GE/Final/cyl3_40.csv")
df_42 = pd.read_csv("../../../RadiomiK/Features_GE/Final/cyl3_42.csv")
df_43 = pd.read_csv("../../../RadiomiK/Features_GE/Final/cyl3_43.csv")

df = pd.concat([df_21, df_35, df_40, df_42, df_43], ignore_index=True)

#Elimino le colonne diagnostics
string_to_match = 'diagnostics'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
string_to_match = 'Unnamed:'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
df_GE = df
df_GE

,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,...,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,image_ID,Manufacturer,Slice Thickness,Pixel_Spacing,Kernel,Dose,ASIR,Num_Acquisition
0,33325.0,33505.6,1.412288e+12,3.555159,96.0,3.160652,33724.0,57.120772,33412.995257,33409.0,...,44.173770,0.005024,RAD_GE_LUNG_14_ASIR10_1,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,1
1,33318.0,33504.6,1.412494e+12,3.610902,99.0,3.288510,33674.0,58.597830,33415.418182,33415.0,...,45.341925,0.005333,RAD_GE_LUNG_14_ASIR10_2,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,2
2,33255.6,33548.4,2.540512e+12,4.211498,148.0,3.147778,33849.0,89.451522,33402.320597,33403.0,...,184.113248,0.001759,RAD_GE_LUNG_7_ASIR10_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,2
3,33271.6,33545.0,2.541316e+12,4.146137,142.0,3.136285,33744.0,85.423638,33407.623188,33407.0,...,125.106580,0.002686,RAD_GE_LUNG_7_ASIR10_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,3
4,33259.0,33560.0,2.541891e+12,4.289137,156.0,2.979189,33816.0,94.731871,33411.361440,33412.0,...,121.618506,0.003909,RAD_GE_LUNG_7_ASIR10_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,1
5,33383.0,33447.0,2.542383e+12,2.077846,33.0,3.050709,33504.0,19.647435,33414.801054,33414.0,...,1.125245,0.007201,RAD_GE_LUNG_7_ASIR40_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,1
6,33378.0,33438.0,2.541360e+12,2.040733,32.0,3.069656,33484.0,19.038193,33408.074220,33408.0,...,1.421386,0.003802,RAD_GE_LUNG_7_ASIR40_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,2
7,33381.0,33442.4,2.541978e+12,2.046705,31.0,3.287427,33524.0,18.917752,33412.135705,33412.0,...,1.052752,0.007739,RAD_GE_LUNG_7_ASIR40_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,3
8,33317.0,33503.0,2.541699e+12,3.591697,99.0,3.007534,33667.0,58.164320,33410.231445,33410.0,...,37.351910,0.004562,RAD_GE_LUNG_7_ASIR70_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,1
9,33321.0,33491.0,2.541195e+12,3.463725,89.0,3.146735,33630.0,52.719802,33406.934124,33407.0,...,33.006972,0.004049,RAD_GE_LUNG_7_ASIR70_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,3
10,33312.6,33489.0,2.540471e+12,3.509487,92.0,3.133286,33664.0,54.609268,33402.172596,33404.0,...,46.264511,0.002847,RAD_GE_LUNG_7_ASIR70_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,2
11,33292.0,33537.0,2.541715e+12,3.974581,123.0,3.102016,33789.0,75.997485,33410.282389,33409.0,...,92.965110,0.003049,RAD_GE_LUNG_14_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,1
12,33283.6,33540.0,2.542083e+12,4.050384,137.0,3.090237,33770.0,80.069915,33412.682916,33414.0,...,76.565865,0.007372,RAD_GE_LUNG_14_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,2
13,33247.0,33572.0,2.541909e+12,4.395927,170.0,2.979805,33846.0,102.018513,33411.449715,33412.0,...,147.192974,0.003864,RAD_GE_LUNG_7_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,1
14,33261.6,33554.0,2.541324e+12,4.250726,154.0,3.137654,33767.0,91.903098,33407.645586,33408.0,...,144.616653,0.002592,RAD_GE_LUNG_7_FBP_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,3
15,33244.0,33561.0,2.540504e+12,4.323086,160.0,3.153041,33887.0,96.522484,33402.232323,33402.0,...,218.172372,0.001751,RAD_GE_LUNG_7_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,2

In [4]:
df_TOGE = pd.concat([df_TO, df_GE], ignore_index=True)
df_TOGE

,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,...,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,image_ID,Manufacturer,Slice Thickness,Pixel_Spacing,Kernel,Dose,ASIR,Num_Acquisition
0,32331.6,32445.0,2.273077e+12,2.842853,65.0,2.442648,32507.0,35.970498,32387.484079,32387.0,...,3.844810,0.015246,RAD_TO_LUNG_4_STRONG_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STRONG,1
1,32330.0,32441.0,2.272759e+12,2.857729,65.0,2.624602,32518.0,35.595862,32385.222427,32384.0,...,5.469541,0.008347,RAD_TO_LUNG_4_STRONG_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STRONG,2
2,32328.0,32441.0,2.272806e+12,2.842110,64.0,2.443522,32509.0,35.896113,32385.551454,32387.0,...,5.219272,0.007670,RAD_TO_LUNG_4_STRONG_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STRONG,3
3,32325.0,32446.0,2.272925e+12,2.936380,67.0,2.521435,32528.0,37.815437,32386.401477,32385.0,...,7.593458,0.004509,RAD_TO_LUNG_2_STRONG_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STRONG,1
4,32326.6,32444.4,2.272798e+12,2.908631,67.0,2.536384,32532.0,37.199597,32385.496078,32386.0,...,5.295244,0.009337,RAD_TO_LUNG_2_STRONG_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STRONG,3
5,32327.0,32450.0,2.273217e+12,2.971008,70.0,2.629883,32563.0,39.466211,32388.479926,32388.0,...,9.681974,0.003323,RAD_TO_LUNG_2_STRONG_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STRONG,2
6,32316.0,32452.4,2.272711e+12,3.087085,79.0,2.374503,32525.0,43.152009,32384.863867,32385.0,...,11.607278,0.004735,RAD_TO_LUNG_4_STD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STD,3
7,32320.0,32449.0,2.272679e+12,3.061675,76.0,2.543412,32527.0,41.623285,32384.637287,32383.0,...,9.121487,0.007615,RAD_TO_LUNG_4_STD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STD,2
8,32320.0,32455.0,2.273017e+12,3.085396,77.0,2.383998,32533.0,42.924161,32387.044762,32387.0,...,7.695169,0.013854,RAD_TO_LUNG_4_STD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STD,1
9,32314.0,32465.4,2.273205e+12,3.285925,90.0,2.609937,32616.0,49.350008,32388.371020,32389.0,...,17.572324,0.004052,RAD_TO_LUNG_2_STD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STD,2
10,32293.0,32483.0,2.273170e+12,3.573847,111.0,2.475803,32616.0,60.471022,32388.091832,32390.0,...,29.560068,0.005192,RAD_TO_LUNG_2_MILD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,MILD,2
11,32291.0,32478.4,2.272723e+12,3.523406,103.5,2.432517,32587.0,57.854715,32384.918782,32386.0,...,28.939519,0.004907,RAD_TO_LUNG_2_MILD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,MILD,3
12,32312.0,32460.0,2.272722e+12,3.227041,84.0,2.504906,32568.0,46.518717,32384.937702,32385.0,...,10.327557,0.010506,RAD_TO_LUNG_2_STD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STD,3
13,32312.0,32461.0,2.272886e+12,3.236147,85.5,2.403209,32556.0,47.466221,32386.100138,32386.0,...,10.761258,0.008638,RAD_TO_LUNG_2_STD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STD,1
14,32291.0,32478.4,2.272723e+12,3.523406,103.5,2.432517,32587.0,57.854715,32384.918782,32386.0,...,28.939519,0.004907,RAD_TO_LUNG_2_MILD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,MILD,1
15,32302.0,32474.4,2.273004e+12,3.405909,100.0,2.260502,32556.0,54.465703,32386.925242,32386.0,...,16.869030,0.007758,RAD_TO_LUNG_4_MILD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,MILD,1
16,32297.0,32470.0,2.272665e+12,3.425390,100.0,2.309464,32559.0,54.828364,32384.514998,32386.0,...,20.759441,0.005872,RAD_TO_LUNG_4_MILD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,MILD,3
17,32299.0,32468.0,2.272572e+12,3.400081,96.5,2.380886,32577.0,53.410437,32383.856022,32383.0,...,16.284379,0.009155,RAD_TO_LUNG_4_MILD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,MILD,2
18,32245.0,32514.4,2.272326e+12,4.117349,143.0,3.021147,32716.0,83.810921,32381.993539,32384.0,...,104.059211,0.003076,RAD_TO_LUNG_4_FBP_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,FBP,2
19,32247.0,32520.4,2.272534e+12,4.146499,144.0,3.069952,32745.0,86.064508,32383.467928,32384.0,...,107.984626,0.003246,RAD_TO_LUNG_4_FBP_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,FBP,3
20,32251.0,32524.0,2.272997e+12,4.128003,147.5,2.855686,32729.0,85.425630,32386.771574,32387.0,...,96.096769,0.003536,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,FBP,1
21,33325.0,33505.6,1.412288e+12,3.555159,96.0,3.160652,33724.0,57.120772,33412.995257,33409.0,...,44.173770,0.005024,RAD_GE_LUNG_14_ASIR10_1,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,1
22,33318.0,33504.6,1.412494e+12,3.610902,99.0,3.288510,33674.0,58.597830,33415.418182,33415.0,...,45.341925,0.005333,RAD_GE_LUNG_14_ASIR10_2,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,2
23,33255.6,33548.4,2.540512e+12,4.211498,148.0,3.147778,33849.0,89.451522,33402.320597,33403.0,...,184.113248,0.001759,RAD_GE_LUNG_7_ASIR10_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,2
24,33271.6,33545.0,2.541316e+12,4.146137,142.0,3.136285,33744.0,85.423638,33407.623188,33407.0,...,125.106580,0.002686,RAD_GE_LUNG_7_ASIR10_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,3
25,33259.0,33560.0,2.541891e+12,4.289137,156.0,2.979189,33816.0,94.731871,33411.361440,33412.0,...,121.618506,0.003909,RAD_GE_LUNG_7_ASIR10_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,1
26,33383.0,33447.0,2.542383e+12,2.077846,33.0,3.050709,33504.0,19.647435,33414.801054,33414.0,...,1.125245,0.007201,RAD_GE_LUNG_7_ASIR40_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,1
27,33378.0,33438.0,2.541360e+12,2.040733,32.0,3.069656,33484.0,19.038193,33408.074220,33408.0,...,1.421386,0.003802,RAD_GE_LUNG_7_ASIR40_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,2
28,33381.0,33442.4,2.541978e+12,2.046705,31.0,3.287427,33524.0,18.917752,33412.135705,33412.0,...,1.052752,0.007739,RAD_GE_LUNG_7_ASIR40_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,3
29,33317.0,33503.0,2.541699e+12,3.591697,99.0,3.007534,33667.0,58.164320,33410.231445,33410.0,...,37.351910,0.004562,RAD_GE_LUNG_7_ASIR70_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,1
30,33321.0,33491.0,2.541195e+12,3.463725,89.0,3.146735,33630.0,52.719802,33406.934124,33407.0,...,33.006972,0.004049,RAD_GE_LUNG_7_ASIR70_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,3
31,33312.6,33489.0,2.540471e+12,3.509487,92.0,3.133286,33664.0,54.609268,33402.172596,33404.0,...,46.264511,0.002847,RAD_GE_LUNG_7_ASIR70_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,2
32,33292.0,33537.0,2.541715e+12,3.974581,123.0,3.102016,33789.0,75.997485,33410.282389,33409.0,...,92.965110,0.003049,RAD_GE_LUNG_14_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,1
33,33283.6,33540.0,2.542083e+12,4.050384,137.0,3.090237,33770.0,80.069915,33412.682916,33414.0,...,76.565865,0.007372,RAD_GE_LUNG_14_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,2
34,33247.0,33572.0,2.541909e+12,4.395927,170.0,2.979805,33846.0,102.018513,33411.449715,33412.0,...,147.192974,0.003864,RAD_GE_LUNG_7_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,1
35,33261.6,33554.0,2.541324e+12,4.250726,154.0,3.137654,33767.0,91.903098,33407.645586,33408.0,...,144.616653,0.002592,RAD_GE_LUNG_7_FBP_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,3
36,33244.0,33561.0,2.540504e+12,4.323086,160.0,3.153041,33887.0,96.522484,33402.232323,33402.0,...,218.172372,0.001751,RAD_GE_LUNG_7_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,2

In [5]:
#Save the dataframe in a csv file
df_TOGE.to_csv('../../../RadiomiK/Features_Global/cyl3_glob.csv', index=False)