In [1]:
import pandas as pd
import pingouin as pg
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import statsmodels.api as sm

In [ ]:
# Loding the TO csv file
df = pd.read_csv("../../RadiomiK/Features_TO/Final/rect6.csv")
#Elimino le colonne diagnostics
string_to_match = 'diagnostics'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
string_to_match = 'Unnamed:'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
df_TO = df
df_TO

,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,...,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,image_ID,Manufacturer,Slice Thickness,Pixel_Spacing,Kernel,Dose,ASIR,Num_Acquisition
0,32158.5,32668.0,2.960744e+12,4.828153,330.25,1.879239,32847.0,164.920632,32424.745384,32438.0,...,238.686840,0.002880,RAD_TO_LUNG_4_STRONG_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STRONG,1
1,32166.0,32658.0,2.960816e+12,4.814722,315.00,1.966911,32831.0,159.941170,32425.169034,32444.0,...,238.888443,0.003321,RAD_TO_LUNG_4_STRONG_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STRONG,2
2,32161.5,32671.0,2.960878e+12,4.830843,328.00,1.889498,32842.0,164.298311,32425.485085,32434.0,...,209.391783,0.004917,RAD_TO_LUNG_4_STRONG_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STRONG,3
3,32196.0,32639.0,2.960601e+12,4.675447,271.00,2.012097,32788.0,141.765106,32424.100497,32436.5,...,162.972816,0.004773,RAD_TO_LUNG_2_STRONG_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STRONG,1
4,32191.0,32644.0,2.960913e+12,4.695804,292.00,1.959196,32811.0,146.858519,32425.784091,32436.0,...,168.429589,0.004872,RAD_TO_LUNG_2_STRONG_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STRONG,3
5,32188.0,32633.0,2.960022e+12,4.667697,282.00,1.935679,32767.0,144.156373,32420.924361,32435.0,...,165.956444,0.004019,RAD_TO_LUNG_2_STRONG_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STRONG,2
6,32145.0,32685.5,2.960789e+12,4.929516,351.00,1.899023,32872.0,175.185763,32424.923651,32435.5,...,241.570473,0.004973,RAD_TO_LUNG_4_STD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STD,3
7,32145.0,32673.0,2.960735e+12,4.913742,335.25,2.007889,32857.0,170.358082,32424.655540,32445.0,...,404.238173,0.001516,RAD_TO_LUNG_4_STD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STD,2
8,32144.0,32686.0,2.960836e+12,4.938140,356.25,1.889058,32871.0,177.223462,32425.164418,32438.0,...,312.895757,0.002438,RAD_TO_LUNG_4_STD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STD,1
9,32157.5,32658.0,2.959991e+12,4.840431,320.00,1.943826,32818.0,162.536131,32420.637074,32433.0,...,209.463176,0.005857,RAD_TO_LUNG_2_STD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STD,2
10,32132.0,32682.0,2.959570e+12,4.974005,336.00,2.051002,32855.0,173.766004,32418.237571,32433.0,...,293.083290,0.004892,RAD_TO_LUNG_2_MILD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,MILD,2
11,32134.5,32686.5,2.960454e+12,4.999283,338.00,2.071469,32885.0,176.981935,32423.056463,32435.0,...,304.593908,0.003459,RAD_TO_LUNG_2_MILD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,MILD,3
12,32168.0,32668.5,2.961074e+12,4.866179,326.00,1.973697,32874.0,165.178580,32426.551491,32435.0,...,222.329441,0.005130,RAD_TO_LUNG_2_STD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STD,3
13,32169.5,32663.0,2.960706e+12,4.843918,305.00,2.027113,32840.0,159.046224,32424.567827,32435.0,...,290.010467,0.002198,RAD_TO_LUNG_2_STD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STD,1
14,32134.5,32686.5,2.960454e+12,4.999283,338.00,2.071469,32885.0,176.981935,32423.056463,32435.0,...,304.593908,0.003459,RAD_TO_LUNG_2_MILD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,MILD,1
15,32115.0,32702.5,2.960056e+12,5.068330,366.00,2.012577,32900.0,189.082245,32420.783736,32439.5,...,326.603768,0.004376,RAD_TO_LUNG_4_MILD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,MILD,1
16,32117.0,32705.5,2.960019e+12,5.075701,363.00,2.025771,32883.0,188.072776,32420.589844,32436.0,...,327.527022,0.004552,RAD_TO_LUNG_4_MILD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,MILD,3
17,32115.5,32691.0,2.960108e+12,5.044461,346.00,2.122754,32860.0,182.647119,32421.112571,32446.0,...,456.429100,0.001742,RAD_TO_LUNG_4_MILD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,MILD,2
18,32071.0,32727.0,2.959296e+12,5.326026,375.00,2.647101,33016.0,208.907227,32416.390625,32450.0,...,856.459883,0.001597,RAD_TO_LUNG_4_FBP_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,2
19,32062.0,32744.5,2.959012e+12,5.364161,388.50,2.463578,33053.0,214.925741,32414.781960,32438.0,...,659.080484,0.002475,RAD_TO_LUNG_4_FBP_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,3
20,32063.5,32736.0,2.959042e+12,5.346772,392.00,2.508172,32991.0,213.969848,32414.963068,32438.0,...,648.161205,0.003638,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1

In [3]:
# Loding the GE csv files and joining them in a single dataframe
df_21 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect6_21.csv")
df_35 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect6_35.csv")
df_40 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect6_40.csv")
df_42 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect6_42.csv")
df_43 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect6_43.csv")

df = pd.concat([df_21, df_35, df_40, df_42, df_43], ignore_index=True)

#Elimino le colonne diagnostics
string_to_match = 'diagnostics'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
string_to_match = 'Unnamed:'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
df_GE = df
df_GE

,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,...,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,image_ID,Manufacturer,Slice Thickness,Pixel_Spacing,Kernel,Dose,ASIR,Num_Acquisition
0,33220.0,33624.0,1.812043e+12,4.543068,180.25,2.894265,33844.0,116.432526,33444.330247,33456.5,...,175.234068,0.004662,RAD_GE_LUNG_14_ASIR10_1,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,1
1,33241.9,33605.0,1.811555e+12,4.452969,189.00,2.669002,33837.0,111.021007,33439.873457,33455.0,...,121.991652,0.010502,RAD_GE_LUNG_14_ASIR10_2,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,2
2,32877.5,33985.5,3.263871e+12,5.773246,628.25,2.017986,34345.0,337.696432,33453.540123,33459.0,...,810.010988,0.021092,RAD_GE_LUNG_7_ASIR10_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,2
3,32910.0,33936.0,3.262472e+12,5.746326,585.25,2.050418,34348.0,317.519810,33446.639918,33463.0,...,778.025510,0.018670,RAD_GE_LUNG_7_ASIR10_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,3
4,32927.5,33920.0,3.261557e+12,5.734136,566.25,2.107292,34325.0,304.962019,33442.072016,33454.0,...,732.809904,0.021510,RAD_GE_LUNG_7_ASIR10_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,1
5,33230.0,33615.5,3.259778e+12,4.451693,241.00,2.134660,33735.0,124.865348,33434.597051,33444.0,...,126.548623,0.004343,RAD_GE_LUNG_7_ASIR40_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,1
6,33218.0,33630.0,3.261125e+12,4.551836,265.00,2.123548,33753.0,135.213910,33441.451989,33455.0,...,158.183637,0.004222,RAD_GE_LUNG_7_ASIR40_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,2
7,33226.5,33617.0,3.260534e+12,4.459340,248.00,2.091224,33731.0,128.079844,33438.463992,33455.0,...,125.470620,0.004731,RAD_GE_LUNG_7_ASIR40_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,3
8,32936.0,33910.0,3.261402e+12,5.718826,553.25,2.107681,34295.0,299.820203,33441.349794,33454.0,...,708.803656,0.020733,RAD_GE_LUNG_7_ASIR70_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,1
9,32916.0,33928.5,3.262314e+12,5.730938,575.50,2.053302,34319.0,312.551697,33445.900892,33460.0,...,756.120327,0.018656,RAD_GE_LUNG_7_ASIR70_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,3
10,32889.0,33974.5,3.263679e+12,5.772738,622.25,2.020424,34333.0,333.157863,33452.621399,33459.5,...,791.829118,0.021286,RAD_GE_LUNG_7_ASIR70_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,2
11,32869.0,33957.5,3.262448e+12,5.740036,604.00,2.016524,34247.0,325.265623,33446.388889,33459.0,...,764.938151,0.023655,RAD_GE_LUNG_14_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,1
12,32886.0,33919.0,3.261119e+12,5.703965,567.00,2.048531,34207.0,307.288822,33439.811728,33456.0,...,712.789239,0.024636,RAD_GE_LUNG_14_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,2
13,32923.0,33922.0,3.261577e+12,5.735773,569.50,2.107278,34331.0,306.260534,33442.156722,33453.0,...,737.498336,0.022077,RAD_GE_LUNG_7_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,1
14,32908.0,33939.0,3.262496e+12,5.749587,587.25,2.050104,34356.0,318.739369,33446.750000,33465.0,...,780.356588,0.019532,RAD_GE_LUNG_7_FBP_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,3
15,32875.5,33987.0,3.263901e+12,5.775279,629.50,2.017402,34348.0,338.816177,33453.677298,33460.5,...,822.252267,0.021526,RAD_GE_LUNG_7_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,2

In [4]:
df_TOGE = pd.concat([df_TO, df_GE], ignore_index=True)
df_TOGE

,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,...,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,image_ID,Manufacturer,Slice Thickness,Pixel_Spacing,Kernel,Dose,ASIR,Num_Acquisition
0,32158.5,32668.0,2.960744e+12,4.828153,330.25,1.879239,32847.0,164.920632,32424.745384,32438.0,...,238.686840,0.002880,RAD_TO_LUNG_4_STRONG_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STRONG,1
1,32166.0,32658.0,2.960816e+12,4.814722,315.00,1.966911,32831.0,159.941170,32425.169034,32444.0,...,238.888443,0.003321,RAD_TO_LUNG_4_STRONG_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STRONG,2
2,32161.5,32671.0,2.960878e+12,4.830843,328.00,1.889498,32842.0,164.298311,32425.485085,32434.0,...,209.391783,0.004917,RAD_TO_LUNG_4_STRONG_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STRONG,3
3,32196.0,32639.0,2.960601e+12,4.675447,271.00,2.012097,32788.0,141.765106,32424.100497,32436.5,...,162.972816,0.004773,RAD_TO_LUNG_2_STRONG_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STRONG,1
4,32191.0,32644.0,2.960913e+12,4.695804,292.00,1.959196,32811.0,146.858519,32425.784091,32436.0,...,168.429589,0.004872,RAD_TO_LUNG_2_STRONG_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STRONG,3
5,32188.0,32633.0,2.960022e+12,4.667697,282.00,1.935679,32767.0,144.156373,32420.924361,32435.0,...,165.956444,0.004019,RAD_TO_LUNG_2_STRONG_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STRONG,2
6,32145.0,32685.5,2.960789e+12,4.929516,351.00,1.899023,32872.0,175.185763,32424.923651,32435.5,...,241.570473,0.004973,RAD_TO_LUNG_4_STD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STD,3
7,32145.0,32673.0,2.960735e+12,4.913742,335.25,2.007889,32857.0,170.358082,32424.655540,32445.0,...,404.238173,0.001516,RAD_TO_LUNG_4_STD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STD,2
8,32144.0,32686.0,2.960836e+12,4.938140,356.25,1.889058,32871.0,177.223462,32425.164418,32438.0,...,312.895757,0.002438,RAD_TO_LUNG_4_STD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STD,1
9,32157.5,32658.0,2.959991e+12,4.840431,320.00,1.943826,32818.0,162.536131,32420.637074,32433.0,...,209.463176,0.005857,RAD_TO_LUNG_2_STD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STD,2
10,32132.0,32682.0,2.959570e+12,4.974005,336.00,2.051002,32855.0,173.766004,32418.237571,32433.0,...,293.083290,0.004892,RAD_TO_LUNG_2_MILD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,MILD,2
11,32134.5,32686.5,2.960454e+12,4.999283,338.00,2.071469,32885.0,176.981935,32423.056463,32435.0,...,304.593908,0.003459,RAD_TO_LUNG_2_MILD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,MILD,3
12,32168.0,32668.5,2.961074e+12,4.866179,326.00,1.973697,32874.0,165.178580,32426.551491,32435.0,...,222.329441,0.005130,RAD_TO_LUNG_2_STD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STD,3
13,32169.5,32663.0,2.960706e+12,4.843918,305.00,2.027113,32840.0,159.046224,32424.567827,32435.0,...,290.010467,0.002198,RAD_TO_LUNG_2_STD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STD,1
14,32134.5,32686.5,2.960454e+12,4.999283,338.00,2.071469,32885.0,176.981935,32423.056463,32435.0,...,304.593908,0.003459,RAD_TO_LUNG_2_MILD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,MILD,1
15,32115.0,32702.5,2.960056e+12,5.068330,366.00,2.012577,32900.0,189.082245,32420.783736,32439.5,...,326.603768,0.004376,RAD_TO_LUNG_4_MILD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,MILD,1
16,32117.0,32705.5,2.960019e+12,5.075701,363.00,2.025771,32883.0,188.072776,32420.589844,32436.0,...,327.527022,0.004552,RAD_TO_LUNG_4_MILD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,MILD,3
17,32115.5,32691.0,2.960108e+12,5.044461,346.00,2.122754,32860.0,182.647119,32421.112571,32446.0,...,456.429100,0.001742,RAD_TO_LUNG_4_MILD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,MILD,2
18,32071.0,32727.0,2.959296e+12,5.326026,375.00,2.647101,33016.0,208.907227,32416.390625,32450.0,...,856.459883,0.001597,RAD_TO_LUNG_4_FBP_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,FBP,2
19,32062.0,32744.5,2.959012e+12,5.364161,388.50,2.463578,33053.0,214.925741,32414.781960,32438.0,...,659.080484,0.002475,RAD_TO_LUNG_4_FBP_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,FBP,3
20,32063.5,32736.0,2.959042e+12,5.346772,392.00,2.508172,32991.0,213.969848,32414.963068,32438.0,...,648.161205,0.003638,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,FBP,1
21,33220.0,33624.0,1.812043e+12,4.543068,180.25,2.894265,33844.0,116.432526,33444.330247,33456.5,...,175.234068,0.004662,RAD_GE_LUNG_14_ASIR10_1,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,1
22,33241.9,33605.0,1.811555e+12,4.452969,189.00,2.669002,33837.0,111.021007,33439.873457,33455.0,...,121.991652,0.010502,RAD_GE_LUNG_14_ASIR10_2,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,2
23,32877.5,33985.5,3.263871e+12,5.773246,628.25,2.017986,34345.0,337.696432,33453.540123,33459.0,...,810.010988,0.021092,RAD_GE_LUNG_7_ASIR10_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,2
24,32910.0,33936.0,3.262472e+12,5.746326,585.25,2.050418,34348.0,317.519810,33446.639918,33463.0,...,778.025510,0.018670,RAD_GE_LUNG_7_ASIR10_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,3
25,32927.5,33920.0,3.261557e+12,5.734136,566.25,2.107292,34325.0,304.962019,33442.072016,33454.0,...,732.809904,0.021510,RAD_GE_LUNG_7_ASIR10_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,1
26,33230.0,33615.5,3.259778e+12,4.451693,241.00,2.134660,33735.0,124.865348,33434.597051,33444.0,...,126.548623,0.004343,RAD_GE_LUNG_7_ASIR40_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,1
27,33218.0,33630.0,3.261125e+12,4.551836,265.00,2.123548,33753.0,135.213910,33441.451989,33455.0,...,158.183637,0.004222,RAD_GE_LUNG_7_ASIR40_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,2
28,33226.5,33617.0,3.260534e+12,4.459340,248.00,2.091224,33731.0,128.079844,33438.463992,33455.0,...,125.470620,0.004731,RAD_GE_LUNG_7_ASIR40_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,3
29,32936.0,33910.0,3.261402e+12,5.718826,553.25,2.107681,34295.0,299.820203,33441.349794,33454.0,...,708.803656,0.020733,RAD_GE_LUNG_7_ASIR70_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,1
30,32916.0,33928.5,3.262314e+12,5.730938,575.50,2.053302,34319.0,312.551697,33445.900892,33460.0,...,756.120327,0.018656,RAD_GE_LUNG_7_ASIR70_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,3
31,32889.0,33974.5,3.263679e+12,5.772738,622.25,2.020424,34333.0,333.157863,33452.621399,33459.5,...,791.829118,0.021286,RAD_GE_LUNG_7_ASIR70_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,2
32,32869.0,33957.5,3.262448e+12,5.740036,604.00,2.016524,34247.0,325.265623,33446.388889,33459.0,...,764.938151,0.023655,RAD_GE_LUNG_14_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,1
33,32886.0,33919.0,3.261119e+12,5.703965,567.00,2.048531,34207.0,307.288822,33439.811728,33456.0,...,712.789239,0.024636,RAD_GE_LUNG_14_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,2
34,32923.0,33922.0,3.261577e+12,5.735773,569.50,2.107278,34331.0,306.260534,33442.156722,33453.0,...,737.498336,0.022077,RAD_GE_LUNG_7_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,1
35,32908.0,33939.0,3.262496e+12,5.749587,587.25,2.050104,34356.0,318.739369,33446.750000,33465.0,...,780.356588,0.019532,RAD_GE_LUNG_7_FBP_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,3
36,32875.5,33987.0,3.263901e+12,5.775279,629.50,2.017402,34348.0,338.816177,33453.677298,33460.5,...,822.252267,0.021526,RAD_GE_LUNG_7_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,2

In [5]:
#Save the dataframe in a csv file
df_TOGE.to_csv('../../../RadiomiK/Features_Global/rect6_glob.csv', index=False)