In [1]:
import pandas as pd
import pingouin as pg
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import statsmodels.api as sm

In [ ]:
# Loding the TO csv file
df = pd.read_csv("../../RadiomiK/Features_TO/Final/rect13.csv")
#Elimino le colonne diagnostics
string_to_match = 'diagnostics'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
string_to_match = 'Unnamed:'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
df_TO = df
df_TO

,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,...,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,image_ID,Manufacturer,Slice Thickness,Pixel_Spacing,Kernel,Dose,ASIR,Num_Acquisition
0,32877.0,32968.0,3.052145e+12,2.524196,51.00,2.414562,33024.0,28.657013,32921.985085,32922.0,...,2.982507,0.004830,RAD_TO_LUNG_4_STRONG_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STRONG,1
1,32881.0,32964.0,3.052166e+12,2.455419,48.00,2.619518,33035.0,26.713185,32922.101562,32921.0,...,3.468810,0.003139,RAD_TO_LUNG_4_STRONG_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STRONG,2
2,32879.5,32965.0,3.052079e+12,2.458404,48.00,2.624986,33028.0,26.896407,32921.629972,32922.0,...,2.693916,0.004977,RAD_TO_LUNG_4_STRONG_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STRONG,3
3,32872.0,32972.0,3.052408e+12,2.649315,54.00,2.587412,33036.0,30.668667,32923.401634,32924.0,...,3.291051,0.005906,RAD_TO_LUNG_2_STRONG_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STRONG,1
4,32874.0,32971.0,3.052106e+12,2.617480,55.00,2.522272,33041.0,30.055965,32921.771307,32921.0,...,2.998500,0.006750,RAD_TO_LUNG_2_STRONG_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STRONG,3
5,32871.0,32971.5,3.052115e+12,2.679700,56.00,2.629649,33065.0,31.314107,32921.819602,32922.0,...,3.230742,0.007587,RAD_TO_LUNG_2_STRONG_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STRONG,2
6,32871.5,32972.0,3.052073e+12,2.671579,56.00,2.600090,33054.0,31.459095,32921.594460,32922.0,...,6.229995,0.003045,RAD_TO_LUNG_4_STD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STD,3
7,32874.0,32971.5,3.052166e+12,2.659737,57.00,2.561270,33050.0,31.270885,32922.097301,32921.0,...,6.659442,0.003046,RAD_TO_LUNG_4_STD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STD,2
8,32870.0,32975.0,3.052180e+12,2.742707,59.00,2.450501,33030.0,33.365060,32922.166903,32922.0,...,5.312357,0.004587,RAD_TO_LUNG_4_STD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STD,1
9,32860.0,32984.0,3.052141e+12,2.974956,70.00,2.545112,33076.0,39.298455,32921.944957,32921.0,...,6.619012,0.007876,RAD_TO_LUNG_2_STD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STD,2
10,32843.0,33001.0,3.052147e+12,3.287539,92.00,2.362390,33084.0,49.733343,32921.958807,32921.0,...,16.295769,0.005043,RAD_TO_LUNG_2_MILD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,MILD,2
11,32847.0,32996.5,3.052091e+12,3.206185,87.00,2.316397,33078.0,47.011728,32921.664418,32922.0,...,11.158813,0.007088,RAD_TO_LUNG_2_MILD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,MILD,3
12,32863.0,32981.0,3.052082e+12,2.913804,66.00,2.541330,33070.0,37.265296,32921.634233,32921.0,...,5.996149,0.007298,RAD_TO_LUNG_2_STD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STD,3
13,32862.0,32984.0,3.052463e+12,2.942026,66.25,2.502560,33065.0,37.952265,32923.686080,32925.0,...,6.925107,0.006443,RAD_TO_LUNG_2_STD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STD,1
14,32847.0,32996.5,3.052091e+12,3.206185,87.00,2.316397,33078.0,47.011728,32921.664418,32922.0,...,11.158813,0.007088,RAD_TO_LUNG_2_MILD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,MILD,1
15,32855.0,32991.0,3.052160e+12,3.079482,79.00,2.329405,33066.0,43.285921,32922.041193,32922.0,...,9.871948,0.005309,RAD_TO_LUNG_4_MILD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,MILD,1
16,32858.0,32988.0,3.052095e+12,3.029195,74.00,2.469946,33080.0,41.092220,32921.697798,32923.0,...,9.755030,0.005393,RAD_TO_LUNG_4_MILD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,MILD,3
17,32859.0,32985.0,3.052143e+12,3.011449,74.00,2.436748,33092.0,40.624056,32921.958807,32921.0,...,9.668470,0.005448,RAD_TO_LUNG_4_MILD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,MILD,2
18,32817.0,33028.0,3.052086e+12,3.779706,110.00,3.117070,33262.0,66.319216,32921.580256,32923.0,...,54.442269,0.004450,RAD_TO_LUNG_4_FBP_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,2
19,32817.0,33030.0,3.052118e+12,3.807745,113.00,3.144912,33233.0,67.090751,32921.748580,32923.0,...,53.884976,0.004774,RAD_TO_LUNG_4_FBP_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,3
20,32809.0,33035.0,3.052151e+12,3.874609,120.25,2.960929,33222.0,70.928594,32921.914062,32923.0,...,67.614320,0.004160,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1

In [3]:
# Loding the GE csv files and joining them in a single dataframe
df_21 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect13_21.csv")
df_35 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect13_35.csv")
df_40 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect13_40.csv")
df_42 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect13_42.csv")
df_43 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect13_43.csv")

df = pd.concat([df_21, df_35, df_40, df_42, df_43], ignore_index=True)

#Elimino le colonne diagnostics
string_to_match = 'diagnostics'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
string_to_match = 'Unnamed:'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
df_GE = df
df_GE

,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,...,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,image_ID,Manufacturer,Slice Thickness,Pixel_Spacing,Kernel,Dose,ASIR,Num_Acquisition
0,33902.9,33991.0,1.866789e+12,2.542622,46.0,3.187370,34096.0,27.408150,33946.101852,33946.0,...,4.736569,0.011362,RAD_GE_LUNG_14_ASIR10_1,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,1
1,33904.0,33993.0,1.867117e+12,2.566511,48.0,3.172185,34088.0,27.995593,33949.084568,33949.0,...,4.643058,0.009349,RAD_GE_LUNG_14_ASIR10_2,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,2
2,33855.0,34034.0,3.360112e+12,3.514281,92.0,2.966705,34203.0,54.941690,33945.502743,33946.0,...,25.647995,0.008040,RAD_GE_LUNG_7_ASIR10_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,2
3,33851.0,34033.0,3.359395e+12,3.535293,97.0,2.820105,34167.0,56.334702,33941.876200,33942.0,...,32.076638,0.005433,RAD_GE_LUNG_7_ASIR10_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,3
4,33855.0,34036.0,3.360299e+12,3.542116,92.0,3.125830,34210.0,55.663090,33946.443073,33947.0,...,38.523976,0.003786,RAD_GE_LUNG_7_ASIR10_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,1
5,33928.0,33967.0,3.360265e+12,1.459917,20.0,3.192013,34007.0,12.047572,33946.339849,33945.0,...,0.425868,0.004899,RAD_GE_LUNG_7_ASIR40_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,1
6,33926.0,33965.0,3.359856e+12,1.464896,20.0,3.318741,34008.0,12.153691,33944.274005,33943.0,...,0.439750,0.004015,RAD_GE_LUNG_7_ASIR40_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,2
7,33923.0,33960.0,3.359118e+12,1.398145,18.0,3.258177,33995.0,11.178615,33940.545610,33940.0,...,0.412318,0.004184,RAD_GE_LUNG_7_ASIR40_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,3
8,33890.0,34003.0,3.360470e+12,2.874591,58.0,3.094585,34107.0,34.617756,33947.351509,33948.0,...,9.365181,0.005129,RAD_GE_LUNG_7_ASIR70_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,1
9,33885.0,33999.0,3.359440e+12,2.872511,60.0,2.856230,34073.0,35.184084,33942.145748,33942.0,...,9.351160,0.005520,RAD_GE_LUNG_7_ASIR70_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,3
10,33890.0,34000.0,3.360201e+12,2.832421,57.0,3.026779,34113.0,33.895155,33945.992455,33946.0,...,6.721623,0.009201,RAD_GE_LUNG_7_ASIR70_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,2
11,33890.0,34005.0,3.360372e+12,2.900980,61.0,3.082468,34114.0,35.841979,33946.854252,33946.0,...,12.408567,0.003843,RAD_GE_LUNG_14_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,1
12,33889.0,34006.0,3.360510e+12,2.952039,62.0,3.050239,34120.0,36.747871,33947.551783,33948.0,...,10.680346,0.006092,RAD_GE_LUNG_14_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,2
13,33861.0,34028.0,3.360248e+12,3.448408,88.0,3.239651,34228.0,51.994050,33946.195816,33947.0,...,29.404894,0.004595,RAD_GE_LUNG_7_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,1
14,33857.5,34025.0,3.359342e+12,3.433481,90.0,2.906057,34165.0,52.445187,33941.620370,33941.0,...,24.241573,0.006357,RAD_GE_LUNG_7_FBP_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,3
15,33859.0,34029.0,3.360064e+12,3.457672,87.0,3.011356,34189.0,52.445065,33945.265775,33946.0,...,24.360658,0.007157,RAD_GE_LUNG_7_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,2

In [4]:
df_TOGE = pd.concat([df_TO, df_GE], ignore_index=True)
df_TOGE

,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,...,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,image_ID,Manufacturer,Slice Thickness,Pixel_Spacing,Kernel,Dose,ASIR,Num_Acquisition
0,32877.0,32968.0,3.052145e+12,2.524196,51.00,2.414562,33024.0,28.657013,32921.985085,32922.0,...,2.982507,0.004830,RAD_TO_LUNG_4_STRONG_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STRONG,1
1,32881.0,32964.0,3.052166e+12,2.455419,48.00,2.619518,33035.0,26.713185,32922.101562,32921.0,...,3.468810,0.003139,RAD_TO_LUNG_4_STRONG_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STRONG,2
2,32879.5,32965.0,3.052079e+12,2.458404,48.00,2.624986,33028.0,26.896407,32921.629972,32922.0,...,2.693916,0.004977,RAD_TO_LUNG_4_STRONG_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STRONG,3
3,32872.0,32972.0,3.052408e+12,2.649315,54.00,2.587412,33036.0,30.668667,32923.401634,32924.0,...,3.291051,0.005906,RAD_TO_LUNG_2_STRONG_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STRONG,1
4,32874.0,32971.0,3.052106e+12,2.617480,55.00,2.522272,33041.0,30.055965,32921.771307,32921.0,...,2.998500,0.006750,RAD_TO_LUNG_2_STRONG_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STRONG,3
5,32871.0,32971.5,3.052115e+12,2.679700,56.00,2.629649,33065.0,31.314107,32921.819602,32922.0,...,3.230742,0.007587,RAD_TO_LUNG_2_STRONG_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STRONG,2
6,32871.5,32972.0,3.052073e+12,2.671579,56.00,2.600090,33054.0,31.459095,32921.594460,32922.0,...,6.229995,0.003045,RAD_TO_LUNG_4_STD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STD,3
7,32874.0,32971.5,3.052166e+12,2.659737,57.00,2.561270,33050.0,31.270885,32922.097301,32921.0,...,6.659442,0.003046,RAD_TO_LUNG_4_STD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STD,2
8,32870.0,32975.0,3.052180e+12,2.742707,59.00,2.450501,33030.0,33.365060,32922.166903,32922.0,...,5.312357,0.004587,RAD_TO_LUNG_4_STD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STD,1
9,32860.0,32984.0,3.052141e+12,2.974956,70.00,2.545112,33076.0,39.298455,32921.944957,32921.0,...,6.619012,0.007876,RAD_TO_LUNG_2_STD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STD,2
10,32843.0,33001.0,3.052147e+12,3.287539,92.00,2.362390,33084.0,49.733343,32921.958807,32921.0,...,16.295769,0.005043,RAD_TO_LUNG_2_MILD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,MILD,2
11,32847.0,32996.5,3.052091e+12,3.206185,87.00,2.316397,33078.0,47.011728,32921.664418,32922.0,...,11.158813,0.007088,RAD_TO_LUNG_2_MILD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,MILD,3
12,32863.0,32981.0,3.052082e+12,2.913804,66.00,2.541330,33070.0,37.265296,32921.634233,32921.0,...,5.996149,0.007298,RAD_TO_LUNG_2_STD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STD,3
13,32862.0,32984.0,3.052463e+12,2.942026,66.25,2.502560,33065.0,37.952265,32923.686080,32925.0,...,6.925107,0.006443,RAD_TO_LUNG_2_STD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STD,1
14,32847.0,32996.5,3.052091e+12,3.206185,87.00,2.316397,33078.0,47.011728,32921.664418,32922.0,...,11.158813,0.007088,RAD_TO_LUNG_2_MILD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,MILD,1
15,32855.0,32991.0,3.052160e+12,3.079482,79.00,2.329405,33066.0,43.285921,32922.041193,32922.0,...,9.871948,0.005309,RAD_TO_LUNG_4_MILD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,MILD,1
16,32858.0,32988.0,3.052095e+12,3.029195,74.00,2.469946,33080.0,41.092220,32921.697798,32923.0,...,9.755030,0.005393,RAD_TO_LUNG_4_MILD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,MILD,3
17,32859.0,32985.0,3.052143e+12,3.011449,74.00,2.436748,33092.0,40.624056,32921.958807,32921.0,...,9.668470,0.005448,RAD_TO_LUNG_4_MILD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,MILD,2
18,32817.0,33028.0,3.052086e+12,3.779706,110.00,3.117070,33262.0,66.319216,32921.580256,32923.0,...,54.442269,0.004450,RAD_TO_LUNG_4_FBP_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,FBP,2
19,32817.0,33030.0,3.052118e+12,3.807745,113.00,3.144912,33233.0,67.090751,32921.748580,32923.0,...,53.884976,0.004774,RAD_TO_LUNG_4_FBP_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,FBP,3
20,32809.0,33035.0,3.052151e+12,3.874609,120.25,2.960929,33222.0,70.928594,32921.914062,32923.0,...,67.614320,0.004160,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,FBP,1
21,33902.9,33991.0,1.866789e+12,2.542622,46.00,3.187370,34096.0,27.408150,33946.101852,33946.0,...,4.736569,0.011362,RAD_GE_LUNG_14_ASIR10_1,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,1
22,33904.0,33993.0,1.867117e+12,2.566511,48.00,3.172185,34088.0,27.995593,33949.084568,33949.0,...,4.643058,0.009349,RAD_GE_LUNG_14_ASIR10_2,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,2
23,33855.0,34034.0,3.360112e+12,3.514281,92.00,2.966705,34203.0,54.941690,33945.502743,33946.0,...,25.647995,0.008040,RAD_GE_LUNG_7_ASIR10_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,2
24,33851.0,34033.0,3.359395e+12,3.535293,97.00,2.820105,34167.0,56.334702,33941.876200,33942.0,...,32.076638,0.005433,RAD_GE_LUNG_7_ASIR10_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,3
25,33855.0,34036.0,3.360299e+12,3.542116,92.00,3.125830,34210.0,55.663090,33946.443073,33947.0,...,38.523976,0.003786,RAD_GE_LUNG_7_ASIR10_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,1
26,33928.0,33967.0,3.360265e+12,1.459917,20.00,3.192013,34007.0,12.047572,33946.339849,33945.0,...,0.425868,0.004899,RAD_GE_LUNG_7_ASIR40_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,1
27,33926.0,33965.0,3.359856e+12,1.464896,20.00,3.318741,34008.0,12.153691,33944.274005,33943.0,...,0.439750,0.004015,RAD_GE_LUNG_7_ASIR40_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,2
28,33923.0,33960.0,3.359118e+12,1.398145,18.00,3.258177,33995.0,11.178615,33940.545610,33940.0,...,0.412318,0.004184,RAD_GE_LUNG_7_ASIR40_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,3
29,33890.0,34003.0,3.360470e+12,2.874591,58.00,3.094585,34107.0,34.617756,33947.351509,33948.0,...,9.365181,0.005129,RAD_GE_LUNG_7_ASIR70_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,1
30,33885.0,33999.0,3.359440e+12,2.872511,60.00,2.856230,34073.0,35.184084,33942.145748,33942.0,...,9.351160,0.005520,RAD_GE_LUNG_7_ASIR70_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,3
31,33890.0,34000.0,3.360201e+12,2.832421,57.00,3.026779,34113.0,33.895155,33945.992455,33946.0,...,6.721623,0.009201,RAD_GE_LUNG_7_ASIR70_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,2
32,33890.0,34005.0,3.360372e+12,2.900980,61.00,3.082468,34114.0,35.841979,33946.854252,33946.0,...,12.408567,0.003843,RAD_GE_LUNG_14_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,1
33,33889.0,34006.0,3.360510e+12,2.952039,62.00,3.050239,34120.0,36.747871,33947.551783,33948.0,...,10.680346,0.006092,RAD_GE_LUNG_14_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,2
34,33861.0,34028.0,3.360248e+12,3.448408,88.00,3.239651,34228.0,51.994050,33946.195816,33947.0,...,29.404894,0.004595,RAD_GE_LUNG_7_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,1
35,33857.5,34025.0,3.359342e+12,3.433481,90.00,2.906057,34165.0,52.445187,33941.620370,33941.0,...,24.241573,0.006357,RAD_GE_LUNG_7_FBP_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,3
36,33859.0,34029.0,3.360064e+12,3.457672,87.00,3.011356,34189.0,52.445065,33945.265775,33946.0,...,24.360658,0.007157,RAD_GE_LUNG_7_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,2

In [5]:
#Save the dataframe in a csv file
df_TOGE.to_csv('../../../RadiomiK/Features_Global/rect13_glob.csv', index=False)