In [1]:
import pandas as pd
import pingouin as pg
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import statsmodels.api as sm

In [ ]:
# Loding the TO csv file
df = pd.read_csv("../../RadiomiK/Features_TO/Final/rect7.csv")
#Elimino le colonne diagnostics
string_to_match = 'diagnostics'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
string_to_match = 'Unnamed:'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
df_TO = df
df_TO

,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,...,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,image_ID,Manufacturer,Slice Thickness,Pixel_Spacing,Kernel,Dose,ASIR,Num_Acquisition
0,31677.0,32384.0,2.880440e+12,5.161115,476.00,1.862435,32660.0,240.089870,31981.400568,31888.0,...,267.806849,0.004544,RAD_TO_LUNG_4_STRONG_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STRONG,1
1,31677.0,32402.5,2.880912e+12,5.192882,483.00,1.937420,32680.0,244.096227,31983.966619,31887.0,...,273.219807,0.004517,RAD_TO_LUNG_4_STRONG_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STRONG,2
2,31677.0,32394.0,2.880706e+12,5.174742,487.25,1.898512,32698.0,245.014804,31982.822088,31881.0,...,293.014032,0.003552,RAD_TO_LUNG_4_STRONG_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STRONG,3
3,31696.0,32358.0,2.881056e+12,5.127969,434.25,1.903851,32629.0,221.635110,31984.970881,31917.0,...,289.915449,0.002278,RAD_TO_LUNG_2_STRONG_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STRONG,1
4,31699.0,32353.0,2.880700e+12,5.072668,434.00,1.877970,32594.0,219.151889,31983.027344,31910.5,...,230.881530,0.003779,RAD_TO_LUNG_2_STRONG_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STRONG,3
5,31692.0,32352.0,2.880427e+12,5.100500,431.00,1.891505,32569.0,218.796180,31981.502486,31914.0,...,232.409545,0.004460,RAD_TO_LUNG_2_STRONG_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STRONG,2
6,31651.0,32429.0,2.880742e+12,5.304778,530.00,1.968807,32777.0,263.317178,31982.814986,31878.0,...,380.246199,0.003100,RAD_TO_LUNG_4_STD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STD,3
7,31650.0,32437.5,2.880946e+12,5.325478,515.25,1.997157,32773.0,262.333265,31983.942472,31881.0,...,334.390852,0.006537,RAD_TO_LUNG_4_STD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STD,2
8,31652.0,32411.0,2.880243e+12,5.277224,507.25,1.927314,32743.0,256.666528,31980.122159,31881.5,...,341.810730,0.003787,RAD_TO_LUNG_4_STD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STD,1
9,31665.0,32385.0,2.880295e+12,5.235074,475.00,1.937299,32628.0,237.367165,31980.587003,31905.5,...,302.781274,0.004372,RAD_TO_LUNG_2_STD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STD,2
10,31646.0,32424.5,2.880210e+12,5.292451,500.00,1.921295,32640.0,253.443598,31979.954901,31897.0,...,328.895952,0.003665,RAD_TO_LUNG_2_MILD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,MILD,2
11,31656.0,32425.0,2.880643e+12,5.277027,492.25,1.938310,32692.0,253.073073,31982.370028,31886.5,...,333.935304,0.003844,RAD_TO_LUNG_2_MILD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,MILD,3
12,31674.5,32383.5,2.880666e+12,5.213872,473.00,1.928930,32645.0,238.114630,31982.650213,31898.5,...,297.475531,0.003810,RAD_TO_LUNG_2_STD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STD,3
13,31669.0,32396.0,2.880942e+12,5.265755,469.50,1.942098,32668.0,241.679518,31984.139560,31904.5,...,362.878975,0.002838,RAD_TO_LUNG_2_STD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STD,1
14,31656.0,32425.0,2.880643e+12,5.277027,492.25,1.938310,32692.0,253.073073,31982.370028,31886.5,...,333.935304,0.003844,RAD_TO_LUNG_2_MILD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,MILD,1
15,31632.0,32464.0,2.880417e+12,5.349261,541.25,1.920538,32727.0,276.225490,31980.876776,31869.0,...,348.086571,0.004650,RAD_TO_LUNG_4_MILD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,MILD,1
16,31632.5,32479.0,2.880692e+12,5.376782,554.00,1.953645,32799.0,281.456388,31982.334872,31868.0,...,386.841222,0.003977,RAD_TO_LUNG_4_MILD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,MILD,3
17,31629.0,32479.5,2.880921e+12,5.385028,554.00,1.960373,32783.0,281.187789,31983.605114,31872.0,...,355.516247,0.005289,RAD_TO_LUNG_4_MILD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,MILD,2
18,31566.5,32551.0,2.880831e+12,5.732485,604.00,2.203368,33002.0,320.716007,31982.515270,31870.5,...,1091.744385,0.000920,RAD_TO_LUNG_4_FBP_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,2
19,31569.0,32542.0,2.880415e+12,5.736196,605.50,2.251649,33047.0,320.224412,31980.210227,31868.0,...,1045.744658,0.001227,RAD_TO_LUNG_4_FBP_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,3
20,31567.5,32533.5,2.880523e+12,5.720235,598.50,2.230787,33144.0,318.336382,31980.844460,31873.0,...,917.880420,0.001463,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1

In [3]:
# Loding the GE csv files and joining them in a single dataframe
df_21 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect7_21.csv")
df_35 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect7_35.csv")
df_40 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect7_40.csv")
df_42 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect7_42.csv")
df_43 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect7_43.csv")

df = pd.concat([df_21, df_35, df_40, df_42, df_43], ignore_index=True)

#Elimino le colonne diagnostics
string_to_match = 'diagnostics'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
string_to_match = 'Unnamed:'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
df_GE = df
df_GE

,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,...,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,image_ID,Manufacturer,Slice Thickness,Pixel_Spacing,Kernel,Dose,ASIR,Num_Acquisition
0,32768.0,33716.2,1.774040e+12,4.280801,645.50,2.584220,34278.0,351.407899,33089.630247,32831.0,...,305.158342,0.011779,RAD_GE_LUNG_14_ASIR10_1,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,1
1,32768.0,33700.0,1.773899e+12,4.264081,665.00,2.514707,34214.0,347.808011,33088.385185,32835.5,...,301.254508,0.011399,RAD_GE_LUNG_14_ASIR10_2,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,2
2,32768.0,33719.5,3.194192e+12,4.368660,640.00,2.718449,34342.0,349.877350,33094.390947,32865.0,...,345.853366,0.011110,RAD_GE_LUNG_7_ASIR10_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,2
3,32768.0,33709.0,3.193161e+12,4.358713,632.50,2.714506,34323.0,345.696138,33089.100480,32854.0,...,335.897721,0.012424,RAD_GE_LUNG_7_ASIR10_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,3
4,32768.0,33715.0,3.193253e+12,4.291144,646.25,2.674418,34298.0,346.927443,33089.563443,32854.5,...,330.926285,0.011887,RAD_GE_LUNG_7_ASIR10_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,1
5,32792.0,33326.0,3.179897e+12,4.565493,375.00,1.938546,33545.0,187.167200,33022.037037,32992.5,...,79.839650,0.011624,RAD_GE_LUNG_7_ASIR40_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,1
6,32800.0,33339.0,3.181812e+12,4.609205,375.00,1.948077,33567.0,186.980671,33031.980453,33000.0,...,89.108473,0.010584,RAD_GE_LUNG_7_ASIR40_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,2
7,32803.0,33338.0,3.181395e+12,4.552915,371.00,1.955100,33546.0,185.084093,33029.832647,32996.0,...,87.128691,0.008570,RAD_GE_LUNG_7_ASIR40_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,3
8,32768.0,33704.5,3.192280e+12,4.254999,635.50,2.694833,34266.0,344.439142,33084.555213,32839.0,...,319.558634,0.011881,RAD_GE_LUNG_7_ASIR70_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,1
9,32768.0,33699.5,3.192367e+12,4.346185,627.50,2.731701,34291.0,343.280468,33085.019890,32842.0,...,316.882157,0.012038,RAD_GE_LUNG_7_ASIR70_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,3
10,32768.0,33714.5,3.193329e+12,4.332795,626.00,2.731237,34346.0,347.616005,33089.947531,32847.5,...,338.806789,0.011367,RAD_GE_LUNG_7_ASIR70_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,2
11,32768.0,33719.5,3.193123e+12,4.277026,645.00,2.625311,34246.0,351.376590,33088.846022,32835.0,...,325.273503,0.011306,RAD_GE_LUNG_14_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,1
12,32768.0,33695.0,3.192703e+12,4.262279,660.00,2.547594,34274.0,347.242747,33086.754801,32837.0,...,319.145904,0.011149,RAD_GE_LUNG_14_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,2
13,32768.0,33717.5,3.193480e+12,4.306562,646.25,2.669888,34306.0,347.587160,33090.727366,32857.5,...,335.047187,0.012531,RAD_GE_LUNG_7_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,1
14,32768.0,33710.5,3.193339e+12,4.364974,634.25,2.710217,34331.0,346.324347,33090.018176,32857.0,...,344.456489,0.013145,RAD_GE_LUNG_7_FBP_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,3
15,32768.0,33721.0,3.194388e+12,4.376990,643.25,2.715670,34341.0,350.504980,33095.398491,32866.5,...,346.487791,0.010704,RAD_GE_LUNG_7_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,2

In [4]:
df_TOGE = pd.concat([df_TO, df_GE], ignore_index=True)
df_TOGE

,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,...,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,image_ID,Manufacturer,Slice Thickness,Pixel_Spacing,Kernel,Dose,ASIR,Num_Acquisition
0,31677.0,32384.0,2.880440e+12,5.161115,476.00,1.862435,32660.0,240.089870,31981.400568,31888.0,...,267.806849,0.004544,RAD_TO_LUNG_4_STRONG_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STRONG,1
1,31677.0,32402.5,2.880912e+12,5.192882,483.00,1.937420,32680.0,244.096227,31983.966619,31887.0,...,273.219807,0.004517,RAD_TO_LUNG_4_STRONG_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STRONG,2
2,31677.0,32394.0,2.880706e+12,5.174742,487.25,1.898512,32698.0,245.014804,31982.822088,31881.0,...,293.014032,0.003552,RAD_TO_LUNG_4_STRONG_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STRONG,3
3,31696.0,32358.0,2.881056e+12,5.127969,434.25,1.903851,32629.0,221.635110,31984.970881,31917.0,...,289.915449,0.002278,RAD_TO_LUNG_2_STRONG_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STRONG,1
4,31699.0,32353.0,2.880700e+12,5.072668,434.00,1.877970,32594.0,219.151889,31983.027344,31910.5,...,230.881530,0.003779,RAD_TO_LUNG_2_STRONG_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STRONG,3
5,31692.0,32352.0,2.880427e+12,5.100500,431.00,1.891505,32569.0,218.796180,31981.502486,31914.0,...,232.409545,0.004460,RAD_TO_LUNG_2_STRONG_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STRONG,2
6,31651.0,32429.0,2.880742e+12,5.304778,530.00,1.968807,32777.0,263.317178,31982.814986,31878.0,...,380.246199,0.003100,RAD_TO_LUNG_4_STD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STD,3
7,31650.0,32437.5,2.880946e+12,5.325478,515.25,1.997157,32773.0,262.333265,31983.942472,31881.0,...,334.390852,0.006537,RAD_TO_LUNG_4_STD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STD,2
8,31652.0,32411.0,2.880243e+12,5.277224,507.25,1.927314,32743.0,256.666528,31980.122159,31881.5,...,341.810730,0.003787,RAD_TO_LUNG_4_STD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STD,1
9,31665.0,32385.0,2.880295e+12,5.235074,475.00,1.937299,32628.0,237.367165,31980.587003,31905.5,...,302.781274,0.004372,RAD_TO_LUNG_2_STD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STD,2
10,31646.0,32424.5,2.880210e+12,5.292451,500.00,1.921295,32640.0,253.443598,31979.954901,31897.0,...,328.895952,0.003665,RAD_TO_LUNG_2_MILD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,MILD,2
11,31656.0,32425.0,2.880643e+12,5.277027,492.25,1.938310,32692.0,253.073073,31982.370028,31886.5,...,333.935304,0.003844,RAD_TO_LUNG_2_MILD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,MILD,3
12,31674.5,32383.5,2.880666e+12,5.213872,473.00,1.928930,32645.0,238.114630,31982.650213,31898.5,...,297.475531,0.003810,RAD_TO_LUNG_2_STD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STD,3
13,31669.0,32396.0,2.880942e+12,5.265755,469.50,1.942098,32668.0,241.679518,31984.139560,31904.5,...,362.878975,0.002838,RAD_TO_LUNG_2_STD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STD,1
14,31656.0,32425.0,2.880643e+12,5.277027,492.25,1.938310,32692.0,253.073073,31982.370028,31886.5,...,333.935304,0.003844,RAD_TO_LUNG_2_MILD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,MILD,1
15,31632.0,32464.0,2.880417e+12,5.349261,541.25,1.920538,32727.0,276.225490,31980.876776,31869.0,...,348.086571,0.004650,RAD_TO_LUNG_4_MILD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,MILD,1
16,31632.5,32479.0,2.880692e+12,5.376782,554.00,1.953645,32799.0,281.456388,31982.334872,31868.0,...,386.841222,0.003977,RAD_TO_LUNG_4_MILD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,MILD,3
17,31629.0,32479.5,2.880921e+12,5.385028,554.00,1.960373,32783.0,281.187789,31983.605114,31872.0,...,355.516247,0.005289,RAD_TO_LUNG_4_MILD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,MILD,2
18,31566.5,32551.0,2.880831e+12,5.732485,604.00,2.203368,33002.0,320.716007,31982.515270,31870.5,...,1091.744385,0.000920,RAD_TO_LUNG_4_FBP_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,FBP,2
19,31569.0,32542.0,2.880415e+12,5.736196,605.50,2.251649,33047.0,320.224412,31980.210227,31868.0,...,1045.744658,0.001227,RAD_TO_LUNG_4_FBP_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,FBP,3
20,31567.5,32533.5,2.880523e+12,5.720235,598.50,2.230787,33144.0,318.336382,31980.844460,31873.0,...,917.880420,0.001463,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,FBP,1
21,32768.0,33716.2,1.774040e+12,4.280801,645.50,2.584220,34278.0,351.407899,33089.630247,32831.0,...,305.158342,0.011779,RAD_GE_LUNG_14_ASIR10_1,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,1
22,32768.0,33700.0,1.773899e+12,4.264081,665.00,2.514707,34214.0,347.808011,33088.385185,32835.5,...,301.254508,0.011399,RAD_GE_LUNG_14_ASIR10_2,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,2
23,32768.0,33719.5,3.194192e+12,4.368660,640.00,2.718449,34342.0,349.877350,33094.390947,32865.0,...,345.853366,0.011110,RAD_GE_LUNG_7_ASIR10_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,2
24,32768.0,33709.0,3.193161e+12,4.358713,632.50,2.714506,34323.0,345.696138,33089.100480,32854.0,...,335.897721,0.012424,RAD_GE_LUNG_7_ASIR10_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,3
25,32768.0,33715.0,3.193253e+12,4.291144,646.25,2.674418,34298.0,346.927443,33089.563443,32854.5,...,330.926285,0.011887,RAD_GE_LUNG_7_ASIR10_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,1
26,32792.0,33326.0,3.179897e+12,4.565493,375.00,1.938546,33545.0,187.167200,33022.037037,32992.5,...,79.839650,0.011624,RAD_GE_LUNG_7_ASIR40_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,1
27,32800.0,33339.0,3.181812e+12,4.609205,375.00,1.948077,33567.0,186.980671,33031.980453,33000.0,...,89.108473,0.010584,RAD_GE_LUNG_7_ASIR40_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,2
28,32803.0,33338.0,3.181395e+12,4.552915,371.00,1.955100,33546.0,185.084093,33029.832647,32996.0,...,87.128691,0.008570,RAD_GE_LUNG_7_ASIR40_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,3
29,32768.0,33704.5,3.192280e+12,4.254999,635.50,2.694833,34266.0,344.439142,33084.555213,32839.0,...,319.558634,0.011881,RAD_GE_LUNG_7_ASIR70_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,1
30,32768.0,33699.5,3.192367e+12,4.346185,627.50,2.731701,34291.0,343.280468,33085.019890,32842.0,...,316.882157,0.012038,RAD_GE_LUNG_7_ASIR70_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,3
31,32768.0,33714.5,3.193329e+12,4.332795,626.00,2.731237,34346.0,347.616005,33089.947531,32847.5,...,338.806789,0.011367,RAD_GE_LUNG_7_ASIR70_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,2
32,32768.0,33719.5,3.193123e+12,4.277026,645.00,2.625311,34246.0,351.376590,33088.846022,32835.0,...,325.273503,0.011306,RAD_GE_LUNG_14_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,1
33,32768.0,33695.0,3.192703e+12,4.262279,660.00,2.547594,34274.0,347.242747,33086.754801,32837.0,...,319.145904,0.011149,RAD_GE_LUNG_14_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,2
34,32768.0,33717.5,3.193480e+12,4.306562,646.25,2.669888,34306.0,347.587160,33090.727366,32857.5,...,335.047187,0.012531,RAD_GE_LUNG_7_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,1
35,32768.0,33710.5,3.193339e+12,4.364974,634.25,2.710217,34331.0,346.324347,33090.018176,32857.0,...,344.456489,0.013145,RAD_GE_LUNG_7_FBP_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,3
36,32768.0,33721.0,3.194388e+12,4.376990,643.25,2.715670,34341.0,350.504980,33095.398491,32866.5,...,346.487791,0.010704,RAD_GE_LUNG_7_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,2

In [5]:
#Save the dataframe in a csv file
df_TOGE.to_csv('../../../RadiomiK/Features_Global/rect7_glob.csv', index=False)