In [1]:
import pandas as pd
import pingouin as pg
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import statsmodels.api as sm

In [ ]:
# Loding the TO csv file
df = pd.read_csv("../../RadiomiK/Features_TO/Final/rect8.csv")
#Elimino le colonne diagnostics
string_to_match = 'diagnostics'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
string_to_match = 'Unnamed:'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
df_TO = df
df_TO

,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,...,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,image_ID,Manufacturer,Slice Thickness,Pixel_Spacing,Kernel,Dose,ASIR,Num_Acquisition
0,32101.0,32799.0,2.967909e+12,5.268557,481.00,1.855910,33097.0,234.829962,32463.409446,32506.0,...,459.777582,0.002533,RAD_TO_LUNG_4_STRONG_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STRONG,1
1,32098.0,32791.5,2.967636e+12,5.252377,487.25,1.827105,33040.0,236.086683,32461.910511,32509.5,...,425.699940,0.002800,RAD_TO_LUNG_4_STRONG_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STRONG,2
2,32097.5,32798.0,2.967711e+12,5.268249,491.00,1.847142,33080.0,236.569813,32462.304688,32503.0,...,441.834593,0.002755,RAD_TO_LUNG_4_STRONG_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STRONG,3
3,32163.5,32713.0,2.965336e+12,4.947152,372.00,1.894309,32889.0,182.262817,32449.761719,32480.0,...,242.171110,0.004424,RAD_TO_LUNG_2_STRONG_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STRONG,1
4,32168.0,32710.5,2.965236e+12,4.942520,362.00,1.899954,32918.0,180.635555,32449.229759,32479.0,...,239.344752,0.003770,RAD_TO_LUNG_2_STRONG_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STRONG,3
5,32160.0,32710.5,2.964828e+12,4.967320,369.00,1.916655,32913.0,184.156392,32446.976918,32480.0,...,317.038760,0.002429,RAD_TO_LUNG_2_STRONG_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STRONG,2
6,32035.5,32868.0,2.969286e+12,5.491153,587.00,1.825079,33214.0,281.105476,32470.462003,32518.5,...,661.400684,0.002317,RAD_TO_LUNG_4_STD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STD,3
7,32034.0,32860.0,2.969274e+12,5.483798,581.00,1.815675,33233.0,281.839778,32470.401278,32528.0,...,650.470021,0.002794,RAD_TO_LUNG_4_STD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STD,2
8,32038.5,32866.0,2.969689e+12,5.506529,578.00,1.863763,33264.0,280.612087,32472.670455,32520.0,...,679.664798,0.002349,RAD_TO_LUNG_4_STD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STD,1
9,32103.0,32783.0,2.966650e+12,5.251597,464.00,1.883749,33056.0,228.266463,32456.582031,32495.0,...,507.863944,0.002044,RAD_TO_LUNG_2_STD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STD,2
10,31975.5,32798.5,2.962156e+12,5.417203,529.25,1.877574,33054.0,266.036104,32431.587713,32495.5,...,545.841074,0.004112,RAD_TO_LUNG_2_MILD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,MILD,2
11,31979.5,32799.5,2.962562e+12,5.411324,533.25,1.899134,33058.0,262.592271,32433.835582,32498.5,...,611.272779,0.002271,RAD_TO_LUNG_2_MILD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,MILD,3
12,32111.5,32775.0,2.967167e+12,5.224900,461.25,1.858515,33026.0,223.975156,32459.445668,32501.0,...,414.146115,0.003347,RAD_TO_LUNG_2_STD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STD,3
13,32115.0,32783.0,2.967213e+12,5.224860,463.00,1.875089,33025.0,224.130719,32459.688565,32497.0,...,401.497882,0.003385,RAD_TO_LUNG_2_STD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STD,1
14,31979.5,32799.5,2.962562e+12,5.411324,533.25,1.899134,33058.0,262.592271,32433.835582,32498.5,...,611.272779,0.002271,RAD_TO_LUNG_2_MILD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,MILD,1
15,31885.0,32881.0,2.963802e+12,5.652361,667.00,1.827374,33267.0,325.016235,32439.900213,32520.0,...,815.971760,0.002605,RAD_TO_LUNG_4_MILD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,MILD,1
16,31887.5,32882.5,2.963573e+12,5.621170,675.00,1.783349,33217.0,325.571471,32438.649858,32519.0,...,739.986151,0.004828,RAD_TO_LUNG_4_MILD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,MILD,3
17,31881.5,32874.5,2.963383e+12,5.633107,666.25,1.804844,33232.0,326.162966,32437.609730,32528.5,...,796.355245,0.002695,RAD_TO_LUNG_4_MILD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,MILD,2
18,31603.5,32941.0,2.956776e+12,6.129004,764.00,2.376825,33392.0,422.324363,32399.692116,32540.0,...,2543.649732,0.001000,RAD_TO_LUNG_4_FBP_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,2
19,31612.5,32947.5,2.957207e+12,6.121985,776.50,2.305267,33639.0,421.067791,32402.088778,32530.5,...,2242.951774,0.001490,RAD_TO_LUNG_4_FBP_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,3
20,31600.5,32958.5,2.957245e+12,6.129911,757.50,2.359918,33411.0,421.679332,32402.250000,32525.5,...,2605.235221,0.000867,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1

In [3]:
# Loding the GE csv files and joining them in a single dataframe
df_21 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect8_21.csv")
df_35 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect8_35.csv")
df_40 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect8_40.csv")
df_42 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect8_42.csv")
df_43 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect8_43.csv")

df = pd.concat([df_21, df_35, df_40, df_42, df_43], ignore_index=True)

#Elimino le colonne diagnostics
string_to_match = 'diagnostics'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
string_to_match = 'Unnamed:'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
df_GE = df
df_GE

,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,...,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,image_ID,Manufacturer,Slice Thickness,Pixel_Spacing,Kernel,Dose,ASIR,Num_Acquisition
0,32768.0,34332.3,1.827067e+12,5.373356,1319.50,1.520760,34658.0,550.564929,33577.432099,33694.5,...,1325.040187,0.010314,RAD_GE_LUNG_14_ASIR10_1,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,1
1,32768.0,34332.1,1.826631e+12,5.353222,1291.75,1.543865,34633.0,540.001125,33573.596296,33703.5,...,1284.971062,0.009851,RAD_GE_LUNG_14_ASIR10_2,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,2
2,32768.0,34341.0,3.288842e+12,5.434932,1315.00,1.567904,34924.0,550.007526,33577.992455,33685.0,...,1328.747220,0.009544,RAD_GE_LUNG_7_ASIR10_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,2
3,32768.0,34341.0,3.288594e+12,5.435838,1289.25,1.569311,34768.0,542.136101,33576.857682,33675.5,...,1350.473603,0.008977,RAD_GE_LUNG_7_ASIR10_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,3
4,32768.0,34341.0,3.288596e+12,5.408860,1315.25,1.564004,34897.0,548.539604,33576.783265,33685.0,...,1361.473222,0.008905,RAD_GE_LUNG_7_ASIR10_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,1
5,33065.0,33643.5,3.258354e+12,4.765001,318.00,2.492166,33765.0,181.043546,33426.921811,33500.0,...,233.907301,0.004116,RAD_GE_LUNG_7_ASIR40_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,1
6,33073.0,33646.5,3.258944e+12,4.764688,322.00,2.500159,33776.0,180.374088,33429.951989,33502.0,...,244.506281,0.002871,RAD_GE_LUNG_7_ASIR40_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,2
7,33070.0,33644.5,3.259015e+12,4.748828,321.00,2.493542,33755.0,178.254291,33430.329561,33500.5,...,211.866737,0.005966,RAD_GE_LUNG_7_ASIR40_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,3
8,32768.0,34323.0,3.287359e+12,5.419132,1287.50,1.565873,34845.0,540.215289,33570.621742,33680.5,...,1282.754382,0.009395,RAD_GE_LUNG_7_ASIR70_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,1
9,32768.0,34328.0,3.287487e+12,5.437775,1266.25,1.576084,34742.0,534.251274,33571.346365,33669.5,...,1313.393476,0.008751,RAD_GE_LUNG_7_ASIR70_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,3
10,32768.0,34334.0,3.287631e+12,5.423734,1292.75,1.569127,34882.0,541.782904,33571.967421,33680.5,...,1291.210852,0.009626,RAD_GE_LUNG_7_ASIR70_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,2
11,32768.0,34345.0,3.289222e+12,5.409452,1319.25,1.525984,34704.0,555.428503,33579.888203,33694.5,...,1309.032827,0.008941,RAD_GE_LUNG_14_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,1
12,32768.0,34340.0,3.288216e+12,5.374027,1310.50,1.545007,34704.0,544.231023,33574.940329,33696.0,...,1290.140947,0.008705,RAD_GE_LUNG_14_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,2
13,32768.0,34345.5,3.288900e+12,5.408714,1324.50,1.564055,34909.0,550.626119,33578.293896,33686.5,...,1360.069581,0.008654,RAD_GE_LUNG_7_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,1
14,32768.0,34343.0,3.288864e+12,5.434473,1292.50,1.568043,34777.0,544.183627,33578.198903,33677.5,...,1357.796378,0.009116,RAD_GE_LUNG_7_FBP_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,3
15,32768.0,34345.5,3.289143e+12,5.434456,1325.25,1.568027,34935.0,552.116511,33579.485254,33685.5,...,1338.239462,0.009756,RAD_GE_LUNG_7_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,2

In [4]:
df_TOGE = pd.concat([df_TO, df_GE], ignore_index=True)
df_TOGE

,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,...,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,image_ID,Manufacturer,Slice Thickness,Pixel_Spacing,Kernel,Dose,ASIR,Num_Acquisition
0,32101.0,32799.0,2.967909e+12,5.268557,481.00,1.855910,33097.0,234.829962,32463.409446,32506.0,...,459.777582,0.002533,RAD_TO_LUNG_4_STRONG_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STRONG,1
1,32098.0,32791.5,2.967636e+12,5.252377,487.25,1.827105,33040.0,236.086683,32461.910511,32509.5,...,425.699940,0.002800,RAD_TO_LUNG_4_STRONG_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STRONG,2
2,32097.5,32798.0,2.967711e+12,5.268249,491.00,1.847142,33080.0,236.569813,32462.304688,32503.0,...,441.834593,0.002755,RAD_TO_LUNG_4_STRONG_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STRONG,3
3,32163.5,32713.0,2.965336e+12,4.947152,372.00,1.894309,32889.0,182.262817,32449.761719,32480.0,...,242.171110,0.004424,RAD_TO_LUNG_2_STRONG_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STRONG,1
4,32168.0,32710.5,2.965236e+12,4.942520,362.00,1.899954,32918.0,180.635555,32449.229759,32479.0,...,239.344752,0.003770,RAD_TO_LUNG_2_STRONG_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STRONG,3
5,32160.0,32710.5,2.964828e+12,4.967320,369.00,1.916655,32913.0,184.156392,32446.976918,32480.0,...,317.038760,0.002429,RAD_TO_LUNG_2_STRONG_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STRONG,2
6,32035.5,32868.0,2.969286e+12,5.491153,587.00,1.825079,33214.0,281.105476,32470.462003,32518.5,...,661.400684,0.002317,RAD_TO_LUNG_4_STD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STD,3
7,32034.0,32860.0,2.969274e+12,5.483798,581.00,1.815675,33233.0,281.839778,32470.401278,32528.0,...,650.470021,0.002794,RAD_TO_LUNG_4_STD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STD,2
8,32038.5,32866.0,2.969689e+12,5.506529,578.00,1.863763,33264.0,280.612087,32472.670455,32520.0,...,679.664798,0.002349,RAD_TO_LUNG_4_STD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STD,1
9,32103.0,32783.0,2.966650e+12,5.251597,464.00,1.883749,33056.0,228.266463,32456.582031,32495.0,...,507.863944,0.002044,RAD_TO_LUNG_2_STD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STD,2
10,31975.5,32798.5,2.962156e+12,5.417203,529.25,1.877574,33054.0,266.036104,32431.587713,32495.5,...,545.841074,0.004112,RAD_TO_LUNG_2_MILD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,MILD,2
11,31979.5,32799.5,2.962562e+12,5.411324,533.25,1.899134,33058.0,262.592271,32433.835582,32498.5,...,611.272779,0.002271,RAD_TO_LUNG_2_MILD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,MILD,3
12,32111.5,32775.0,2.967167e+12,5.224900,461.25,1.858515,33026.0,223.975156,32459.445668,32501.0,...,414.146115,0.003347,RAD_TO_LUNG_2_STD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STD,3
13,32115.0,32783.0,2.967213e+12,5.224860,463.00,1.875089,33025.0,224.130719,32459.688565,32497.0,...,401.497882,0.003385,RAD_TO_LUNG_2_STD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STD,1
14,31979.5,32799.5,2.962562e+12,5.411324,533.25,1.899134,33058.0,262.592271,32433.835582,32498.5,...,611.272779,0.002271,RAD_TO_LUNG_2_MILD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,MILD,1
15,31885.0,32881.0,2.963802e+12,5.652361,667.00,1.827374,33267.0,325.016235,32439.900213,32520.0,...,815.971760,0.002605,RAD_TO_LUNG_4_MILD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,MILD,1
16,31887.5,32882.5,2.963573e+12,5.621170,675.00,1.783349,33217.0,325.571471,32438.649858,32519.0,...,739.986151,0.004828,RAD_TO_LUNG_4_MILD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,MILD,3
17,31881.5,32874.5,2.963383e+12,5.633107,666.25,1.804844,33232.0,326.162966,32437.609730,32528.5,...,796.355245,0.002695,RAD_TO_LUNG_4_MILD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,MILD,2
18,31603.5,32941.0,2.956776e+12,6.129004,764.00,2.376825,33392.0,422.324363,32399.692116,32540.0,...,2543.649732,0.001000,RAD_TO_LUNG_4_FBP_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,FBP,2
19,31612.5,32947.5,2.957207e+12,6.121985,776.50,2.305267,33639.0,421.067791,32402.088778,32530.5,...,2242.951774,0.001490,RAD_TO_LUNG_4_FBP_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,FBP,3
20,31600.5,32958.5,2.957245e+12,6.129911,757.50,2.359918,33411.0,421.679332,32402.250000,32525.5,...,2605.235221,0.000867,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,FBP,1
21,32768.0,34332.3,1.827067e+12,5.373356,1319.50,1.520760,34658.0,550.564929,33577.432099,33694.5,...,1325.040187,0.010314,RAD_GE_LUNG_14_ASIR10_1,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,1
22,32768.0,34332.1,1.826631e+12,5.353222,1291.75,1.543865,34633.0,540.001125,33573.596296,33703.5,...,1284.971062,0.009851,RAD_GE_LUNG_14_ASIR10_2,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,2
23,32768.0,34341.0,3.288842e+12,5.434932,1315.00,1.567904,34924.0,550.007526,33577.992455,33685.0,...,1328.747220,0.009544,RAD_GE_LUNG_7_ASIR10_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,2
24,32768.0,34341.0,3.288594e+12,5.435838,1289.25,1.569311,34768.0,542.136101,33576.857682,33675.5,...,1350.473603,0.008977,RAD_GE_LUNG_7_ASIR10_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,3
25,32768.0,34341.0,3.288596e+12,5.408860,1315.25,1.564004,34897.0,548.539604,33576.783265,33685.0,...,1361.473222,0.008905,RAD_GE_LUNG_7_ASIR10_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,1
26,33065.0,33643.5,3.258354e+12,4.765001,318.00,2.492166,33765.0,181.043546,33426.921811,33500.0,...,233.907301,0.004116,RAD_GE_LUNG_7_ASIR40_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,1
27,33073.0,33646.5,3.258944e+12,4.764688,322.00,2.500159,33776.0,180.374088,33429.951989,33502.0,...,244.506281,0.002871,RAD_GE_LUNG_7_ASIR40_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,2
28,33070.0,33644.5,3.259015e+12,4.748828,321.00,2.493542,33755.0,178.254291,33430.329561,33500.5,...,211.866737,0.005966,RAD_GE_LUNG_7_ASIR40_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,3
29,32768.0,34323.0,3.287359e+12,5.419132,1287.50,1.565873,34845.0,540.215289,33570.621742,33680.5,...,1282.754382,0.009395,RAD_GE_LUNG_7_ASIR70_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,1
30,32768.0,34328.0,3.287487e+12,5.437775,1266.25,1.576084,34742.0,534.251274,33571.346365,33669.5,...,1313.393476,0.008751,RAD_GE_LUNG_7_ASIR70_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,3
31,32768.0,34334.0,3.287631e+12,5.423734,1292.75,1.569127,34882.0,541.782904,33571.967421,33680.5,...,1291.210852,0.009626,RAD_GE_LUNG_7_ASIR70_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,2
32,32768.0,34345.0,3.289222e+12,5.409452,1319.25,1.525984,34704.0,555.428503,33579.888203,33694.5,...,1309.032827,0.008941,RAD_GE_LUNG_14_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,1
33,32768.0,34340.0,3.288216e+12,5.374027,1310.50,1.545007,34704.0,544.231023,33574.940329,33696.0,...,1290.140947,0.008705,RAD_GE_LUNG_14_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,2
34,32768.0,34345.5,3.288900e+12,5.408714,1324.50,1.564055,34909.0,550.626119,33578.293896,33686.5,...,1360.069581,0.008654,RAD_GE_LUNG_7_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,1
35,32768.0,34343.0,3.288864e+12,5.434473,1292.50,1.568043,34777.0,544.183627,33578.198903,33677.5,...,1357.796378,0.009116,RAD_GE_LUNG_7_FBP_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,3
36,32768.0,34345.5,3.289143e+12,5.434456,1325.25,1.568027,34935.0,552.116511,33579.485254,33685.5,...,1338.239462,0.009756,RAD_GE_LUNG_7_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,2

In [5]:
#Save the dataframe in a csv file
df_TOGE.to_csv('../../../RadiomiK/Features_Global/rect8_glob.csv', index=False)