In [1]:
import pandas as pd
import pingouin as pg
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import statsmodels.api as sm

In [ ]:
# Loding the TO csv file
df = pd.read_csv("../../RadiomiK/Features_TO/Final/rect11.csv")
#Elimino le colonne diagnostics
string_to_match = 'diagnostics'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
string_to_match = 'Unnamed:'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
df_TO = df
df_TO

,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,...,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,image_ID,Manufacturer,Slice Thickness,Pixel_Spacing,Kernel,Dose,ASIR,Num_Acquisition
0,31737.0,32212.0,2.879503e+12,4.734075,313.00,1.840086,32368.0,155.006008,31976.853338,31982.0,...,177.072560,0.004536,RAD_TO_LUNG_4_STRONG_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STRONG,1
1,31746.0,32208.0,2.879982e+12,4.730076,310.25,1.880399,32379.0,153.973178,31979.515625,31983.0,...,205.078754,0.003804,RAD_TO_LUNG_4_STRONG_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STRONG,2
2,31741.0,32209.0,2.879901e+12,4.718036,306.25,1.848552,32352.0,154.028125,31979.069247,31982.0,...,147.975123,0.010735,RAD_TO_LUNG_4_STRONG_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STRONG,3
3,31794.5,32171.5,2.880698e+12,4.442664,243.25,1.943360,32330.0,122.636006,31983.667259,31985.0,...,114.358065,0.005082,RAD_TO_LUNG_2_STRONG_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STRONG,1
4,31790.0,32169.0,2.880619e+12,4.460534,244.00,1.973815,32311.0,123.625909,31983.221946,31986.0,...,145.352787,0.003344,RAD_TO_LUNG_2_STRONG_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STRONG,3
5,31791.0,32171.0,2.880579e+12,4.477220,248.25,1.962851,32299.0,125.000759,31982.995739,31985.0,...,117.086948,0.006685,RAD_TO_LUNG_2_STRONG_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STRONG,2
6,31709.0,32238.0,2.879409e+12,4.893169,349.25,1.838990,32397.0,174.801164,31976.202770,31982.5,...,213.670564,0.011112,RAD_TO_LUNG_4_STD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STD,3
7,31715.0,32239.0,2.879589e+12,4.911107,355.25,1.869668,32430.0,174.622950,31977.193537,31978.0,...,291.105774,0.002805,RAD_TO_LUNG_4_STD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STD,2
8,31702.5,32239.0,2.878983e+12,4.913646,358.25,1.834075,32424.0,176.158134,31973.823153,31977.0,...,224.771608,0.005973,RAD_TO_LUNG_4_STD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STD,1
9,31758.0,32203.0,2.880123e+12,4.716403,295.00,1.958114,32354.0,148.295465,31980.330966,31982.0,...,187.584315,0.004529,RAD_TO_LUNG_2_STD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STD,2
10,31723.0,32241.0,2.880368e+12,4.893725,328.50,1.949502,32444.0,166.682242,31981.559659,31979.0,...,230.791336,0.005151,RAD_TO_LUNG_2_MILD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,MILD,2
11,31723.0,32241.5,2.880422e+12,4.881551,319.25,1.957442,32421.0,164.736947,31981.873580,31981.0,...,232.392500,0.004667,RAD_TO_LUNG_2_MILD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,MILD,3
12,31757.0,32201.5,2.880121e+12,4.696498,288.00,1.960384,32377.0,145.961791,31980.330611,31983.0,...,205.612651,0.003423,RAD_TO_LUNG_2_STD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STD,3
13,31759.0,32202.0,2.880218e+12,4.686301,293.00,1.917867,32408.0,146.450894,31980.871804,31979.0,...,170.989935,0.005376,RAD_TO_LUNG_2_STD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STD,1
14,31723.0,32241.5,2.880422e+12,4.881551,319.25,1.957442,32421.0,164.736947,31981.873580,31981.0,...,232.392500,0.004667,RAD_TO_LUNG_2_MILD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,MILD,1
15,31677.0,32292.5,2.879579e+12,5.075142,394.00,1.851909,32463.0,196.334348,31976.960227,31975.0,...,303.447537,0.004271,RAD_TO_LUNG_4_MILD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,MILD,1
16,31677.0,32286.5,2.879935e+12,5.056955,390.00,1.839527,32460.0,195.201261,31978.953125,31980.0,...,260.592196,0.009611,RAD_TO_LUNG_4_MILD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,MILD,3
17,31676.5,32284.0,2.879957e+12,5.072455,390.25,1.862805,32511.0,194.759370,31979.074574,31976.5,...,335.896903,0.003560,RAD_TO_LUNG_4_MILD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,MILD,2
18,31606.0,32361.0,2.880141e+12,5.493898,436.00,2.295598,32817.0,236.043232,31979.636719,31973.5,...,633.224565,0.003741,RAD_TO_LUNG_4_FBP_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,2
19,31617.0,32364.0,2.880290e+12,5.487111,434.00,2.306006,32782.0,235.968419,31980.469460,31968.0,...,783.584064,0.001565,RAD_TO_LUNG_4_FBP_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,3
20,31616.5,32377.5,2.879882e+12,5.500282,442.00,2.315578,32781.0,237.251004,31978.183239,31969.5,...,623.031979,0.003806,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1

In [3]:
# Loding the GE csv files and joining them in a single dataframe
df_21 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect11_21.csv")
df_35 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect11_35.csv")
df_40 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect11_40.csv")
df_42 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect11_42.csv")
df_43 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect11_43.csv")

df = pd.concat([df_21, df_35, df_40, df_42, df_43], ignore_index=True)

#Elimino le colonne diagnostics
string_to_match = 'diagnostics'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
string_to_match = 'Unnamed:'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
df_GE = df
df_GE

,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,...,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,image_ID,Manufacturer,Slice Thickness,Pixel_Spacing,Kernel,Dose,ASIR,Num_Acquisition
0,32768.0,33287.0,1.767015e+12,4.668706,298.25,2.122227,33573.0,157.218717,33025.984568,33020.0,...,131.869483,0.034848,RAD_GE_LUNG_14_ASIR10_1,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,1
1,32768.0,33297.0,1.767643e+12,4.679564,302.25,2.106098,33578.0,160.023350,33031.839506,33024.5,...,137.619490,0.031410,RAD_GE_LUNG_14_ASIR10_2,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,2
2,32768.0,33435.0,3.185674e+12,4.597171,484.00,2.103416,33840.0,223.810253,33051.684499,33006.0,...,198.710805,0.019064,RAD_GE_LUNG_7_ASIR10_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,2
3,32768.0,33450.5,3.187662e+12,4.646162,504.25,2.037225,33771.0,232.314998,33061.936557,33015.0,...,204.667535,0.018789,RAD_GE_LUNG_7_ASIR10_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,3
4,32768.0,33462.0,3.187863e+12,4.604242,517.00,2.099872,33883.0,237.744332,33062.919067,33019.0,...,214.203521,0.018326,RAD_GE_LUNG_7_ASIR10_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,1
5,32872.0,33152.0,3.179997e+12,4.014119,162.00,2.146182,33283.0,86.842254,33023.070645,33034.0,...,45.684384,0.013075,RAD_GE_LUNG_7_ASIR40_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,1
6,32880.0,33143.0,3.179332e+12,3.915419,150.00,2.177949,33261.0,80.409788,33019.640604,33028.0,...,40.415439,0.009389,RAD_GE_LUNG_7_ASIR40_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,2
7,32882.0,33153.0,3.180978e+12,3.964278,156.00,2.115175,33264.0,84.023208,33028.177984,33038.5,...,43.489422,0.009158,RAD_GE_LUNG_7_ASIR40_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,3
8,32768.0,33444.0,3.187095e+12,4.612909,504.00,2.100858,33868.0,231.074171,33058.996914,33019.0,...,207.912686,0.019079,RAD_GE_LUNG_7_ASIR70_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,1
9,32768.0,33432.0,3.186930e+12,4.637224,485.00,2.031970,33749.0,225.246504,33058.202675,33018.0,...,203.572538,0.018467,RAD_GE_LUNG_7_ASIR70_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,3
10,32768.0,33413.0,3.184849e+12,4.607459,461.50,2.097481,33795.0,216.029842,33047.472565,33008.0,...,183.571338,0.020317,RAD_GE_LUNG_7_ASIR70_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,2
11,32768.0,33457.5,3.187191e+12,4.521871,518.00,1.884100,33756.0,240.972282,33059.441701,33011.0,...,208.775927,0.017491,RAD_GE_LUNG_14_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,1
12,32768.0,33458.0,3.187863e+12,4.538142,530.00,1.859088,33883.0,241.939038,33062.921468,33021.0,...,213.674965,0.016764,RAD_GE_LUNG_14_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,2
13,32768.0,33466.0,3.188041e+12,4.598018,519.00,2.100799,33887.0,239.359213,33063.823731,33019.0,...,215.932813,0.017928,RAD_GE_LUNG_7_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,1
14,32768.0,33455.5,3.187832e+12,4.647553,509.50,2.039873,33777.0,233.980806,33062.805213,33014.0,...,212.021779,0.019185,RAD_GE_LUNG_7_FBP_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,3
15,32768.0,33441.5,3.185872e+12,4.596123,489.25,2.106194,33850.0,225.698681,33052.697188,33007.0,...,203.841568,0.018399,RAD_GE_LUNG_7_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,2

In [4]:
df_TOGE = pd.concat([df_TO, df_GE], ignore_index=True)
df_TOGE

,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,...,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,image_ID,Manufacturer,Slice Thickness,Pixel_Spacing,Kernel,Dose,ASIR,Num_Acquisition
0,31737.0,32212.0,2.879503e+12,4.734075,313.00,1.840086,32368.0,155.006008,31976.853338,31982.0,...,177.072560,0.004536,RAD_TO_LUNG_4_STRONG_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STRONG,1
1,31746.0,32208.0,2.879982e+12,4.730076,310.25,1.880399,32379.0,153.973178,31979.515625,31983.0,...,205.078754,0.003804,RAD_TO_LUNG_4_STRONG_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STRONG,2
2,31741.0,32209.0,2.879901e+12,4.718036,306.25,1.848552,32352.0,154.028125,31979.069247,31982.0,...,147.975123,0.010735,RAD_TO_LUNG_4_STRONG_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STRONG,3
3,31794.5,32171.5,2.880698e+12,4.442664,243.25,1.943360,32330.0,122.636006,31983.667259,31985.0,...,114.358065,0.005082,RAD_TO_LUNG_2_STRONG_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STRONG,1
4,31790.0,32169.0,2.880619e+12,4.460534,244.00,1.973815,32311.0,123.625909,31983.221946,31986.0,...,145.352787,0.003344,RAD_TO_LUNG_2_STRONG_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STRONG,3
5,31791.0,32171.0,2.880579e+12,4.477220,248.25,1.962851,32299.0,125.000759,31982.995739,31985.0,...,117.086948,0.006685,RAD_TO_LUNG_2_STRONG_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STRONG,2
6,31709.0,32238.0,2.879409e+12,4.893169,349.25,1.838990,32397.0,174.801164,31976.202770,31982.5,...,213.670564,0.011112,RAD_TO_LUNG_4_STD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STD,3
7,31715.0,32239.0,2.879589e+12,4.911107,355.25,1.869668,32430.0,174.622950,31977.193537,31978.0,...,291.105774,0.002805,RAD_TO_LUNG_4_STD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STD,2
8,31702.5,32239.0,2.878983e+12,4.913646,358.25,1.834075,32424.0,176.158134,31973.823153,31977.0,...,224.771608,0.005973,RAD_TO_LUNG_4_STD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STD,1
9,31758.0,32203.0,2.880123e+12,4.716403,295.00,1.958114,32354.0,148.295465,31980.330966,31982.0,...,187.584315,0.004529,RAD_TO_LUNG_2_STD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STD,2
10,31723.0,32241.0,2.880368e+12,4.893725,328.50,1.949502,32444.0,166.682242,31981.559659,31979.0,...,230.791336,0.005151,RAD_TO_LUNG_2_MILD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,MILD,2
11,31723.0,32241.5,2.880422e+12,4.881551,319.25,1.957442,32421.0,164.736947,31981.873580,31981.0,...,232.392500,0.004667,RAD_TO_LUNG_2_MILD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,MILD,3
12,31757.0,32201.5,2.880121e+12,4.696498,288.00,1.960384,32377.0,145.961791,31980.330611,31983.0,...,205.612651,0.003423,RAD_TO_LUNG_2_STD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STD,3
13,31759.0,32202.0,2.880218e+12,4.686301,293.00,1.917867,32408.0,146.450894,31980.871804,31979.0,...,170.989935,0.005376,RAD_TO_LUNG_2_STD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STD,1
14,31723.0,32241.5,2.880422e+12,4.881551,319.25,1.957442,32421.0,164.736947,31981.873580,31981.0,...,232.392500,0.004667,RAD_TO_LUNG_2_MILD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,MILD,1
15,31677.0,32292.5,2.879579e+12,5.075142,394.00,1.851909,32463.0,196.334348,31976.960227,31975.0,...,303.447537,0.004271,RAD_TO_LUNG_4_MILD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,MILD,1
16,31677.0,32286.5,2.879935e+12,5.056955,390.00,1.839527,32460.0,195.201261,31978.953125,31980.0,...,260.592196,0.009611,RAD_TO_LUNG_4_MILD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,MILD,3
17,31676.5,32284.0,2.879957e+12,5.072455,390.25,1.862805,32511.0,194.759370,31979.074574,31976.5,...,335.896903,0.003560,RAD_TO_LUNG_4_MILD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,MILD,2
18,31606.0,32361.0,2.880141e+12,5.493898,436.00,2.295598,32817.0,236.043232,31979.636719,31973.5,...,633.224565,0.003741,RAD_TO_LUNG_4_FBP_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,FBP,2
19,31617.0,32364.0,2.880290e+12,5.487111,434.00,2.306006,32782.0,235.968419,31980.469460,31968.0,...,783.584064,0.001565,RAD_TO_LUNG_4_FBP_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,FBP,3
20,31616.5,32377.5,2.879882e+12,5.500282,442.00,2.315578,32781.0,237.251004,31978.183239,31969.5,...,623.031979,0.003806,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,FBP,1
21,32768.0,33287.0,1.767015e+12,4.668706,298.25,2.122227,33573.0,157.218717,33025.984568,33020.0,...,131.869483,0.034848,RAD_GE_LUNG_14_ASIR10_1,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,1
22,32768.0,33297.0,1.767643e+12,4.679564,302.25,2.106098,33578.0,160.023350,33031.839506,33024.5,...,137.619490,0.031410,RAD_GE_LUNG_14_ASIR10_2,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,2
23,32768.0,33435.0,3.185674e+12,4.597171,484.00,2.103416,33840.0,223.810253,33051.684499,33006.0,...,198.710805,0.019064,RAD_GE_LUNG_7_ASIR10_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,2
24,32768.0,33450.5,3.187662e+12,4.646162,504.25,2.037225,33771.0,232.314998,33061.936557,33015.0,...,204.667535,0.018789,RAD_GE_LUNG_7_ASIR10_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,3
25,32768.0,33462.0,3.187863e+12,4.604242,517.00,2.099872,33883.0,237.744332,33062.919067,33019.0,...,214.203521,0.018326,RAD_GE_LUNG_7_ASIR10_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,1
26,32872.0,33152.0,3.179997e+12,4.014119,162.00,2.146182,33283.0,86.842254,33023.070645,33034.0,...,45.684384,0.013075,RAD_GE_LUNG_7_ASIR40_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,1
27,32880.0,33143.0,3.179332e+12,3.915419,150.00,2.177949,33261.0,80.409788,33019.640604,33028.0,...,40.415439,0.009389,RAD_GE_LUNG_7_ASIR40_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,2
28,32882.0,33153.0,3.180978e+12,3.964278,156.00,2.115175,33264.0,84.023208,33028.177984,33038.5,...,43.489422,0.009158,RAD_GE_LUNG_7_ASIR40_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,3
29,32768.0,33444.0,3.187095e+12,4.612909,504.00,2.100858,33868.0,231.074171,33058.996914,33019.0,...,207.912686,0.019079,RAD_GE_LUNG_7_ASIR70_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,1
30,32768.0,33432.0,3.186930e+12,4.637224,485.00,2.031970,33749.0,225.246504,33058.202675,33018.0,...,203.572538,0.018467,RAD_GE_LUNG_7_ASIR70_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,3
31,32768.0,33413.0,3.184849e+12,4.607459,461.50,2.097481,33795.0,216.029842,33047.472565,33008.0,...,183.571338,0.020317,RAD_GE_LUNG_7_ASIR70_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,2
32,32768.0,33457.5,3.187191e+12,4.521871,518.00,1.884100,33756.0,240.972282,33059.441701,33011.0,...,208.775927,0.017491,RAD_GE_LUNG_14_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,1
33,32768.0,33458.0,3.187863e+12,4.538142,530.00,1.859088,33883.0,241.939038,33062.921468,33021.0,...,213.674965,0.016764,RAD_GE_LUNG_14_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,2
34,32768.0,33466.0,3.188041e+12,4.598018,519.00,2.100799,33887.0,239.359213,33063.823731,33019.0,...,215.932813,0.017928,RAD_GE_LUNG_7_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,1
35,32768.0,33455.5,3.187832e+12,4.647553,509.50,2.039873,33777.0,233.980806,33062.805213,33014.0,...,212.021779,0.019185,RAD_GE_LUNG_7_FBP_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,3
36,32768.0,33441.5,3.185872e+12,4.596123,489.25,2.106194,33850.0,225.698681,33052.697188,33007.0,...,203.841568,0.018399,RAD_GE_LUNG_7_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,2

In [5]:
#Save the dataframe in a csv file
df_TOGE.to_csv('../../../RadiomiK/Features_Global/rect11_glob.csv', index=False)