In [1]:
import pandas as pd
import pingouin as pg
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import statsmodels.api as sm

In [ ]:
# Loding the TO csv file
df = pd.read_csv("../../RadiomiK/Features_TO/Final/rect14.csv")
#Elimino le colonne diagnostics
string_to_match = 'diagnostics'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
string_to_match = 'Unnamed:'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
df_TO = df
df_TO

,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,...,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,image_ID,Manufacturer,Slice Thickness,Pixel_Spacing,Kernel,Dose,ASIR,Num_Acquisition
0,32791.5,32894.0,3.037488e+12,2.691028,58.00,2.468412,32962.0,32.124956,32842.836293,32843.0,...,3.209443,0.008218,RAD_TO_LUNG_4_STRONG_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STRONG,1
1,32797.0,32890.0,3.037501e+12,2.606618,52.00,2.694057,32966.0,29.594505,32842.910156,32842.0,...,3.085310,0.007990,RAD_TO_LUNG_4_STRONG_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STRONG,2
2,32791.0,32890.0,3.037046e+12,2.700067,57.00,2.654314,32971.0,31.797825,32840.446023,32840.0,...,4.369240,0.004835,RAD_TO_LUNG_4_STRONG_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STRONG,3
3,32787.0,32900.0,3.037608e+12,2.824428,62.00,2.523672,32969.0,34.989565,32843.482955,32844.5,...,4.903446,0.006123,RAD_TO_LUNG_2_STRONG_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STRONG,1
4,32788.0,32896.0,3.037333e+12,2.774173,62.00,2.496678,32958.0,33.971219,32841.995384,32841.0,...,4.197643,0.005029,RAD_TO_LUNG_2_STRONG_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STRONG,3
5,32792.5,32895.0,3.037495e+12,2.730046,59.00,2.489977,32971.0,32.861328,32842.875000,32842.0,...,4.398603,0.004288,RAD_TO_LUNG_2_STRONG_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STRONG,2
6,32781.0,32899.5,3.037051e+12,2.918567,68.00,2.537939,32993.0,37.818661,32840.465199,32841.0,...,5.936918,0.008365,RAD_TO_LUNG_4_STD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STD,3
7,32787.0,32900.0,3.037528e+12,2.856641,63.00,2.588315,32973.0,35.622684,32843.047940,32843.0,...,6.254285,0.006807,RAD_TO_LUNG_4_STD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STD,2
8,32782.0,32905.0,3.037513e+12,2.951227,70.25,2.418888,32977.0,38.767009,32842.959162,32843.0,...,5.936516,0.008592,RAD_TO_LUNG_4_STD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STD,1
9,32779.0,32908.5,3.037499e+12,3.032097,74.00,2.487652,33003.0,41.013280,32842.882102,32841.0,...,6.654681,0.009093,RAD_TO_LUNG_2_STD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STD,2
10,32763.0,32925.0,3.037500e+12,3.316968,91.00,2.424800,33013.0,50.236038,32842.869318,32840.0,...,15.551390,0.005986,RAD_TO_LUNG_2_MILD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,MILD,2
11,32759.0,32924.5,3.037354e+12,3.371027,96.25,2.412225,33064.0,52.599294,32842.076349,32842.0,...,19.653919,0.004311,RAD_TO_LUNG_2_MILD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,MILD,3
12,32773.5,32910.0,3.037289e+12,3.091084,78.00,2.431752,32990.0,43.023438,32841.744318,32841.5,...,10.183977,0.003910,RAD_TO_LUNG_2_STD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STD,3
13,32773.0,32915.0,3.037701e+12,3.144308,78.00,2.515939,33004.0,44.040771,32843.968750,32844.0,...,11.754482,0.004878,RAD_TO_LUNG_2_STD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STD,1
14,32759.0,32924.5,3.037354e+12,3.371027,96.25,2.412225,33064.0,52.599294,32842.076349,32842.0,...,19.653919,0.004311,RAD_TO_LUNG_2_MILD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,MILD,1
15,32766.0,32920.0,3.037550e+12,3.258219,90.50,2.334003,33036.0,48.779321,32843.142045,32843.0,...,14.359850,0.005355,RAD_TO_LUNG_4_MILD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,MILD,1
16,32765.0,32916.0,3.037016e+12,3.248798,88.00,2.430793,33018.0,48.162847,32840.257812,32840.0,...,14.121939,0.005728,RAD_TO_LUNG_4_MILD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,MILD,3
17,32772.0,32917.0,3.037567e+12,3.191537,81.00,2.522282,33017.0,45.604135,32843.241477,32842.0,...,12.398458,0.009268,RAD_TO_LUNG_4_MILD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,MILD,2
18,32727.0,32966.0,3.037743e+12,3.968287,124.00,3.220290,33207.0,74.802252,32844.099077,32842.0,...,90.561751,0.003037,RAD_TO_LUNG_4_FBP_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,2
19,32713.0,32964.5,3.036990e+12,4.034665,133.25,3.092605,33168.0,79.161007,32840.015270,32839.0,...,80.905080,0.004218,RAD_TO_LUNG_4_FBP_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,3
20,32717.0,32967.0,3.037571e+12,4.016995,134.25,2.942530,33250.0,78.976238,32843.159446,32844.0,...,92.118778,0.002813,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1

In [3]:
# Loding the GE csv files and joining them in a single dataframe
df_21 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect14_21.csv")
df_35 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect14_35.csv")
df_40 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect14_40.csv")
df_42 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect14_42.csv")
df_43 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect14_43.csv")

df = pd.concat([df_21, df_35, df_40, df_42, df_43], ignore_index=True)

#Elimino le colonne diagnostics
string_to_match = 'diagnostics'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
string_to_match = 'Unnamed:'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
df_GE = df
df_GE

,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,...,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,image_ID,Manufacturer,Slice Thickness,Pixel_Spacing,Kernel,Dose,ASIR,Num_Acquisition
0,33793.0,33930.0,1.857500e+12,3.147411,71.00,3.224791,34064.0,42.552890,33861.514815,33860.0,...,17.968963,0.004812,RAD_GE_LUNG_14_ASIR10_1,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,1
1,33792.9,33929.0,1.857396e+12,3.137780,69.00,3.243183,34078.0,41.951399,33860.566667,33859.0,...,17.379350,0.004489,RAD_GE_LUNG_14_ASIR10_2,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,2
2,33731.0,33982.0,3.342755e+12,4.029887,135.00,3.062690,34213.0,78.886873,33857.640261,33857.0,...,89.178689,0.003664,RAD_GE_LUNG_7_ASIR10_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,2
3,33731.0,33979.0,3.342081e+12,4.011439,133.00,3.083975,34292.0,78.302369,33854.229081,33855.0,...,72.427778,0.005133,RAD_GE_LUNG_7_ASIR10_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,3
4,33729.0,33998.0,3.344289e+12,4.125884,146.00,2.991641,34243.0,84.909898,33865.387174,33864.0,...,89.433619,0.004544,RAD_GE_LUNG_7_ASIR10_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,1
5,33839.0,33888.0,3.343986e+12,1.734110,25.00,3.117306,33931.0,15.007007,33864.010288,33864.0,...,0.464866,0.010269,RAD_GE_LUNG_7_ASIR40_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,1
6,33830.0,33880.0,3.342355e+12,1.817163,26.00,2.976259,33929.0,15.783961,33855.749657,33856.0,...,0.523362,0.005472,RAD_GE_LUNG_7_ASIR40_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,2
7,33830.0,33877.0,3.341901e+12,1.707359,25.00,3.037716,33914.0,14.667635,33853.451989,33854.0,...,0.437319,0.004428,RAD_GE_LUNG_7_ASIR40_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,3
8,33782.0,33946.0,3.344218e+12,3.422817,88.00,2.991289,34099.0,51.718360,33865.130658,33866.0,...,23.656874,0.006348,RAD_GE_LUNG_7_ASIR70_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,1
9,33779.0,33929.0,3.342036e+12,3.312680,81.00,3.120730,34125.0,47.848750,33854.088820,33854.0,...,21.839655,0.004220,RAD_GE_LUNG_7_ASIR70_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,3
10,33781.0,33933.0,3.342625e+12,3.308739,81.00,3.060310,34079.0,47.581271,33857.070988,33857.0,...,21.719617,0.004085,RAD_GE_LUNG_7_ASIR70_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,2
11,33773.0,33955.0,3.343839e+12,3.543599,93.00,3.002253,34115.0,56.052500,33863.201303,33861.0,...,36.054467,0.003758,RAD_GE_LUNG_14_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,1
12,33772.0,33950.0,3.343247e+12,3.550244,94.00,3.274752,34136.0,56.010015,33860.200274,33860.0,...,35.465986,0.004956,RAD_GE_LUNG_14_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,2
13,33733.0,33995.0,3.344271e+12,4.100502,141.00,3.135411,34251.0,83.240811,33865.300069,33863.0,...,96.962583,0.003401,RAD_GE_LUNG_7_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,1
14,33732.0,33976.0,3.342057e+12,3.978842,127.00,3.237251,34317.0,76.101052,33854.111111,33855.0,...,81.452760,0.003472,RAD_GE_LUNG_7_FBP_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,3
15,33733.0,33980.5,3.342734e+12,4.010884,131.25,3.144383,34219.0,77.750711,33857.536351,33857.0,...,91.174566,0.002462,RAD_GE_LUNG_7_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,2

In [4]:
df_TOGE = pd.concat([df_TO, df_GE], ignore_index=True)
df_TOGE

,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,...,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,image_ID,Manufacturer,Slice Thickness,Pixel_Spacing,Kernel,Dose,ASIR,Num_Acquisition
0,32791.5,32894.0,3.037488e+12,2.691028,58.00,2.468412,32962.0,32.124956,32842.836293,32843.0,...,3.209443,0.008218,RAD_TO_LUNG_4_STRONG_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STRONG,1
1,32797.0,32890.0,3.037501e+12,2.606618,52.00,2.694057,32966.0,29.594505,32842.910156,32842.0,...,3.085310,0.007990,RAD_TO_LUNG_4_STRONG_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STRONG,2
2,32791.0,32890.0,3.037046e+12,2.700067,57.00,2.654314,32971.0,31.797825,32840.446023,32840.0,...,4.369240,0.004835,RAD_TO_LUNG_4_STRONG_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STRONG,3
3,32787.0,32900.0,3.037608e+12,2.824428,62.00,2.523672,32969.0,34.989565,32843.482955,32844.5,...,4.903446,0.006123,RAD_TO_LUNG_2_STRONG_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STRONG,1
4,32788.0,32896.0,3.037333e+12,2.774173,62.00,2.496678,32958.0,33.971219,32841.995384,32841.0,...,4.197643,0.005029,RAD_TO_LUNG_2_STRONG_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STRONG,3
5,32792.5,32895.0,3.037495e+12,2.730046,59.00,2.489977,32971.0,32.861328,32842.875000,32842.0,...,4.398603,0.004288,RAD_TO_LUNG_2_STRONG_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STRONG,2
6,32781.0,32899.5,3.037051e+12,2.918567,68.00,2.537939,32993.0,37.818661,32840.465199,32841.0,...,5.936918,0.008365,RAD_TO_LUNG_4_STD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STD,3
7,32787.0,32900.0,3.037528e+12,2.856641,63.00,2.588315,32973.0,35.622684,32843.047940,32843.0,...,6.254285,0.006807,RAD_TO_LUNG_4_STD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STD,2
8,32782.0,32905.0,3.037513e+12,2.951227,70.25,2.418888,32977.0,38.767009,32842.959162,32843.0,...,5.936516,0.008592,RAD_TO_LUNG_4_STD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STD,1
9,32779.0,32908.5,3.037499e+12,3.032097,74.00,2.487652,33003.0,41.013280,32842.882102,32841.0,...,6.654681,0.009093,RAD_TO_LUNG_2_STD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STD,2
10,32763.0,32925.0,3.037500e+12,3.316968,91.00,2.424800,33013.0,50.236038,32842.869318,32840.0,...,15.551390,0.005986,RAD_TO_LUNG_2_MILD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,MILD,2
11,32759.0,32924.5,3.037354e+12,3.371027,96.25,2.412225,33064.0,52.599294,32842.076349,32842.0,...,19.653919,0.004311,RAD_TO_LUNG_2_MILD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,MILD,3
12,32773.5,32910.0,3.037289e+12,3.091084,78.00,2.431752,32990.0,43.023438,32841.744318,32841.5,...,10.183977,0.003910,RAD_TO_LUNG_2_STD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STD,3
13,32773.0,32915.0,3.037701e+12,3.144308,78.00,2.515939,33004.0,44.040771,32843.968750,32844.0,...,11.754482,0.004878,RAD_TO_LUNG_2_STD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STD,1
14,32759.0,32924.5,3.037354e+12,3.371027,96.25,2.412225,33064.0,52.599294,32842.076349,32842.0,...,19.653919,0.004311,RAD_TO_LUNG_2_MILD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,MILD,1
15,32766.0,32920.0,3.037550e+12,3.258219,90.50,2.334003,33036.0,48.779321,32843.142045,32843.0,...,14.359850,0.005355,RAD_TO_LUNG_4_MILD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,MILD,1
16,32765.0,32916.0,3.037016e+12,3.248798,88.00,2.430793,33018.0,48.162847,32840.257812,32840.0,...,14.121939,0.005728,RAD_TO_LUNG_4_MILD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,MILD,3
17,32772.0,32917.0,3.037567e+12,3.191537,81.00,2.522282,33017.0,45.604135,32843.241477,32842.0,...,12.398458,0.009268,RAD_TO_LUNG_4_MILD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,MILD,2
18,32727.0,32966.0,3.037743e+12,3.968287,124.00,3.220290,33207.0,74.802252,32844.099077,32842.0,...,90.561751,0.003037,RAD_TO_LUNG_4_FBP_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,FBP,2
19,32713.0,32964.5,3.036990e+12,4.034665,133.25,3.092605,33168.0,79.161007,32840.015270,32839.0,...,80.905080,0.004218,RAD_TO_LUNG_4_FBP_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,FBP,3
20,32717.0,32967.0,3.037571e+12,4.016995,134.25,2.942530,33250.0,78.976238,32843.159446,32844.0,...,92.118778,0.002813,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,FBP,1
21,33793.0,33930.0,1.857500e+12,3.147411,71.00,3.224791,34064.0,42.552890,33861.514815,33860.0,...,17.968963,0.004812,RAD_GE_LUNG_14_ASIR10_1,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,1
22,33792.9,33929.0,1.857396e+12,3.137780,69.00,3.243183,34078.0,41.951399,33860.566667,33859.0,...,17.379350,0.004489,RAD_GE_LUNG_14_ASIR10_2,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,2
23,33731.0,33982.0,3.342755e+12,4.029887,135.00,3.062690,34213.0,78.886873,33857.640261,33857.0,...,89.178689,0.003664,RAD_GE_LUNG_7_ASIR10_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,2
24,33731.0,33979.0,3.342081e+12,4.011439,133.00,3.083975,34292.0,78.302369,33854.229081,33855.0,...,72.427778,0.005133,RAD_GE_LUNG_7_ASIR10_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,3
25,33729.0,33998.0,3.344289e+12,4.125884,146.00,2.991641,34243.0,84.909898,33865.387174,33864.0,...,89.433619,0.004544,RAD_GE_LUNG_7_ASIR10_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,1
26,33839.0,33888.0,3.343986e+12,1.734110,25.00,3.117306,33931.0,15.007007,33864.010288,33864.0,...,0.464866,0.010269,RAD_GE_LUNG_7_ASIR40_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,1
27,33830.0,33880.0,3.342355e+12,1.817163,26.00,2.976259,33929.0,15.783961,33855.749657,33856.0,...,0.523362,0.005472,RAD_GE_LUNG_7_ASIR40_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,2
28,33830.0,33877.0,3.341901e+12,1.707359,25.00,3.037716,33914.0,14.667635,33853.451989,33854.0,...,0.437319,0.004428,RAD_GE_LUNG_7_ASIR40_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,3
29,33782.0,33946.0,3.344218e+12,3.422817,88.00,2.991289,34099.0,51.718360,33865.130658,33866.0,...,23.656874,0.006348,RAD_GE_LUNG_7_ASIR70_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,1
30,33779.0,33929.0,3.342036e+12,3.312680,81.00,3.120730,34125.0,47.848750,33854.088820,33854.0,...,21.839655,0.004220,RAD_GE_LUNG_7_ASIR70_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,3
31,33781.0,33933.0,3.342625e+12,3.308739,81.00,3.060310,34079.0,47.581271,33857.070988,33857.0,...,21.719617,0.004085,RAD_GE_LUNG_7_ASIR70_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,2
32,33773.0,33955.0,3.343839e+12,3.543599,93.00,3.002253,34115.0,56.052500,33863.201303,33861.0,...,36.054467,0.003758,RAD_GE_LUNG_14_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,1
33,33772.0,33950.0,3.343247e+12,3.550244,94.00,3.274752,34136.0,56.010015,33860.200274,33860.0,...,35.465986,0.004956,RAD_GE_LUNG_14_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,2
34,33733.0,33995.0,3.344271e+12,4.100502,141.00,3.135411,34251.0,83.240811,33865.300069,33863.0,...,96.962583,0.003401,RAD_GE_LUNG_7_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,1
35,33732.0,33976.0,3.342057e+12,3.978842,127.00,3.237251,34317.0,76.101052,33854.111111,33855.0,...,81.452760,0.003472,RAD_GE_LUNG_7_FBP_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,3
36,33733.0,33980.5,3.342734e+12,4.010884,131.25,3.144383,34219.0,77.750711,33857.536351,33857.0,...,91.174566,0.002462,RAD_GE_LUNG_7_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,2

In [5]:
#Save the dataframe in a csv file
df_TOGE.to_csv('../../../RadiomiK/Features_Global/rect14_glob.csv', index=False)