In [1]:
import pandas as pd
import pingouin as pg
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import statsmodels.api as sm

In [ ]:
# Loding the TO csv file
df = pd.read_csv("../../RadiomiK/Features_TO/Final/rect9.csv")
#Elimino le colonne diagnostics
string_to_match = 'diagnostics'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
string_to_match = 'Unnamed:'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
df_TO = df
df_TO

,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,...,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,image_ID,Manufacturer,Slice Thickness,Pixel_Spacing,Kernel,Dose,ASIR,Num_Acquisition
0,31670.0,32350.0,2.882089e+12,5.265056,445.25,2.177031,32726.0,232.647111,31990.582031,31934.5,...,295.894420,0.004372,RAD_TO_LUNG_4_STRONG_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STRONG,1
1,31670.0,32343.5,2.882158e+12,5.268647,441.25,2.227414,32728.0,229.407158,31990.984020,31936.0,...,302.676723,0.003981,RAD_TO_LUNG_4_STRONG_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STRONG,2
2,31677.0,32331.5,2.882253e+12,5.231036,453.00,2.159033,32736.0,229.581485,31991.528054,31942.0,...,301.812211,0.003606,RAD_TO_LUNG_4_STRONG_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STRONG,3
3,31715.0,32305.0,2.883402e+12,5.123783,383.00,2.293764,32681.0,199.408092,31998.140625,31961.0,...,234.224775,0.003574,RAD_TO_LUNG_2_STRONG_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STRONG,1
4,31715.0,32315.0,2.883503e+12,5.150094,386.50,2.348964,32666.0,204.085990,31998.663707,31958.0,...,225.417266,0.005491,RAD_TO_LUNG_2_STRONG_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STRONG,3
5,31710.0,32317.0,2.883630e+12,5.158771,393.25,2.244138,32669.0,205.621255,31999.357244,31956.0,...,250.223968,0.003143,RAD_TO_LUNG_2_STRONG_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STRONG,2
6,31642.0,32365.0,2.881642e+12,5.357909,487.25,2.133530,32772.0,249.430917,31987.938920,31935.5,...,366.635548,0.003438,RAD_TO_LUNG_4_STD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STD,3
7,31634.0,32371.0,2.881357e+12,5.398316,482.00,2.184105,32776.0,250.085529,31986.332741,31934.5,...,379.569881,0.003816,RAD_TO_LUNG_4_STD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STD,2
8,31638.5,32382.0,2.881417e+12,5.395078,492.25,2.135206,32759.0,253.487041,31986.638139,31929.5,...,371.267057,0.003844,RAD_TO_LUNG_4_STD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STD,1
9,31672.0,32349.0,2.882727e+12,5.314626,437.25,2.193853,32751.0,228.539975,31994.145952,31953.5,...,357.726311,0.002867,RAD_TO_LUNG_2_STD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STD,2
10,31651.0,32385.0,2.883317e+12,5.395730,473.00,2.139929,32787.0,245.163663,31997.255327,31948.5,...,403.669386,0.002682,RAD_TO_LUNG_2_MILD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,MILD,2
11,31658.0,32379.5,2.883469e+12,5.379451,465.00,2.229879,32799.0,242.586775,31998.121094,31942.5,...,344.773587,0.005175,RAD_TO_LUNG_2_MILD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,MILD,3
12,31679.0,32343.0,2.882961e+12,5.286694,430.00,2.277549,32731.0,226.575932,31995.454901,31947.0,...,331.701387,0.003797,RAD_TO_LUNG_2_STD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STD,3
13,31682.5,32328.0,2.882554e+12,5.271181,429.00,2.228824,32725.0,221.989048,31993.243963,31954.0,...,355.989203,0.002491,RAD_TO_LUNG_2_STD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STD,1
14,31658.0,32379.5,2.883469e+12,5.379451,465.00,2.229879,32799.0,242.586775,31998.121094,31942.5,...,344.773587,0.005175,RAD_TO_LUNG_2_MILD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,MILD,1
15,31616.0,32426.5,2.882492e+12,5.485538,537.25,2.071750,32877.0,274.129380,31992.389560,31917.0,...,380.038897,0.005212,RAD_TO_LUNG_4_MILD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,MILD,1
16,31627.0,32411.0,2.882467e+12,5.454544,526.25,2.058963,32844.0,269.505726,31992.312500,31929.0,...,419.744352,0.003133,RAD_TO_LUNG_4_MILD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,MILD,3
17,31617.0,32419.0,2.882306e+12,5.486061,524.25,2.095171,32870.0,269.974244,31991.392756,31928.5,...,388.202061,0.004899,RAD_TO_LUNG_4_MILD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,MILD,2
18,31554.0,32539.0,2.883239e+12,5.817722,595.25,2.299967,33191.0,322.125402,31995.842330,31923.0,...,957.359208,0.002023,RAD_TO_LUNG_4_FBP_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,2
19,31554.5,32535.5,2.883239e+12,5.807677,605.00,2.292546,33176.0,320.844071,31995.868963,31927.5,...,1025.348217,0.001453,RAD_TO_LUNG_4_FBP_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,3
20,31556.0,32556.0,2.883709e+12,5.825169,606.00,2.314049,33197.0,327.657076,31998.377486,31909.0,...,1038.666321,0.001365,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1

In [3]:
# Loding the GE csv files and joining them in a single dataframe
df_21 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect9_21.csv")
df_35 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect9_35.csv")
df_40 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect9_40.csv")
df_42 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect9_42.csv")
df_43 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect9_43.csv")

df = pd.concat([df_21, df_35, df_40, df_42, df_43], ignore_index=True)

#Elimino le colonne diagnostics
string_to_match = 'diagnostics'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
string_to_match = 'Unnamed:'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
df_GE = df
df_GE

,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,...,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,image_ID,Manufacturer,Slice Thickness,Pixel_Spacing,Kernel,Dose,ASIR,Num_Acquisition
0,32768.0,33784.0,1.777889e+12,4.455745,685.00,2.719328,34705.0,365.567737,33125.272222,32913.0,...,379.787767,0.014208,RAD_GE_LUNG_14_ASIR10_1,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,1
1,32768.0,33773.5,1.778076e+12,4.414971,724.50,2.670867,34742.0,373.517987,33126.954938,32894.5,...,387.527865,0.013553,RAD_GE_LUNG_14_ASIR10_2,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,2
2,32768.0,33782.5,3.201305e+12,4.485719,710.25,2.526443,34611.0,365.343907,33131.016118,32936.0,...,387.948170,0.011262,RAD_GE_LUNG_7_ASIR10_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,2
3,32768.0,33783.0,3.201096e+12,4.525628,707.50,2.770935,34821.0,367.632570,33129.875514,32922.0,...,413.859425,0.012149,RAD_GE_LUNG_7_ASIR10_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,3
4,32768.0,33813.0,3.201196e+12,4.475813,692.25,3.018620,34977.0,373.672324,33130.263032,32910.0,...,419.402951,0.011889,RAD_GE_LUNG_7_ASIR10_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,1
5,32815.0,33282.5,3.184694e+12,4.741980,325.00,3.011615,33787.0,166.983060,33047.020233,33023.0,...,80.910012,0.009824,RAD_GE_LUNG_7_ASIR40_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,1
6,32820.0,33286.5,3.185679e+12,4.753879,312.00,2.910586,33748.0,161.763107,33052.165981,33030.0,...,78.240149,0.008238,RAD_GE_LUNG_7_ASIR40_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,2
7,32826.0,33287.0,3.185847e+12,4.743142,316.00,2.986053,33757.0,162.050316,33053.033265,33030.0,...,80.350164,0.009657,RAD_GE_LUNG_7_ASIR40_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,3
8,32768.0,33791.5,3.200105e+12,4.464699,678.25,3.077011,34968.0,368.041603,33124.699246,32905.0,...,411.692407,0.013290,RAD_GE_LUNG_7_ASIR70_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,1
9,32768.0,33766.5,3.200137e+12,4.527604,696.00,2.830276,34821.0,362.224786,33124.981824,32919.0,...,386.676424,0.012235,RAD_GE_LUNG_7_ASIR70_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,3
10,32768.0,33764.0,3.200238e+12,4.471373,698.00,2.585820,34632.0,359.465412,33125.573045,32934.0,...,364.498694,0.011568,RAD_GE_LUNG_7_ASIR70_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,2
11,32768.0,33785.0,3.200490e+12,4.494740,681.00,2.744329,34759.0,364.651055,33126.776406,32922.0,...,394.739075,0.012028,RAD_GE_LUNG_14_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,1
12,32768.0,33782.5,3.200547e+12,4.440303,714.00,2.747936,34765.0,373.540109,33126.978395,32897.0,...,393.768973,0.013787,RAD_GE_LUNG_14_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,2
13,32768.0,33818.0,3.201449e+12,4.472675,695.50,3.007303,34979.0,375.067506,33131.548697,32911.5,...,419.007621,0.011283,RAD_GE_LUNG_7_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,1
14,32768.0,33788.5,3.201318e+12,4.524399,713.00,2.758694,34820.0,368.944703,33131.007545,32920.5,...,414.952461,0.012485,RAD_GE_LUNG_7_FBP_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,3
15,32768.0,33787.0,3.201518e+12,4.482200,712.00,2.513494,34605.0,366.865468,33132.100823,32936.5,...,393.036979,0.011310,RAD_GE_LUNG_7_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,2

In [4]:
df_TOGE = pd.concat([df_TO, df_GE], ignore_index=True)
df_TOGE

,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,...,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,image_ID,Manufacturer,Slice Thickness,Pixel_Spacing,Kernel,Dose,ASIR,Num_Acquisition
0,31670.0,32350.0,2.882089e+12,5.265056,445.25,2.177031,32726.0,232.647111,31990.582031,31934.5,...,295.894420,0.004372,RAD_TO_LUNG_4_STRONG_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STRONG,1
1,31670.0,32343.5,2.882158e+12,5.268647,441.25,2.227414,32728.0,229.407158,31990.984020,31936.0,...,302.676723,0.003981,RAD_TO_LUNG_4_STRONG_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STRONG,2
2,31677.0,32331.5,2.882253e+12,5.231036,453.00,2.159033,32736.0,229.581485,31991.528054,31942.0,...,301.812211,0.003606,RAD_TO_LUNG_4_STRONG_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STRONG,3
3,31715.0,32305.0,2.883402e+12,5.123783,383.00,2.293764,32681.0,199.408092,31998.140625,31961.0,...,234.224775,0.003574,RAD_TO_LUNG_2_STRONG_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STRONG,1
4,31715.0,32315.0,2.883503e+12,5.150094,386.50,2.348964,32666.0,204.085990,31998.663707,31958.0,...,225.417266,0.005491,RAD_TO_LUNG_2_STRONG_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STRONG,3
5,31710.0,32317.0,2.883630e+12,5.158771,393.25,2.244138,32669.0,205.621255,31999.357244,31956.0,...,250.223968,0.003143,RAD_TO_LUNG_2_STRONG_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STRONG,2
6,31642.0,32365.0,2.881642e+12,5.357909,487.25,2.133530,32772.0,249.430917,31987.938920,31935.5,...,366.635548,0.003438,RAD_TO_LUNG_4_STD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STD,3
7,31634.0,32371.0,2.881357e+12,5.398316,482.00,2.184105,32776.0,250.085529,31986.332741,31934.5,...,379.569881,0.003816,RAD_TO_LUNG_4_STD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STD,2
8,31638.5,32382.0,2.881417e+12,5.395078,492.25,2.135206,32759.0,253.487041,31986.638139,31929.5,...,371.267057,0.003844,RAD_TO_LUNG_4_STD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STD,1
9,31672.0,32349.0,2.882727e+12,5.314626,437.25,2.193853,32751.0,228.539975,31994.145952,31953.5,...,357.726311,0.002867,RAD_TO_LUNG_2_STD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STD,2
10,31651.0,32385.0,2.883317e+12,5.395730,473.00,2.139929,32787.0,245.163663,31997.255327,31948.5,...,403.669386,0.002682,RAD_TO_LUNG_2_MILD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,MILD,2
11,31658.0,32379.5,2.883469e+12,5.379451,465.00,2.229879,32799.0,242.586775,31998.121094,31942.5,...,344.773587,0.005175,RAD_TO_LUNG_2_MILD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,MILD,3
12,31679.0,32343.0,2.882961e+12,5.286694,430.00,2.277549,32731.0,226.575932,31995.454901,31947.0,...,331.701387,0.003797,RAD_TO_LUNG_2_STD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STD,3
13,31682.5,32328.0,2.882554e+12,5.271181,429.00,2.228824,32725.0,221.989048,31993.243963,31954.0,...,355.989203,0.002491,RAD_TO_LUNG_2_STD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STD,1
14,31658.0,32379.5,2.883469e+12,5.379451,465.00,2.229879,32799.0,242.586775,31998.121094,31942.5,...,344.773587,0.005175,RAD_TO_LUNG_2_MILD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,MILD,1
15,31616.0,32426.5,2.882492e+12,5.485538,537.25,2.071750,32877.0,274.129380,31992.389560,31917.0,...,380.038897,0.005212,RAD_TO_LUNG_4_MILD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,MILD,1
16,31627.0,32411.0,2.882467e+12,5.454544,526.25,2.058963,32844.0,269.505726,31992.312500,31929.0,...,419.744352,0.003133,RAD_TO_LUNG_4_MILD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,MILD,3
17,31617.0,32419.0,2.882306e+12,5.486061,524.25,2.095171,32870.0,269.974244,31991.392756,31928.5,...,388.202061,0.004899,RAD_TO_LUNG_4_MILD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,MILD,2
18,31554.0,32539.0,2.883239e+12,5.817722,595.25,2.299967,33191.0,322.125402,31995.842330,31923.0,...,957.359208,0.002023,RAD_TO_LUNG_4_FBP_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,FBP,2
19,31554.5,32535.5,2.883239e+12,5.807677,605.00,2.292546,33176.0,320.844071,31995.868963,31927.5,...,1025.348217,0.001453,RAD_TO_LUNG_4_FBP_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,FBP,3
20,31556.0,32556.0,2.883709e+12,5.825169,606.00,2.314049,33197.0,327.657076,31998.377486,31909.0,...,1038.666321,0.001365,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,FBP,1
21,32768.0,33784.0,1.777889e+12,4.455745,685.00,2.719328,34705.0,365.567737,33125.272222,32913.0,...,379.787767,0.014208,RAD_GE_LUNG_14_ASIR10_1,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,1
22,32768.0,33773.5,1.778076e+12,4.414971,724.50,2.670867,34742.0,373.517987,33126.954938,32894.5,...,387.527865,0.013553,RAD_GE_LUNG_14_ASIR10_2,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,2
23,32768.0,33782.5,3.201305e+12,4.485719,710.25,2.526443,34611.0,365.343907,33131.016118,32936.0,...,387.948170,0.011262,RAD_GE_LUNG_7_ASIR10_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,2
24,32768.0,33783.0,3.201096e+12,4.525628,707.50,2.770935,34821.0,367.632570,33129.875514,32922.0,...,413.859425,0.012149,RAD_GE_LUNG_7_ASIR10_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,3
25,32768.0,33813.0,3.201196e+12,4.475813,692.25,3.018620,34977.0,373.672324,33130.263032,32910.0,...,419.402951,0.011889,RAD_GE_LUNG_7_ASIR10_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,1
26,32815.0,33282.5,3.184694e+12,4.741980,325.00,3.011615,33787.0,166.983060,33047.020233,33023.0,...,80.910012,0.009824,RAD_GE_LUNG_7_ASIR40_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,1
27,32820.0,33286.5,3.185679e+12,4.753879,312.00,2.910586,33748.0,161.763107,33052.165981,33030.0,...,78.240149,0.008238,RAD_GE_LUNG_7_ASIR40_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,2
28,32826.0,33287.0,3.185847e+12,4.743142,316.00,2.986053,33757.0,162.050316,33053.033265,33030.0,...,80.350164,0.009657,RAD_GE_LUNG_7_ASIR40_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,3
29,32768.0,33791.5,3.200105e+12,4.464699,678.25,3.077011,34968.0,368.041603,33124.699246,32905.0,...,411.692407,0.013290,RAD_GE_LUNG_7_ASIR70_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,1
30,32768.0,33766.5,3.200137e+12,4.527604,696.00,2.830276,34821.0,362.224786,33124.981824,32919.0,...,386.676424,0.012235,RAD_GE_LUNG_7_ASIR70_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,3
31,32768.0,33764.0,3.200238e+12,4.471373,698.00,2.585820,34632.0,359.465412,33125.573045,32934.0,...,364.498694,0.011568,RAD_GE_LUNG_7_ASIR70_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,2
32,32768.0,33785.0,3.200490e+12,4.494740,681.00,2.744329,34759.0,364.651055,33126.776406,32922.0,...,394.739075,0.012028,RAD_GE_LUNG_14_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,1
33,32768.0,33782.5,3.200547e+12,4.440303,714.00,2.747936,34765.0,373.540109,33126.978395,32897.0,...,393.768973,0.013787,RAD_GE_LUNG_14_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,2
34,32768.0,33818.0,3.201449e+12,4.472675,695.50,3.007303,34979.0,375.067506,33131.548697,32911.5,...,419.007621,0.011283,RAD_GE_LUNG_7_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,1
35,32768.0,33788.5,3.201318e+12,4.524399,713.00,2.758694,34820.0,368.944703,33131.007545,32920.5,...,414.952461,0.012485,RAD_GE_LUNG_7_FBP_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,3
36,32768.0,33787.0,3.201518e+12,4.482200,712.00,2.513494,34605.0,366.865468,33132.100823,32936.5,...,393.036979,0.011310,RAD_GE_LUNG_7_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,2

In [5]:
#Save the dataframe in a csv file
df_TOGE.to_csv('../../../RadiomiK/Features_Global/rect9_glob.csv', index=False)