In [1]:
import pandas as pd
import pingouin as pg
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import statsmodels.api as sm

In [ ]:
# Loding the TO csv file
df = pd.read_csv("../../RadiomiK/Features_TO/Final/rect1.csv")
#Elimino le colonne diagnostics
string_to_match = 'diagnostics'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
string_to_match = 'Unnamed:'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
df_TO = df
df_TO

,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,...,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,image_ID,Manufacturer,Slice Thickness,Pixel_Spacing,Kernel,Dose,ASIR,Num_Acquisition
0,31985.0,32745.0,2.954785e+12,5.320037,532.25,1.760183,33053.0,255.298355,32391.365767,32448.0,...,471.121485,0.003263,RAD_TO_LUNG_4_STRONG_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STRONG,1
1,31993.0,32742.0,2.954906e+12,5.333261,533.00,1.808361,33103.0,256.311705,32392.020952,32448.0,...,516.104955,0.003441,RAD_TO_LUNG_4_STRONG_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STRONG,2
2,31976.0,32742.0,2.954125e+12,5.353925,539.00,1.794405,33016.0,260.563289,32387.700639,32452.0,...,498.623834,0.003379,RAD_TO_LUNG_4_STRONG_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STRONG,3
3,32046.0,32669.0,2.952529e+12,5.077379,430.00,1.828618,32879.0,209.891981,32379.409091,32427.0,...,324.437900,0.004345,RAD_TO_LUNG_2_STRONG_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STRONG,1
4,32050.0,32666.0,2.951682e+12,5.044582,425.25,1.803173,32824.0,206.913102,32374.789773,32415.0,...,305.718614,0.003790,RAD_TO_LUNG_2_STRONG_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STRONG,3
5,32046.5,32662.0,2.951740e+12,5.036371,434.00,1.799775,32876.0,208.458262,32375.102628,32431.0,...,314.986156,0.003796,RAD_TO_LUNG_2_STRONG_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STRONG,2
6,31915.5,32806.0,2.955626e+12,5.587952,622.00,1.807941,33174.0,303.665838,32395.448153,32471.0,...,751.967251,0.002121,RAD_TO_LUNG_4_STD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STD,3
7,31938.5,32810.5,2.956619e+12,5.556982,618.00,1.811378,33231.0,299.262890,32400.935724,32468.0,...,753.426155,0.002226,RAD_TO_LUNG_4_STD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STD,2
8,31925.0,32810.5,2.956391e+12,5.541701,617.25,1.763500,33164.0,297.769229,32399.705256,32466.0,...,685.076638,0.002831,RAD_TO_LUNG_4_STD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STD,1
9,31993.0,32726.5,2.953508e+12,5.283397,515.00,1.795629,32988.0,249.048292,32384.430753,32455.5,...,501.357758,0.002960,RAD_TO_LUNG_2_STD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STD,2
10,31870.5,32743.0,2.948917e+12,5.436469,599.00,1.812151,32988.0,289.020509,32358.796520,32458.5,...,620.775814,0.004612,RAD_TO_LUNG_2_MILD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,MILD,2
11,31869.5,32748.5,2.948800e+12,5.433300,610.00,1.786205,32953.0,287.764348,32358.154830,32440.5,...,593.437872,0.003581,RAD_TO_LUNG_2_MILD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,MILD,3
12,31992.0,32730.5,2.953190e+12,5.314510,516.00,1.803757,32938.0,249.277599,32382.674006,32437.0,...,479.351042,0.003659,RAD_TO_LUNG_2_STD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STD,3
13,31984.5,32734.0,2.954170e+12,5.328518,513.00,1.814919,32990.0,252.141935,32388.025923,32449.0,...,519.568570,0.003464,RAD_TO_LUNG_2_STD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STD,1
14,31869.5,32748.5,2.948800e+12,5.433300,610.00,1.786205,32953.0,287.764348,32358.154830,32440.5,...,593.437872,0.003581,RAD_TO_LUNG_2_MILD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,MILD,1
15,31796.5,32827.0,2.950695e+12,5.638543,741.25,1.748669,33185.0,342.119202,32367.877131,32470.0,...,818.405494,0.003631,RAD_TO_LUNG_4_MILD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,MILD,1
16,31791.0,32820.0,2.950094e+12,5.678193,752.00,1.756011,33175.0,347.168098,32364.527699,32472.5,...,846.244110,0.003695,RAD_TO_LUNG_4_MILD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,MILD,3
17,31793.5,32824.0,2.950791e+12,5.666212,732.00,1.762651,33249.0,343.502167,32368.389205,32471.0,...,820.546163,0.004010,RAD_TO_LUNG_4_MILD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,MILD,2
18,31561.5,32868.0,2.944168e+12,6.056917,771.50,2.252627,33339.0,416.320954,32330.687145,32474.5,...,1959.645007,0.001461,RAD_TO_LUNG_4_FBP_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,2
19,31583.5,32862.5,2.943754e+12,6.082272,790.00,2.251915,33253.0,418.673897,32328.386719,32480.0,...,2083.696393,0.001778,RAD_TO_LUNG_4_FBP_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,3
20,31565.0,32860.0,2.944198e+12,6.068820,785.25,2.257293,33285.0,413.524132,32330.885298,32475.5,...,2078.486888,0.001300,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1

In [3]:
# Loding the GE csv files and joining them in a single dataframe
df_21 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect1_21.csv")
df_35 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect1_35.csv")
df_40 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect1_40.csv")
df_42 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect1_42.csv")
df_43 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect1_43.csv")

df = pd.concat([df_21, df_35, df_40, df_42, df_43], ignore_index=True)

#Elimino le colonne diagnostics
string_to_match = 'diagnostics'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
string_to_match = 'Unnamed:'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
df_GE = df
df_GE

,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,...,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,image_ID,Manufacturer,Slice Thickness,Pixel_Spacing,Kernel,Dose,ASIR,Num_Acquisition
0,32768.0,33287.0,1.767015e+12,4.668706,298.25,2.122227,33573.0,157.218717,33025.984568,33020.0,...,131.869483,0.034848,RAD_GE_LUNG_14_ASIR10_1,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,1
1,32768.0,33297.0,1.767643e+12,4.679564,302.25,2.106098,33578.0,160.023350,33031.839506,33024.5,...,137.619490,0.031410,RAD_GE_LUNG_14_ASIR10_2,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,2
2,32768.0,33435.0,3.185674e+12,4.597171,484.00,2.103416,33840.0,223.810253,33051.684499,33006.0,...,198.710805,0.019064,RAD_GE_LUNG_7_ASIR10_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,2
3,32768.0,33450.5,3.187662e+12,4.646162,504.25,2.037225,33771.0,232.314998,33061.936557,33015.0,...,204.667535,0.018789,RAD_GE_LUNG_7_ASIR10_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,3
4,32768.0,33462.0,3.187863e+12,4.604242,517.00,2.099872,33883.0,237.744332,33062.919067,33019.0,...,214.203521,0.018326,RAD_GE_LUNG_7_ASIR10_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,1
5,32872.0,33152.0,3.179997e+12,4.014119,162.00,2.146182,33283.0,86.842254,33023.070645,33034.0,...,45.684384,0.013075,RAD_GE_LUNG_7_ASIR40_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,1
6,32880.0,33143.0,3.179332e+12,3.915419,150.00,2.177949,33261.0,80.409788,33019.640604,33028.0,...,40.415439,0.009389,RAD_GE_LUNG_7_ASIR40_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,2
7,32882.0,33153.0,3.180978e+12,3.964278,156.00,2.115175,33264.0,84.023208,33028.177984,33038.5,...,43.489422,0.009158,RAD_GE_LUNG_7_ASIR40_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,3
8,32768.0,33444.0,3.187095e+12,4.612909,504.00,2.100858,33868.0,231.074171,33058.996914,33019.0,...,207.912686,0.019079,RAD_GE_LUNG_7_ASIR70_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,1
9,32768.0,33432.0,3.186930e+12,4.637224,485.00,2.031970,33749.0,225.246504,33058.202675,33018.0,...,203.572538,0.018467,RAD_GE_LUNG_7_ASIR70_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,3
10,32768.0,33413.0,3.184849e+12,4.607459,461.50,2.097481,33795.0,216.029842,33047.472565,33008.0,...,183.571338,0.020317,RAD_GE_LUNG_7_ASIR70_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,2
11,32768.0,33457.5,3.187191e+12,4.521871,518.00,1.884100,33756.0,240.972282,33059.441701,33011.0,...,208.775927,0.017491,RAD_GE_LUNG_14_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,1
12,32768.0,33458.0,3.187863e+12,4.538142,530.00,1.859088,33883.0,241.939038,33062.921468,33021.0,...,213.674965,0.016764,RAD_GE_LUNG_14_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,2
13,32768.0,33466.0,3.188041e+12,4.598018,519.00,2.100799,33887.0,239.359213,33063.823731,33019.0,...,215.932813,0.017928,RAD_GE_LUNG_7_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,1
14,32768.0,33455.5,3.187832e+12,4.647553,509.50,2.039873,33777.0,233.980806,33062.805213,33014.0,...,212.021779,0.019185,RAD_GE_LUNG_7_FBP_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,3
15,32768.0,33441.5,3.185872e+12,4.596123,489.25,2.106194,33850.0,225.698681,33052.697188,33007.0,...,203.841568,0.018399,RAD_GE_LUNG_7_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,2

In [4]:
df_TOGE = pd.concat([df_TO, df_GE], ignore_index=True)
df_TOGE

,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,...,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,image_ID,Manufacturer,Slice Thickness,Pixel_Spacing,Kernel,Dose,ASIR,Num_Acquisition
0,31985.0,32745.0,2.954785e+12,5.320037,532.25,1.760183,33053.0,255.298355,32391.365767,32448.0,...,471.121485,0.003263,RAD_TO_LUNG_4_STRONG_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STRONG,1
1,31993.0,32742.0,2.954906e+12,5.333261,533.00,1.808361,33103.0,256.311705,32392.020952,32448.0,...,516.104955,0.003441,RAD_TO_LUNG_4_STRONG_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STRONG,2
2,31976.0,32742.0,2.954125e+12,5.353925,539.00,1.794405,33016.0,260.563289,32387.700639,32452.0,...,498.623834,0.003379,RAD_TO_LUNG_4_STRONG_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STRONG,3
3,32046.0,32669.0,2.952529e+12,5.077379,430.00,1.828618,32879.0,209.891981,32379.409091,32427.0,...,324.437900,0.004345,RAD_TO_LUNG_2_STRONG_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STRONG,1
4,32050.0,32666.0,2.951682e+12,5.044582,425.25,1.803173,32824.0,206.913102,32374.789773,32415.0,...,305.718614,0.003790,RAD_TO_LUNG_2_STRONG_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STRONG,3
5,32046.5,32662.0,2.951740e+12,5.036371,434.00,1.799775,32876.0,208.458262,32375.102628,32431.0,...,314.986156,0.003796,RAD_TO_LUNG_2_STRONG_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STRONG,2
6,31915.5,32806.0,2.955626e+12,5.587952,622.00,1.807941,33174.0,303.665838,32395.448153,32471.0,...,751.967251,0.002121,RAD_TO_LUNG_4_STD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STD,3
7,31938.5,32810.5,2.956619e+12,5.556982,618.00,1.811378,33231.0,299.262890,32400.935724,32468.0,...,753.426155,0.002226,RAD_TO_LUNG_4_STD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STD,2
8,31925.0,32810.5,2.956391e+12,5.541701,617.25,1.763500,33164.0,297.769229,32399.705256,32466.0,...,685.076638,0.002831,RAD_TO_LUNG_4_STD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STD,1
9,31993.0,32726.5,2.953508e+12,5.283397,515.00,1.795629,32988.0,249.048292,32384.430753,32455.5,...,501.357758,0.002960,RAD_TO_LUNG_2_STD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STD,2
10,31870.5,32743.0,2.948917e+12,5.436469,599.00,1.812151,32988.0,289.020509,32358.796520,32458.5,...,620.775814,0.004612,RAD_TO_LUNG_2_MILD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,MILD,2
11,31869.5,32748.5,2.948800e+12,5.433300,610.00,1.786205,32953.0,287.764348,32358.154830,32440.5,...,593.437872,0.003581,RAD_TO_LUNG_2_MILD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,MILD,3
12,31992.0,32730.5,2.953190e+12,5.314510,516.00,1.803757,32938.0,249.277599,32382.674006,32437.0,...,479.351042,0.003659,RAD_TO_LUNG_2_STD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STD,3
13,31984.5,32734.0,2.954170e+12,5.328518,513.00,1.814919,32990.0,252.141935,32388.025923,32449.0,...,519.568570,0.003464,RAD_TO_LUNG_2_STD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STD,1
14,31869.5,32748.5,2.948800e+12,5.433300,610.00,1.786205,32953.0,287.764348,32358.154830,32440.5,...,593.437872,0.003581,RAD_TO_LUNG_2_MILD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,MILD,1
15,31796.5,32827.0,2.950695e+12,5.638543,741.25,1.748669,33185.0,342.119202,32367.877131,32470.0,...,818.405494,0.003631,RAD_TO_LUNG_4_MILD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,MILD,1
16,31791.0,32820.0,2.950094e+12,5.678193,752.00,1.756011,33175.0,347.168098,32364.527699,32472.5,...,846.244110,0.003695,RAD_TO_LUNG_4_MILD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,MILD,3
17,31793.5,32824.0,2.950791e+12,5.666212,732.00,1.762651,33249.0,343.502167,32368.389205,32471.0,...,820.546163,0.004010,RAD_TO_LUNG_4_MILD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,MILD,2
18,31561.5,32868.0,2.944168e+12,6.056917,771.50,2.252627,33339.0,416.320954,32330.687145,32474.5,...,1959.645007,0.001461,RAD_TO_LUNG_4_FBP_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,FBP,2
19,31583.5,32862.5,2.943754e+12,6.082272,790.00,2.251915,33253.0,418.673897,32328.386719,32480.0,...,2083.696393,0.001778,RAD_TO_LUNG_4_FBP_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,FBP,3
20,31565.0,32860.0,2.944198e+12,6.068820,785.25,2.257293,33285.0,413.524132,32330.885298,32475.5,...,2078.486888,0.001300,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,FBP,1
21,32768.0,33287.0,1.767015e+12,4.668706,298.25,2.122227,33573.0,157.218717,33025.984568,33020.0,...,131.869483,0.034848,RAD_GE_LUNG_14_ASIR10_1,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,1
22,32768.0,33297.0,1.767643e+12,4.679564,302.25,2.106098,33578.0,160.023350,33031.839506,33024.5,...,137.619490,0.031410,RAD_GE_LUNG_14_ASIR10_2,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,2
23,32768.0,33435.0,3.185674e+12,4.597171,484.00,2.103416,33840.0,223.810253,33051.684499,33006.0,...,198.710805,0.019064,RAD_GE_LUNG_7_ASIR10_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,2
24,32768.0,33450.5,3.187662e+12,4.646162,504.25,2.037225,33771.0,232.314998,33061.936557,33015.0,...,204.667535,0.018789,RAD_GE_LUNG_7_ASIR10_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,3
25,32768.0,33462.0,3.187863e+12,4.604242,517.00,2.099872,33883.0,237.744332,33062.919067,33019.0,...,214.203521,0.018326,RAD_GE_LUNG_7_ASIR10_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,1
26,32872.0,33152.0,3.179997e+12,4.014119,162.00,2.146182,33283.0,86.842254,33023.070645,33034.0,...,45.684384,0.013075,RAD_GE_LUNG_7_ASIR40_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,1
27,32880.0,33143.0,3.179332e+12,3.915419,150.00,2.177949,33261.0,80.409788,33019.640604,33028.0,...,40.415439,0.009389,RAD_GE_LUNG_7_ASIR40_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,2
28,32882.0,33153.0,3.180978e+12,3.964278,156.00,2.115175,33264.0,84.023208,33028.177984,33038.5,...,43.489422,0.009158,RAD_GE_LUNG_7_ASIR40_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,3
29,32768.0,33444.0,3.187095e+12,4.612909,504.00,2.100858,33868.0,231.074171,33058.996914,33019.0,...,207.912686,0.019079,RAD_GE_LUNG_7_ASIR70_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,1
30,32768.0,33432.0,3.186930e+12,4.637224,485.00,2.031970,33749.0,225.246504,33058.202675,33018.0,...,203.572538,0.018467,RAD_GE_LUNG_7_ASIR70_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,3
31,32768.0,33413.0,3.184849e+12,4.607459,461.50,2.097481,33795.0,216.029842,33047.472565,33008.0,...,183.571338,0.020317,RAD_GE_LUNG_7_ASIR70_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,2
32,32768.0,33457.5,3.187191e+12,4.521871,518.00,1.884100,33756.0,240.972282,33059.441701,33011.0,...,208.775927,0.017491,RAD_GE_LUNG_14_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,1
33,32768.0,33458.0,3.187863e+12,4.538142,530.00,1.859088,33883.0,241.939038,33062.921468,33021.0,...,213.674965,0.016764,RAD_GE_LUNG_14_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,2
34,32768.0,33466.0,3.188041e+12,4.598018,519.00,2.100799,33887.0,239.359213,33063.823731,33019.0,...,215.932813,0.017928,RAD_GE_LUNG_7_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,1
35,32768.0,33455.5,3.187832e+12,4.647553,509.50,2.039873,33777.0,233.980806,33062.805213,33014.0,...,212.021779,0.019185,RAD_GE_LUNG_7_FBP_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,3
36,32768.0,33441.5,3.185872e+12,4.596123,489.25,2.106194,33850.0,225.698681,33052.697188,33007.0,...,203.841568,0.018399,RAD_GE_LUNG_7_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,2

In [5]:
#Save the dataframe in a csv file
df_TOGE.to_csv('../../../RadiomiK/Features_Global/rect1_glob.csv', index=False)