In [1]:
import pandas as pd
import pingouin as pg
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import statsmodels.api as sm

In [ ]:
# Loding the TO csv file
df = pd.read_csv("../../RadiomiK/Features_TO/Final/rect10.csv")
#Elimino le colonne diagnostics
string_to_match = 'diagnostics'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
string_to_match = 'Unnamed:'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
df_TO = df
df_TO

,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,...,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,image_ID,Manufacturer,Slice Thickness,Pixel_Spacing,Kernel,Dose,ASIR,Num_Acquisition
0,32209.5,32683.0,2.963369e+12,4.734455,301.25,1.930891,32844.0,153.752042,32439.191761,32416.0,...,182.350043,0.003149,RAD_TO_LUNG_4_STRONG_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STRONG,1
1,32211.0,32680.0,2.963198e+12,4.723147,297.25,1.919187,32838.0,153.099665,32438.265625,32420.0,...,147.143374,0.005480,RAD_TO_LUNG_4_STRONG_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STRONG,2
2,32209.5,32682.0,2.963282e+12,4.757702,305.25,1.920834,32857.0,156.241410,32438.704190,32422.0,...,148.466434,0.005499,RAD_TO_LUNG_4_STRONG_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STRONG,3
3,32252.5,32627.0,2.963465e+12,4.453374,241.25,1.965077,32782.0,123.554166,32439.889915,32432.0,...,103.424496,0.003956,RAD_TO_LUNG_2_STRONG_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STRONG,1
4,32258.0,32627.0,2.963695e+12,4.431744,236.00,1.988002,32775.0,120.430810,32441.160511,32433.0,...,97.830655,0.005345,RAD_TO_LUNG_2_STRONG_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STRONG,3
5,32260.0,32630.0,2.964012e+12,4.439946,234.00,2.008129,32819.0,120.446138,32442.894886,32435.5,...,99.145621,0.004392,RAD_TO_LUNG_2_STRONG_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STRONG,2
6,32171.0,32721.0,2.963530e+12,4.969864,358.25,1.896132,32908.0,182.375602,32439.885298,32422.0,...,225.723884,0.004281,RAD_TO_LUNG_4_STD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STD,3
7,32173.5,32719.0,2.963513e+12,4.940824,346.00,1.909730,32913.0,178.596056,32439.817116,32419.0,...,228.521445,0.004088,RAD_TO_LUNG_4_STD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STD,2
8,32177.0,32723.0,2.963770e+12,4.946875,354.00,1.909562,32910.0,179.671696,32441.216264,32418.0,...,253.816795,0.003099,RAD_TO_LUNG_4_STD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STD,1
9,32223.0,32671.0,2.964001e+12,4.699570,290.50,1.956745,32889.0,146.981411,32442.690341,32433.0,...,178.684926,0.003108,RAD_TO_LUNG_2_STD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STD,2
10,32199.0,32731.0,2.965566e+12,4.902873,344.00,1.911694,32926.0,172.241187,32451.087003,32430.0,...,218.731667,0.003632,RAD_TO_LUNG_2_MILD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,MILD,2
11,32191.5,32739.0,2.965371e+12,4.893497,350.25,1.885936,32895.0,173.282097,32450.010653,32428.0,...,196.160188,0.005842,RAD_TO_LUNG_2_MILD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,MILD,3
12,32221.0,32669.0,2.963735e+12,4.695113,286.00,1.957265,32844.0,146.616335,32441.237926,32430.0,...,143.881158,0.005449,RAD_TO_LUNG_2_STD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STD,3
13,32212.0,32668.0,2.963339e+12,4.737936,300.25,1.941188,32842.0,152.221079,32439.037642,32431.0,...,175.908272,0.003599,RAD_TO_LUNG_2_STD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STD,1
14,32191.5,32739.0,2.965371e+12,4.893497,350.25,1.885936,32895.0,173.282097,32450.010653,32428.0,...,196.160188,0.005842,RAD_TO_LUNG_2_MILD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,MILD,1
15,32133.0,32804.0,2.965427e+12,5.136347,435.00,1.814710,33008.0,215.060992,32449.990057,32415.0,...,330.076019,0.003356,RAD_TO_LUNG_4_MILD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,MILD,1
16,32138.5,32805.0,2.965286e+12,5.136833,442.00,1.802859,32961.0,215.502969,32449.220881,32416.5,...,297.520611,0.004504,RAD_TO_LUNG_4_MILD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,MILD,3
17,32137.0,32796.5,2.965206e+12,5.119572,428.00,1.821039,32978.0,212.322260,32448.808594,32415.0,...,276.811263,0.005750,RAD_TO_LUNG_4_MILD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,MILD,2
18,32035.0,32957.5,2.967198e+12,5.760839,498.25,2.378990,33372.0,284.280747,32458.803622,32413.5,...,909.450311,0.002528,RAD_TO_LUNG_4_FBP_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,2
19,32037.0,32964.0,2.967375e+12,5.764309,500.00,2.377993,33353.0,286.809581,32459.753551,32417.0,...,1054.910671,0.001460,RAD_TO_LUNG_4_FBP_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,3
20,32021.0,32969.0,2.967383e+12,5.794103,517.00,2.380249,33465.0,290.981950,32459.724432,32420.5,...,1072.346875,0.001501,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1

In [3]:
# Loding the GE csv files and joining them in a single dataframe
df_21 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect10_21.csv")
df_35 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect10_35.csv")
df_40 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect10_40.csv")
df_42 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect10_42.csv")
df_43 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect10_43.csv")

df = pd.concat([df_21, df_35, df_40, df_42, df_43], ignore_index=True)

#Elimino le colonne diagnostics
string_to_match = 'diagnostics'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
string_to_match = 'Unnamed:'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
df_GE = df
df_GE

,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,...,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,image_ID,Manufacturer,Slice Thickness,Pixel_Spacing,Kernel,Dose,ASIR,Num_Acquisition
0,32820.8,34297.0,1.819205e+12,6.009518,856.75,2.016862,34779.0,446.197000,33506.558025,33420.0,...,1055.606069,0.023122,RAD_GE_LUNG_14_ASIR10_1,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,1
1,32837.8,34287.2,1.819215e+12,6.026328,838.25,2.019900,34695.0,440.103973,33506.776543,33419.0,...,1089.832349,0.020755,RAD_GE_LUNG_14_ASIR10_2,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,2
2,32817.5,34281.5,3.273113e+12,6.031553,818.00,2.085376,34758.0,434.781406,33499.266804,33422.0,...,1082.707288,0.020903,RAD_GE_LUNG_7_ASIR10_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,2
3,32821.5,34275.0,3.273877e+12,6.029641,813.50,2.082132,34868.0,435.259147,33503.192730,33416.0,...,1086.213791,0.023733,RAD_GE_LUNG_7_ASIR10_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,3
4,32804.5,34302.0,3.274571e+12,6.037006,872.25,2.054023,34818.0,448.760938,33506.485940,33433.5,...,1135.366146,0.022841,RAD_GE_LUNG_7_ASIR10_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,1
5,33313.5,33679.0,3.268930e+12,4.437154,212.50,2.345100,33847.0,114.095997,33481.537037,33464.0,...,122.141603,0.002990,RAD_GE_LUNG_7_ASIR40_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,1
6,33313.0,33675.0,3.268159e+12,4.416032,208.25,2.370932,33859.0,111.576632,33477.599451,33459.0,...,87.253140,0.004499,RAD_GE_LUNG_7_ASIR40_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,2
7,33319.0,33678.0,3.268876e+12,4.408895,209.00,2.372041,33871.0,111.633086,33481.273663,33464.0,...,96.404132,0.004734,RAD_GE_LUNG_7_ASIR40_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,3
8,32831.5,34275.5,3.273812e+12,6.051506,832.25,2.077584,34781.0,433.232553,33502.867284,33429.0,...,1105.204033,0.023753,RAD_GE_LUNG_7_ASIR70_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,1
9,32846.0,34248.5,3.273186e+12,6.042749,778.50,2.105175,34835.0,419.977976,33499.909808,33417.0,...,1068.540434,0.022144,RAD_GE_LUNG_7_ASIR70_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,3
10,32851.0,34250.0,3.272404e+12,6.037126,785.25,2.108280,34702.0,418.740675,33495.904321,33424.0,...,1033.443917,0.020178,RAD_GE_LUNG_7_ASIR70_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,2
11,32801.5,34299.0,3.275067e+12,6.039312,864.75,2.028694,34793.0,450.234069,33509.016118,33424.0,...,1083.454338,0.020754,RAD_GE_LUNG_14_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,1
12,32816.5,34298.0,3.274745e+12,6.035928,864.25,2.032633,34741.0,445.655854,33507.463992,33425.0,...,1103.338395,0.020541,RAD_GE_LUNG_14_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,2
13,32798.0,34311.5,3.274768e+12,6.033240,881.50,2.048472,34827.0,452.558186,33507.426955,33434.5,...,1162.554238,0.022150,RAD_GE_LUNG_7_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,1
14,32816.0,34283.0,3.274058e+12,6.034478,821.25,2.076780,34877.0,438.955532,33504.056927,33416.5,...,1099.941343,0.024473,RAD_GE_LUNG_7_FBP_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,3
15,32809.5,34288.5,3.273296e+12,6.032179,828.25,2.079987,34772.0,438.750419,33500.133402,33420.0,...,1097.735885,0.021175,RAD_GE_LUNG_7_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,2

In [4]:
df_TOGE = pd.concat([df_TO, df_GE], ignore_index=True)
df_TOGE

,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,...,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,image_ID,Manufacturer,Slice Thickness,Pixel_Spacing,Kernel,Dose,ASIR,Num_Acquisition
0,32209.5,32683.0,2.963369e+12,4.734455,301.25,1.930891,32844.0,153.752042,32439.191761,32416.0,...,182.350043,0.003149,RAD_TO_LUNG_4_STRONG_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STRONG,1
1,32211.0,32680.0,2.963198e+12,4.723147,297.25,1.919187,32838.0,153.099665,32438.265625,32420.0,...,147.143374,0.005480,RAD_TO_LUNG_4_STRONG_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STRONG,2
2,32209.5,32682.0,2.963282e+12,4.757702,305.25,1.920834,32857.0,156.241410,32438.704190,32422.0,...,148.466434,0.005499,RAD_TO_LUNG_4_STRONG_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STRONG,3
3,32252.5,32627.0,2.963465e+12,4.453374,241.25,1.965077,32782.0,123.554166,32439.889915,32432.0,...,103.424496,0.003956,RAD_TO_LUNG_2_STRONG_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STRONG,1
4,32258.0,32627.0,2.963695e+12,4.431744,236.00,1.988002,32775.0,120.430810,32441.160511,32433.0,...,97.830655,0.005345,RAD_TO_LUNG_2_STRONG_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STRONG,3
5,32260.0,32630.0,2.964012e+12,4.439946,234.00,2.008129,32819.0,120.446138,32442.894886,32435.5,...,99.145621,0.004392,RAD_TO_LUNG_2_STRONG_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STRONG,2
6,32171.0,32721.0,2.963530e+12,4.969864,358.25,1.896132,32908.0,182.375602,32439.885298,32422.0,...,225.723884,0.004281,RAD_TO_LUNG_4_STD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STD,3
7,32173.5,32719.0,2.963513e+12,4.940824,346.00,1.909730,32913.0,178.596056,32439.817116,32419.0,...,228.521445,0.004088,RAD_TO_LUNG_4_STD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STD,2
8,32177.0,32723.0,2.963770e+12,4.946875,354.00,1.909562,32910.0,179.671696,32441.216264,32418.0,...,253.816795,0.003099,RAD_TO_LUNG_4_STD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STD,1
9,32223.0,32671.0,2.964001e+12,4.699570,290.50,1.956745,32889.0,146.981411,32442.690341,32433.0,...,178.684926,0.003108,RAD_TO_LUNG_2_STD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STD,2
10,32199.0,32731.0,2.965566e+12,4.902873,344.00,1.911694,32926.0,172.241187,32451.087003,32430.0,...,218.731667,0.003632,RAD_TO_LUNG_2_MILD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,MILD,2
11,32191.5,32739.0,2.965371e+12,4.893497,350.25,1.885936,32895.0,173.282097,32450.010653,32428.0,...,196.160188,0.005842,RAD_TO_LUNG_2_MILD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,MILD,3
12,32221.0,32669.0,2.963735e+12,4.695113,286.00,1.957265,32844.0,146.616335,32441.237926,32430.0,...,143.881158,0.005449,RAD_TO_LUNG_2_STD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STD,3
13,32212.0,32668.0,2.963339e+12,4.737936,300.25,1.941188,32842.0,152.221079,32439.037642,32431.0,...,175.908272,0.003599,RAD_TO_LUNG_2_STD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STD,1
14,32191.5,32739.0,2.965371e+12,4.893497,350.25,1.885936,32895.0,173.282097,32450.010653,32428.0,...,196.160188,0.005842,RAD_TO_LUNG_2_MILD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,MILD,1
15,32133.0,32804.0,2.965427e+12,5.136347,435.00,1.814710,33008.0,215.060992,32449.990057,32415.0,...,330.076019,0.003356,RAD_TO_LUNG_4_MILD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,MILD,1
16,32138.5,32805.0,2.965286e+12,5.136833,442.00,1.802859,32961.0,215.502969,32449.220881,32416.5,...,297.520611,0.004504,RAD_TO_LUNG_4_MILD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,MILD,3
17,32137.0,32796.5,2.965206e+12,5.119572,428.00,1.821039,32978.0,212.322260,32448.808594,32415.0,...,276.811263,0.005750,RAD_TO_LUNG_4_MILD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,MILD,2
18,32035.0,32957.5,2.967198e+12,5.760839,498.25,2.378990,33372.0,284.280747,32458.803622,32413.5,...,909.450311,0.002528,RAD_TO_LUNG_4_FBP_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,FBP,2
19,32037.0,32964.0,2.967375e+12,5.764309,500.00,2.377993,33353.0,286.809581,32459.753551,32417.0,...,1054.910671,0.001460,RAD_TO_LUNG_4_FBP_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,FBP,3
20,32021.0,32969.0,2.967383e+12,5.794103,517.00,2.380249,33465.0,290.981950,32459.724432,32420.5,...,1072.346875,0.001501,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,FBP,1
21,32820.8,34297.0,1.819205e+12,6.009518,856.75,2.016862,34779.0,446.197000,33506.558025,33420.0,...,1055.606069,0.023122,RAD_GE_LUNG_14_ASIR10_1,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,1
22,32837.8,34287.2,1.819215e+12,6.026328,838.25,2.019900,34695.0,440.103973,33506.776543,33419.0,...,1089.832349,0.020755,RAD_GE_LUNG_14_ASIR10_2,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,2
23,32817.5,34281.5,3.273113e+12,6.031553,818.00,2.085376,34758.0,434.781406,33499.266804,33422.0,...,1082.707288,0.020903,RAD_GE_LUNG_7_ASIR10_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,2
24,32821.5,34275.0,3.273877e+12,6.029641,813.50,2.082132,34868.0,435.259147,33503.192730,33416.0,...,1086.213791,0.023733,RAD_GE_LUNG_7_ASIR10_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,3
25,32804.5,34302.0,3.274571e+12,6.037006,872.25,2.054023,34818.0,448.760938,33506.485940,33433.5,...,1135.366146,0.022841,RAD_GE_LUNG_7_ASIR10_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,1
26,33313.5,33679.0,3.268930e+12,4.437154,212.50,2.345100,33847.0,114.095997,33481.537037,33464.0,...,122.141603,0.002990,RAD_GE_LUNG_7_ASIR40_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,1
27,33313.0,33675.0,3.268159e+12,4.416032,208.25,2.370932,33859.0,111.576632,33477.599451,33459.0,...,87.253140,0.004499,RAD_GE_LUNG_7_ASIR40_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,2
28,33319.0,33678.0,3.268876e+12,4.408895,209.00,2.372041,33871.0,111.633086,33481.273663,33464.0,...,96.404132,0.004734,RAD_GE_LUNG_7_ASIR40_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,3
29,32831.5,34275.5,3.273812e+12,6.051506,832.25,2.077584,34781.0,433.232553,33502.867284,33429.0,...,1105.204033,0.023753,RAD_GE_LUNG_7_ASIR70_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,1
30,32846.0,34248.5,3.273186e+12,6.042749,778.50,2.105175,34835.0,419.977976,33499.909808,33417.0,...,1068.540434,0.022144,RAD_GE_LUNG_7_ASIR70_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,3
31,32851.0,34250.0,3.272404e+12,6.037126,785.25,2.108280,34702.0,418.740675,33495.904321,33424.0,...,1033.443917,0.020178,RAD_GE_LUNG_7_ASIR70_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,2
32,32801.5,34299.0,3.275067e+12,6.039312,864.75,2.028694,34793.0,450.234069,33509.016118,33424.0,...,1083.454338,0.020754,RAD_GE_LUNG_14_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,1
33,32816.5,34298.0,3.274745e+12,6.035928,864.25,2.032633,34741.0,445.655854,33507.463992,33425.0,...,1103.338395,0.020541,RAD_GE_LUNG_14_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,2
34,32798.0,34311.5,3.274768e+12,6.033240,881.50,2.048472,34827.0,452.558186,33507.426955,33434.5,...,1162.554238,0.022150,RAD_GE_LUNG_7_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,1
35,32816.0,34283.0,3.274058e+12,6.034478,821.25,2.076780,34877.0,438.955532,33504.056927,33416.5,...,1099.941343,0.024473,RAD_GE_LUNG_7_FBP_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,3
36,32809.5,34288.5,3.273296e+12,6.032179,828.25,2.079987,34772.0,438.750419,33500.133402,33420.0,...,1097.735885,0.021175,RAD_GE_LUNG_7_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,2

In [5]:
#Save the dataframe in a csv file
df_TOGE.to_csv('../../../RadiomiK/Features_Global/rect10_glob.csv', index=False)