In [1]:
import pandas as pd
import pingouin as pg
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import statsmodels.api as sm

In [ ]:
# Loding the TO csv file
df = pd.read_csv("../../RadiomiK/Features_TO/Final/rect3.csv")
#Elimino le colonne diagnostics
string_to_match = 'diagnostics'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
string_to_match = 'Unnamed:'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
df_TO = df
df_TO

,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,...,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,image_ID,Manufacturer,Slice Thickness,Pixel_Spacing,Kernel,Dose,ASIR,Num_Acquisition
0,32286.0,32416.0,2.946772e+12,3.055843,70.00,2.702033,32512.0,40.684415,32348.671875,32346.0,...,6.810057,0.005484,RAD_TO_LUNG_4_STRONG_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STRONG,1
1,32289.5,32414.0,2.946981e+12,2.980739,68.00,2.574805,32498.0,38.978378,32349.821023,32348.0,...,5.960682,0.005679,RAD_TO_LUNG_4_STRONG_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STRONG,2
2,32289.0,32416.0,2.947039e+12,3.011185,67.00,2.724261,32491.0,39.270272,32350.137784,32348.0,...,4.638924,0.011657,RAD_TO_LUNG_4_STRONG_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STRONG,3
3,32283.0,32421.0,2.947084e+12,3.142877,75.00,2.632331,32503.0,43.371280,32350.378906,32348.0,...,8.486301,0.004396,RAD_TO_LUNG_2_STRONG_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STRONG,1
4,32282.0,32415.5,2.946766e+12,3.093969,74.00,2.745748,32563.0,42.282786,32348.635653,32347.0,...,6.318084,0.008192,RAD_TO_LUNG_2_STRONG_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STRONG,3
5,32286.0,32416.0,2.946936e+12,3.050091,71.00,2.638444,32511.0,41.171713,32349.566761,32347.0,...,6.333069,0.006630,RAD_TO_LUNG_2_STRONG_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STRONG,2
6,32277.0,32425.0,2.946973e+12,3.206113,80.00,2.634535,32531.0,45.425535,32349.764205,32347.0,...,8.067300,0.010414,RAD_TO_LUNG_4_STD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STD,3
7,32281.0,32424.0,2.946893e+12,3.168782,80.00,2.526670,32514.0,45.059356,32349.324929,32347.0,...,10.271027,0.005689,RAD_TO_LUNG_4_STD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STD,2
8,32276.0,32425.5,2.946688e+12,3.252887,83.00,2.609925,32528.0,47.249539,32348.195312,32346.0,...,8.612121,0.011102,RAD_TO_LUNG_4_STD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STD,1
9,32272.0,32430.0,2.946928e+12,3.306024,88.00,2.571327,32545.0,49.511534,32349.509233,32348.0,...,12.297788,0.006753,RAD_TO_LUNG_2_STD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STD,2
10,32255.0,32448.0,2.947004e+12,3.588232,108.00,2.475257,32568.0,60.864616,32349.898082,32349.0,...,21.302414,0.007644,RAD_TO_LUNG_2_MILD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,MILD,2
11,32250.0,32448.0,2.946646e+12,3.627940,113.25,2.531377,32594.0,62.535330,32347.926136,32345.5,...,25.859301,0.006425,RAD_TO_LUNG_2_MILD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,MILD,3
12,32267.0,32430.0,2.946653e+12,3.334889,91.00,2.568929,32573.0,50.992762,32347.993608,32345.0,...,11.361788,0.007516,RAD_TO_LUNG_2_STD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STD,3
13,32269.0,32434.0,2.947028e+12,3.381551,89.00,2.597663,32540.0,51.401428,32350.050426,32349.0,...,15.467767,0.005040,RAD_TO_LUNG_2_STD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STD,1
14,32250.0,32448.0,2.946646e+12,3.627940,113.25,2.531377,32594.0,62.535330,32347.926136,32345.5,...,25.859301,0.006425,RAD_TO_LUNG_2_MILD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,MILD,1
15,32256.0,32442.0,2.946765e+12,3.555288,106.00,2.519778,32570.0,59.189023,32348.589844,32346.0,...,19.433795,0.008014,RAD_TO_LUNG_4_MILD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,MILD,1
16,32259.0,32441.5,2.947008e+12,3.524391,102.25,2.569972,32602.0,57.133018,32349.928977,32349.0,...,20.179258,0.007218,RAD_TO_LUNG_4_MILD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,MILD,3
17,32263.5,32444.0,2.946993e+12,3.494726,100.00,2.547767,32574.0,56.546317,32349.846946,32347.0,...,22.956506,0.004476,RAD_TO_LUNG_4_MILD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,MILD,2
18,32227.0,32477.0,2.946964e+12,4.028684,131.00,3.172031,32708.0,78.142392,32349.610440,32348.0,...,95.192539,0.002766,RAD_TO_LUNG_4_FBP_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,2
19,32222.0,32480.0,2.946920e+12,4.053538,137.25,3.160726,32783.0,79.854588,32349.362216,32348.5,...,77.993855,0.005128,RAD_TO_LUNG_4_FBP_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,3
20,32217.0,32484.5,2.946718e+12,4.084288,138.00,3.087609,32735.0,82.229514,32348.247159,32345.0,...,88.561149,0.003869,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1

In [3]:
# Loding the GE csv files and joining them in a single dataframe
df_21 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect3_21.csv")
df_35 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect3_35.csv")
df_40 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect3_40.csv")
df_42 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect3_42.csv")
df_43 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect3_43.csv")

df = pd.concat([df_21, df_35, df_40, df_42, df_43], ignore_index=True)

#Elimino le colonne diagnostics
string_to_match = 'diagnostics'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
string_to_match = 'Unnamed:'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
df_GE = df
df_GE

,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,...,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,image_ID,Manufacturer,Slice Thickness,Pixel_Spacing,Kernel,Dose,ASIR,Num_Acquisition
0,33293.0,33479.0,1.805062e+12,3.604460,89.25,3.554242,33658.0,58.002356,33380.087654,33374.0,...,31.252897,0.007056,RAD_GE_LUNG_14_ASIR10_1,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,1
1,33296.0,33483.0,1.805435e+12,3.603003,92.00,3.474045,33653.0,58.811660,33383.530864,33376.0,...,37.008754,0.004303,RAD_GE_LUNG_14_ASIR10_2,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,2
2,33253.0,33528.0,3.250546e+12,4.150912,138.25,3.258672,33764.0,85.099337,33387.361111,33384.0,...,107.922940,0.003028,RAD_GE_LUNG_7_ASIR10_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,2
3,33252.5,33522.5,3.250960e+12,4.127609,136.00,3.279168,33736.0,83.645014,33389.494170,33388.5,...,106.293859,0.002771,RAD_GE_LUNG_7_ASIR10_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,3
4,33247.0,33528.0,3.249962e+12,4.158778,137.25,3.233440,33829.0,85.333094,33384.361797,33383.0,...,135.347925,0.002200,RAD_GE_LUNG_7_ASIR10_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,1
5,33356.0,33424.5,3.250686e+12,2.173150,32.00,3.903870,33509.0,20.832689,33388.246571,33386.0,...,0.915487,0.007267,RAD_GE_LUNG_7_ASIR40_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,1
6,33356.0,33426.0,3.250863e+12,2.247705,34.00,3.568646,33499.0,22.156582,33389.152263,33386.0,...,1.441178,0.003786,RAD_GE_LUNG_7_ASIR40_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,2
7,33360.0,33430.0,3.251527e+12,2.193201,34.00,3.423561,33490.0,21.371752,33392.562071,33390.0,...,0.986490,0.006409,RAD_GE_LUNG_7_ASIR40_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,3
8,33296.0,33476.0,3.249849e+12,3.537661,91.00,3.399636,33687.0,55.276557,33383.882030,33382.0,...,38.294609,0.002839,RAD_GE_LUNG_7_ASIR70_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,1
9,33302.0,33475.0,3.250785e+12,3.519642,88.00,3.392979,33623.0,54.345713,33388.695130,33387.0,...,27.329009,0.006366,RAD_GE_LUNG_7_ASIR70_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,3
10,33301.0,33477.0,3.250269e+12,3.537401,89.00,3.423105,33643.0,55.137013,33386.038409,33382.0,...,31.676939,0.003935,RAD_GE_LUNG_7_ASIR70_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,2
11,33269.0,33504.0,3.249765e+12,3.913136,117.25,3.374893,33782.0,72.082495,33383.399520,33381.0,...,68.030698,0.003173,RAD_GE_LUNG_14_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,1
12,33270.0,33510.0,3.250082e+12,3.957098,124.00,3.215385,33713.0,74.907231,33385.021262,33379.0,...,64.484542,0.004602,RAD_GE_LUNG_14_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,2
13,33238.0,33538.0,3.249973e+12,4.246827,146.25,3.216712,33855.0,90.894969,33384.396776,33383.0,...,154.160609,0.002079,RAD_GE_LUNG_7_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,1
14,33244.0,33532.0,3.250984e+12,4.217290,145.00,3.265441,33756.0,89.099141,33389.591221,33389.0,...,126.851350,0.002658,RAD_GE_LUNG_7_FBP_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,3
15,33245.0,33539.0,3.250590e+12,4.243526,147.00,3.238656,33786.0,90.761485,33387.562414,33384.0,...,137.161696,0.002227,RAD_GE_LUNG_7_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,2

In [4]:
df_TOGE = pd.concat([df_TO, df_GE], ignore_index=True)
df_TOGE

,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,...,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,image_ID,Manufacturer,Slice Thickness,Pixel_Spacing,Kernel,Dose,ASIR,Num_Acquisition
0,32286.0,32416.0,2.946772e+12,3.055843,70.00,2.702033,32512.0,40.684415,32348.671875,32346.0,...,6.810057,0.005484,RAD_TO_LUNG_4_STRONG_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STRONG,1
1,32289.5,32414.0,2.946981e+12,2.980739,68.00,2.574805,32498.0,38.978378,32349.821023,32348.0,...,5.960682,0.005679,RAD_TO_LUNG_4_STRONG_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STRONG,2
2,32289.0,32416.0,2.947039e+12,3.011185,67.00,2.724261,32491.0,39.270272,32350.137784,32348.0,...,4.638924,0.011657,RAD_TO_LUNG_4_STRONG_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STRONG,3
3,32283.0,32421.0,2.947084e+12,3.142877,75.00,2.632331,32503.0,43.371280,32350.378906,32348.0,...,8.486301,0.004396,RAD_TO_LUNG_2_STRONG_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STRONG,1
4,32282.0,32415.5,2.946766e+12,3.093969,74.00,2.745748,32563.0,42.282786,32348.635653,32347.0,...,6.318084,0.008192,RAD_TO_LUNG_2_STRONG_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STRONG,3
5,32286.0,32416.0,2.946936e+12,3.050091,71.00,2.638444,32511.0,41.171713,32349.566761,32347.0,...,6.333069,0.006630,RAD_TO_LUNG_2_STRONG_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STRONG,2
6,32277.0,32425.0,2.946973e+12,3.206113,80.00,2.634535,32531.0,45.425535,32349.764205,32347.0,...,8.067300,0.010414,RAD_TO_LUNG_4_STD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STD,3
7,32281.0,32424.0,2.946893e+12,3.168782,80.00,2.526670,32514.0,45.059356,32349.324929,32347.0,...,10.271027,0.005689,RAD_TO_LUNG_4_STD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STD,2
8,32276.0,32425.5,2.946688e+12,3.252887,83.00,2.609925,32528.0,47.249539,32348.195312,32346.0,...,8.612121,0.011102,RAD_TO_LUNG_4_STD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STD,1
9,32272.0,32430.0,2.946928e+12,3.306024,88.00,2.571327,32545.0,49.511534,32349.509233,32348.0,...,12.297788,0.006753,RAD_TO_LUNG_2_STD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STD,2
10,32255.0,32448.0,2.947004e+12,3.588232,108.00,2.475257,32568.0,60.864616,32349.898082,32349.0,...,21.302414,0.007644,RAD_TO_LUNG_2_MILD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,MILD,2
11,32250.0,32448.0,2.946646e+12,3.627940,113.25,2.531377,32594.0,62.535330,32347.926136,32345.5,...,25.859301,0.006425,RAD_TO_LUNG_2_MILD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,MILD,3
12,32267.0,32430.0,2.946653e+12,3.334889,91.00,2.568929,32573.0,50.992762,32347.993608,32345.0,...,11.361788,0.007516,RAD_TO_LUNG_2_STD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STD,3
13,32269.0,32434.0,2.947028e+12,3.381551,89.00,2.597663,32540.0,51.401428,32350.050426,32349.0,...,15.467767,0.005040,RAD_TO_LUNG_2_STD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STD,1
14,32250.0,32448.0,2.946646e+12,3.627940,113.25,2.531377,32594.0,62.535330,32347.926136,32345.5,...,25.859301,0.006425,RAD_TO_LUNG_2_MILD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,MILD,1
15,32256.0,32442.0,2.946765e+12,3.555288,106.00,2.519778,32570.0,59.189023,32348.589844,32346.0,...,19.433795,0.008014,RAD_TO_LUNG_4_MILD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,MILD,1
16,32259.0,32441.5,2.947008e+12,3.524391,102.25,2.569972,32602.0,57.133018,32349.928977,32349.0,...,20.179258,0.007218,RAD_TO_LUNG_4_MILD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,MILD,3
17,32263.5,32444.0,2.946993e+12,3.494726,100.00,2.547767,32574.0,56.546317,32349.846946,32347.0,...,22.956506,0.004476,RAD_TO_LUNG_4_MILD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,MILD,2
18,32227.0,32477.0,2.946964e+12,4.028684,131.00,3.172031,32708.0,78.142392,32349.610440,32348.0,...,95.192539,0.002766,RAD_TO_LUNG_4_FBP_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,FBP,2
19,32222.0,32480.0,2.946920e+12,4.053538,137.25,3.160726,32783.0,79.854588,32349.362216,32348.5,...,77.993855,0.005128,RAD_TO_LUNG_4_FBP_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,FBP,3
20,32217.0,32484.5,2.946718e+12,4.084288,138.00,3.087609,32735.0,82.229514,32348.247159,32345.0,...,88.561149,0.003869,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,FBP,1
21,33293.0,33479.0,1.805062e+12,3.604460,89.25,3.554242,33658.0,58.002356,33380.087654,33374.0,...,31.252897,0.007056,RAD_GE_LUNG_14_ASIR10_1,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,1
22,33296.0,33483.0,1.805435e+12,3.603003,92.00,3.474045,33653.0,58.811660,33383.530864,33376.0,...,37.008754,0.004303,RAD_GE_LUNG_14_ASIR10_2,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,2
23,33253.0,33528.0,3.250546e+12,4.150912,138.25,3.258672,33764.0,85.099337,33387.361111,33384.0,...,107.922940,0.003028,RAD_GE_LUNG_7_ASIR10_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,2
24,33252.5,33522.5,3.250960e+12,4.127609,136.00,3.279168,33736.0,83.645014,33389.494170,33388.5,...,106.293859,0.002771,RAD_GE_LUNG_7_ASIR10_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,3
25,33247.0,33528.0,3.249962e+12,4.158778,137.25,3.233440,33829.0,85.333094,33384.361797,33383.0,...,135.347925,0.002200,RAD_GE_LUNG_7_ASIR10_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,1
26,33356.0,33424.5,3.250686e+12,2.173150,32.00,3.903870,33509.0,20.832689,33388.246571,33386.0,...,0.915487,0.007267,RAD_GE_LUNG_7_ASIR40_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,1
27,33356.0,33426.0,3.250863e+12,2.247705,34.00,3.568646,33499.0,22.156582,33389.152263,33386.0,...,1.441178,0.003786,RAD_GE_LUNG_7_ASIR40_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,2
28,33360.0,33430.0,3.251527e+12,2.193201,34.00,3.423561,33490.0,21.371752,33392.562071,33390.0,...,0.986490,0.006409,RAD_GE_LUNG_7_ASIR40_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,3
29,33296.0,33476.0,3.249849e+12,3.537661,91.00,3.399636,33687.0,55.276557,33383.882030,33382.0,...,38.294609,0.002839,RAD_GE_LUNG_7_ASIR70_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,1
30,33302.0,33475.0,3.250785e+12,3.519642,88.00,3.392979,33623.0,54.345713,33388.695130,33387.0,...,27.329009,0.006366,RAD_GE_LUNG_7_ASIR70_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,3
31,33301.0,33477.0,3.250269e+12,3.537401,89.00,3.423105,33643.0,55.137013,33386.038409,33382.0,...,31.676939,0.003935,RAD_GE_LUNG_7_ASIR70_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,2
32,33269.0,33504.0,3.249765e+12,3.913136,117.25,3.374893,33782.0,72.082495,33383.399520,33381.0,...,68.030698,0.003173,RAD_GE_LUNG_14_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,1
33,33270.0,33510.0,3.250082e+12,3.957098,124.00,3.215385,33713.0,74.907231,33385.021262,33379.0,...,64.484542,0.004602,RAD_GE_LUNG_14_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,2
34,33238.0,33538.0,3.249973e+12,4.246827,146.25,3.216712,33855.0,90.894969,33384.396776,33383.0,...,154.160609,0.002079,RAD_GE_LUNG_7_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,1
35,33244.0,33532.0,3.250984e+12,4.217290,145.00,3.265441,33756.0,89.099141,33389.591221,33389.0,...,126.851350,0.002658,RAD_GE_LUNG_7_FBP_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,3
36,33245.0,33539.0,3.250590e+12,4.243526,147.00,3.238656,33786.0,90.761485,33387.562414,33384.0,...,137.161696,0.002227,RAD_GE_LUNG_7_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,2

In [5]:
#Save the dataframe in a csv file
df_TOGE.to_csv('../../../RadiomiK/Features_Global/rect3_glob.csv', index=False)