In [1]:
import pandas as pd
import pingouin as pg
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import statsmodels.api as sm

In [ ]:
# Loding the TO csv file
df = pd.read_csv("../../RadiomiK/Features_TO/Final/rect4.csv")
#Elimino le colonne diagnostics
string_to_match = 'diagnostics'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
string_to_match = 'Unnamed:'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
df_TO = df
df_TO

,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,...,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,image_ID,Manufacturer,Slice Thickness,Pixel_Spacing,Kernel,Dose,ASIR,Num_Acquisition
0,32838.0,32953.0,3.047533e+12,2.875032,60.00,3.135858,33014.0,35.635204,32897.089844,32899.0,...,5.884309,0.003151,RAD_TO_LUNG_4_STRONG_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STRONG,1
1,32838.0,32952.0,3.047708e+12,2.862691,59.00,3.312375,33007.0,35.524968,32898.033026,32902.0,...,8.130975,0.002747,RAD_TO_LUNG_4_STRONG_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STRONG,2
2,32840.0,32954.0,3.047714e+12,2.903251,63.00,3.202435,33013.0,36.595344,32898.067827,32901.0,...,7.957434,0.002524,RAD_TO_LUNG_4_STRONG_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STRONG,3
3,32839.0,32957.5,3.047718e+12,2.978837,63.00,3.418978,33027.0,37.587640,32898.085227,32901.0,...,11.383482,0.002212,RAD_TO_LUNG_2_STRONG_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STRONG,1
4,32833.0,32957.0,3.047489e+12,2.990537,68.25,2.846382,33021.0,38.988869,32896.844815,32899.0,...,7.001933,0.004436,RAD_TO_LUNG_2_STRONG_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STRONG,3
5,32838.0,32960.0,3.047810e+12,2.986588,65.00,3.048118,33033.0,38.403057,32898.580966,32900.0,...,6.721330,0.002980,RAD_TO_LUNG_2_STRONG_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STRONG,2
6,32832.0,32963.0,3.047776e+12,3.071661,71.00,2.955862,33029.0,41.477910,32898.392756,32900.0,...,12.621134,0.002492,RAD_TO_LUNG_4_STD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STD,3
7,32832.0,32960.0,3.047773e+12,3.033366,70.00,3.165494,33027.0,40.125115,32898.379972,32902.0,...,10.374561,0.004058,RAD_TO_LUNG_4_STD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STD,2
8,32832.0,32960.0,3.047529e+12,3.051091,68.00,2.988380,33035.0,40.345795,32897.058949,32898.0,...,9.642296,0.003002,RAD_TO_LUNG_4_STD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STD,1
9,32827.0,32972.0,3.047884e+12,3.215762,78.00,2.817099,33061.0,45.738632,32898.964489,32900.0,...,12.491935,0.004073,RAD_TO_LUNG_2_STD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STD,2
10,32812.0,32986.0,3.047940e+12,3.463002,97.00,2.661852,33117.0,55.059157,32899.247159,32900.5,...,25.662344,0.003310,RAD_TO_LUNG_2_MILD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,MILD,2
11,32807.0,32984.0,3.047702e+12,3.481588,101.00,2.596762,33124.0,55.823955,32897.962358,32899.0,...,22.013568,0.005422,RAD_TO_LUNG_2_MILD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,MILD,3
12,32824.0,32970.0,3.047683e+12,3.226630,83.00,2.658159,33061.0,46.243792,32897.881037,32899.0,...,12.758612,0.004955,RAD_TO_LUNG_2_STD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STD,3
13,32828.0,32967.0,3.047735e+12,3.197054,76.00,3.201020,33049.0,44.492095,32898.164773,32900.0,...,18.394751,0.002465,RAD_TO_LUNG_2_STD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STD,1
14,32807.0,32984.0,3.047702e+12,3.481588,101.00,2.596762,33124.0,55.823955,32897.962358,32899.0,...,22.013568,0.005422,RAD_TO_LUNG_2_MILD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,MILD,1
15,32816.0,32975.0,3.047551e+12,3.319179,89.00,2.640820,33066.0,49.778199,32897.161932,32898.0,...,13.813436,0.006299,RAD_TO_LUNG_4_MILD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,MILD,1
16,32816.5,32977.0,3.047773e+12,3.335005,90.00,2.698601,33066.0,50.594443,32898.358310,32900.0,...,17.632717,0.004440,RAD_TO_LUNG_4_MILD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,MILD,3
17,32819.0,32975.0,3.047787e+12,3.302144,87.00,2.788550,33053.0,49.229359,32898.433239,32902.0,...,21.961532,0.002935,RAD_TO_LUNG_4_MILD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,MILD,2
18,32780.0,33012.0,3.047793e+12,3.884759,126.00,2.986261,33171.0,71.570944,32898.400213,32903.0,...,88.013377,0.002452,RAD_TO_LUNG_4_FBP_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,2
19,32783.0,33014.0,3.047793e+12,3.904456,123.25,3.035558,33236.0,73.049172,32898.398438,32900.0,...,74.764825,0.002884,RAD_TO_LUNG_4_FBP_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,3
20,32780.0,33014.0,3.047559e+12,3.915704,124.00,2.901261,33153.0,72.941497,32897.135653,32897.0,...,75.600964,0.002897,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1

In [3]:
# Loding the GE csv files and joining them in a single dataframe
df_21 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect4_21.csv")
df_35 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect4_35.csv")
df_40 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect4_40.csv")
df_42 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect4_42.csv")
df_43 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect4_43.csv")

df = pd.concat([df_21, df_35, df_40, df_42, df_43], ignore_index=True)

#Elimino le colonne diagnostics
string_to_match = 'diagnostics'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
string_to_match = 'Unnamed:'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
df_GE = df
df_GE

,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,...,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,image_ID,Manufacturer,Slice Thickness,Pixel_Spacing,Kernel,Dose,ASIR,Num_Acquisition
0,33864.0,33993.0,1.865030e+12,3.069554,67.00,3.163943,34072.0,40.409236,33930.083951,33934.0,...,18.268597,0.003591,RAD_GE_LUNG_14_ASIR10_1,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,1
1,33866.0,34002.1,1.865547e+12,3.166937,72.00,3.063319,34087.0,43.064121,33934.778395,33935.0,...,19.788286,0.003527,RAD_GE_LUNG_14_ASIR10_2,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,2
2,33793.0,34043.0,3.355354e+12,3.994835,129.25,2.944575,34216.0,77.051344,33921.391632,33924.0,...,79.192014,0.003532,RAD_GE_LUNG_7_ASIR10_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,2
3,33804.0,34044.0,3.355752e+12,3.948933,124.00,3.063869,34217.0,74.459858,33923.412209,33923.0,...,79.384799,0.003487,RAD_GE_LUNG_7_ASIR10_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,3
4,33803.0,34047.0,3.356331e+12,3.991530,129.25,3.051522,34238.0,76.912623,33926.327160,33931.0,...,78.824031,0.003307,RAD_GE_LUNG_7_ASIR10_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,1
5,33887.0,33960.0,3.356204e+12,2.295581,32.00,5.256521,34005.0,22.985372,33925.811728,33930.0,...,1.756369,0.001612,RAD_GE_LUNG_7_ASIR40_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,1
6,33880.0,33959.0,3.355406e+12,2.369558,37.00,3.795674,34005.0,24.453747,33921.774005,33926.0,...,1.730688,0.001708,RAD_GE_LUNG_7_ASIR40_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,2
7,33886.0,33957.0,3.355731e+12,2.298128,32.00,4.940918,34014.0,22.957177,33923.421125,33928.0,...,1.916530,0.002274,RAD_GE_LUNG_7_ASIR40_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,3
8,33845.0,34006.0,3.356477e+12,3.407863,84.00,3.194299,34121.0,50.910412,33927.141289,33930.0,...,25.910569,0.003939,RAD_GE_LUNG_7_ASIR70_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,1
9,33844.0,34004.0,3.355943e+12,3.378338,82.00,3.217247,34115.0,49.589080,33924.445816,33925.0,...,28.957260,0.002534,RAD_GE_LUNG_7_ASIR70_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,3
10,33837.5,34001.0,3.355582e+12,3.403559,86.00,2.967826,34112.0,51.133507,33922.620713,33926.0,...,24.910153,0.003594,RAD_GE_LUNG_7_ASIR70_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,2
11,33841.0,34016.0,3.356846e+12,3.542843,93.00,3.287952,34160.0,55.710867,33928.993827,33933.0,...,35.716193,0.003499,RAD_GE_LUNG_14_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,1
12,33837.0,34021.0,3.357337e+12,3.557100,95.00,3.143871,34165.0,56.602059,33931.474966,33935.0,...,36.341927,0.003236,RAD_GE_LUNG_14_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,2
13,33805.0,34045.0,3.356311e+12,3.987631,126.00,3.178570,34249.0,76.088130,33926.228395,33930.0,...,78.843345,0.003332,RAD_GE_LUNG_7_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,1
14,33808.0,34040.0,3.355731e+12,3.934911,121.00,3.228218,34224.0,73.008079,33923.305213,33924.0,...,88.028006,0.002425,RAD_GE_LUNG_7_FBP_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,3
15,33794.0,34041.0,3.355321e+12,3.986539,126.00,3.093202,34227.0,76.276564,33921.223251,33925.0,...,87.320099,0.002883,RAD_GE_LUNG_7_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,2

In [4]:
df_TOGE = pd.concat([df_TO, df_GE], ignore_index=True)
df_TOGE

,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,...,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,image_ID,Manufacturer,Slice Thickness,Pixel_Spacing,Kernel,Dose,ASIR,Num_Acquisition
0,32838.0,32953.0,3.047533e+12,2.875032,60.00,3.135858,33014.0,35.635204,32897.089844,32899.0,...,5.884309,0.003151,RAD_TO_LUNG_4_STRONG_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STRONG,1
1,32838.0,32952.0,3.047708e+12,2.862691,59.00,3.312375,33007.0,35.524968,32898.033026,32902.0,...,8.130975,0.002747,RAD_TO_LUNG_4_STRONG_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STRONG,2
2,32840.0,32954.0,3.047714e+12,2.903251,63.00,3.202435,33013.0,36.595344,32898.067827,32901.0,...,7.957434,0.002524,RAD_TO_LUNG_4_STRONG_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STRONG,3
3,32839.0,32957.5,3.047718e+12,2.978837,63.00,3.418978,33027.0,37.587640,32898.085227,32901.0,...,11.383482,0.002212,RAD_TO_LUNG_2_STRONG_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STRONG,1
4,32833.0,32957.0,3.047489e+12,2.990537,68.25,2.846382,33021.0,38.988869,32896.844815,32899.0,...,7.001933,0.004436,RAD_TO_LUNG_2_STRONG_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STRONG,3
5,32838.0,32960.0,3.047810e+12,2.986588,65.00,3.048118,33033.0,38.403057,32898.580966,32900.0,...,6.721330,0.002980,RAD_TO_LUNG_2_STRONG_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STRONG,2
6,32832.0,32963.0,3.047776e+12,3.071661,71.00,2.955862,33029.0,41.477910,32898.392756,32900.0,...,12.621134,0.002492,RAD_TO_LUNG_4_STD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STD,3
7,32832.0,32960.0,3.047773e+12,3.033366,70.00,3.165494,33027.0,40.125115,32898.379972,32902.0,...,10.374561,0.004058,RAD_TO_LUNG_4_STD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STD,2
8,32832.0,32960.0,3.047529e+12,3.051091,68.00,2.988380,33035.0,40.345795,32897.058949,32898.0,...,9.642296,0.003002,RAD_TO_LUNG_4_STD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STD,1
9,32827.0,32972.0,3.047884e+12,3.215762,78.00,2.817099,33061.0,45.738632,32898.964489,32900.0,...,12.491935,0.004073,RAD_TO_LUNG_2_STD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STD,2
10,32812.0,32986.0,3.047940e+12,3.463002,97.00,2.661852,33117.0,55.059157,32899.247159,32900.5,...,25.662344,0.003310,RAD_TO_LUNG_2_MILD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,MILD,2
11,32807.0,32984.0,3.047702e+12,3.481588,101.00,2.596762,33124.0,55.823955,32897.962358,32899.0,...,22.013568,0.005422,RAD_TO_LUNG_2_MILD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,MILD,3
12,32824.0,32970.0,3.047683e+12,3.226630,83.00,2.658159,33061.0,46.243792,32897.881037,32899.0,...,12.758612,0.004955,RAD_TO_LUNG_2_STD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STD,3
13,32828.0,32967.0,3.047735e+12,3.197054,76.00,3.201020,33049.0,44.492095,32898.164773,32900.0,...,18.394751,0.002465,RAD_TO_LUNG_2_STD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STD,1
14,32807.0,32984.0,3.047702e+12,3.481588,101.00,2.596762,33124.0,55.823955,32897.962358,32899.0,...,22.013568,0.005422,RAD_TO_LUNG_2_MILD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,MILD,1
15,32816.0,32975.0,3.047551e+12,3.319179,89.00,2.640820,33066.0,49.778199,32897.161932,32898.0,...,13.813436,0.006299,RAD_TO_LUNG_4_MILD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,MILD,1
16,32816.5,32977.0,3.047773e+12,3.335005,90.00,2.698601,33066.0,50.594443,32898.358310,32900.0,...,17.632717,0.004440,RAD_TO_LUNG_4_MILD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,MILD,3
17,32819.0,32975.0,3.047787e+12,3.302144,87.00,2.788550,33053.0,49.229359,32898.433239,32902.0,...,21.961532,0.002935,RAD_TO_LUNG_4_MILD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,MILD,2
18,32780.0,33012.0,3.047793e+12,3.884759,126.00,2.986261,33171.0,71.570944,32898.400213,32903.0,...,88.013377,0.002452,RAD_TO_LUNG_4_FBP_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,FBP,2
19,32783.0,33014.0,3.047793e+12,3.904456,123.25,3.035558,33236.0,73.049172,32898.398438,32900.0,...,74.764825,0.002884,RAD_TO_LUNG_4_FBP_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,FBP,3
20,32780.0,33014.0,3.047559e+12,3.915704,124.00,2.901261,33153.0,72.941497,32897.135653,32897.0,...,75.600964,0.002897,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,FBP,1
21,33864.0,33993.0,1.865030e+12,3.069554,67.00,3.163943,34072.0,40.409236,33930.083951,33934.0,...,18.268597,0.003591,RAD_GE_LUNG_14_ASIR10_1,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,1
22,33866.0,34002.1,1.865547e+12,3.166937,72.00,3.063319,34087.0,43.064121,33934.778395,33935.0,...,19.788286,0.003527,RAD_GE_LUNG_14_ASIR10_2,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,2
23,33793.0,34043.0,3.355354e+12,3.994835,129.25,2.944575,34216.0,77.051344,33921.391632,33924.0,...,79.192014,0.003532,RAD_GE_LUNG_7_ASIR10_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,2
24,33804.0,34044.0,3.355752e+12,3.948933,124.00,3.063869,34217.0,74.459858,33923.412209,33923.0,...,79.384799,0.003487,RAD_GE_LUNG_7_ASIR10_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,3
25,33803.0,34047.0,3.356331e+12,3.991530,129.25,3.051522,34238.0,76.912623,33926.327160,33931.0,...,78.824031,0.003307,RAD_GE_LUNG_7_ASIR10_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,1
26,33887.0,33960.0,3.356204e+12,2.295581,32.00,5.256521,34005.0,22.985372,33925.811728,33930.0,...,1.756369,0.001612,RAD_GE_LUNG_7_ASIR40_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,1
27,33880.0,33959.0,3.355406e+12,2.369558,37.00,3.795674,34005.0,24.453747,33921.774005,33926.0,...,1.730688,0.001708,RAD_GE_LUNG_7_ASIR40_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,2
28,33886.0,33957.0,3.355731e+12,2.298128,32.00,4.940918,34014.0,22.957177,33923.421125,33928.0,...,1.916530,0.002274,RAD_GE_LUNG_7_ASIR40_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,3
29,33845.0,34006.0,3.356477e+12,3.407863,84.00,3.194299,34121.0,50.910412,33927.141289,33930.0,...,25.910569,0.003939,RAD_GE_LUNG_7_ASIR70_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,1
30,33844.0,34004.0,3.355943e+12,3.378338,82.00,3.217247,34115.0,49.589080,33924.445816,33925.0,...,28.957260,0.002534,RAD_GE_LUNG_7_ASIR70_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,3
31,33837.5,34001.0,3.355582e+12,3.403559,86.00,2.967826,34112.0,51.133507,33922.620713,33926.0,...,24.910153,0.003594,RAD_GE_LUNG_7_ASIR70_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,2
32,33841.0,34016.0,3.356846e+12,3.542843,93.00,3.287952,34160.0,55.710867,33928.993827,33933.0,...,35.716193,0.003499,RAD_GE_LUNG_14_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,1
33,33837.0,34021.0,3.357337e+12,3.557100,95.00,3.143871,34165.0,56.602059,33931.474966,33935.0,...,36.341927,0.003236,RAD_GE_LUNG_14_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,2
34,33805.0,34045.0,3.356311e+12,3.987631,126.00,3.178570,34249.0,76.088130,33926.228395,33930.0,...,78.843345,0.003332,RAD_GE_LUNG_7_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,1
35,33808.0,34040.0,3.355731e+12,3.934911,121.00,3.228218,34224.0,73.008079,33923.305213,33924.0,...,88.028006,0.002425,RAD_GE_LUNG_7_FBP_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,3
36,33794.0,34041.0,3.355321e+12,3.986539,126.00,3.093202,34227.0,76.276564,33921.223251,33925.0,...,87.320099,0.002883,RAD_GE_LUNG_7_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,2

In [5]:
#Save the dataframe in a csv file
df_TOGE.to_csv('../../../RadiomiK/Features_Global/rect4_glob.csv', index=False)