In [1]:
import pandas as pd
import pingouin as pg
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import statsmodels.api as sm

In [ ]:
# Loding the TO csv file
df = pd.read_csv("../../RadiomiK/Features_TO/Final/rect12.csv")
#Elimino le colonne diagnostics
string_to_match = 'diagnostics'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
string_to_match = 'Unnamed:'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
df_TO = df
df_TO

,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,...,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,image_ID,Manufacturer,Slice Thickness,Pixel_Spacing,Kernel,Dose,ASIR,Num_Acquisition
0,32394.0,32510.0,2.965662e+12,2.853962,61.00,2.681274,32608.0,35.357971,32452.195312,32453.0,...,5.832434,0.005522,RAD_TO_LUNG_4_STRONG_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STRONG,1
1,32397.0,32508.0,2.965774e+12,2.824901,62.00,2.562390,32613.0,34.945559,32452.813565,32454.0,...,4.437949,0.009718,RAD_TO_LUNG_4_STRONG_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STRONG,2
2,32391.0,32510.0,2.965561e+12,2.882145,66.00,2.498758,32578.0,36.660764,32451.644176,32452.0,...,5.596977,0.005035,RAD_TO_LUNG_4_STRONG_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STRONG,3
3,32393.0,32512.0,2.965878e+12,2.910056,67.00,2.549892,32598.0,37.332555,32453.375710,32454.0,...,6.511210,0.005291,RAD_TO_LUNG_2_STRONG_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STRONG,1
4,32393.0,32518.0,2.965992e+12,2.991275,69.00,2.592834,32587.0,39.317535,32453.995739,32454.0,...,8.659639,0.003750,RAD_TO_LUNG_2_STRONG_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STRONG,3
5,32390.0,32510.0,2.965329e+12,2.928242,66.00,2.528637,32584.0,37.638864,32450.372514,32451.0,...,6.418011,0.005523,RAD_TO_LUNG_2_STRONG_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STRONG,2
6,32383.0,32519.5,2.965460e+12,3.104337,78.00,2.427501,32604.0,43.087666,32451.080966,32452.0,...,7.488572,0.009508,RAD_TO_LUNG_4_STD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STD,3
7,32388.0,32517.0,2.965779e+12,3.041500,73.00,2.565030,32633.0,40.819948,32452.827415,32454.0,...,8.433375,0.009115,RAD_TO_LUNG_4_STD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STD,2
8,32385.0,32518.0,2.965655e+12,3.075284,72.00,2.642894,32630.0,41.280484,32452.148438,32453.0,...,9.753009,0.005260,RAD_TO_LUNG_4_STD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STD,1
9,32376.0,32522.0,2.965196e+12,3.196485,84.00,2.486806,32619.0,45.853672,32449.631747,32451.0,...,14.376643,0.004348,RAD_TO_LUNG_2_STD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STD,2
10,32359.0,32545.0,2.965299e+12,3.529972,107.25,2.471015,32673.0,58.255981,32450.162287,32449.0,...,25.836890,0.005069,RAD_TO_LUNG_2_MILD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,MILD,2
11,32358.5,32549.0,2.966005e+12,3.572525,107.00,2.471893,32681.0,60.046822,32454.024858,32455.0,...,30.800702,0.003649,RAD_TO_LUNG_2_MILD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,MILD,3
12,32378.0,32532.0,2.965951e+12,3.259918,85.00,2.563391,32624.0,47.936976,32453.754261,32453.0,...,15.998558,0.004248,RAD_TO_LUNG_2_STD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STD,3
13,32380.0,32526.0,2.965797e+12,3.207962,84.00,2.516319,32640.0,46.112632,32452.914418,32453.0,...,15.291797,0.004101,RAD_TO_LUNG_2_STD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STD,1
14,32358.5,32549.0,2.966005e+12,3.572525,107.00,2.471893,32681.0,60.046822,32454.024858,32455.0,...,30.800702,0.003649,RAD_TO_LUNG_2_MILD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,MILD,1
15,32366.0,32538.0,2.965737e+12,3.411753,97.00,2.453785,32672.0,53.287359,32452.574929,32453.0,...,18.814937,0.006351,RAD_TO_LUNG_4_MILD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,MILD,1
16,32362.5,32537.0,2.965569e+12,3.441392,103.00,2.356371,32627.0,55.627393,32451.651278,32453.0,...,27.819538,0.003244,RAD_TO_LUNG_4_MILD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,MILD,3
17,32368.0,32537.0,2.965776e+12,3.402234,98.00,2.458638,32668.0,53.128532,32452.787642,32453.0,...,19.534131,0.006569,RAD_TO_LUNG_4_MILD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,MILD,2
18,32322.0,32581.0,2.965601e+12,4.069958,136.00,2.994036,32836.0,80.793392,32451.734020,32452.0,...,82.541577,0.005713,RAD_TO_LUNG_4_FBP_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,2
19,32314.5,32584.0,2.965488e+12,4.104855,148.00,2.946278,32778.0,83.904487,32451.106179,32450.0,...,130.869565,0.002065,RAD_TO_LUNG_4_FBP_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,3
20,32322.0,32582.0,2.965639e+12,4.067585,139.00,2.987923,32829.0,81.119213,32451.941406,32452.0,...,89.030935,0.003766,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1

In [3]:
# Loding the GE csv files and joining them in a single dataframe
df_21 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect12_21.csv")
df_35 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect12_35.csv")
df_40 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect12_40.csv")
df_42 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect12_42.csv")
df_43 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect12_43.csv")

df = pd.concat([df_21, df_35, df_40, df_42, df_43], ignore_index=True)

#Elimino le colonne diagnostics
string_to_match = 'diagnostics'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
string_to_match = 'Unnamed:'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
df_GE = df
df_GE

,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,...,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,image_ID,Manufacturer,Slice Thickness,Pixel_Spacing,Kernel,Dose,ASIR,Num_Acquisition
0,33383.0,33574.0,1.815747e+12,3.626093,109.25,2.648244,33696.0,61.174624,33478.736420,33478.0,...,34.361752,0.006489,RAD_GE_LUNG_14_ASIR10_1,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,1
1,33402.0,33560.1,1.815878e+12,3.357493,85.25,2.900926,33694.0,49.450450,33479.972840,33479.0,...,23.327200,0.006814,RAD_GE_LUNG_14_ASIR10_2,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,2
2,33354.0,33587.0,3.266594e+12,3.918667,122.00,3.082855,33816.0,73.016089,33469.729081,33469.0,...,70.733063,0.004698,RAD_GE_LUNG_7_ASIR10_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,2
3,33351.0,33591.5,3.266979e+12,3.964370,126.00,3.081932,33852.0,75.363966,33471.691015,33472.0,...,78.380635,0.003203,RAD_GE_LUNG_7_ASIR10_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,3
4,33353.5,33604.0,3.267911e+12,3.979593,131.00,2.882678,33791.0,77.005287,33476.462277,33475.0,...,87.740569,0.003123,RAD_GE_LUNG_7_ASIR10_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,1
5,33446.5,33513.0,3.268445e+12,2.152924,36.00,2.853267,33576.0,20.719956,33479.324760,33479.0,...,1.752233,0.004960,RAD_GE_LUNG_7_ASIR40_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,1
6,33444.0,33507.0,3.267535e+12,2.072655,33.00,3.045378,33569.0,19.641625,33474.666324,33474.0,...,1.341977,0.004798,RAD_GE_LUNG_7_ASIR40_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,2
7,33445.0,33511.0,3.268179e+12,2.136884,33.25,3.233105,33604.0,20.323433,33477.962277,33478.0,...,1.582406,0.005608,RAD_GE_LUNG_7_ASIR40_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,3
8,33398.0,33556.0,3.267807e+12,3.342581,84.00,2.880879,33673.0,48.891165,33476.010288,33475.0,...,24.546079,0.004594,RAD_GE_LUNG_7_ASIR70_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,1
9,33396.0,33549.5,3.267179e+12,3.345373,80.00,3.248624,33737.0,48.478133,33472.793896,33473.0,...,26.230086,0.003658,RAD_GE_LUNG_7_ASIR70_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,3
10,33398.0,33545.0,3.266705e+12,3.252876,76.00,3.152343,33702.0,45.917053,33470.371742,33470.0,...,17.842429,0.008299,RAD_GE_LUNG_7_ASIR70_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,2
11,33362.0,33596.0,3.268279e+12,3.908542,126.25,2.805462,33778.0,72.990619,33478.364540,33478.0,...,64.982371,0.004469,RAD_GE_LUNG_14_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,1
12,33377.0,33579.0,3.267879e+12,3.714695,107.00,3.009939,33760.0,63.224441,33476.341907,33476.0,...,56.256968,0.003428,RAD_GE_LUNG_14_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,2
13,33345.0,33613.0,3.267885e+12,4.082802,139.25,2.884337,33813.0,82.250691,33476.308299,33475.0,...,103.433616,0.002927,RAD_GE_LUNG_7_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,1
14,33342.0,33600.0,3.266917e+12,4.059387,134.25,3.070875,33874.0,80.392715,33471.355281,33472.0,...,96.118165,0.002927,RAD_GE_LUNG_7_FBP_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,3
15,33346.0,33594.0,3.266539e+12,4.008961,130.00,3.078897,33837.0,78.179890,33469.426612,33469.0,...,85.940242,0.004406,RAD_GE_LUNG_7_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,2

In [4]:
df_TOGE = pd.concat([df_TO, df_GE], ignore_index=True)
df_TOGE

,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,...,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,image_ID,Manufacturer,Slice Thickness,Pixel_Spacing,Kernel,Dose,ASIR,Num_Acquisition
0,32394.0,32510.0,2.965662e+12,2.853962,61.00,2.681274,32608.0,35.357971,32452.195312,32453.0,...,5.832434,0.005522,RAD_TO_LUNG_4_STRONG_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STRONG,1
1,32397.0,32508.0,2.965774e+12,2.824901,62.00,2.562390,32613.0,34.945559,32452.813565,32454.0,...,4.437949,0.009718,RAD_TO_LUNG_4_STRONG_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STRONG,2
2,32391.0,32510.0,2.965561e+12,2.882145,66.00,2.498758,32578.0,36.660764,32451.644176,32452.0,...,5.596977,0.005035,RAD_TO_LUNG_4_STRONG_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STRONG,3
3,32393.0,32512.0,2.965878e+12,2.910056,67.00,2.549892,32598.0,37.332555,32453.375710,32454.0,...,6.511210,0.005291,RAD_TO_LUNG_2_STRONG_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STRONG,1
4,32393.0,32518.0,2.965992e+12,2.991275,69.00,2.592834,32587.0,39.317535,32453.995739,32454.0,...,8.659639,0.003750,RAD_TO_LUNG_2_STRONG_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STRONG,3
5,32390.0,32510.0,2.965329e+12,2.928242,66.00,2.528637,32584.0,37.638864,32450.372514,32451.0,...,6.418011,0.005523,RAD_TO_LUNG_2_STRONG_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STRONG,2
6,32383.0,32519.5,2.965460e+12,3.104337,78.00,2.427501,32604.0,43.087666,32451.080966,32452.0,...,7.488572,0.009508,RAD_TO_LUNG_4_STD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STD,3
7,32388.0,32517.0,2.965779e+12,3.041500,73.00,2.565030,32633.0,40.819948,32452.827415,32454.0,...,8.433375,0.009115,RAD_TO_LUNG_4_STD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STD,2
8,32385.0,32518.0,2.965655e+12,3.075284,72.00,2.642894,32630.0,41.280484,32452.148438,32453.0,...,9.753009,0.005260,RAD_TO_LUNG_4_STD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STD,1
9,32376.0,32522.0,2.965196e+12,3.196485,84.00,2.486806,32619.0,45.853672,32449.631747,32451.0,...,14.376643,0.004348,RAD_TO_LUNG_2_STD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STD,2
10,32359.0,32545.0,2.965299e+12,3.529972,107.25,2.471015,32673.0,58.255981,32450.162287,32449.0,...,25.836890,0.005069,RAD_TO_LUNG_2_MILD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,MILD,2
11,32358.5,32549.0,2.966005e+12,3.572525,107.00,2.471893,32681.0,60.046822,32454.024858,32455.0,...,30.800702,0.003649,RAD_TO_LUNG_2_MILD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,MILD,3
12,32378.0,32532.0,2.965951e+12,3.259918,85.00,2.563391,32624.0,47.936976,32453.754261,32453.0,...,15.998558,0.004248,RAD_TO_LUNG_2_STD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STD,3
13,32380.0,32526.0,2.965797e+12,3.207962,84.00,2.516319,32640.0,46.112632,32452.914418,32453.0,...,15.291797,0.004101,RAD_TO_LUNG_2_STD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STD,1
14,32358.5,32549.0,2.966005e+12,3.572525,107.00,2.471893,32681.0,60.046822,32454.024858,32455.0,...,30.800702,0.003649,RAD_TO_LUNG_2_MILD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,MILD,1
15,32366.0,32538.0,2.965737e+12,3.411753,97.00,2.453785,32672.0,53.287359,32452.574929,32453.0,...,18.814937,0.006351,RAD_TO_LUNG_4_MILD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,MILD,1
16,32362.5,32537.0,2.965569e+12,3.441392,103.00,2.356371,32627.0,55.627393,32451.651278,32453.0,...,27.819538,0.003244,RAD_TO_LUNG_4_MILD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,MILD,3
17,32368.0,32537.0,2.965776e+12,3.402234,98.00,2.458638,32668.0,53.128532,32452.787642,32453.0,...,19.534131,0.006569,RAD_TO_LUNG_4_MILD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,MILD,2
18,32322.0,32581.0,2.965601e+12,4.069958,136.00,2.994036,32836.0,80.793392,32451.734020,32452.0,...,82.541577,0.005713,RAD_TO_LUNG_4_FBP_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,FBP,2
19,32314.5,32584.0,2.965488e+12,4.104855,148.00,2.946278,32778.0,83.904487,32451.106179,32450.0,...,130.869565,0.002065,RAD_TO_LUNG_4_FBP_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,FBP,3
20,32322.0,32582.0,2.965639e+12,4.067585,139.00,2.987923,32829.0,81.119213,32451.941406,32452.0,...,89.030935,0.003766,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,FBP,1
21,33383.0,33574.0,1.815747e+12,3.626093,109.25,2.648244,33696.0,61.174624,33478.736420,33478.0,...,34.361752,0.006489,RAD_GE_LUNG_14_ASIR10_1,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,1
22,33402.0,33560.1,1.815878e+12,3.357493,85.25,2.900926,33694.0,49.450450,33479.972840,33479.0,...,23.327200,0.006814,RAD_GE_LUNG_14_ASIR10_2,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,2
23,33354.0,33587.0,3.266594e+12,3.918667,122.00,3.082855,33816.0,73.016089,33469.729081,33469.0,...,70.733063,0.004698,RAD_GE_LUNG_7_ASIR10_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,2
24,33351.0,33591.5,3.266979e+12,3.964370,126.00,3.081932,33852.0,75.363966,33471.691015,33472.0,...,78.380635,0.003203,RAD_GE_LUNG_7_ASIR10_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,3
25,33353.5,33604.0,3.267911e+12,3.979593,131.00,2.882678,33791.0,77.005287,33476.462277,33475.0,...,87.740569,0.003123,RAD_GE_LUNG_7_ASIR10_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,1
26,33446.5,33513.0,3.268445e+12,2.152924,36.00,2.853267,33576.0,20.719956,33479.324760,33479.0,...,1.752233,0.004960,RAD_GE_LUNG_7_ASIR40_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,1
27,33444.0,33507.0,3.267535e+12,2.072655,33.00,3.045378,33569.0,19.641625,33474.666324,33474.0,...,1.341977,0.004798,RAD_GE_LUNG_7_ASIR40_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,2
28,33445.0,33511.0,3.268179e+12,2.136884,33.25,3.233105,33604.0,20.323433,33477.962277,33478.0,...,1.582406,0.005608,RAD_GE_LUNG_7_ASIR40_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,3
29,33398.0,33556.0,3.267807e+12,3.342581,84.00,2.880879,33673.0,48.891165,33476.010288,33475.0,...,24.546079,0.004594,RAD_GE_LUNG_7_ASIR70_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,1
30,33396.0,33549.5,3.267179e+12,3.345373,80.00,3.248624,33737.0,48.478133,33472.793896,33473.0,...,26.230086,0.003658,RAD_GE_LUNG_7_ASIR70_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,3
31,33398.0,33545.0,3.266705e+12,3.252876,76.00,3.152343,33702.0,45.917053,33470.371742,33470.0,...,17.842429,0.008299,RAD_GE_LUNG_7_ASIR70_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,2
32,33362.0,33596.0,3.268279e+12,3.908542,126.25,2.805462,33778.0,72.990619,33478.364540,33478.0,...,64.982371,0.004469,RAD_GE_LUNG_14_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,1
33,33377.0,33579.0,3.267879e+12,3.714695,107.00,3.009939,33760.0,63.224441,33476.341907,33476.0,...,56.256968,0.003428,RAD_GE_LUNG_14_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,2
34,33345.0,33613.0,3.267885e+12,4.082802,139.25,2.884337,33813.0,82.250691,33476.308299,33475.0,...,103.433616,0.002927,RAD_GE_LUNG_7_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,1
35,33342.0,33600.0,3.266917e+12,4.059387,134.25,3.070875,33874.0,80.392715,33471.355281,33472.0,...,96.118165,0.002927,RAD_GE_LUNG_7_FBP_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,3
36,33346.0,33594.0,3.266539e+12,4.008961,130.00,3.078897,33837.0,78.179890,33469.426612,33469.0,...,85.940242,0.004406,RAD_GE_LUNG_7_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,2

In [5]:
#Save the dataframe in a csv file
df_TOGE.to_csv('../../../RadiomiK/Features_Global/rect12_glob.csv', index=False)