In [1]:
import pandas as pd
import pingouin as pg
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import statsmodels.api as sm

In [ ]:
# Loding the TO csv file
df = pd.read_csv("../../RadiomiK/Features_TO/Final/rect0.csv")
#Elimino le colonne diagnostics
string_to_match = 'diagnostics'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
string_to_match = 'Unnamed:'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
df_TO = df
df_TO

,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,...,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,image_ID,Manufacturer,Slice Thickness,Pixel_Spacing,Kernel,Dose,ASIR,Num_Acquisition
0,32073.0,32600.0,2.945270e+12,4.957860,343.00,2.007931,32902.0,174.278064,32339.828835,32340.5,...,302.342795,0.002508,RAD_TO_LUNG_4_STRONG_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STRONG,1
1,32062.0,32601.0,2.944749e+12,4.989626,353.00,2.029146,32959.0,177.717561,32336.942116,32336.0,...,302.393634,0.002757,RAD_TO_LUNG_4_STRONG_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STRONG,2
2,32062.0,32592.5,2.944623e+12,4.964803,354.00,1.973207,32875.0,177.517125,32336.259233,32340.0,...,239.067813,0.005203,RAD_TO_LUNG_4_STRONG_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STRONG,3
3,32102.0,32568.0,2.944755e+12,4.804629,291.00,2.121743,32853.0,151.574896,32337.149503,32340.0,...,226.980238,0.003405,RAD_TO_LUNG_2_STRONG_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STRONG,1
4,32092.0,32561.0,2.944401e+12,4.792798,293.25,2.100375,32878.0,151.569245,32335.203835,32341.0,...,226.558783,0.002847,RAD_TO_LUNG_2_STRONG_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STRONG,3
5,32098.0,32563.5,2.944277e+12,4.819793,288.25,2.231976,32872.0,149.954805,32334.519176,32336.0,...,252.408168,0.002617,RAD_TO_LUNG_2_STRONG_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STRONG,2
6,32046.5,32611.0,2.944638e+12,5.047868,376.25,1.955196,32892.0,189.465702,32336.256037,32340.0,...,384.390702,0.001964,RAD_TO_LUNG_4_STD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STD,3
7,32046.0,32615.0,2.944746e+12,5.068907,376.00,2.007995,32991.0,189.258119,32336.840909,32338.0,...,367.608456,0.002365,RAD_TO_LUNG_4_STD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STD,2
8,32058.0,32617.0,2.945413e+12,5.033386,367.00,1.985071,32937.0,185.349129,32340.538707,32344.0,...,334.363709,0.002482,RAD_TO_LUNG_4_STD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STD,1
9,32067.0,32592.5,2.944197e+12,4.984308,328.00,2.191693,32920.0,170.480902,32333.945312,32334.0,...,334.702319,0.002430,RAD_TO_LUNG_2_STD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STD,2
10,32036.0,32615.0,2.943798e+12,5.111850,344.25,2.206381,32956.0,183.336945,32331.643821,32333.5,...,369.582955,0.003170,RAD_TO_LUNG_2_MILD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,MILD,2
11,32027.0,32610.0,2.943980e+12,5.077409,354.25,2.094325,32937.0,184.485528,32332.649503,32342.0,...,337.419767,0.003466,RAD_TO_LUNG_2_MILD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,MILD,3
12,32059.5,32591.0,2.944450e+12,4.957663,337.25,2.045678,32903.0,172.380169,32335.335227,32342.0,...,291.258996,0.003266,RAD_TO_LUNG_2_STD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STD,3
13,32073.5,32595.0,2.944835e+12,4.963230,336.25,2.056706,32880.0,172.239592,32337.450284,32341.5,...,294.315497,0.003081,RAD_TO_LUNG_2_STD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STD,1
14,32027.0,32610.0,2.943980e+12,5.077409,354.25,2.094325,32937.0,184.485528,32332.649503,32342.0,...,337.419767,0.003466,RAD_TO_LUNG_2_MILD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,MILD,1
15,32019.5,32637.5,2.944758e+12,5.168109,379.00,2.039810,32937.0,198.784443,32336.814986,32344.0,...,384.557064,0.003072,RAD_TO_LUNG_4_MILD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,MILD,1
16,32008.0,32635.0,2.944076e+12,5.171525,393.25,2.009911,32912.0,202.366966,32333.050781,32338.5,...,399.303726,0.002944,RAD_TO_LUNG_4_MILD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,MILD,3
17,32007.0,32639.5,2.944099e+12,5.194434,390.50,2.054042,32996.0,202.224633,32333.168679,32338.5,...,419.245674,0.002812,RAD_TO_LUNG_4_MILD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,MILD,2
18,31957.0,32677.5,2.943214e+12,5.471380,421.25,2.440759,33107.0,231.595525,32327.976207,32341.5,...,944.850877,0.001312,RAD_TO_LUNG_4_FBP_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,2
19,31952.0,32674.5,2.943291e+12,5.461333,418.50,2.402793,33084.0,231.812748,32328.406960,32342.0,...,802.698970,0.001853,RAD_TO_LUNG_4_FBP_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,3
20,31961.0,32680.5,2.943823e+12,5.448234,412.00,2.448626,33110.0,228.588345,32331.353693,32343.0,...,871.228089,0.001408,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1

In [3]:
# Loding the GE csv files and joining them in a single dataframe
df_21 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect0_21.csv")
df_35 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect0_35.csv")
df_40 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect0_40.csv")
df_42 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect0_42.csv")
df_43 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect0_43.csv")

df = pd.concat([df_21, df_35, df_40, df_42, df_43], ignore_index=True)

#Elimino le colonne diagnostics
string_to_match = 'diagnostics'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
string_to_match = 'Unnamed:'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
df_GE = df
df_GE

,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,...,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,image_ID,Manufacturer,Slice Thickness,Pixel_Spacing,Kernel,Dose,ASIR,Num_Acquisition
0,33137.0,33546.2,1.803191e+12,4.696611,201.25,3.331974,33918.0,128.024435,33362.460494,33385.0,...,336.085176,0.002207,RAD_GE_LUNG_14_ASIR10_1,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,1
1,33138.8,33562.0,1.803308e+12,4.722744,213.25,3.214462,33832.0,129.663445,33363.541975,33384.0,...,370.876849,0.002492,RAD_GE_LUNG_14_ASIR10_2,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,2
2,32819.0,33945.0,3.250845e+12,5.729027,672.00,1.916441,34412.0,348.245737,33386.617284,33373.0,...,731.220886,0.022119,RAD_GE_LUNG_7_ASIR10_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,2
3,32838.5,33920.5,3.250426e+12,5.703712,648.00,1.963520,34401.0,334.976161,33384.628601,33386.0,...,706.252922,0.019939,RAD_GE_LUNG_7_ASIR10_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,3
4,32839.0,33891.0,3.248779e+12,5.710284,615.00,2.028828,34330.0,323.739890,33376.278807,33381.5,...,684.152510,0.022467,RAD_GE_LUNG_7_ASIR10_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,1
5,33158.0,33580.5,3.246538e+12,4.650152,254.00,2.246017,33807.0,132.847325,33366.572702,33371.0,...,172.749040,0.004094,RAD_GE_LUNG_7_ASIR40_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,1
6,33151.5,33598.0,3.247778e+12,4.686254,280.00,2.115354,33835.0,141.547440,33372.897805,33376.0,...,201.770773,0.003052,RAD_GE_LUNG_7_ASIR40_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,2
7,33157.0,33589.5,3.247559e+12,4.685334,260.25,2.257388,33855.0,136.858393,33371.794925,33377.0,...,183.439140,0.004506,RAD_GE_LUNG_7_ASIR40_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,3
8,32852.0,33877.5,3.248423e+12,5.692192,604.25,2.034846,34298.0,316.606734,33374.547668,33383.0,...,653.085650,0.020987,RAD_GE_LUNG_7_ASIR70_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,1
9,32852.0,33907.0,3.250096e+12,5.700176,633.25,1.973496,34376.0,328.543814,33383.019890,33386.0,...,671.433137,0.020570,RAD_GE_LUNG_7_ASIR70_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,3
10,32833.0,33934.0,3.250483e+12,5.714113,661.25,1.919417,34394.0,341.602164,33384.847737,33375.5,...,701.304337,0.021422,RAD_GE_LUNG_7_ASIR70_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,2
11,32821.0,33882.0,3.249035e+12,5.654334,630.25,1.968644,34447.0,324.299628,33377.610082,33385.5,...,682.852277,0.023847,RAD_GE_LUNG_14_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,1
12,32819.5,33881.0,3.249303e+12,5.667365,629.25,1.980439,34418.0,324.955977,33378.969822,33388.5,...,689.843245,0.023659,RAD_GE_LUNG_14_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,2
13,32836.0,33895.5,3.248865e+12,5.712516,617.25,2.027903,34339.0,325.582667,33376.698560,33382.0,...,689.508007,0.022974,RAD_GE_LUNG_7_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,1
14,32837.0,33924.0,3.250502e+12,5.705709,651.25,1.961321,34407.0,336.597053,33384.998285,33386.5,...,697.702722,0.019965,RAD_GE_LUNG_7_FBP_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,3
15,32817.5,33950.0,3.250932e+12,5.735223,675.25,1.916113,34419.0,349.968918,33387.039438,33374.0,...,720.553323,0.022663,RAD_GE_LUNG_7_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,2

In [4]:
df_TOGE = pd.concat([df_TO, df_GE], ignore_index=True)
df_TOGE

,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,...,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,image_ID,Manufacturer,Slice Thickness,Pixel_Spacing,Kernel,Dose,ASIR,Num_Acquisition
0,32073.0,32600.0,2.945270e+12,4.957860,343.00,2.007931,32902.0,174.278064,32339.828835,32340.5,...,302.342795,0.002508,RAD_TO_LUNG_4_STRONG_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STRONG,1
1,32062.0,32601.0,2.944749e+12,4.989626,353.00,2.029146,32959.0,177.717561,32336.942116,32336.0,...,302.393634,0.002757,RAD_TO_LUNG_4_STRONG_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STRONG,2
2,32062.0,32592.5,2.944623e+12,4.964803,354.00,1.973207,32875.0,177.517125,32336.259233,32340.0,...,239.067813,0.005203,RAD_TO_LUNG_4_STRONG_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STRONG,3
3,32102.0,32568.0,2.944755e+12,4.804629,291.00,2.121743,32853.0,151.574896,32337.149503,32340.0,...,226.980238,0.003405,RAD_TO_LUNG_2_STRONG_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STRONG,1
4,32092.0,32561.0,2.944401e+12,4.792798,293.25,2.100375,32878.0,151.569245,32335.203835,32341.0,...,226.558783,0.002847,RAD_TO_LUNG_2_STRONG_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STRONG,3
5,32098.0,32563.5,2.944277e+12,4.819793,288.25,2.231976,32872.0,149.954805,32334.519176,32336.0,...,252.408168,0.002617,RAD_TO_LUNG_2_STRONG_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STRONG,2
6,32046.5,32611.0,2.944638e+12,5.047868,376.25,1.955196,32892.0,189.465702,32336.256037,32340.0,...,384.390702,0.001964,RAD_TO_LUNG_4_STD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STD,3
7,32046.0,32615.0,2.944746e+12,5.068907,376.00,2.007995,32991.0,189.258119,32336.840909,32338.0,...,367.608456,0.002365,RAD_TO_LUNG_4_STD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STD,2
8,32058.0,32617.0,2.945413e+12,5.033386,367.00,1.985071,32937.0,185.349129,32340.538707,32344.0,...,334.363709,0.002482,RAD_TO_LUNG_4_STD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STD,1
9,32067.0,32592.5,2.944197e+12,4.984308,328.00,2.191693,32920.0,170.480902,32333.945312,32334.0,...,334.702319,0.002430,RAD_TO_LUNG_2_STD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STD,2
10,32036.0,32615.0,2.943798e+12,5.111850,344.25,2.206381,32956.0,183.336945,32331.643821,32333.5,...,369.582955,0.003170,RAD_TO_LUNG_2_MILD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,MILD,2
11,32027.0,32610.0,2.943980e+12,5.077409,354.25,2.094325,32937.0,184.485528,32332.649503,32342.0,...,337.419767,0.003466,RAD_TO_LUNG_2_MILD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,MILD,3
12,32059.5,32591.0,2.944450e+12,4.957663,337.25,2.045678,32903.0,172.380169,32335.335227,32342.0,...,291.258996,0.003266,RAD_TO_LUNG_2_STD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STD,3
13,32073.5,32595.0,2.944835e+12,4.963230,336.25,2.056706,32880.0,172.239592,32337.450284,32341.5,...,294.315497,0.003081,RAD_TO_LUNG_2_STD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STD,1
14,32027.0,32610.0,2.943980e+12,5.077409,354.25,2.094325,32937.0,184.485528,32332.649503,32342.0,...,337.419767,0.003466,RAD_TO_LUNG_2_MILD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,MILD,1
15,32019.5,32637.5,2.944758e+12,5.168109,379.00,2.039810,32937.0,198.784443,32336.814986,32344.0,...,384.557064,0.003072,RAD_TO_LUNG_4_MILD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,MILD,1
16,32008.0,32635.0,2.944076e+12,5.171525,393.25,2.009911,32912.0,202.366966,32333.050781,32338.5,...,399.303726,0.002944,RAD_TO_LUNG_4_MILD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,MILD,3
17,32007.0,32639.5,2.944099e+12,5.194434,390.50,2.054042,32996.0,202.224633,32333.168679,32338.5,...,419.245674,0.002812,RAD_TO_LUNG_4_MILD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,MILD,2
18,31957.0,32677.5,2.943214e+12,5.471380,421.25,2.440759,33107.0,231.595525,32327.976207,32341.5,...,944.850877,0.001312,RAD_TO_LUNG_4_FBP_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,FBP,2
19,31952.0,32674.5,2.943291e+12,5.461333,418.50,2.402793,33084.0,231.812748,32328.406960,32342.0,...,802.698970,0.001853,RAD_TO_LUNG_4_FBP_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,FBP,3
20,31961.0,32680.5,2.943823e+12,5.448234,412.00,2.448626,33110.0,228.588345,32331.353693,32343.0,...,871.228089,0.001408,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,FBP,1
21,33137.0,33546.2,1.803191e+12,4.696611,201.25,3.331974,33918.0,128.024435,33362.460494,33385.0,...,336.085176,0.002207,RAD_GE_LUNG_14_ASIR10_1,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,1
22,33138.8,33562.0,1.803308e+12,4.722744,213.25,3.214462,33832.0,129.663445,33363.541975,33384.0,...,370.876849,0.002492,RAD_GE_LUNG_14_ASIR10_2,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,2
23,32819.0,33945.0,3.250845e+12,5.729027,672.00,1.916441,34412.0,348.245737,33386.617284,33373.0,...,731.220886,0.022119,RAD_GE_LUNG_7_ASIR10_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,2
24,32838.5,33920.5,3.250426e+12,5.703712,648.00,1.963520,34401.0,334.976161,33384.628601,33386.0,...,706.252922,0.019939,RAD_GE_LUNG_7_ASIR10_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,3
25,32839.0,33891.0,3.248779e+12,5.710284,615.00,2.028828,34330.0,323.739890,33376.278807,33381.5,...,684.152510,0.022467,RAD_GE_LUNG_7_ASIR10_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,1
26,33158.0,33580.5,3.246538e+12,4.650152,254.00,2.246017,33807.0,132.847325,33366.572702,33371.0,...,172.749040,0.004094,RAD_GE_LUNG_7_ASIR40_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,1
27,33151.5,33598.0,3.247778e+12,4.686254,280.00,2.115354,33835.0,141.547440,33372.897805,33376.0,...,201.770773,0.003052,RAD_GE_LUNG_7_ASIR40_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,2
28,33157.0,33589.5,3.247559e+12,4.685334,260.25,2.257388,33855.0,136.858393,33371.794925,33377.0,...,183.439140,0.004506,RAD_GE_LUNG_7_ASIR40_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,3
29,32852.0,33877.5,3.248423e+12,5.692192,604.25,2.034846,34298.0,316.606734,33374.547668,33383.0,...,653.085650,0.020987,RAD_GE_LUNG_7_ASIR70_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,1
30,32852.0,33907.0,3.250096e+12,5.700176,633.25,1.973496,34376.0,328.543814,33383.019890,33386.0,...,671.433137,0.020570,RAD_GE_LUNG_7_ASIR70_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,3
31,32833.0,33934.0,3.250483e+12,5.714113,661.25,1.919417,34394.0,341.602164,33384.847737,33375.5,...,701.304337,0.021422,RAD_GE_LUNG_7_ASIR70_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,2
32,32821.0,33882.0,3.249035e+12,5.654334,630.25,1.968644,34447.0,324.299628,33377.610082,33385.5,...,682.852277,0.023847,RAD_GE_LUNG_14_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,1
33,32819.5,33881.0,3.249303e+12,5.667365,629.25,1.980439,34418.0,324.955977,33378.969822,33388.5,...,689.843245,0.023659,RAD_GE_LUNG_14_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,2
34,32836.0,33895.5,3.248865e+12,5.712516,617.25,2.027903,34339.0,325.582667,33376.698560,33382.0,...,689.508007,0.022974,RAD_GE_LUNG_7_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,1
35,32837.0,33924.0,3.250502e+12,5.705709,651.25,1.961321,34407.0,336.597053,33384.998285,33386.5,...,697.702722,0.019965,RAD_GE_LUNG_7_FBP_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,3
36,32817.5,33950.0,3.250932e+12,5.735223,675.25,1.916113,34419.0,349.968918,33387.039438,33374.0,...,720.553323,0.022663,RAD_GE_LUNG_7_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,2

In [5]:
#Save the dataframe in a csv file
df_TOGE.to_csv('../../../RadiomiK/Features_Global/rect0_glob.csv', index=False)