In [1]:
import pandas as pd
import pingouin as pg
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import statsmodels.api as sm

In [ ]:
# Loding the TO csv file
df = pd.read_csv("../../RadiomiK/Features_TO/Final/rect5.csv")
#Elimino le colonne diagnostics
string_to_match = 'diagnostics'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
string_to_match = 'Unnamed:'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
df_TO = df
df_TO

,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,...,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,image_ID,Manufacturer,Slice Thickness,Pixel_Spacing,Kernel,Dose,ASIR,Num_Acquisition
0,32175.0,32671.0,2.962131e+12,4.823398,320.25,1.957535,32841.0,161.272183,32432.360440,32450.0,...,247.411400,0.002932,RAD_TO_LUNG_4_STRONG_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STRONG,1
1,32170.5,32676.0,2.962073e+12,4.882840,310.25,2.059682,32865.0,161.979934,32432.029830,32442.5,...,257.481755,0.003120,RAD_TO_LUNG_4_STRONG_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STRONG,2
2,32168.5,32678.0,2.962183e+12,4.891372,322.25,2.002768,32919.0,165.224706,32432.613636,32441.0,...,248.136404,0.004288,RAD_TO_LUNG_4_STRONG_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STRONG,3
3,32190.0,32657.0,2.961907e+12,4.792610,274.00,2.182386,32863.0,147.656419,32431.201349,32441.0,...,226.214436,0.003633,RAD_TO_LUNG_2_STRONG_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STRONG,1
4,32197.0,32656.0,2.961853e+12,4.763118,282.00,2.085694,32832.0,148.315062,32430.914418,32441.5,...,179.327687,0.005518,RAD_TO_LUNG_2_STRONG_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STRONG,3
5,32199.0,32649.0,2.961874e+12,4.722125,285.00,2.040311,32828.0,145.346720,32431.045455,32439.5,...,177.501204,0.004846,RAD_TO_LUNG_2_STRONG_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STRONG,2
6,32157.5,32688.0,2.962112e+12,4.942053,340.00,1.979097,32930.0,172.653157,32432.175781,32443.0,...,268.555798,0.003843,RAD_TO_LUNG_4_STD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STD,3
7,32160.0,32685.5,2.962068e+12,4.927179,326.50,2.017843,32884.0,169.397580,32431.950994,32444.0,...,289.337420,0.002928,RAD_TO_LUNG_4_STD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STD,2
8,32164.0,32681.0,2.962121e+12,4.881789,340.00,1.921019,32850.0,169.564872,32432.257457,32449.0,...,229.620771,0.004361,RAD_TO_LUNG_4_STD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STD,1
9,32178.0,32671.5,2.961903e+12,4.862011,320.00,2.015702,32873.0,160.872144,32431.105824,32441.0,...,239.425360,0.004372,RAD_TO_LUNG_2_STD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STD,2
10,32146.0,32693.0,2.961348e+12,4.979275,333.00,2.075570,32882.0,172.294897,32427.978693,32440.0,...,272.728243,0.005040,RAD_TO_LUNG_2_MILD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,MILD,2
11,32140.0,32692.0,2.961133e+12,5.018876,334.00,2.144916,32883.0,176.243799,32426.768111,32442.5,...,328.671294,0.004109,RAD_TO_LUNG_2_MILD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,MILD,3
12,32171.0,32678.0,2.961770e+12,4.894920,316.00,2.047121,32884.0,164.151835,32430.358665,32442.0,...,240.675808,0.004454,RAD_TO_LUNG_2_STD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STD,3
13,32167.0,32677.0,2.961824e+12,4.922394,308.00,2.151679,32915.0,162.600918,32430.651989,32438.5,...,281.022364,0.002988,RAD_TO_LUNG_2_STD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STD,1
14,32140.0,32692.0,2.961133e+12,5.018876,334.00,2.144916,32883.0,176.243799,32426.768111,32442.5,...,328.671294,0.004109,RAD_TO_LUNG_2_MILD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,MILD,1
15,32128.0,32696.0,2.961389e+12,5.003491,356.25,2.021719,32851.0,180.923960,32428.148793,32450.0,...,287.354595,0.004471,RAD_TO_LUNG_4_MILD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,MILD,1
16,32128.0,32703.5,2.961358e+12,5.066558,356.00,2.078157,32941.0,184.634561,32427.946733,32445.0,...,321.987010,0.004034,RAD_TO_LUNG_4_MILD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,MILD,3
17,32132.5,32701.5,2.961495e+12,5.043793,343.50,2.138566,32892.0,180.627609,32428.717685,32444.0,...,325.763408,0.004163,RAD_TO_LUNG_4_MILD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,MILD,2
18,32096.0,32729.0,2.960722e+12,5.275357,357.00,2.602358,32957.0,201.584570,32424.265270,32447.5,...,642.290165,0.002558,RAD_TO_LUNG_4_FBP_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,2
19,32078.0,32733.0,2.960252e+12,5.307902,372.00,2.538719,33002.0,206.068599,32421.655895,32446.0,...,857.037224,0.001144,RAD_TO_LUNG_4_FBP_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,3
20,32087.5,32721.0,2.960422e+12,5.262100,372.00,2.462812,32975.0,201.862899,32422.637784,32446.0,...,617.015600,0.002478,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1

In [3]:
# Loding the GE csv files and joining them in a single dataframe
df_21 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect5_21.csv")
df_35 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect5_35.csv")
df_40 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect5_40.csv")
df_42 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect5_42.csv")
df_43 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect5_43.csv")

df = pd.concat([df_21, df_35, df_40, df_42, df_43], ignore_index=True)

#Elimino le colonne diagnostics
string_to_match = 'diagnostics'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
string_to_match = 'Unnamed:'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
df_GE = df
df_GE

,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,...,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,image_ID,Manufacturer,Slice Thickness,Pixel_Spacing,Kernel,Dose,ASIR,Num_Acquisition
0,33262.9,33620.0,1.812407e+12,4.506625,203.00,3.134678,33838.0,115.922029,33447.710494,33462.5,...,229.075875,0.003909,RAD_GE_LUNG_14_ASIR10_1,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,1
1,33317.9,33577.0,1.812421e+12,4.100303,132.00,3.588971,33831.0,82.120027,33447.977778,33449.0,...,97.958991,0.004002,RAD_GE_LUNG_14_ASIR10_2,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,2
2,32944.0,33959.0,3.264914e+12,5.788341,617.00,2.020899,34390.0,322.673139,33459.104252,33466.0,...,804.176881,0.029226,RAD_GE_LUNG_7_ASIR10_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,2
3,32990.5,33896.5,3.263338e+12,5.663175,559.00,2.047117,34239.0,293.945168,33451.405350,33463.0,...,732.048397,0.028836,RAD_GE_LUNG_7_ASIR10_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,3
4,32999.0,33876.5,3.262471e+12,5.653819,528.25,2.097797,34208.0,283.168815,33447.069959,33464.0,...,707.140420,0.026091,RAD_GE_LUNG_7_ASIR10_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,1
5,33249.5,33613.0,3.260724e+12,4.386724,236.00,2.233250,33714.0,120.698554,33439.471536,33452.0,...,157.859236,0.002992,RAD_GE_LUNG_7_ASIR40_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,1
6,33231.0,33627.0,3.261877e+12,4.517308,267.00,2.269794,33770.0,132.971072,33445.319959,33460.0,...,234.680915,0.002044,RAD_GE_LUNG_7_ASIR40_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,2
7,33251.5,33616.0,3.261496e+12,4.386120,244.00,2.245238,33736.0,123.890089,33443.416667,33453.0,...,148.683998,0.004963,RAD_GE_LUNG_7_ASIR40_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,3
8,33001.5,33875.0,3.262411e+12,5.639114,525.25,2.093754,34193.0,280.896536,33446.792867,33463.0,...,700.114582,0.025331,RAD_GE_LUNG_7_ASIR70_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,1
9,32993.5,33892.0,3.263274e+12,5.644236,555.25,2.050187,34234.0,291.619902,33451.107339,33462.0,...,713.668531,0.028805,RAD_GE_LUNG_7_ASIR70_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,3
10,32948.5,33954.5,3.264842e+12,5.778020,608.75,2.021369,34368.0,320.395078,33458.765089,33463.0,...,793.852453,0.029302,RAD_GE_LUNG_7_ASIR70_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,2
11,32952.5,33907.0,3.262755e+12,5.703839,595.00,1.973238,34278.0,312.799357,33448.242112,33463.0,...,755.077380,0.032063,RAD_GE_LUNG_14_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,1
12,33011.5,33865.0,3.262210e+12,5.596834,554.00,1.997208,34228.0,290.515975,33445.723594,33460.5,...,707.831381,0.028817,RAD_GE_LUNG_14_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,2
13,32997.0,33878.0,3.262453e+12,5.655801,533.00,2.099049,34211.0,283.757659,33446.972222,33464.0,...,709.727814,0.025996,RAD_GE_LUNG_7_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,1
14,32987.0,33896.0,3.263332e+12,5.664923,559.50,2.046519,34240.0,294.521902,33451.367970,33461.0,...,733.257536,0.028924,RAD_GE_LUNG_7_FBP_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,3
15,32942.0,33959.0,3.264911e+12,5.787562,619.25,2.020795,34396.0,323.250252,33459.080933,33465.5,...,809.499688,0.028457,RAD_GE_LUNG_7_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,2

In [4]:
df_TOGE = pd.concat([df_TO, df_GE], ignore_index=True)
df_TOGE

,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,...,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,image_ID,Manufacturer,Slice Thickness,Pixel_Spacing,Kernel,Dose,ASIR,Num_Acquisition
0,32175.0,32671.0,2.962131e+12,4.823398,320.25,1.957535,32841.0,161.272183,32432.360440,32450.0,...,247.411400,0.002932,RAD_TO_LUNG_4_STRONG_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STRONG,1
1,32170.5,32676.0,2.962073e+12,4.882840,310.25,2.059682,32865.0,161.979934,32432.029830,32442.5,...,257.481755,0.003120,RAD_TO_LUNG_4_STRONG_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STRONG,2
2,32168.5,32678.0,2.962183e+12,4.891372,322.25,2.002768,32919.0,165.224706,32432.613636,32441.0,...,248.136404,0.004288,RAD_TO_LUNG_4_STRONG_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STRONG,3
3,32190.0,32657.0,2.961907e+12,4.792610,274.00,2.182386,32863.0,147.656419,32431.201349,32441.0,...,226.214436,0.003633,RAD_TO_LUNG_2_STRONG_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STRONG,1
4,32197.0,32656.0,2.961853e+12,4.763118,282.00,2.085694,32832.0,148.315062,32430.914418,32441.5,...,179.327687,0.005518,RAD_TO_LUNG_2_STRONG_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STRONG,3
5,32199.0,32649.0,2.961874e+12,4.722125,285.00,2.040311,32828.0,145.346720,32431.045455,32439.5,...,177.501204,0.004846,RAD_TO_LUNG_2_STRONG_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STRONG,2
6,32157.5,32688.0,2.962112e+12,4.942053,340.00,1.979097,32930.0,172.653157,32432.175781,32443.0,...,268.555798,0.003843,RAD_TO_LUNG_4_STD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STD,3
7,32160.0,32685.5,2.962068e+12,4.927179,326.50,2.017843,32884.0,169.397580,32431.950994,32444.0,...,289.337420,0.002928,RAD_TO_LUNG_4_STD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STD,2
8,32164.0,32681.0,2.962121e+12,4.881789,340.00,1.921019,32850.0,169.564872,32432.257457,32449.0,...,229.620771,0.004361,RAD_TO_LUNG_4_STD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STD,1
9,32178.0,32671.5,2.961903e+12,4.862011,320.00,2.015702,32873.0,160.872144,32431.105824,32441.0,...,239.425360,0.004372,RAD_TO_LUNG_2_STD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STD,2
10,32146.0,32693.0,2.961348e+12,4.979275,333.00,2.075570,32882.0,172.294897,32427.978693,32440.0,...,272.728243,0.005040,RAD_TO_LUNG_2_MILD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,MILD,2
11,32140.0,32692.0,2.961133e+12,5.018876,334.00,2.144916,32883.0,176.243799,32426.768111,32442.5,...,328.671294,0.004109,RAD_TO_LUNG_2_MILD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,MILD,3
12,32171.0,32678.0,2.961770e+12,4.894920,316.00,2.047121,32884.0,164.151835,32430.358665,32442.0,...,240.675808,0.004454,RAD_TO_LUNG_2_STD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STD,3
13,32167.0,32677.0,2.961824e+12,4.922394,308.00,2.151679,32915.0,162.600918,32430.651989,32438.5,...,281.022364,0.002988,RAD_TO_LUNG_2_STD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STD,1
14,32140.0,32692.0,2.961133e+12,5.018876,334.00,2.144916,32883.0,176.243799,32426.768111,32442.5,...,328.671294,0.004109,RAD_TO_LUNG_2_MILD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,MILD,1
15,32128.0,32696.0,2.961389e+12,5.003491,356.25,2.021719,32851.0,180.923960,32428.148793,32450.0,...,287.354595,0.004471,RAD_TO_LUNG_4_MILD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,MILD,1
16,32128.0,32703.5,2.961358e+12,5.066558,356.00,2.078157,32941.0,184.634561,32427.946733,32445.0,...,321.987010,0.004034,RAD_TO_LUNG_4_MILD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,MILD,3
17,32132.5,32701.5,2.961495e+12,5.043793,343.50,2.138566,32892.0,180.627609,32428.717685,32444.0,...,325.763408,0.004163,RAD_TO_LUNG_4_MILD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,MILD,2
18,32096.0,32729.0,2.960722e+12,5.275357,357.00,2.602358,32957.0,201.584570,32424.265270,32447.5,...,642.290165,0.002558,RAD_TO_LUNG_4_FBP_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,FBP,2
19,32078.0,32733.0,2.960252e+12,5.307902,372.00,2.538719,33002.0,206.068599,32421.655895,32446.0,...,857.037224,0.001144,RAD_TO_LUNG_4_FBP_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,FBP,3
20,32087.5,32721.0,2.960422e+12,5.262100,372.00,2.462812,32975.0,201.862899,32422.637784,32446.0,...,617.015600,0.002478,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,FBP,1
21,33262.9,33620.0,1.812407e+12,4.506625,203.00,3.134678,33838.0,115.922029,33447.710494,33462.5,...,229.075875,0.003909,RAD_GE_LUNG_14_ASIR10_1,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,1
22,33317.9,33577.0,1.812421e+12,4.100303,132.00,3.588971,33831.0,82.120027,33447.977778,33449.0,...,97.958991,0.004002,RAD_GE_LUNG_14_ASIR10_2,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,2
23,32944.0,33959.0,3.264914e+12,5.788341,617.00,2.020899,34390.0,322.673139,33459.104252,33466.0,...,804.176881,0.029226,RAD_GE_LUNG_7_ASIR10_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,2
24,32990.5,33896.5,3.263338e+12,5.663175,559.00,2.047117,34239.0,293.945168,33451.405350,33463.0,...,732.048397,0.028836,RAD_GE_LUNG_7_ASIR10_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,3
25,32999.0,33876.5,3.262471e+12,5.653819,528.25,2.097797,34208.0,283.168815,33447.069959,33464.0,...,707.140420,0.026091,RAD_GE_LUNG_7_ASIR10_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,1
26,33249.5,33613.0,3.260724e+12,4.386724,236.00,2.233250,33714.0,120.698554,33439.471536,33452.0,...,157.859236,0.002992,RAD_GE_LUNG_7_ASIR40_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,1
27,33231.0,33627.0,3.261877e+12,4.517308,267.00,2.269794,33770.0,132.971072,33445.319959,33460.0,...,234.680915,0.002044,RAD_GE_LUNG_7_ASIR40_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,2
28,33251.5,33616.0,3.261496e+12,4.386120,244.00,2.245238,33736.0,123.890089,33443.416667,33453.0,...,148.683998,0.004963,RAD_GE_LUNG_7_ASIR40_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,3
29,33001.5,33875.0,3.262411e+12,5.639114,525.25,2.093754,34193.0,280.896536,33446.792867,33463.0,...,700.114582,0.025331,RAD_GE_LUNG_7_ASIR70_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,1
30,32993.5,33892.0,3.263274e+12,5.644236,555.25,2.050187,34234.0,291.619902,33451.107339,33462.0,...,713.668531,0.028805,RAD_GE_LUNG_7_ASIR70_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,3
31,32948.5,33954.5,3.264842e+12,5.778020,608.75,2.021369,34368.0,320.395078,33458.765089,33463.0,...,793.852453,0.029302,RAD_GE_LUNG_7_ASIR70_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,2
32,32952.5,33907.0,3.262755e+12,5.703839,595.00,1.973238,34278.0,312.799357,33448.242112,33463.0,...,755.077380,0.032063,RAD_GE_LUNG_14_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,1
33,33011.5,33865.0,3.262210e+12,5.596834,554.00,1.997208,34228.0,290.515975,33445.723594,33460.5,...,707.831381,0.028817,RAD_GE_LUNG_14_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,2
34,32997.0,33878.0,3.262453e+12,5.655801,533.00,2.099049,34211.0,283.757659,33446.972222,33464.0,...,709.727814,0.025996,RAD_GE_LUNG_7_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,1
35,32987.0,33896.0,3.263332e+12,5.664923,559.50,2.046519,34240.0,294.521902,33451.367970,33461.0,...,733.257536,0.028924,RAD_GE_LUNG_7_FBP_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,3
36,32942.0,33959.0,3.264911e+12,5.787562,619.25,2.020795,34396.0,323.250252,33459.080933,33465.5,...,809.499688,0.028457,RAD_GE_LUNG_7_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,2

In [5]:
#Save the dataframe in a csv file
df_TOGE.to_csv('../../../RadiomiK/Features_Global/rect5_glob.csv', index=False)