In [1]:
import pandas as pd
import pingouin as pg
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import statsmodels.api as sm

In [ ]:
# Loding the TO csv file
df = pd.read_csv("../../RadiomiK/Features_TO/Final/rect2.csv")
#Elimino le colonne diagnostics
string_to_match = 'diagnostics'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
string_to_match = 'Unnamed:'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
df_TO = df
df_TO

,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,...,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,image_ID,Manufacturer,Slice Thickness,Pixel_Spacing,Kernel,Dose,ASIR,Num_Acquisition
0,32130.0,32607.0,2.950477e+12,4.717976,317.00,1.786866,32778.0,157.969440,32368.536222,32365.5,...,150.441523,0.005116,RAD_TO_LUNG_4_STRONG_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STRONG,1
1,32132.0,32599.0,2.950118e+12,4.697764,318.00,1.796311,32751.0,155.298390,32366.585938,32360.0,...,164.570123,0.003725,RAD_TO_LUNG_4_STRONG_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STRONG,2
2,32128.5,32598.0,2.950168e+12,4.700269,313.00,1.817708,32758.0,154.402415,32366.860085,32363.0,...,140.306060,0.008117,RAD_TO_LUNG_4_STRONG_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STRONG,3
3,32171.0,32561.0,2.950188e+12,4.451539,267.00,1.793507,32695.0,130.516150,32367.108665,32363.0,...,109.617272,0.003878,RAD_TO_LUNG_2_STRONG_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STRONG,1
4,32182.5,32558.5,2.950488e+12,4.433792,248.25,1.908074,32712.0,124.654319,32368.779119,32360.0,...,99.860956,0.005002,RAD_TO_LUNG_2_STRONG_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STRONG,3
5,32180.0,32555.0,2.949974e+12,4.407714,252.25,1.828230,32689.0,125.244500,32365.959872,32360.0,...,89.416082,0.006705,RAD_TO_LUNG_2_STRONG_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STRONG,2
6,32094.0,32638.0,2.950467e+12,4.920917,359.25,1.827239,32826.0,179.001906,32368.334517,32364.0,...,219.782217,0.005374,RAD_TO_LUNG_4_STD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STD,3
7,32091.0,32638.0,2.950361e+12,4.907856,368.00,1.801308,32810.0,180.469955,32367.747869,32362.5,...,211.871203,0.005240,RAD_TO_LUNG_4_STD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STD,2
8,32091.5,32643.5,2.950742e+12,4.941889,368.00,1.804406,32847.0,183.392242,32369.816406,32363.5,...,214.461255,0.005731,RAD_TO_LUNG_4_STD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,STD,1
9,32138.5,32596.0,2.949978e+12,4.677299,307.00,1.822973,32756.0,150.927984,32365.841974,32359.0,...,150.205890,0.005015,RAD_TO_LUNG_2_STD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STD,2
10,32114.0,32672.0,2.951871e+12,4.917078,362.25,1.849206,32864.0,179.922888,32376.010298,32355.0,...,196.304671,0.007926,RAD_TO_LUNG_2_MILD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,MILD,2
11,32109.0,32675.5,2.952209e+12,4.960834,359.25,1.906021,32893.0,181.016615,32377.853693,32355.0,...,257.043985,0.003191,RAD_TO_LUNG_2_MILD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,MILD,3
12,32142.5,32597.0,2.950493e+12,4.699718,301.25,1.885742,32785.0,150.874575,32368.660511,32359.0,...,192.243747,0.003182,RAD_TO_LUNG_2_STD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STD,3
13,32129.0,32600.0,2.950163e+12,4.706257,319.25,1.780655,32746.0,157.081768,32366.819602,32359.0,...,149.166175,0.005357,RAD_TO_LUNG_2_STD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,STD,1
14,32109.0,32675.5,2.952209e+12,4.960834,359.25,1.906021,32893.0,181.016615,32377.853693,32355.0,...,257.043985,0.003191,RAD_TO_LUNG_2_MILD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,2,MILD,1
15,32052.0,32735.0,2.952534e+12,5.166106,445.75,1.812752,33002.0,219.215147,32379.334872,32360.5,...,288.928272,0.005837,RAD_TO_LUNG_4_MILD_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,MILD,1
16,32052.0,32733.0,2.952230e+12,5.174476,427.25,1.863510,32965.0,215.593135,32377.684659,32361.5,...,277.325777,0.009997,RAD_TO_LUNG_4_MILD_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,MILD,3
17,32052.5,32732.0,2.952272e+12,5.159369,432.00,1.826419,32919.0,216.699971,32377.915128,32358.0,...,298.553942,0.006066,RAD_TO_LUNG_4_MILD_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,MILD,2
18,31972.5,32903.0,2.954595e+12,5.760330,478.00,2.544540,33343.0,282.299326,32389.757102,32351.0,...,980.466112,0.001817,RAD_TO_LUNG_4_FBP_2,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,2
19,31965.5,32905.5,2.954383e+12,5.774497,477.00,2.568683,33363.0,281.658161,32388.579901,32360.5,...,1039.000857,0.001614,RAD_TO_LUNG_4_FBP_3,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,3
20,31962.0,32899.0,2.954776e+12,5.765376,504.00,2.476692,33416.0,285.145305,32390.738281,32354.0,...,976.242056,0.001567,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1

In [3]:
# Loding the GE csv files and joining them in a single dataframe
df_21 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect2_21.csv")
df_35 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect2_35.csv")
df_40 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect2_40.csv")
df_42 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect2_42.csv")
df_43 = pd.read_csv("../../../RadiomiK/Features_GE/Final/rect2_43.csv")

df = pd.concat([df_21, df_35, df_40, df_42, df_43], ignore_index=True)

#Elimino le colonne diagnostics
string_to_match = 'diagnostics'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
string_to_match = 'Unnamed:'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
df_GE = df
df_GE

,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,...,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,image_ID,Manufacturer,Slice Thickness,Pixel_Spacing,Kernel,Dose,ASIR,Num_Acquisition
0,32770.9,34176.1,1.810609e+12,5.898315,810.25,2.156550,34687.0,423.620624,33427.658642,33337.0,...,892.678483,0.026109,RAD_GE_LUNG_14_ASIR10_1,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,1
1,32768.0,34188.0,1.810923e+12,5.879978,779.50,2.124586,34601.0,425.602561,33430.515432,33340.0,...,882.668160,0.026201,RAD_GE_LUNG_14_ASIR10_2,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,2
2,32768.0,34195.0,3.260501e+12,5.922232,799.50,2.115394,34720.0,427.311911,33434.828532,33370.0,...,940.180373,0.025183,RAD_GE_LUNG_7_ASIR10_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,2
3,32768.0,34218.5,3.261303e+12,5.925736,808.25,2.158496,34673.0,431.134911,33438.829218,33358.0,...,970.971018,0.023629,RAD_GE_LUNG_7_ASIR10_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,3
4,32769.5,34210.0,3.260109e+12,5.950566,822.25,2.189473,34788.0,435.226118,33432.653292,33334.5,...,974.000788,0.024526,RAD_GE_LUNG_7_ASIR10_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,1
5,33254.0,33616.0,3.256525e+12,4.404422,209.00,2.362672,33785.0,114.979590,33417.946502,33399.0,...,87.128292,0.004916,RAD_GE_LUNG_7_ASIR40_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,1
6,33255.5,33611.0,3.256792e+12,4.398131,200.00,2.369084,33798.0,112.411168,33419.326475,33405.0,...,86.745382,0.004810,RAD_GE_LUNG_7_ASIR40_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,2
7,33259.0,33619.0,3.257538e+12,4.388682,205.00,2.355869,33798.0,113.622969,33423.148491,33407.0,...,83.398554,0.004463,RAD_GE_LUNG_7_ASIR40_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,3
8,32783.0,34197.0,3.259792e+12,5.955937,794.75,2.198669,34772.0,428.708903,33431.135460,33334.0,...,945.422726,0.024379,RAD_GE_LUNG_7_ASIR70_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,1
9,32768.0,34206.0,3.260991e+12,5.923548,796.50,2.164264,34646.0,425.229008,33437.321674,33358.0,...,952.957865,0.023522,RAD_GE_LUNG_7_ASIR70_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,3
10,32775.5,34181.0,3.260163e+12,5.931014,785.00,2.123368,34679.0,421.051620,33433.195473,33366.5,...,940.189645,0.026033,RAD_GE_LUNG_7_ASIR70_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,2
11,32779.5,34191.0,3.259888e+12,5.946288,811.50,2.160108,34743.0,427.278606,33431.651578,33345.0,...,914.447954,0.024876,RAD_GE_LUNG_14_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,1
12,32768.0,34196.5,3.260181e+12,5.893193,802.25,2.131603,34723.0,429.659387,33433.104595,33347.0,...,893.574714,0.022440,RAD_GE_LUNG_14_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,2
13,32768.0,34214.5,3.260185e+12,5.948471,826.50,2.187365,34792.0,436.850565,33433.013032,33335.0,...,987.672141,0.025599,RAD_GE_LUNG_7_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,1
14,32768.0,34220.0,3.261376e+12,5.926591,811.25,2.157216,34679.0,432.597541,33439.175583,33357.0,...,971.853801,0.024588,RAD_GE_LUNG_7_FBP_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,3
15,32768.0,34197.5,3.260582e+12,5.919165,802.00,2.113571,34730.0,428.855693,33435.221193,33372.0,...,936.929614,0.025037,RAD_GE_LUNG_7_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,2

In [4]:
df_TOGE = pd.concat([df_TO, df_GE], ignore_index=True)
df_TOGE

,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,...,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,image_ID,Manufacturer,Slice Thickness,Pixel_Spacing,Kernel,Dose,ASIR,Num_Acquisition
0,32130.0,32607.0,2.950477e+12,4.717976,317.00,1.786866,32778.0,157.969440,32368.536222,32365.5,...,150.441523,0.005116,RAD_TO_LUNG_4_STRONG_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STRONG,1
1,32132.0,32599.0,2.950118e+12,4.697764,318.00,1.796311,32751.0,155.298390,32366.585938,32360.0,...,164.570123,0.003725,RAD_TO_LUNG_4_STRONG_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STRONG,2
2,32128.5,32598.0,2.950168e+12,4.700269,313.00,1.817708,32758.0,154.402415,32366.860085,32363.0,...,140.306060,0.008117,RAD_TO_LUNG_4_STRONG_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STRONG,3
3,32171.0,32561.0,2.950188e+12,4.451539,267.00,1.793507,32695.0,130.516150,32367.108665,32363.0,...,109.617272,0.003878,RAD_TO_LUNG_2_STRONG_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STRONG,1
4,32182.5,32558.5,2.950488e+12,4.433792,248.25,1.908074,32712.0,124.654319,32368.779119,32360.0,...,99.860956,0.005002,RAD_TO_LUNG_2_STRONG_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STRONG,3
5,32180.0,32555.0,2.949974e+12,4.407714,252.25,1.828230,32689.0,125.244500,32365.959872,32360.0,...,89.416082,0.006705,RAD_TO_LUNG_2_STRONG_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STRONG,2
6,32094.0,32638.0,2.950467e+12,4.920917,359.25,1.827239,32826.0,179.001906,32368.334517,32364.0,...,219.782217,0.005374,RAD_TO_LUNG_4_STD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STD,3
7,32091.0,32638.0,2.950361e+12,4.907856,368.00,1.801308,32810.0,180.469955,32367.747869,32362.5,...,211.871203,0.005240,RAD_TO_LUNG_4_STD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STD,2
8,32091.5,32643.5,2.950742e+12,4.941889,368.00,1.804406,32847.0,183.392242,32369.816406,32363.5,...,214.461255,0.005731,RAD_TO_LUNG_4_STD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,STD,1
9,32138.5,32596.0,2.949978e+12,4.677299,307.00,1.822973,32756.0,150.927984,32365.841974,32359.0,...,150.205890,0.005015,RAD_TO_LUNG_2_STD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STD,2
10,32114.0,32672.0,2.951871e+12,4.917078,362.25,1.849206,32864.0,179.922888,32376.010298,32355.0,...,196.304671,0.007926,RAD_TO_LUNG_2_MILD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,MILD,2
11,32109.0,32675.5,2.952209e+12,4.960834,359.25,1.906021,32893.0,181.016615,32377.853693,32355.0,...,257.043985,0.003191,RAD_TO_LUNG_2_MILD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,MILD,3
12,32142.5,32597.0,2.950493e+12,4.699718,301.25,1.885742,32785.0,150.874575,32368.660511,32359.0,...,192.243747,0.003182,RAD_TO_LUNG_2_STD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STD,3
13,32129.0,32600.0,2.950163e+12,4.706257,319.25,1.780655,32746.0,157.081768,32366.819602,32359.0,...,149.166175,0.005357,RAD_TO_LUNG_2_STD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,STD,1
14,32109.0,32675.5,2.952209e+12,4.960834,359.25,1.906021,32893.0,181.016615,32377.853693,32355.0,...,257.043985,0.003191,RAD_TO_LUNG_2_MILD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,2,MILD,1
15,32052.0,32735.0,2.952534e+12,5.166106,445.75,1.812752,33002.0,219.215147,32379.334872,32360.5,...,288.928272,0.005837,RAD_TO_LUNG_4_MILD_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,MILD,1
16,32052.0,32733.0,2.952230e+12,5.174476,427.25,1.863510,32965.0,215.593135,32377.684659,32361.5,...,277.325777,0.009997,RAD_TO_LUNG_4_MILD_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,MILD,3
17,32052.5,32732.0,2.952272e+12,5.159369,432.00,1.826419,32919.0,216.699971,32377.915128,32358.0,...,298.553942,0.006066,RAD_TO_LUNG_4_MILD_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,MILD,2
18,31972.5,32903.0,2.954595e+12,5.760330,478.00,2.544540,33343.0,282.299326,32389.757102,32351.0,...,980.466112,0.001817,RAD_TO_LUNG_4_FBP_2,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,FBP,2
19,31965.5,32905.5,2.954383e+12,5.774497,477.00,2.568683,33363.0,281.658161,32388.579901,32360.5,...,1039.000857,0.001614,RAD_TO_LUNG_4_FBP_3,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,FBP,3
20,31962.0,32899.0,2.954776e+12,5.765376,504.00,2.476692,33416.0,285.145305,32390.738281,32354.0,...,976.242056,0.001567,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1.00,"[0.781, 0.781]",LUNG,4,FBP,1
21,32770.9,34176.1,1.810609e+12,5.898315,810.25,2.156550,34687.0,423.620624,33427.658642,33337.0,...,892.678483,0.026109,RAD_GE_LUNG_14_ASIR10_1,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,1
22,32768.0,34188.0,1.810923e+12,5.879978,779.50,2.124586,34601.0,425.602561,33430.515432,33340.0,...,882.668160,0.026201,RAD_GE_LUNG_14_ASIR10_2,GE MEDICAL SYSTEMS,2.50,"[0.703125, 0.703125]",LUNG,14,ASIR10,2
23,32768.0,34195.0,3.260501e+12,5.922232,799.50,2.115394,34720.0,427.311911,33434.828532,33370.0,...,940.180373,0.025183,RAD_GE_LUNG_7_ASIR10_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,2
24,32768.0,34218.5,3.261303e+12,5.925736,808.25,2.158496,34673.0,431.134911,33438.829218,33358.0,...,970.971018,0.023629,RAD_GE_LUNG_7_ASIR10_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,3
25,32769.5,34210.0,3.260109e+12,5.950566,822.25,2.189473,34788.0,435.226118,33432.653292,33334.5,...,974.000788,0.024526,RAD_GE_LUNG_7_ASIR10_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR10,1
26,33254.0,33616.0,3.256525e+12,4.404422,209.00,2.362672,33785.0,114.979590,33417.946502,33399.0,...,87.128292,0.004916,RAD_GE_LUNG_7_ASIR40_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,1
27,33255.5,33611.0,3.256792e+12,4.398131,200.00,2.369084,33798.0,112.411168,33419.326475,33405.0,...,86.745382,0.004810,RAD_GE_LUNG_7_ASIR40_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,2
28,33259.0,33619.0,3.257538e+12,4.388682,205.00,2.355869,33798.0,113.622969,33423.148491,33407.0,...,83.398554,0.004463,RAD_GE_LUNG_7_ASIR40_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR40,3
29,32783.0,34197.0,3.259792e+12,5.955937,794.75,2.198669,34772.0,428.708903,33431.135460,33334.0,...,945.422726,0.024379,RAD_GE_LUNG_7_ASIR70_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,1
30,32768.0,34206.0,3.260991e+12,5.923548,796.50,2.164264,34646.0,425.229008,33437.321674,33358.0,...,952.957865,0.023522,RAD_GE_LUNG_7_ASIR70_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,3
31,32775.5,34181.0,3.260163e+12,5.931014,785.00,2.123368,34679.0,421.051620,33433.195473,33366.5,...,940.189645,0.026033,RAD_GE_LUNG_7_ASIR70_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,ASIR70,2
32,32779.5,34191.0,3.259888e+12,5.946288,811.50,2.160108,34743.0,427.278606,33431.651578,33345.0,...,914.447954,0.024876,RAD_GE_LUNG_14_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,1
33,32768.0,34196.5,3.260181e+12,5.893193,802.25,2.131603,34723.0,429.659387,33433.104595,33347.0,...,893.574714,0.022440,RAD_GE_LUNG_14_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,14,FBP,2
34,32768.0,34214.5,3.260185e+12,5.948471,826.50,2.187365,34792.0,436.850565,33433.013032,33335.0,...,987.672141,0.025599,RAD_GE_LUNG_7_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,1
35,32768.0,34220.0,3.261376e+12,5.926591,811.25,2.157216,34679.0,432.597541,33439.175583,33357.0,...,971.853801,0.024588,RAD_GE_LUNG_7_FBP_3,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,3
36,32768.0,34197.5,3.260582e+12,5.919165,802.00,2.113571,34730.0,428.855693,33435.221193,33372.0,...,936.929614,0.025037,RAD_GE_LUNG_7_FBP_2,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,2

In [5]:
#Save the dataframe in a csv file
df_TOGE.to_csv('../../../RadiomiK/Features_Global/rect2_glob.csv', index=False)