In [2]:
#Load csv files into a pandas dataframe

import pandas as pd
import pingouin as pg
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import statsmodels.api as sm

/Users/mariairenetenerani/anaconda3/envs/Apple_tensorflow_env/lib/python3.10/site-packages/outdated/utils.py:14: OutdatedPackageWarning: The package pingouin is out of date. Your version is 0.5.3, the latest is 0.5.4.
Set the environment variable OUTDATED_IGNORE=1 to disable these warnings.
  return warn(

In [ ]:
#Create daframe for the insert Cyl0
#Read in the csv files
#Load test-retest csv file into dataframe
df_cyl0_tr = pd.read_csv('../../../RadiomiK/Filtered_features/Test_ReTest/Final/Cyl0_testRetest.csv')

#Add a new column 'Test' to the dataframe in witch the value is 'Test-Retest' for all rows
df_cyl0_tr['Test'] = 'Test-Retest'

#Add a new column 'CT' to the dataframe in witch the value is 'TO-GE' for all rows
df_cyl0_tr['Manufacturer'] = 'TO-GE'

#delete the column 'count' from the dataframe
df_cyl0_tr = df_cyl0_tr.drop(['count'], axis=1)

#load the positioning csv file into a dataframe
df_cyl0_pos = pd.read_csv('../../../../RadiomiK/Features_Positioning_test/Features_Not_Repeatable/cv_Cyl0.csv')

#Add a new column 'Test' to the dataframe in witch the value is 'Positioning' for all rows
df_cyl0_pos['Test'] = 'Positioning'

#delete the column 'cv' from the dataframe
df_cyl0_pos = df_cyl0_pos.drop(['CV'], axis=1)

#Load the volume csv file into a dataframe
df_cyl0_vol = pd.read_csv('../../../../RadiomiK/Features_Volume_test/Features_Not_Repeatable/cv_Cyl0.csv')

#Add a new column 'Test' to the dataframe in witch the value is 'Volume' for all rows
df_cyl0_vol['Test'] = 'Volume'

#delete the column 'cv' from the dataframe
df_cyl0_vol = df_cyl0_vol.drop(['CV'], axis=1)

#Concatenate the three dataframes into one
df_cyl0 = pd.concat([df_cyl0_tr, df_cyl0_pos, df_cyl0_vol], ignore_index=True)

#Save the concatenated dataframe as csv file
df_cyl0.to_csv('../../../../RadiomiK/Features_not_repeatable_global/Cyl0_all_test.csv', index=False)

df_cyl0

,Feature,Test,Manufacturer
0,original_gldm_SmallDependenceLowGrayLevelEmphasis,Test-Retest,TO-GE
1,original_glcm_Idmn,Test-Retest,TO-GE
2,original_glszm_SizeZoneNonUniformityNormalized,Test-Retest,TO-GE
3,original_gldm_LargeDependenceHighGrayLevelEmph...,Test-Retest,TO-GE
4,original_glcm_Idn,Test-Retest,TO-GE
...,...,...,...
85,original_gldm_LargeDependenceHighGrayLevelEmph...,Volume,GE
86,original_gldm_LargeDependenceLowGrayLevelEmphasis,Volume,GE
87,original_gldm_LowGrayLevelEmphasis,Volume,GE
88,original_gldm_SmallDependenceHighGrayLevelEmph...,Volume,GE
89,original_gldm_SmallDependenceLowGrayLevelEmphasis,Volume,GE

In [4]:
#Create daframe for the insert Cyl1
#Read in the csv files
#Load test-retest csv file into dataframe
df_cyl1_tr = pd.read_csv('../../../../RadiomiK/Filtered_features/Test_ReTest/Final/Cyl1_testRetest.csv')

#Add a new column 'Test' to the dataframe in witch the value is 'Test-Retest' for all rows
df_cyl1_tr['Test'] = 'Test-Retest'

#Add a new column 'CT' to the dataframe in witch the value is 'TO-GE' for all rows
df_cyl1_tr['Manufacturer'] = 'TO-GE'

#delete the column 'count' from the dataframe
df_cyl1_tr = df_cyl1_tr.drop(['count'], axis=1)

#load the positioning csv file into a dataframe
df_cyl1_pos = pd.read_csv('../../../../RadiomiK/Features_Positioning_test/Features_Not_Repeatable/cv_Cyl1.csv')

#Add a new column 'Test' to the dataframe in witch the value is 'Positioning' for all rows
df_cyl1_pos['Test'] = 'Positioning'

#delete the column 'cv' from the dataframe
df_cyl1_pos = df_cyl1_pos.drop(['CV'], axis=1)

#Load the volume csv file into a dataframe
df_cyl1_vol = pd.read_csv('../../../../RadiomiK/Features_Volume_test/Features_Not_Repeatable/cv_Cyl1.csv')

#Add a new column 'Test' to the dataframe in witch the value is 'Volume' for all rows
df_cyl1_vol['Test'] = 'Volume'

#delete the column 'cv' from the dataframe
df_cyl1_vol = df_cyl1_vol.drop(['CV'], axis=1)

#Concatenate the three dataframes into one
df_cyl1 = pd.concat([df_cyl1_tr, df_cyl1_pos, df_cyl1_vol], ignore_index=True)

#Save the concatenated dataframe as csv file
df_cyl1.to_csv('../../../../RadiomiK/Features_not_repeatable_global/Cyl1_all_test.csv', index=False)

df_cyl1

,Feature,Test,Manufacturer
0,original_glszm_SmallAreaLowGrayLevelEmphasis,Test-Retest,TO-GE
1,original_gldm_SmallDependenceLowGrayLevelEmphasis,Test-Retest,TO-GE
2,original_glszm_SmallAreaLowGrayLevelEmphasis,Positioning,GE
3,original_firstorder_Energy,Volume,Toshiba
4,original_firstorder_TotalEnergy,Volume,Toshiba
5,original_glcm_JointEnergy,Volume,Toshiba
6,original_glcm_JointEntropy,Volume,Toshiba
7,original_glcm_MaximumProbability,Volume,Toshiba
8,original_glrlm_GrayLevelNonUniformity,Volume,Toshiba
9,original_glrlm_LongRunLowGrayLevelEmphasis,Volume,Toshiba
10,original_glrlm_LowGrayLevelRunEmphasis,Volume,Toshiba
11,original_glrlm_RunLengthNonUniformity,Volume,Toshiba
12,original_glrlm_RunVariance,Volume,Toshiba
13,original_glrlm_ShortRunLowGrayLevelEmphasis,Volume,Toshiba
14,original_glszm_GrayLevelNonUniformity,Volume,Toshiba
15,original_glszm_LargeAreaLowGrayLevelEmphasis,Volume,Toshiba
16,original_glszm_LowGrayLevelZoneEmphasis,Volume,Toshiba
17,original_glszm_SizeZoneNonUniformity,Volume,Toshiba
18,original_glszm_SmallAreaLowGrayLevelEmphasis,Volume,Toshiba
19,original_gldm_DependenceNonUniformity,Volume,Toshiba
20,original_gldm_DependenceVariance,Volume,Toshiba
21,original_gldm_GrayLevelNonUniformity,Volume,Toshiba
22,original_gldm_LargeDependenceHighGrayLevelEmph...,Volume,Toshiba
23,original_gldm_LargeDependenceLowGrayLevelEmphasis,Volume,Toshiba
24,original_gldm_LowGrayLevelEmphasis,Volume,Toshiba
25,original_gldm_SmallDependenceLowGrayLevelEmphasis,Volume,Toshiba
26,original_firstorder_Energy,Volume,GE
27,original_firstorder_TotalEnergy,Volume,GE
28,original_glcm_Correlation,Volume,GE
29,original_glrlm_GrayLevelNonUniformity,Volume,GE
30,original_glrlm_LongRunLowGrayLevelEmphasis,Volume,GE
31,original_glrlm_RunLengthNonUniformity,Volume,GE
32,original_glrlm_RunVariance,Volume,GE
33,original_glszm_GrayLevelNonUniformity,Volume,GE
34,original_glszm_GrayLevelNonUniformityNormalized,Volume,GE
35,original_glszm_LargeAreaEmphasis,Volume,GE
36,original_glszm_LargeAreaLowGrayLevelEmphasis,Volume,GE
37,original_glszm_LowGrayLevelZoneEmphasis,Volume,GE
38,original_glszm_SizeZoneNonUniformity,Volume,GE
39,original_glszm_SmallAreaLowGrayLevelEmphasis,Volume,GE
40,original_glszm_ZoneVariance,Volume,GE
41,original_gldm_DependenceNonUniformity,Volume,GE
42,original_gldm_DependenceVariance,Volume,GE
43,original_gldm_GrayLevelNonUniformity,Volume,GE
44,original_gldm_LargeDependenceEmphasis,Volume,GE
45,original_gldm_LargeDependenceLowGrayLevelEmphasis,Volume,GE

In [6]:
# Create daframe for the insert Cyl2
#Read in the csv files
#Load test-retest csv file into dataframe
df_cyl2_tr = pd.read_csv('../../../../RadiomiK/Filtered_features/Test_ReTest/Final/Cyl2_testRetest.csv')

#Add a new column 'Test' to the dataframe in witch the value is 'Test-Retest' for all rows
df_cyl2_tr['Test'] = 'Test-Retest'

#Add a new column 'CT' to the dataframe in witch the value is 'TO-GE' for all rows
df_cyl2_tr['Manufacturer'] = 'TO-GE'

#delete the column 'count' from the dataframe
df_cyl2_tr = df_cyl2_tr.drop(['count'], axis=1)

#load the positioning csv file into a dataframe
df_cyl2_pos = pd.read_csv('../../../../RadiomiK/Features_Positioning_test/Features_Not_Repeatable/cv_Cyl2.csv')

#Add a new column 'Test' to the dataframe in witch the value is 'Positioning' for all rows
df_cyl2_pos['Test'] = 'Positioning'

#delete the column 'cv' from the dataframe
df_cyl2_pos = df_cyl2_pos.drop(['CV'], axis=1)

#Load the volume csv file into a dataframe
df_cyl2_vol = pd.read_csv('../../../../RadiomiK/Features_Volume_test/Features_Not_Repeatable/cv_Cyl2.csv')

#Add a new column 'Test' to the dataframe in witch the value is 'Volume' for all rows
df_cyl2_vol['Test'] = 'Volume'

#delete the column 'cv' from the dataframe
df_cyl2_vol = df_cyl2_vol.drop(['CV'], axis=1)

#Concatenate the three dataframes into one
df_cyl2 = pd.concat([df_cyl2_tr, df_cyl2_pos, df_cyl2_vol], ignore_index=True)

#Save the concatenated dataframe as csv file
df_cyl2.to_csv('../../../../RadiomiK/Features_not_repeatable_global/Cyl2_all_test.csv', index=False)

df_cyl2

,Feature,Test,Manufacturer
0,original_glcm_Idmn,Test-Retest,TO-GE
1,original_glcm_Idn,Test-Retest,TO-GE
2,original_firstorder_Kurtosis,Test-Retest,TO-GE
3,original_glszm_LargeAreaHighGrayLevelEmphasis,Test-Retest,TO-GE
4,original_gldm_LargeDependenceHighGrayLevelEmph...,Test-Retest,TO-GE
5,original_glszm_SmallAreaEmphasis,Test-Retest,TO-GE
6,original_glszm_GrayLevelNonUniformity,Test-Retest,TO-GE
7,original_glszm_SmallAreaLowGrayLevelEmphasis,Test-Retest,TO-GE
8,original_glszm_ZoneEntropy,Test-Retest,TO-GE
9,original_gldm_SmallDependenceLowGrayLevelEmphasis,Test-Retest,TO-GE
10,original_glszm_SizeZoneNonUniformityNormalized,Test-Retest,TO-GE
11,original_firstorder_Energy,Volume,Toshiba
12,original_firstorder_TotalEnergy,Volume,Toshiba
13,original_glcm_Autocorrelation,Volume,Toshiba
14,original_glcm_JointEnergy,Volume,Toshiba
15,original_glcm_JointEntropy,Volume,Toshiba
16,original_glcm_MaximumProbability,Volume,Toshiba
17,original_glrlm_GrayLevelNonUniformity,Volume,Toshiba
18,original_glrlm_HighGrayLevelRunEmphasis,Volume,Toshiba
19,original_glrlm_LongRunHighGrayLevelEmphasis,Volume,Toshiba
20,original_glrlm_LongRunLowGrayLevelEmphasis,Volume,Toshiba
21,original_glrlm_LowGrayLevelRunEmphasis,Volume,Toshiba
22,original_glrlm_RunLengthNonUniformity,Volume,Toshiba
23,original_glrlm_ShortRunHighGrayLevelEmphasis,Volume,Toshiba
24,original_glrlm_ShortRunLowGrayLevelEmphasis,Volume,Toshiba
25,original_glszm_GrayLevelNonUniformity,Volume,Toshiba
26,original_glszm_LargeAreaHighGrayLevelEmphasis,Volume,Toshiba
27,original_glszm_LargeAreaLowGrayLevelEmphasis,Volume,Toshiba
28,original_glszm_LowGrayLevelZoneEmphasis,Volume,Toshiba
29,original_glszm_SizeZoneNonUniformity,Volume,Toshiba
30,original_glszm_SmallAreaLowGrayLevelEmphasis,Volume,Toshiba
31,original_gldm_DependenceNonUniformity,Volume,Toshiba
32,original_gldm_GrayLevelNonUniformity,Volume,Toshiba
33,original_gldm_HighGrayLevelEmphasis,Volume,Toshiba
34,original_gldm_LargeDependenceHighGrayLevelEmph...,Volume,Toshiba
35,original_gldm_LargeDependenceLowGrayLevelEmphasis,Volume,Toshiba
36,original_gldm_LowGrayLevelEmphasis,Volume,Toshiba
37,original_gldm_SmallDependenceLowGrayLevelEmphasis,Volume,Toshiba
38,original_firstorder_Energy,Volume,GE
39,original_firstorder_TotalEnergy,Volume,GE
40,original_glcm_JointEnergy,Volume,GE
41,original_glcm_Imc2,Volume,GE
42,original_glrlm_GrayLevelNonUniformity,Volume,GE
43,original_glrlm_RunLengthNonUniformity,Volume,GE
44,original_glrlm_RunVariance,Volume,GE
45,original_glszm_GrayLevelNonUniformity,Volume,GE
46,original_glszm_LargeAreaEmphasis,Volume,GE
47,original_glszm_LargeAreaHighGrayLevelEmphasis,Volume,GE
48,original_glszm_LargeAreaLowGrayLevelEmphasis,Volume,GE
49,original_glszm_LowGrayLevelZoneEmphasis,Volume,GE
50,original_glszm_SizeZoneNonUniformity,Volume,GE
51,original_glszm_SmallAreaLowGrayLevelEmphasis,Volume,GE
52,original_glszm_ZoneVariance,Volume,GE
53,original_gldm_DependenceNonUniformity,Volume,GE
54,original_gldm_GrayLevelNonUniformity,Volume,GE
55,original_gldm_SmallDependenceLowGrayLevelEmphasis,Volume,GE

In [7]:
# Create daframe for the insert Cyl3
#Read in the csv files
#Load test-retest csv file into dataframe
df_cyl3_tr = pd.read_csv('../../../../RadiomiK/Filtered_features/Test_ReTest/Final/Cyl3_testRetest.csv')

#Add a new column 'Test' to the dataframe in witch the value is 'Test-Retest' for all rows
df_cyl3_tr['Test'] = 'Test-Retest'

#Add a new column 'CT' to the dataframe in witch the value is 'TO-GE' for all rows
df_cyl3_tr['Manufacturer'] = 'TO-GE'

#delete the column 'count' from the dataframe
df_cyl3_tr = df_cyl3_tr.drop(['count'], axis=1)

#load the positioning csv file into a dataframe
df_cyl3_pos = pd.read_csv('../../../../RadiomiK/Features_Positioning_test/Features_Not_Repeatable/cv_Cyl3.csv')

#Add a new column 'Test' to the dataframe in witch the value is 'Positioning' for all rows
df_cyl3_pos['Test'] = 'Positioning'

#delete the column 'cv' from the dataframe
df_cyl3_pos = df_cyl3_pos.drop(['CV'], axis=1)

#Load the volume csv file into a dataframe
df_cyl3_vol = pd.read_csv('../../../../RadiomiK/Features_Volume_test/Features_Not_Repeatable/cv_Cyl3.csv')

#Add a new column 'Test' to the dataframe in witch the value is 'Volume' for all rows
df_cyl3_vol['Test'] = 'Volume'

#delete the column 'cv' from the dataframe
df_cyl3_vol = df_cyl3_vol.drop(['CV'], axis=1)

#Concatenate the three dataframes into one
df_cyl3 = pd.concat([df_cyl3_tr, df_cyl3_pos, df_cyl3_vol], ignore_index=True)

#Save the concatenated dataframe as csv file
df_cyl3.to_csv('../../../../RadiomiK/Features_not_repeatable_global/Cyl3_all_test.csv', index=False)

df_cyl3

,Feature,Test,Manufacturer
0,original_firstorder_Skewness,Test-Retest,TO-GE
1,original_glcm_ClusterShade,Test-Retest,TO-GE
2,original_gldm_LargeDependenceHighGrayLevelEmph...,Test-Retest,TO-GE
3,original_firstorder_Kurtosis,Test-Retest,TO-GE
4,original_glszm_SmallAreaEmphasis,Test-Retest,TO-GE
...,...,...,...
107,original_gldm_LargeDependenceHighGrayLevelEmph...,Volume,GE
108,original_gldm_LargeDependenceLowGrayLevelEmphasis,Volume,GE
109,original_gldm_LowGrayLevelEmphasis,Volume,GE
110,original_gldm_SmallDependenceHighGrayLevelEmph...,Volume,GE
111,original_gldm_SmallDependenceLowGrayLevelEmphasis,Volume,GE

In [8]:
# Create daframe for the insert Rect0
#Read in the csv files
#Load test-retest csv file into dataframe
df_rect0_tr = pd.read_csv('../../../../RadiomiK/Filtered_features/Test_ReTest/Final/Rect0_testRetest.csv')

#Add a new column 'Test' to the dataframe in witch the value is 'Test-Retest' for all rows
df_rect0_tr['Test'] = 'Test-Retest'

#Add a new column 'CT' to the dataframe in witch the value is 'TO-GE' for all rows
df_rect0_tr['Manufacturer'] = 'TO-GE'

#delete the column 'count' from the dataframe
df_rect0_tr = df_rect0_tr.drop(['count'], axis=1)

#load the positioning csv file into a dataframe
df_rect0_pos = pd.read_csv('../../../../RadiomiK/Features_Positioning_test/Features_Not_Repeatable/cv_Rect0.csv')

#Add a new column 'Test' to the dataframe in witch the value is 'Positioning' for all rows
df_rect0_pos['Test'] = 'Positioning'

#delete the column 'cv' from the dataframe
df_rect0_pos = df_rect0_pos.drop(['CV'], axis=1)

#Load the volume csv file into a dataframe
df_rect0_vol = pd.read_csv('../../../../RadiomiK/Features_Volume_test/Features_Not_Repeatable/cv_Rect0.csv')

#Add a new column 'Test' to the dataframe in witch the value is 'Volume' for all rows
df_rect0_vol['Test'] = 'Volume'

#delete the column 'cv' from the dataframe
df_rect0_vol = df_rect0_vol.drop(['CV'], axis=1)

#Concatenate the three dataframes into one
df_rect0 = pd.concat([df_rect0_tr, df_rect0_pos, df_rect0_vol], ignore_index=True)

#Save the concatenated dataframe as csv file
df_rect0.to_csv('../../../../RadiomiK/Features_not_repeatable_global/Rect0_all_test.csv', index=False)

df_rect0

,Feature,Test,Manufacturer
0,original_glcm_Idmn,Test-Retest,TO-GE
1,original_firstorder_Range,Test-Retest,TO-GE
2,original_glszm_LargeAreaHighGrayLevelEmphasis,Test-Retest,TO-GE
3,original_glcm_Idn,Test-Retest,TO-GE
4,original_firstorder_Kurtosis,Test-Retest,TO-GE
...,...,...,...
59,original_gldm_DependenceVariance,Volume,GE
60,original_gldm_GrayLevelNonUniformity,Volume,GE
61,original_gldm_LargeDependenceLowGrayLevelEmphasis,Volume,GE
62,original_gldm_LowGrayLevelEmphasis,Volume,GE
63,original_gldm_SmallDependenceLowGrayLevelEmphasis,Volume,GE

In [9]:
# Create daframe for the insert Rect1
#Read in the csv files
#Load test-retest csv file into dataframe
df_rect1_tr = pd.read_csv('../../../../RadiomiK/Filtered_features/Test_ReTest/Final/Rect1_testRetest.csv')

#Add a new column 'Test' to the dataframe in witch the value is 'Test-Retest' for all rows
df_rect1_tr['Test'] = 'Test-Retest'

#Add a new column 'CT' to the dataframe in witch the value is 'TO-GE' for all rows
df_rect1_tr['Manufacturer'] = 'TO-GE'

#delete the column 'count' from the dataframe
df_rect1_tr = df_rect1_tr.drop(['count'], axis=1)

#load the positioning csv file into a dataframe
df_rect1_pos = pd.read_csv('../../../../RadiomiK/Features_Positioning_test/Features_Not_Repeatable/cv_Rect1.csv')

#Add a new column 'Test' to the dataframe in witch the value is 'Positioning' for all rows
df_rect1_pos['Test'] = 'Positioning'

#delete the column 'cv' from the dataframe
df_rect1_pos = df_rect1_pos.drop(['CV'], axis=1)

#Load the volume csv file into a dataframe
df_rect1_vol = pd.read_csv('../../../../RadiomiK/Features_Volume_test/Features_Not_Repeatable/cv_Rect1.csv')

#Add a new column 'Test' to the dataframe in witch the value is 'Volume' for all rows
df_rect1_vol['Test'] = 'Volume'

#delete the column 'cv' from the dataframe
df_rect1_vol = df_rect1_vol.drop(['CV'], axis=1)

#Concatenate the three dataframes into one
df_rect1 = pd.concat([df_rect1_tr, df_rect1_pos, df_rect1_vol], ignore_index=True)

#Save the concatenated dataframe as csv file
df_rect1.to_csv('../../../../RadiomiK/Features_not_repeatable_global/Rect1_all_test.csv', index=False)

df_rect1

,Feature,Test,Manufacturer
0,original_glcm_Idn,Test-Retest,TO-GE
1,original_glcm_Idmn,Test-Retest,TO-GE
2,original_firstorder_Maximum,Test-Retest,TO-GE
3,original_firstorder_Kurtosis,Test-Retest,TO-GE
4,original_glszm_SmallAreaEmphasis,Test-Retest,TO-GE
5,original_glszm_SizeZoneNonUniformityNormalized,Test-Retest,TO-GE
6,original_glszm_SizeZoneNonUniformity,Test-Retest,TO-GE
7,original_gldm_SmallDependenceEmphasis,Test-Retest,TO-GE
8,original_gldm_DependenceNonUniformityNormalized,Test-Retest,TO-GE
9,original_glcm_Correlation,Test-Retest,TO-GE
10,original_glrlm_LongRunLowGrayLevelEmphasis,Positioning,Toshiba
11,original_glrlm_LowGrayLevelRunEmphasis,Positioning,Toshiba
12,original_glrlm_ShortRunLowGrayLevelEmphasis,Positioning,Toshiba
13,original_glszm_LargeAreaLowGrayLevelEmphasis,Positioning,Toshiba
14,original_glszm_LowGrayLevelZoneEmphasis,Positioning,Toshiba
15,original_glszm_SmallAreaLowGrayLevelEmphasis,Positioning,Toshiba
16,original_gldm_LargeDependenceLowGrayLevelEmphasis,Positioning,Toshiba
17,original_gldm_LowGrayLevelEmphasis,Positioning,Toshiba
18,original_gldm_SmallDependenceLowGrayLevelEmphasis,Positioning,Toshiba
19,original_firstorder_Energy,Volume,Toshiba
20,original_firstorder_TotalEnergy,Volume,Toshiba
21,original_glcm_Autocorrelation,Volume,Toshiba
22,original_glcm_Correlation,Volume,Toshiba
23,original_glcm_JointEnergy,Volume,Toshiba
24,original_glcm_MaximumProbability,Volume,Toshiba
25,original_glrlm_GrayLevelNonUniformity,Volume,Toshiba
26,original_glrlm_LongRunLowGrayLevelEmphasis,Volume,Toshiba
27,original_glrlm_LowGrayLevelRunEmphasis,Volume,Toshiba
28,original_glrlm_RunLengthNonUniformity,Volume,Toshiba
29,original_glrlm_ShortRunLowGrayLevelEmphasis,Volume,Toshiba
30,original_glszm_GrayLevelNonUniformity,Volume,Toshiba
31,original_glszm_LargeAreaHighGrayLevelEmphasis,Volume,Toshiba
32,original_glszm_LargeAreaLowGrayLevelEmphasis,Volume,Toshiba
33,original_glszm_LowGrayLevelZoneEmphasis,Volume,Toshiba
34,original_glszm_SizeZoneNonUniformity,Volume,Toshiba
35,original_glszm_SmallAreaLowGrayLevelEmphasis,Volume,Toshiba
36,original_gldm_DependenceNonUniformity,Volume,Toshiba
37,original_gldm_GrayLevelNonUniformity,Volume,Toshiba
38,original_gldm_LargeDependenceHighGrayLevelEmph...,Volume,Toshiba
39,original_gldm_LargeDependenceLowGrayLevelEmphasis,Volume,Toshiba
40,original_gldm_LowGrayLevelEmphasis,Volume,Toshiba
41,original_gldm_SmallDependenceLowGrayLevelEmphasis,Volume,Toshiba
42,original_firstorder_Energy,Volume,GE
43,original_firstorder_TotalEnergy,Volume,GE
44,original_glcm_Correlation,Volume,GE
45,original_glcm_JointEnergy,Volume,GE
46,original_glrlm_GrayLevelNonUniformity,Volume,GE
47,original_glrlm_RunLengthNonUniformity,Volume,GE
48,original_glrlm_RunVariance,Volume,GE
49,original_glszm_GrayLevelNonUniformity,Volume,GE
50,original_glszm_LargeAreaEmphasis,Volume,GE
51,original_glszm_LargeAreaLowGrayLevelEmphasis,Volume,GE
52,original_glszm_LowGrayLevelZoneEmphasis,Volume,GE
53,original_glszm_SizeZoneNonUniformity,Volume,GE
54,original_glszm_SmallAreaLowGrayLevelEmphasis,Volume,GE
55,original_glszm_ZoneVariance,Volume,GE
56,original_gldm_DependenceNonUniformity,Volume,GE
57,original_gldm_GrayLevelNonUniformity,Volume,GE
58,original_gldm_SmallDependenceLowGrayLevelEmphasis,Volume,GE

In [10]:
# Create daframe for the insert Rect2
#Read in the csv files
#Load test-retest csv file into dataframe
df_rect2_tr = pd.read_csv('../../../../RadiomiK/Filtered_features/Test_ReTest/Final/Rect2_testRetest.csv')

#Add a new column 'Test' to the dataframe in witch the value is 'Test-Retest' for all rows
df_rect2_tr['Test'] = 'Test-Retest'

#Add a new column 'CT' to the dataframe in witch the value is 'TO-GE' for all rows
df_rect2_tr['Manufacturer'] = 'TO-GE'

#delete the column 'count' from the dataframe
df_rect2_tr = df_rect2_tr.drop(['count'], axis=1)

#load the positioning csv file into a dataframe
df_rect2_pos = pd.read_csv('../../../../RadiomiK/Features_Positioning_test/Features_Not_Repeatable/cv_Rect2.csv')

#Add a new column 'Test' to the dataframe in witch the value is 'Positioning' for all rows
df_rect2_pos['Test'] = 'Positioning'

#delete the column 'cv' from the dataframe
df_rect2_pos = df_rect2_pos.drop(['CV'], axis=1)

#Load the volume csv file into a dataframe
df_rect2_vol = pd.read_csv('../../../../RadiomiK/Features_Volume_test/Features_Not_Repeatable/cv_Rect2.csv')

#Add a new column 'Test' to the dataframe in witch the value is 'Volume' for all rows
df_rect2_vol['Test'] = 'Volume'

#delete the column 'cv' from the dataframe
df_rect2_vol = df_rect2_vol.drop(['CV'], axis=1)

#Concatenate the three dataframes into one
df_rect2 = pd.concat([df_rect2_tr, df_rect2_pos, df_rect2_vol], ignore_index=True)

#Save the concatenated dataframe as csv file
df_rect2.to_csv('../../../../RadiomiK/Features_not_repeatable_global/Rect2_all_test.csv', index=False)

df_rect2

,Feature,Test,Manufacturer
0,original_glcm_Idmn,Test-Retest,TO-GE
1,original_glszm_SmallAreaLowGrayLevelEmphasis,Test-Retest,TO-GE
2,original_glcm_Idn,Test-Retest,TO-GE
3,original_glszm_LargeAreaHighGrayLevelEmphasis,Test-Retest,TO-GE
4,original_glszm_LowGrayLevelZoneEmphasis,Test-Retest,TO-GE
5,original_firstorder_Kurtosis,Test-Retest,TO-GE
6,original_gldm_LargeDependenceHighGrayLevelEmph...,Test-Retest,TO-GE
7,original_gldm_SmallDependenceLowGrayLevelEmphasis,Test-Retest,TO-GE
8,original_firstorder_Skewness,Test-Retest,TO-GE
9,original_glcm_Correlation,Positioning,Toshiba
10,original_firstorder_Energy,Volume,Toshiba
11,original_firstorder_Range,Volume,Toshiba
12,original_firstorder_Skewness,Volume,Toshiba
13,original_firstorder_TotalEnergy,Volume,Toshiba
14,original_glcm_Autocorrelation,Volume,Toshiba
15,original_glcm_ClusterShade,Volume,Toshiba
16,original_glcm_Correlation,Volume,Toshiba
17,original_glcm_JointEnergy,Volume,Toshiba
18,original_glcm_MaximumProbability,Volume,Toshiba
19,original_glrlm_GrayLevelNonUniformity,Volume,Toshiba
20,original_glrlm_HighGrayLevelRunEmphasis,Volume,Toshiba
21,original_glrlm_LongRunHighGrayLevelEmphasis,Volume,Toshiba
22,original_glrlm_LongRunLowGrayLevelEmphasis,Volume,Toshiba
23,original_glrlm_LowGrayLevelRunEmphasis,Volume,Toshiba
24,original_glrlm_RunLengthNonUniformity,Volume,Toshiba
25,original_glrlm_ShortRunHighGrayLevelEmphasis,Volume,Toshiba
26,original_glrlm_ShortRunLowGrayLevelEmphasis,Volume,Toshiba
27,original_glszm_GrayLevelNonUniformity,Volume,Toshiba
28,original_glszm_HighGrayLevelZoneEmphasis,Volume,Toshiba
29,original_glszm_LargeAreaLowGrayLevelEmphasis,Volume,Toshiba
30,original_glszm_LowGrayLevelZoneEmphasis,Volume,Toshiba
31,original_glszm_SizeZoneNonUniformity,Volume,Toshiba
32,original_glszm_SmallAreaHighGrayLevelEmphasis,Volume,Toshiba
33,original_glszm_SmallAreaLowGrayLevelEmphasis,Volume,Toshiba
34,original_glszm_ZoneVariance,Volume,Toshiba
35,original_gldm_DependenceNonUniformity,Volume,Toshiba
36,original_gldm_GrayLevelNonUniformity,Volume,Toshiba
37,original_gldm_HighGrayLevelEmphasis,Volume,Toshiba
38,original_gldm_LargeDependenceLowGrayLevelEmphasis,Volume,Toshiba
39,original_gldm_LowGrayLevelEmphasis,Volume,Toshiba
40,original_gldm_SmallDependenceHighGrayLevelEmph...,Volume,Toshiba
41,original_gldm_SmallDependenceLowGrayLevelEmphasis,Volume,Toshiba
42,original_firstorder_Energy,Volume,GE
43,original_firstorder_TotalEnergy,Volume,GE
44,original_glcm_JointEnergy,Volume,GE
45,original_glcm_MaximumProbability,Volume,GE
46,original_glrlm_GrayLevelNonUniformity,Volume,GE
47,original_glrlm_RunLengthNonUniformity,Volume,GE
48,original_glrlm_RunVariance,Volume,GE
49,original_glszm_GrayLevelNonUniformity,Volume,GE
50,original_glszm_LargeAreaEmphasis,Volume,GE
51,original_glszm_LargeAreaLowGrayLevelEmphasis,Volume,GE
52,original_glszm_SizeZoneNonUniformity,Volume,GE
53,original_glszm_ZoneVariance,Volume,GE
54,original_gldm_DependenceNonUniformity,Volume,GE
55,original_gldm_DependenceVariance,Volume,GE
56,original_gldm_GrayLevelNonUniformity,Volume,GE
57,original_gldm_LargeDependenceLowGrayLevelEmphasis,Volume,GE

In [11]:
# Create daframe for the insert Rect3
#Read in the csv files
#Load test-retest csv file into dataframe
df_rect3_tr = pd.read_csv('../../../../RadiomiK/Filtered_features/Test_ReTest/Final/Rect3_testRetest.csv')

#Add a new column 'Test' to the dataframe in witch the value is 'Test-Retest' for all rows
df_rect3_tr['Test'] = 'Test-Retest'

#Add a new column 'CT' to the dataframe in witch the value is 'TO-GE' for all rows
df_rect3_tr['Manufacturer'] = 'TO-GE'

#delete the column 'count' from the dataframe
df_rect3_tr = df_rect3_tr.drop(['count'], axis=1)

#load the positioning csv file into a dataframe
df_rect3_pos = pd.read_csv('../../../../RadiomiK/Features_Positioning_test/Features_Not_Repeatable/cv_Rect3.csv')

#Add a new column 'Test' to the dataframe in witch the value is 'Positioning' for all rows
df_rect3_pos['Test'] = 'Positioning'

#delete the column 'cv' from the dataframe
df_rect3_pos = df_rect3_pos.drop(['CV'], axis=1)

#Load the volume csv file into a dataframe
df_rect3_vol = pd.read_csv('../../../../RadiomiK/Features_Volume_test/Features_Not_Repeatable/cv_Rect3.csv')

#Add a new column 'Test' to the dataframe in witch the value is 'Volume' for all rows
df_rect3_vol['Test'] = 'Volume'

#delete the column 'cv' from the dataframe
df_rect3_vol = df_rect3_vol.drop(['CV'], axis=1)

#Concatenate the three dataframes into one
df_rect3 = pd.concat([df_rect3_tr, df_rect3_pos, df_rect3_vol], ignore_index=True)

#Save the concatenated dataframe as csv file
df_rect3.to_csv('../../../../RadiomiK/Features_not_repeatable_global/Rect3_all_test.csv', index=False)

df_rect3

,Feature,Test,Manufacturer
0,original_glcm_Idmn,Test-Retest,TO-GE
1,original_gldm_LargeDependenceHighGrayLevelEmph...,Test-Retest,TO-GE
2,original_gldm_DependenceEntropy,Test-Retest,TO-GE
3,original_gldm_SmallDependenceLowGrayLevelEmphasis,Test-Retest,TO-GE
4,original_glcm_Idn,Test-Retest,TO-GE
...,...,...,...
98,original_gldm_LargeDependenceHighGrayLevelEmph...,Volume,GE
99,original_gldm_LargeDependenceLowGrayLevelEmphasis,Volume,GE
100,original_gldm_LowGrayLevelEmphasis,Volume,GE
101,original_gldm_SmallDependenceHighGrayLevelEmph...,Volume,GE
102,original_gldm_SmallDependenceLowGrayLevelEmphasis,Volume,GE

In [12]:
# Create daframe for the insert Rect4
#Read in the csv files
#Load test-retest csv file into dataframe
df_rect4_tr = pd.read_csv('../../../../RadiomiK/Filtered_features/Test_ReTest/Final/Rect4_testRetest.csv')

#Add a new column 'Test' to the dataframe in witch the value is 'Test-Retest' for all rows
df_rect4_tr['Test'] = 'Test-Retest'

#Add a new column 'CT' to the dataframe in witch the value is 'TO-GE' for all rows
df_rect4_tr['Manufacturer'] = 'TO-GE'

#delete the column 'count' from the dataframe
df_rect4_tr = df_rect4_tr.drop(['count'], axis=1)

#load the positioning csv file into a dataframe
df_rect4_pos = pd.read_csv('../../../../RadiomiK/Features_Positioning_test/Features_Not_Repeatable/cv_Rect4.csv')

#Add a new column 'Test' to the dataframe in witch the value is 'Positioning' for all rows
df_rect4_pos['Test'] = 'Positioning'

#delete the column 'cv' from the dataframe
df_rect4_pos = df_rect4_pos.drop(['CV'], axis=1)

#Load the volume csv file into a dataframe
df_rect4_vol = pd.read_csv('../../../../RadiomiK/Features_Volume_test/Features_Not_Repeatable/cv_Rect4.csv')

#Add a new column 'Test' to the dataframe in witch the value is 'Volume' for all rows
df_rect4_vol['Test'] = 'Volume'

#delete the column 'cv' from the dataframe
df_rect4_vol = df_rect4_vol.drop(['CV'], axis=1)

#Concatenate the three dataframes into one
df_rect4 = pd.concat([df_rect4_tr, df_rect4_pos, df_rect4_vol], ignore_index=True)

#Save the concatenated dataframe as csv file
df_rect4.to_csv('../../../../RadiomiK/Features_not_repeatable_global/Rect4_all_test.csv', index=False)

df_rect4

,Feature,Test,Manufacturer
0,original_glcm_ClusterShade,Test-Retest,TO-GE
1,original_gldm_SmallDependenceLowGrayLevelEmphasis,Test-Retest,TO-GE
2,original_gldm_HighGrayLevelEmphasis,Test-Retest,TO-GE
3,original_glrlm_LongRunHighGrayLevelEmphasis,Test-Retest,TO-GE
4,original_gldm_LargeDependenceHighGrayLevelEmph...,Test-Retest,TO-GE
...,...,...,...
76,original_glszm_ZoneVariance,Volume,GE
77,original_gldm_DependenceNonUniformity,Volume,GE
78,original_gldm_GrayLevelNonUniformity,Volume,GE
79,original_gldm_LowGrayLevelEmphasis,Volume,GE
80,original_gldm_SmallDependenceLowGrayLevelEmphasis,Volume,GE

In [13]:
# Create daframe for the insert Rect5
#Read in the csv files
#Load test-retest csv file into dataframe
df_rect5_tr = pd.read_csv('../../../../RadiomiK/Filtered_features/Test_ReTest/Final/Rect5_testRetest.csv')

#Add a new column 'Test' to the dataframe in witch the value is 'Test-Retest' for all rows
df_rect5_tr['Test'] = 'Test-Retest'

#Add a new column 'CT' to the dataframe in witch the value is 'TO-GE' for all rows
df_rect5_tr['Manufacturer'] = 'TO-GE'

#delete the column 'count' from the dataframe
df_rect5_tr = df_rect5_tr.drop(['count'], axis=1)

#load the positioning csv file into a dataframe
df_rect5_pos = pd.read_csv('../../../../RadiomiK/Features_Positioning_test/Features_Not_Repeatable/cv_Rect5.csv')

#Add a new column 'Test' to the dataframe in witch the value is 'Positioning' for all rows
df_rect5_pos['Test'] = 'Positioning'

#delete the column 'cv' from the dataframe
df_rect5_pos = df_rect5_pos.drop(['CV'], axis=1)

#Load the volume csv file into a dataframe
df_rect5_vol = pd.read_csv('../../../../RadiomiK/Features_Volume_test/Features_Not_Repeatable/cv_Rect5.csv')

#Add a new column 'Test' to the dataframe in witch the value is 'Volume' for all rows
df_rect5_vol['Test'] = 'Volume'

#delete the column 'cv' from the dataframe
df_rect5_vol = df_rect5_vol.drop(['CV'], axis=1)

#Concatenate the three dataframes into one
df_rect5 = pd.concat([df_rect5_tr, df_rect5_pos, df_rect5_vol], ignore_index=True)

#Save the concatenated dataframe as csv file
df_rect5.to_csv('../../../../RadiomiK/Features_not_repeatable_global/Rect5_all_test.csv', index=False)

df_rect5

,Feature,Test,Manufacturer
0,original_glszm_HighGrayLevelZoneEmphasis,Test-Retest,TO-GE
1,original_firstorder_Range,Test-Retest,TO-GE
2,original_glszm_ZoneEntropy,Test-Retest,TO-GE
3,original_glszm_SmallAreaHighGrayLevelEmphasis,Test-Retest,TO-GE
4,original_gldm_SmallDependenceHighGrayLevelEmph...,Test-Retest,TO-GE
...,...,...,...
59,original_gldm_DependenceNonUniformity,Volume,GE
60,original_gldm_GrayLevelNonUniformity,Volume,GE
61,original_gldm_LargeDependenceLowGrayLevelEmphasis,Volume,GE
62,original_gldm_LowGrayLevelEmphasis,Volume,GE
63,original_gldm_SmallDependenceLowGrayLevelEmphasis,Volume,GE

In [14]:
# Create daframe for the insert Rect6
#Read in the csv files
#Load test-retest csv file into dataframe
df_rect6_tr = pd.read_csv('../../../../RadiomiK/Filtered_features/Test_ReTest/Final/Rect6_testRetest.csv')

#Add a new column 'Test' to the dataframe in witch the value is 'Test-Retest' for all rows
df_rect6_tr['Test'] = 'Test-Retest'

#Add a new column 'CT' to the dataframe in witch the value is 'TO-GE' for all rows
df_rect6_tr['Manufacturer'] = 'TO-GE'

#delete the column 'count' from the dataframe
df_rect6_tr = df_rect6_tr.drop(['count'], axis=1)

#load the positioning csv file into a dataframe
df_rect6_pos = pd.read_csv('../../../../RadiomiK/Features_Positioning_test/Features_Not_Repeatable/cv_Rect6.csv')

#Add a new column 'Test' to the dataframe in witch the value is 'Positioning' for all rows
df_rect6_pos['Test'] = 'Positioning'

#delete the column 'cv' from the dataframe
df_rect6_pos = df_rect6_pos.drop(['CV'], axis=1)

#Load the volume csv file into a dataframe
df_rect6_vol = pd.read_csv('../../../../RadiomiK/Features_Volume_test/Features_Not_Repeatable/cv_Rect6.csv')

#Add a new column 'Test' to the dataframe in witch the value is 'Volume' for all rows
df_rect6_vol['Test'] = 'Volume'

#delete the column 'cv' from the dataframe
df_rect6_vol = df_rect6_vol.drop(['CV'], axis=1)

#Concatenate the three dataframes into one
df_rect6 = pd.concat([df_rect6_tr, df_rect6_pos, df_rect6_vol], ignore_index=True)

#Save the concatenated dataframe as csv file
df_rect6.to_csv('../../../../RadiomiK/Features_not_repeatable_global/Rect6_all_test.csv', index=False)

df_rect6

,Feature,Test,Manufacturer
0,original_glszm_SmallAreaLowGrayLevelEmphasis,Test-Retest,TO-GE
1,original_glszm_SizeZoneNonUniformityNormalized,Test-Retest,TO-GE
2,original_glcm_Idn,Test-Retest,TO-GE
3,original_glcm_Idmn,Test-Retest,TO-GE
4,original_glszm_SmallAreaEmphasis,Test-Retest,TO-GE
...,...,...,...
74,original_gldm_DependenceNonUniformity,Volume,GE
75,original_gldm_DependenceVariance,Volume,GE
76,original_gldm_GrayLevelNonUniformity,Volume,GE
77,original_gldm_LargeDependenceLowGrayLevelEmphasis,Volume,GE
78,original_gldm_SmallDependenceLowGrayLevelEmphasis,Volume,GE

In [15]:
# Create daframe for the insert Rect7
#Read in the csv files
#Load test-retest csv file into dataframe
df_rect7_tr = pd.read_csv('../../../../RadiomiK/Filtered_features/Test_ReTest/Final/Rect7_testRetest.csv')

#Add a new column 'Test' to the dataframe in witch the value is 'Test-Retest' for all rows
df_rect7_tr['Test'] = 'Test-Retest'

#Add a new column 'CT' to the dataframe in witch the value is 'TO-GE' for all rows
df_rect7_tr['Manufacturer'] = 'TO-GE'

#delete the column 'count' from the dataframe
df_rect7_tr = df_rect7_tr.drop(['count'], axis=1)

#load the positioning csv file into a dataframe
df_rect7_pos = pd.read_csv('../../../../RadiomiK/Features_Positioning_test/Features_Not_Repeatable/cv_Rect7.csv')

#Add a new column 'Test' to the dataframe in witch the value is 'Positioning' for all rows
df_rect7_pos['Test'] = 'Positioning'

#delete the column 'cv' from the dataframe
df_rect7_pos = df_rect7_pos.drop(['CV'], axis=1)

#Load the volume csv file into a dataframe
df_rect7_vol = pd.read_csv('../../../../RadiomiK/Features_Volume_test/Features_Not_Repeatable/cv_Rect7.csv')

#Add a new column 'Test' to the dataframe in witch the value is 'Volume' for all rows
df_rect7_vol['Test'] = 'Volume'

#delete the column 'cv' from the dataframe
df_rect7_vol = df_rect7_vol.drop(['CV'], axis=1)

#Concatenate the three dataframes into one
df_rect7 = pd.concat([df_rect7_tr, df_rect7_pos, df_rect7_vol], ignore_index=True)

#Save the concatenated dataframe as csv file
df_rect7.to_csv('../../../../RadiomiK/Features_not_repeatable_global/Rect7_all_test.csv', index=False)

df_rect7

,Feature,Test,Manufacturer
0,original_glcm_Idmn,Test-Retest,TO-GE
1,original_glszm_ZoneEntropy,Test-Retest,TO-GE
2,original_glcm_Idn,Test-Retest,TO-GE
3,original_glszm_SmallAreaLowGrayLevelEmphasis,Test-Retest,TO-GE
4,original_glrlm_LongRunLowGrayLevelEmphasis,Positioning,Toshiba
...,...,...,...
65,original_gldm_DependenceVariance,Volume,GE
66,original_gldm_GrayLevelNonUniformity,Volume,GE
67,original_gldm_LargeDependenceEmphasis,Volume,GE
68,original_gldm_LargeDependenceLowGrayLevelEmphasis,Volume,GE
69,original_gldm_SmallDependenceHighGrayLevelEmph...,Volume,GE

In [16]:
# Create daframe for the insert Rect8
#Read in the csv files
#Load test-retest csv file into dataframe
df_rect8_tr = pd.read_csv('../../../../RadiomiK/Filtered_features/Test_ReTest/Final/Rect8_testRetest.csv')

#Add a new column 'Test' to the dataframe in witch the value is 'Test-Retest' for all rows
df_rect8_tr['Test'] = 'Test-Retest'

#Add a new column 'CT' to the dataframe in witch the value is 'TO-GE' for all rows
df_rect8_tr['Manufacturer'] = 'TO-GE'

#delete the column 'count' from the dataframe
df_rect8_tr = df_rect8_tr.drop(['count'], axis=1)

#load the positioning csv file into a dataframe
df_rect8_pos = pd.read_csv('../../../../RadiomiK/Features_Positioning_test/Features_Not_Repeatable/cv_Rect8.csv')

#Add a new column 'Test' to the dataframe in witch the value is 'Positioning' for all rows
df_rect8_pos['Test'] = 'Positioning'

#delete the column 'cv' from the dataframe
df_rect8_pos = df_rect8_pos.drop(['CV'], axis=1)

#Load the volume csv file into a dataframe
df_rect8_vol = pd.read_csv('../../../../RadiomiK/Features_Volume_test/Features_Not_Repeatable/cv_Rect8.csv')

#Add a new column 'Test' to the dataframe in witch the value is 'Volume' for all rows
df_rect8_vol['Test'] = 'Volume'

#delete the column 'cv' from the dataframe
df_rect8_vol = df_rect8_vol.drop(['CV'], axis=1)

#Concatenate the three dataframes into one
df_rect8 = pd.concat([df_rect8_tr, df_rect8_pos, df_rect8_vol], ignore_index=True)

#Save the concatenated dataframe as csv file
df_rect8.to_csv('../../../../RadiomiK/Features_not_repeatable_global/Rect8_all_test.csv', index=False)

df_rect8

,Feature,Test,Manufacturer
0,original_glcm_Idn,Test-Retest,TO-GE
1,original_glcm_Idmn,Test-Retest,TO-GE
2,original_glszm_SmallAreaLowGrayLevelEmphasis,Test-Retest,TO-GE
3,original_gldm_DependenceEntropy,Test-Retest,TO-GE
4,original_gldm_SmallDependenceLowGrayLevelEmphasis,Test-Retest,TO-GE
5,original_firstorder_Energy,Volume,Toshiba
6,original_firstorder_TotalEnergy,Volume,Toshiba
7,original_glcm_JointEnergy,Volume,Toshiba
8,original_glcm_MaximumProbability,Volume,Toshiba
9,original_glrlm_GrayLevelNonUniformity,Volume,Toshiba
10,original_glrlm_LongRunLowGrayLevelEmphasis,Volume,Toshiba
11,original_glrlm_LowGrayLevelRunEmphasis,Volume,Toshiba
12,original_glrlm_RunLengthNonUniformity,Volume,Toshiba
13,original_glrlm_ShortRunLowGrayLevelEmphasis,Volume,Toshiba
14,original_glszm_GrayLevelNonUniformity,Volume,Toshiba
15,original_glszm_LargeAreaLowGrayLevelEmphasis,Volume,Toshiba
16,original_glszm_LowGrayLevelZoneEmphasis,Volume,Toshiba
17,original_glszm_SizeZoneNonUniformity,Volume,Toshiba
18,original_glszm_SmallAreaLowGrayLevelEmphasis,Volume,Toshiba
19,original_gldm_DependenceNonUniformity,Volume,Toshiba
20,original_gldm_GrayLevelNonUniformity,Volume,Toshiba
21,original_gldm_LargeDependenceLowGrayLevelEmphasis,Volume,Toshiba
22,original_gldm_LowGrayLevelEmphasis,Volume,Toshiba
23,original_gldm_SmallDependenceLowGrayLevelEmphasis,Volume,Toshiba
24,original_firstorder_Energy,Volume,GE
25,original_firstorder_TotalEnergy,Volume,GE
26,original_firstorder_Uniformity,Volume,GE
27,original_glcm_Correlation,Volume,GE
28,original_glcm_JointEnergy,Volume,GE
29,original_glcm_MaximumProbability,Volume,GE
30,original_glrlm_GrayLevelNonUniformity,Volume,GE
31,original_glrlm_LongRunLowGrayLevelEmphasis,Volume,GE
32,original_glrlm_RunLengthNonUniformity,Volume,GE
33,original_glrlm_RunVariance,Volume,GE
34,original_glszm_GrayLevelNonUniformity,Volume,GE
35,original_glszm_LargeAreaEmphasis,Volume,GE
36,original_glszm_LargeAreaLowGrayLevelEmphasis,Volume,GE
37,original_glszm_LowGrayLevelZoneEmphasis,Volume,GE
38,original_glszm_SizeZoneNonUniformity,Volume,GE
39,original_glszm_SmallAreaLowGrayLevelEmphasis,Volume,GE
40,original_glszm_ZoneVariance,Volume,GE
41,original_gldm_DependenceNonUniformity,Volume,GE
42,original_gldm_DependenceVariance,Volume,GE
43,original_gldm_GrayLevelNonUniformity,Volume,GE
44,original_gldm_LargeDependenceEmphasis,Volume,GE
45,original_gldm_LargeDependenceLowGrayLevelEmphasis,Volume,GE
46,original_gldm_SmallDependenceLowGrayLevelEmphasis,Volume,GE

In [17]:
# Create daframe for the insert Rect9
#Read in the csv files
#Load test-retest csv file into dataframe
df_rect9_tr = pd.read_csv('../../../../RadiomiK/Filtered_features/Test_ReTest/Final/Rect9_testRetest.csv')

#Add a new column 'Test' to the dataframe in witch the value is 'Test-Retest' for all rows
df_rect9_tr['Test'] = 'Test-Retest'

#Add a new column 'CT' to the dataframe in witch the value is 'TO-GE' for all rows
df_rect9_tr['Manufacturer'] = 'TO-GE'

#delete the column 'count' from the dataframe
df_rect9_tr = df_rect9_tr.drop(['count'], axis=1)

#load the positioning csv file into a dataframe
df_rect9_pos = pd.read_csv('../../../../RadiomiK/Features_Positioning_test/Features_Not_Repeatable/cv_Rect9.csv')

#Add a new column 'Test' to the dataframe in witch the value is 'Positioning' for all rows
df_rect9_pos['Test'] = 'Positioning'

#delete the column 'cv' from the dataframe
df_rect9_pos = df_rect9_pos.drop(['CV'], axis=1)

#Load the volume csv file into a dataframe
df_rect9_vol = pd.read_csv('../../../../RadiomiK/Features_Volume_test/Features_Not_Repeatable/cv_Rect9.csv')

#Add a new column 'Test' to the dataframe in witch the value is 'Volume' for all rows
df_rect9_vol['Test'] = 'Volume'

#delete the column 'cv' from the dataframe
df_rect9_vol = df_rect9_vol.drop(['CV'], axis=1)

#Concatenate the three dataframes into one
df_rect9 = pd.concat([df_rect9_tr, df_rect9_pos, df_rect9_vol], ignore_index=True)

#Save the concatenated dataframe as csv file
df_rect9.to_csv('../../../../RadiomiK/Features_not_repeatable_global/Rect9_all_test.csv', index=False)

df_rect9

,Feature,Test,Manufacturer
0,original_glszm_ZoneEntropy,Test-Retest,TO-GE
1,original_glszm_LargeAreaHighGrayLevelEmphasis,Test-Retest,TO-GE
2,original_gldm_DependenceEntropy,Test-Retest,TO-GE
3,original_gldm_SmallDependenceLowGrayLevelEmphasis,Test-Retest,TO-GE
4,original_glszm_SmallAreaLowGrayLevelEmphasis,Test-Retest,TO-GE
...,...,...,...
70,original_gldm_LargeDependenceLowGrayLevelEmphasis,Volume,GE
71,original_gldm_LowGrayLevelEmphasis,Volume,GE
72,original_gldm_SmallDependenceEmphasis,Volume,GE
73,original_gldm_SmallDependenceHighGrayLevelEmph...,Volume,GE
74,original_gldm_SmallDependenceLowGrayLevelEmphasis,Volume,GE

In [18]:
# Create daframe for the insert Rect10
#Read in the csv files
#Load test-retest csv file into dataframe
df_rect10_tr = pd.read_csv('../../../../RadiomiK/Filtered_features/Test_ReTest/Final/Rect10_testRetest.csv')

#Add a new column 'Test' to the dataframe in witch the value is 'Test-Retest' for all rows
df_rect10_tr['Test'] = 'Test-Retest'

#Add a new column 'CT' to the dataframe in witch the value is 'TO-GE' for all rows
df_rect10_tr['Manufacturer'] = 'TO-GE'

#delete the column 'count' from the dataframe
df_rect10_tr = df_rect10_tr.drop(['count'], axis=1)

#load the positioning csv file into a dataframe
df_rect10_pos = pd.read_csv('../../../../RadiomiK/Features_Positioning_test/Features_Not_Repeatable/cv_Rect10.csv')

#Add a new column 'Test' to the dataframe in witch the value is 'Positioning' for all rows
df_rect10_pos['Test'] = 'Positioning'

#delete the column 'cv' from the dataframe
df_rect10_pos = df_rect10_pos.drop(['CV'], axis=1)

#Load the volume csv file into a dataframe
df_rect10_vol = pd.read_csv('../../../../RadiomiK/Features_Volume_test/Features_Not_Repeatable/cv_Rect10.csv')

#Add a new column 'Test' to the dataframe in witch the value is 'Volume' for all rows
df_rect10_vol['Test'] = 'Volume'

#delete the column 'cv' from the dataframe
df_rect10_vol = df_rect10_vol.drop(['CV'], axis=1)

#Concatenate the three dataframes into one
df_rect10 = pd.concat([df_rect10_tr, df_rect10_pos, df_rect10_vol], ignore_index=True)

#Save the concatenated dataframe as csv file
df_rect10.to_csv('../../../../RadiomiK/Features_not_repeatable_global/Rect10_all_test.csv', index=False)

df_rect10

,Feature,Test,Manufacturer
0,original_glszm_SmallAreaLowGrayLevelEmphasis,Test-Retest,TO-GE
1,original_glcm_Idmn,Test-Retest,TO-GE
2,original_glcm_Idn,Test-Retest,TO-GE
3,original_gldm_SmallDependenceLowGrayLevelEmphasis,Test-Retest,TO-GE
4,original_glszm_LargeAreaHighGrayLevelEmphasis,Test-Retest,TO-GE
5,original_glszm_LowGrayLevelZoneEmphasis,Test-Retest,TO-GE
6,original_gldm_LargeDependenceHighGrayLevelEmph...,Test-Retest,TO-GE
7,original_firstorder_Energy,Volume,Toshiba
8,original_firstorder_Skewness,Volume,Toshiba
9,original_firstorder_TotalEnergy,Volume,Toshiba
10,original_glcm_ClusterProminence,Volume,Toshiba
11,original_glcm_ClusterShade,Volume,Toshiba
12,original_glcm_JointEnergy,Volume,Toshiba
13,original_glcm_MaximumProbability,Volume,Toshiba
14,original_glrlm_GrayLevelNonUniformity,Volume,Toshiba
15,original_glrlm_LongRunLowGrayLevelEmphasis,Volume,Toshiba
16,original_glrlm_LowGrayLevelRunEmphasis,Volume,Toshiba
17,original_glrlm_RunLengthNonUniformity,Volume,Toshiba
18,original_glrlm_RunVariance,Volume,Toshiba
19,original_glrlm_ShortRunLowGrayLevelEmphasis,Volume,Toshiba
20,original_glszm_GrayLevelNonUniformity,Volume,Toshiba
21,original_glszm_LargeAreaHighGrayLevelEmphasis,Volume,Toshiba
22,original_glszm_LargeAreaLowGrayLevelEmphasis,Volume,Toshiba
23,original_glszm_LowGrayLevelZoneEmphasis,Volume,Toshiba
24,original_glszm_SizeZoneNonUniformity,Volume,Toshiba
25,original_glszm_SmallAreaLowGrayLevelEmphasis,Volume,Toshiba
26,original_glszm_ZoneVariance,Volume,Toshiba
27,original_gldm_DependenceNonUniformity,Volume,Toshiba
28,original_gldm_DependenceVariance,Volume,Toshiba
29,original_gldm_GrayLevelNonUniformity,Volume,Toshiba
30,original_gldm_LargeDependenceEmphasis,Volume,Toshiba
31,original_gldm_LargeDependenceHighGrayLevelEmph...,Volume,Toshiba
32,original_gldm_LargeDependenceLowGrayLevelEmphasis,Volume,Toshiba
33,original_gldm_LowGrayLevelEmphasis,Volume,Toshiba
34,original_gldm_SmallDependenceLowGrayLevelEmphasis,Volume,Toshiba
35,original_firstorder_Energy,Volume,GE
36,original_firstorder_TotalEnergy,Volume,GE
37,original_glcm_ClusterShade,Volume,GE
38,original_glcm_JointEnergy,Volume,GE
39,original_glrlm_GrayLevelNonUniformity,Volume,GE
40,original_glrlm_LongRunLowGrayLevelEmphasis,Volume,GE
41,original_glrlm_RunLengthNonUniformity,Volume,GE
42,original_glrlm_RunVariance,Volume,GE
43,original_glszm_GrayLevelNonUniformity,Volume,GE
44,original_glszm_LargeAreaEmphasis,Volume,GE
45,original_glszm_LargeAreaLowGrayLevelEmphasis,Volume,GE
46,original_glszm_LowGrayLevelZoneEmphasis,Volume,GE
47,original_glszm_SizeZoneNonUniformity,Volume,GE
48,original_glszm_SmallAreaLowGrayLevelEmphasis,Volume,GE
49,original_glszm_ZoneVariance,Volume,GE
50,original_gldm_DependenceNonUniformity,Volume,GE
51,original_gldm_DependenceVariance,Volume,GE
52,original_gldm_GrayLevelNonUniformity,Volume,GE
53,original_gldm_LargeDependenceLowGrayLevelEmphasis,Volume,GE
54,original_gldm_SmallDependenceLowGrayLevelEmphasis,Volume,GE

In [19]:
# Create daframe for the insert Rect11
#Read in the csv files
#Load test-retest csv file into dataframe
df_rect11_tr = pd.read_csv('../../../../RadiomiK/Filtered_features/Test_ReTest/Final/Rect11_testRetest.csv')

#Add a new column 'Test' to the dataframe in witch the value is 'Test-Retest' for all rows
df_rect11_tr['Test'] = 'Test-Retest'

#Add a new column 'CT' to the dataframe in witch the value is 'TO-GE' for all rows
df_rect11_tr['Manufacturer'] = 'TO-GE'

#delete the column 'count' from the dataframe
df_rect11_tr = df_rect11_tr.drop(['count'], axis=1)

#load the positioning csv file into a dataframe
df_rect11_pos = pd.read_csv('../../../../RadiomiK/Features_Positioning_test/Features_Not_Repeatable/cv_Rect11.csv')

#Add a new column 'Test' to the dataframe in witch the value is 'Positioning' for all rows
df_rect11_pos['Test'] = 'Positioning'

#delete the column 'cv' from the dataframe
df_rect11_pos = df_rect11_pos.drop(['CV'], axis=1)

#Load the volume csv file into a dataframe
df_rect11_vol = pd.read_csv('../../../../RadiomiK/Features_Volume_test/Features_Not_Repeatable/cv_Rect11.csv')

#Add a new column 'Test' to the dataframe in witch the value is 'Volume' for all rows
df_rect11_vol['Test'] = 'Volume'

#delete the column 'cv' from the dataframe
df_rect11_vol = df_rect11_vol.drop(['CV'], axis=1)

#Concatenate the three dataframes into one
df_rect11 = pd.concat([df_rect11_tr, df_rect11_pos, df_rect11_vol], ignore_index=True)

#Save the concatenated dataframe as csv file
df_rect11.to_csv('../../../../RadiomiK/Features_not_repeatable_global/Rect11_all_test.csv', index=False)

df_rect11

,Feature,Test,Manufacturer
0,original_glcm_Idn,Test-Retest,TO-GE
1,original_glcm_Idmn,Test-Retest,TO-GE
2,original_glszm_ZoneEntropy,Test-Retest,TO-GE
3,original_firstorder_Kurtosis,Test-Retest,TO-GE
4,original_glszm_SmallAreaLowGrayLevelEmphasis,Test-Retest,TO-GE
...,...,...,...
69,original_glszm_ZoneVariance,Volume,GE
70,original_gldm_DependenceNonUniformity,Volume,GE
71,original_gldm_GrayLevelNonUniformity,Volume,GE
72,original_gldm_LargeDependenceHighGrayLevelEmph...,Volume,GE
73,original_gldm_SmallDependenceHighGrayLevelEmph...,Volume,GE

In [20]:
# Create daframe for the insert Rect12
#Read in the csv files
#Load test-retest csv file into dataframe
df_rect12_tr = pd.read_csv('../../../../RadiomiK/Filtered_features/Test_ReTest/Final/Rect12_testRetest.csv')

#Add a new column 'Test' to the dataframe in witch the value is 'Test-Retest' for all rows
df_rect12_tr['Test'] = 'Test-Retest'

#Add a new column 'CT' to the dataframe in witch the value is 'TO-GE' for all rows
df_rect12_tr['Manufacturer'] = 'TO-GE'

#delete the column 'count' from the dataframe
df_rect12_tr = df_rect12_tr.drop(['count'], axis=1)

#load the positioning csv file into a dataframe
df_rect12_pos = pd.read_csv('../../../../RadiomiK/Features_Positioning_test/Features_Not_Repeatable/cv_Rect12.csv')

#Add a new column 'Test' to the dataframe in witch the value is 'Positioning' for all rows
df_rect12_pos['Test'] = 'Positioning'

#delete the column 'cv' from the dataframe
df_rect12_pos = df_rect12_pos.drop(['CV'], axis=1)

#Load the volume csv file into a dataframe
df_rect12_vol = pd.read_csv('../../../../RadiomiK/Features_Volume_test/Features_Not_Repeatable/cv_Rect12.csv')

#Add a new column 'Test' to the dataframe in witch the value is 'Volume' for all rows
df_rect12_vol['Test'] = 'Volume'

#delete the column 'cv' from the dataframe
df_rect12_vol = df_rect12_vol.drop(['CV'], axis=1)

#Concatenate the three dataframes into one
df_rect12 = pd.concat([df_rect12_tr, df_rect12_pos, df_rect12_vol], ignore_index=True)

#Save the concatenated dataframe as csv file
df_rect12.to_csv('../../../../RadiomiK/Features_not_repeatable_global/Rect12_all_test.csv', index=False)

df_rect12

,Feature,Test,Manufacturer
0,original_glszm_SizeZoneNonUniformityNormalized,Test-Retest,TO-GE
1,original_gldm_SmallDependenceLowGrayLevelEmphasis,Test-Retest,TO-GE
2,original_gldm_LargeDependenceHighGrayLevelEmph...,Test-Retest,TO-GE
3,original_glcm_ClusterShade,Test-Retest,TO-GE
4,original_glcm_Idmn,Test-Retest,TO-GE
...,...,...,...
108,original_gldm_LargeDependenceHighGrayLevelEmph...,Volume,GE
109,original_gldm_LargeDependenceLowGrayLevelEmphasis,Volume,GE
110,original_gldm_LowGrayLevelEmphasis,Volume,GE
111,original_gldm_SmallDependenceHighGrayLevelEmph...,Volume,GE
112,original_gldm_SmallDependenceLowGrayLevelEmphasis,Volume,GE

In [21]:
# Create daframe for the insert Rect13
#Read in the csv files
#Load test-retest csv file into dataframe
df_rect13_tr = pd.read_csv('../../../../RadiomiK/Filtered_features/Test_ReTest/Final/Rect13_testRetest.csv')

#Add a new column 'Test' to the dataframe in witch the value is 'Test-Retest' for all rows
df_rect13_tr['Test'] = 'Test-Retest'

#Add a new column 'CT' to the dataframe in witch the value is 'TO-GE' for all rows
df_rect13_tr['Manufacturer'] = 'TO-GE'

#delete the column 'count' from the dataframe
df_rect13_tr = df_rect13_tr.drop(['count'], axis=1)

#load the positioning csv file into a dataframe
df_rect13_pos = pd.read_csv('../../../../RadiomiK/Features_Positioning_test/Features_Not_Repeatable/cv_Rect13.csv')

#Add a new column 'Test' to the dataframe in witch the value is 'Positioning' for all rows
df_rect13_pos['Test'] = 'Positioning'

#delete the column 'cv' from the dataframe
df_rect13_pos = df_rect13_pos.drop(['CV'], axis=1)

#Load the volume csv file into a dataframe
df_rect13_vol = pd.read_csv('../../../../RadiomiK/Features_Volume_test/Features_Not_Repeatable/cv_Rect13.csv')

#Add a new column 'Test' to the dataframe in witch the value is 'Volume' for all rows
df_rect13_vol['Test'] = 'Volume'

#delete the column 'cv' from the dataframe
df_rect13_vol = df_rect13_vol.drop(['CV'], axis=1)

#Concatenate the three dataframes into one
df_rect13 = pd.concat([df_rect13_tr, df_rect13_pos, df_rect13_vol], ignore_index=True)

#Save the concatenated dataframe as csv file
df_rect13.to_csv('../../../../RadiomiK/Features_not_repeatable_global/Rect13_all_test.csv', index=False)

df_rect13

,Feature,Test,Manufacturer
0,original_glcm_Idmn,Test-Retest,TO-GE
1,original_gldm_SmallDependenceLowGrayLevelEmphasis,Test-Retest,TO-GE
2,original_gldm_LargeDependenceHighGrayLevelEmph...,Test-Retest,TO-GE
3,original_glcm_ClusterShade,Test-Retest,TO-GE
4,original_glcm_Idn,Test-Retest,TO-GE
...,...,...,...
107,original_gldm_HighGrayLevelEmphasis,Volume,GE
108,original_gldm_LargeDependenceHighGrayLevelEmph...,Volume,GE
109,original_gldm_LargeDependenceLowGrayLevelEmphasis,Volume,GE
110,original_gldm_LowGrayLevelEmphasis,Volume,GE
111,original_gldm_SmallDependenceLowGrayLevelEmphasis,Volume,GE

In [22]:
# Create daframe for the insert Rect14
#Read in the csv files
#Load test-retest csv file into dataframe
df_rect14_tr = pd.read_csv('../../../../RadiomiK/Filtered_features/Test_ReTest/Final/Rect14_testRetest.csv')

#Add a new column 'Test' to the dataframe in witch the value is 'Test-Retest' for all rows
df_rect14_tr['Test'] = 'Test-Retest'

#Add a new column 'CT' to the dataframe in witch the value is 'TO-GE' for all rows
df_rect14_tr['Manufacturer'] = 'TO-GE'

#delete the column 'count' from the dataframe
df_rect14_tr = df_rect14_tr.drop(['count'], axis=1)

#load the positioning csv file into a dataframe
df_rect14_pos = pd.read_csv('../../../../RadiomiK/Features_Positioning_test/Features_Not_Repeatable/cv_Rect14.csv')

#Add a new column 'Test' to the dataframe in witch the value is 'Positioning' for all rows
df_rect14_pos['Test'] = 'Positioning'

#delete the column 'cv' from the dataframe
df_rect14_pos = df_rect14_pos.drop(['CV'], axis=1)

#Load the volume csv file into a dataframe
df_rect14_vol = pd.read_csv('../../../../RadiomiK/Features_Volume_test/Features_Not_Repeatable/cv_Rect14.csv')

#Add a new column 'Test' to the dataframe in witch the value is 'Volume' for all rows
df_rect14_vol['Test'] = 'Volume'

#delete the column 'cv' from the dataframe
df_rect14_vol = df_rect14_vol.drop(['CV'], axis=1)

#Concatenate the three dataframes into one
df_rect14 = pd.concat([df_rect14_tr, df_rect14_pos, df_rect14_vol], ignore_index=True)

#Save the concatenated dataframe as csv file
df_rect14.to_csv('../../../../RadiomiK/Features_not_repeatable_global/Rect14_all_test.csv', index=False)

df_rect14

,Feature,Test,Manufacturer
0,original_gldm_SmallDependenceLowGrayLevelEmphasis,Test-Retest,TO-GE
1,original_glcm_Idn,Test-Retest,TO-GE
2,original_glcm_Idmn,Test-Retest,TO-GE
3,original_firstorder_Skewness,Test-Retest,TO-GE
4,original_glcm_ClusterShade,Test-Retest,TO-GE
...,...,...,...
101,original_gldm_LargeDependenceHighGrayLevelEmph...,Volume,GE
102,original_gldm_LargeDependenceLowGrayLevelEmphasis,Volume,GE
103,original_gldm_LowGrayLevelEmphasis,Volume,GE
104,original_gldm_SmallDependenceHighGrayLevelEmph...,Volume,GE
105,original_gldm_SmallDependenceLowGrayLevelEmphasis,Volume,GE

In [23]:
# print all the unique values in the column 'Feature'
print(df_cyl0.Feature.unique())

# put all the unique values in the column 'Feature' in a list
features = df_cyl0.Feature.unique().tolist()

# print the list
print(features)

# put all the unique values in the column 'Feature' in a dataframe
df_features = pd.DataFrame(features, columns=['Feature'])

# print the dataframe
df_features

['original_gldm_SmallDependenceLowGrayLevelEmphasis' 'original_glcm_Idmn'
 'original_glszm_SizeZoneNonUniformityNormalized'
 'original_gldm_LargeDependenceHighGrayLevelEmphasis' 'original_glcm_Idn'
 'original_glcm_ClusterShade' 'original_glszm_SmallAreaEmphasis'
 'original_firstorder_Skewness' 'original_firstorder_Kurtosis'
 'original_glcm_Imc2' 'original_glrlm_ShortRunLowGrayLevelEmphasis'
 'original_glrlm_LongRunLowGrayLevelEmphasis' 'original_glcm_Imc1'
 'original_glrlm_LowGrayLevelRunEmphasis'
 'original_glszm_SmallAreaLowGrayLevelEmphasis'
 'original_gldm_LowGrayLevelEmphasis'
 'original_glszm_LowGrayLevelZoneEmphasis' 'original_glcm_Correlation'
 'original_firstorder_Energy' 'original_firstorder_Range'
 'original_firstorder_TotalEnergy' 'original_glcm_JointEnergy'
 'original_glcm_MaximumProbability'
 'original_glrlm_GrayLevelNonUniformity'
 'original_glrlm_RunLengthNonUniformity' 'original_glrlm_RunVariance'
 'original_glszm_GrayLevelNonUniformity'
 'original_glszm_LargeAreaEmphasis'
 'original_glszm_LargeAreaHighGrayLevelEmphasis'
 'original_glszm_LargeAreaLowGrayLevelEmphasis'
 'original_glszm_SizeZoneNonUniformity' 'original_glszm_ZonePercentage'
 'original_glszm_ZoneVariance' 'original_gldm_DependenceNonUniformity'
 'original_gldm_GrayLevelNonUniformity'
 'original_gldm_LargeDependenceEmphasis'
 'original_gldm_SmallDependenceEmphasis' 'original_glcm_Autocorrelation'
 'original_glrlm_HighGrayLevelRunEmphasis'
 'original_glrlm_LongRunHighGrayLevelEmphasis'
 'original_glrlm_ShortRunHighGrayLevelEmphasis'
 'original_glszm_HighGrayLevelZoneEmphasis'
 'original_glszm_SmallAreaHighGrayLevelEmphasis'
 'original_gldm_DependenceVariance' 'original_gldm_HighGrayLevelEmphasis'
 'original_gldm_LargeDependenceLowGrayLevelEmphasis'
 'original_gldm_SmallDependenceHighGrayLevelEmphasis']
['original_gldm_SmallDependenceLowGrayLevelEmphasis', 'original_glcm_Idmn', 'original_glszm_SizeZoneNonUniformityNormalized', 'original_gldm_LargeDependenceHighGrayLevelEmphasis', 'original_glcm_Idn', 'original_glcm_ClusterShade', 'original_glszm_SmallAreaEmphasis', 'original_firstorder_Skewness', 'original_firstorder_Kurtosis', 'original_glcm_Imc2', 'original_glrlm_ShortRunLowGrayLevelEmphasis', 'original_glrlm_LongRunLowGrayLevelEmphasis', 'original_glcm_Imc1', 'original_glrlm_LowGrayLevelRunEmphasis', 'original_glszm_SmallAreaLowGrayLevelEmphasis', 'original_gldm_LowGrayLevelEmphasis', 'original_glszm_LowGrayLevelZoneEmphasis', 'original_glcm_Correlation', 'original_firstorder_Energy', 'original_firstorder_Range', 'original_firstorder_TotalEnergy', 'original_glcm_JointEnergy', 'original_glcm_MaximumProbability', 'original_glrlm_GrayLevelNonUniformity', 'original_glrlm_RunLengthNonUniformity', 'original_glrlm_RunVariance', 'original_glszm_GrayLevelNonUniformity', 'original_glszm_LargeAreaEmphasis', 'original_glszm_LargeAreaHighGrayLevelEmphasis', 'original_glszm_LargeAreaLowGrayLevelEmphasis', 'original_glszm_SizeZoneNonUniformity', 'original_glszm_ZonePercentage', 'original_glszm_ZoneVariance', 'original_gldm_DependenceNonUniformity', 'original_gldm_GrayLevelNonUniformity', 'original_gldm_LargeDependenceEmphasis', 'original_gldm_SmallDependenceEmphasis', 'original_glcm_Autocorrelation', 'original_glrlm_HighGrayLevelRunEmphasis', 'original_glrlm_LongRunHighGrayLevelEmphasis', 'original_glrlm_ShortRunHighGrayLevelEmphasis', 'original_glszm_HighGrayLevelZoneEmphasis', 'original_glszm_SmallAreaHighGrayLevelEmphasis', 'original_gldm_DependenceVariance', 'original_gldm_HighGrayLevelEmphasis', 'original_gldm_LargeDependenceLowGrayLevelEmphasis', 'original_gldm_SmallDependenceHighGrayLevelEmphasis']

                                              Feature
0   original_gldm_SmallDependenceLowGrayLevelEmphasis
1                                  original_glcm_Idmn
2      original_glszm_SizeZoneNonUniformityNormalized
3   original_gldm_LargeDependenceHighGrayLevelEmph...
4                                   original_glcm_Idn
5                          original_glcm_ClusterShade
6                    original_glszm_SmallAreaEmphasis
7                        original_firstorder_Skewness
8                        original_firstorder_Kurtosis
9                                  original_glcm_Imc2
10        original_glrlm_ShortRunLowGrayLevelEmphasis
11         original_glrlm_LongRunLowGrayLevelEmphasis
12                                 original_glcm_Imc1
13             original_glrlm_LowGrayLevelRunEmphasis
14       original_glszm_SmallAreaLowGrayLevelEmphasis
15                 original_gldm_LowGrayLevelEmphasis
16            original_glszm_LowGrayLevelZoneEmphasis
17                          original_glcm_Correlation
18                         original_firstorder_Energy
19                          original_firstorder_Range
20                    original_firstorder_TotalEnergy
21                          original_glcm_JointEnergy
22                   original_glcm_MaximumProbability
23              original_glrlm_GrayLevelNonUniformity
24              original_glrlm_RunLengthNonUniformity
25                         original_glrlm_RunVariance
26              original_glszm_GrayLevelNonUniformity
27                   original_glszm_LargeAreaEmphasis
28      original_glszm_LargeAreaHighGrayLevelEmphasis
29       original_glszm_LargeAreaLowGrayLevelEmphasis
30               original_glszm_SizeZoneNonUniformity
31                      original_glszm_ZonePercentage
32                        original_glszm_ZoneVariance
33              original_gldm_DependenceNonUniformity
34               original_gldm_GrayLevelNonUniformity
35              original_gldm_LargeDependenceEmphasis
36              original_gldm_SmallDependenceEmphasis
37                      original_glcm_Autocorrelation
38            original_glrlm_HighGrayLevelRunEmphasis
39        original_glrlm_LongRunHighGrayLevelEmphasis
40       original_glrlm_ShortRunHighGrayLevelEmphasis
41           original_glszm_HighGrayLevelZoneEmphasis
42      original_glszm_SmallAreaHighGrayLevelEmphasis
43                   original_gldm_DependenceVariance
44                original_gldm_HighGrayLevelEmphasis
45  original_gldm_LargeDependenceLowGrayLevelEmphasis
46  original_gldm_SmallDependenceHighGrayLevelEmph...